# Japanese translation dictionary for all missing keys
import json

JAPANESE_TRANSLATIONS = {
    "+1 555-0199": "+1 555-0199",
    "0% Exempt": "0% 非課税",
    "1 day": "1日",
    "10% Happy Hour": "10% ハッピーアワー",
    "14-day zero-risk trial evaluation": "14日間のリスクフリートライアル評価",
    "15% Member VIP": "15% VIP会員割引",
    "20% Promo Clearance": "20% プロモーションクリアランス",
    "256-Bit SSL Encrypted Payment": "256ビットSSL暗号化決済",
    "30 days": "30日間",
    "40% advance milestone required upon quotation acceptance.": "見積承諾時に40%の前受金が必要です。",
    "5% Staff Discount": "5% スタッフ割引",
    "7 days": "7日間",
    "80mm / 58mm": "80mm / 58mm",
    "Abbreviation": "略称",
    "Accepted": "承認済み",
    "Accepted / Approved": "承諾 / 承認済み",
    "Access Control": "アクセス制御",
    "Accounts Payable & Expense Management": "買掛金・経費管理",
    "Accounts Receivable (Customer Credit & Invoices)": "売掛金 (顧客売掛・請求書)",
    "Action": "操作",
    "Actions": "操作",
    "Activate": "有効化",
    "Activate Free Trial": "無料トライアルを開始",
    "Activation / License Key *": "アクティベーション / ライセンスキー *",
    "Active (Visible in POS)": "有効 (POSレジに表示)",
    "Active Account": "有効なアカウント",
    "Active Devices & POS Terminals": "有効な端末・POSレジ",
    "Active Store": "有効な店舗",
    "Active Store Plan": "現在の店舗プラン",
    "Active Supplier": "有効な仕入先",
    "Active subscription plans": "有効なサブスクリプションプラン",
    "Add Currency": "通貨を追加",
    "Add Custom Phrase": "カスタムフレーズを追加",
    "Add Customer": "顧客を追加",
    "Add Floor": "フロアを追加",
    "Add Floor Area": "フロアエリアを追加",
    "Add Method": "決済方法を追加",
    "Add Method Split": "分割決済方法を追加",
    "Add New Category": "新規カテゴリーを追加",
    "Add New Client": "新規クライアントを追加",
    "Add New Customer": "新規顧客を追加",
    "Add New Payment Method": "新規支払い方法を追加",
    "Add New Supplier": "新規仕入先を追加",
    "Add New Unit": "新規単位を追加",
    "Add Row": "行を追加",
    "Add Split": "分割を追加",
    "Add Table": "テーブルを追加",
    "Add Vendor Bill / Expense": "仕入先請求書 / 経費を追加",
    "Add special instructions, client PO reference, warranty notes or cashier remarks...": "特別な指示、クライアントの発注書参照番号、保証備考、レジ担当者メモなどを追加...",
    "Add to Cart": "カートに追加",
    "Add to Order": "注文に追加",
    "Add to Sale +": "販売に追加 +",
    "Add, edit, enable or remove custom payment methods for POS checkout": "POSレジ会計用のカスタム決済方法を追加、編集、有効化、または削除",
    "Add-ons & Extras": "トッピング・オプション",
    "Additional Custom Authored Content (Optional)": "追加のカスタムコンテンツ (任意)",
    "Address": "住所",
    "Address:": "住所:",
    "Adjust": "調整",
    "Adjust Points": "ポイント調整",
    "Adjustment (+/- Qty)": "在庫調整 (+/- 数量)",
    "Admin Full Name *": "管理者氏名 *",
    "Admin Login / Username *": "管理者ログインID / ユーザー名 *",
    "Admin Login Email *": "管理者ログインメールアドレス *",
    "Administration & Settings": "管理 & 設定",
    "Administrator": "管理者",
    "All": "すべて",
    "All Categories": "すべてのカテゴリー",
    "All Customers": "すべての顧客",
    "All Floor Areas": "すべてのフロアエリア",
    "All Items": "すべての商品",
    "All Kitchen Orders Cleared!": "すべての厨房注文が完了しました！",
    "All Menu": "全メニュー",
    "All Quotes": "すべての見積書",
    "All Statuses": "すべてのステータス",
    "All Suppliers": "すべての仕入先",
    "All inventory items are healthy and above minimum threshold.": "すべての在庫商品は正常で、最低基準値を上回っています。",
    "All rates quoted are valid for 15 days from issue date.": "見積金額の有効期限は発行日より15日間です。",
    "All unpaid bills": "すべての未払い請求書",
    "All-inclusive for growing businesses": "成長企業向けのオールインワンプラン",
    "Allocated": "割り当て済み",
    "Amber Gold": "アンバーゴールド",
    "Amount": "金額",
    "Amount ($)": "金額 ($)",
    "App URL": "アプリURL",
    "Application & Navigation Theme Color": "アプリ・ナビゲーションのテーマカラー",
    "Application primary theme color, default POS layout design, logo, and document colors": "アプリのプライマリテーマ色、デフォルトPOSレイアウト、ロゴ、帳票カラー",
    "Apply": "適用",
    "Apply Primary Language": "プライマリ言語を適用",
    "Apply Role Profile Preset:": "役割プロファイルプリセットを適用:",
    "Are you sure you want to delete payment method": "本当にこの決済方法を削除しますか",
    "Are you sure you want to delete the selected quotations?": "選択した見積書を削除してもよろしいですか？",
    "Are you sure you want to delete this bill?": "この請求書を削除してもよろしいですか？",
    "Are you sure you want to delete this quote?": "この見積書を削除してもよろしいですか？",
    "Are you sure you want to delete this translation key?": "この翻訳キーを削除してもよろしいですか？",
    "Area Name *": "エリア名 *",
    "Assigned Role": "割り当てられた役割",
    "Attach Official PDF Document": "公式PDF文書を添付",
    "Authorized POS Devices": "認証済みPOS端末",
    "Automated Database Backup & Retention Policy": "自動データベースバックアップと保持ポリシー",
    "Available": "利用可能",
    "Available Subscription Plans": "利用可能なサブスクリプションプラン",
    "Available database dumps stored on disk": "ディスクに保存されている利用可能なデータベースダンプ",
    "BACK / CLEAR": "戻る / クリア",
    "Back to Quotation Detail": "見積詳細に戻る",
    "Back to Quotes": "見積一覧に戻る",
    "Back to Sales": "売上一覧に戻る",
    "Back to Users & Team": "ユーザー・チーム一覧に戻る",
    "Backup Frequency": "バックアップ頻度",
    "Badge Color": "バッジカラー",
    "Balance Due": "差引請求額 (未払残高)",
    "Balance Due:": "未払残高:",
    "Balance logged to Accounts Receivable": "売掛金として計上された残高",
    "Balanced": "精算一致",
    "Bank & Payment Details (Rich-Text)": "銀行口座・振込先情報 (リッチテキスト)",
    "Bank & Payment Instructions": "お支払い・お振込案内",
    "Bank Reference / Wire TXN / Check #": "銀行参照番号 / 振込取引番号 / 小切手番号 #",
    "Bar / Lounge": "バー / ラウンジ",
    "Barcode": "バーコード",
    "Barcode / SKU": "バーコード / SKU",
    "Base Amount ($)": "基準金額 ($)",
    "Base Currency Code": "基準通貨コード",
    "Base currency code, symbol, decimal precision, and placement used across POS, cart, checkout, and invoices": "POS、カート、会計、請求書で使用される基準通貨コード、記号、小数点桁数、および表示位置",
    "Best Value": "ベストバリュー",
    "Best for: General Retail, Supermarkets, Convenience stores": "最適: 一般小売店、スーパーマーケット、コンビニエンスストア",
    "Best for: Modern tablet/iPad stands, boutique shops, cafes": "最適: タブレット/iPadスタンド、セレクトショップ、カフェ",
    "Best for: Touch registers, high-traffic counters, department stores": "最適: タッチパネルレジ、混雑カウンター、百貨店",
    "Bill": "仕入請求書",
    "Bill #": "請求書番号 #",
    "Bill / Invoice Reference #": "請求書 / インボイス参照番号 #",
    "Bill Amount": "請求金額",
    "Bill Date": "請求日",
    "Bill Title / Description": "請求書タイトル / 説明",
    "Billed": "請求済み",
    "Bottom CTA Banner": "下部CTAバナー",
    "Bottom Dock Bar": "下部ドックバー",
    "Brand": "ブランド",
    "Brand Logo URL / Image Path": "ブランドロゴURL / 画像パス",
    "Brand Name *": "ブランド名 *",
    "Brand names & supplier labels": "ブランド名および仕入先ラベル",
    "Brand or company name displayed to recipients.": "受信者に表示されるブランド名または会社名。",
    "Brands & Manufacturers": "ブランド & メーカー",
    "Brands & Modifiers": "ブランド & オプション",
    "Browser Favicon URL (.ico / .png)": "ファビコンURL (.ico / .png)",
    "Business Contact Email": "ビジネス連絡先メールアドレス",
    "Business details displayed on POS terminal, receipts, and invoices": "POS端末、レシート、請求書に表示される店舗情報",
    "CVV / CVC *": "セキュリティコード (CVV/CVC) *",
    "Call:": "電話:",
    "Cancel KOT": "調理伝票 (KOT) をキャンセル",
    "Cancel Sale & Restock": "販売をキャンセルして在庫を戻す",
    "Cancel [Esc]": "キャンセル [Esc]",
    "Cancel this sale and restore stock?": "この販売をキャンセルして在庫を戻しますか？",
    "Capacity (Seats)": "収容人数 (座席数)",
    "Capacity:": "定員:",
    "Card Number *": "カード番号 *",
    "Cardholder Name *": "カード名義人 *",
    "Cart": "カート",
    "Cart is empty. Tap products to add items.": "カートは空です。商品をタップして追加してください。",
    "Cash In": "入金 (釣銭補充)",
    "Cash In / Out": "入出金",
    "Cash Movement Log": "現金の出納履歴",
    "Cash Out": "出金 (現金引出)",
    "Cash Register (Daily Register Management)": "レジ管理 (日次レジ締め・点検)",
    "Cash Sales": "現金売上",
    "Cash Tendered ($)": "お預かり金額 ($)",
    "Cash Tendered by Customer ($)": "お客様からのお預かり金額 ($)",
    "Casier POS": "POSレジ",
    "Catalog Item...": "カタログ商品...",
    "Catalog Title *": "カタログ名 *",
    "Category": "カテゴリー",
    "Category & Title": "カテゴリー & タイトル",
    "Category Name *": "カテゴリー名 *",
    "Change": "お釣り",
    "Change Due": "お釣り",
    "Change Due to Customer": "お客様へのお釣り",
    "Changes apply immediately upon saving.": "変更は保存後すぐに適用されます。",
    "Charge": "会計する",
    "Choose Option": "オプションを選択",
    "Choose a primary header & table theme color for Quotations and PDF Receipts": "見積書およびPDFレシートのヘッダー・テーブルのメインテーマカラーを選択",
    "Choose between General Retail POS vs Food & Restaurant Mode with strict UI & route isolation": "一般小売POSと飲食店モード(専用UIおよびルート分離)のいずれかを選択",
    "Choose dispatch channel, configure message body, and toggle PDF attachment": "送信チャネルを選択し、メッセージ本文を設定し、PDF添付の有無を切り替えます",
    "Choose the default interface style for your Point of Sale counter": "POSカウンターのデフォルトのインターフェーススタイルを選択",
    "Choose your preferred register design before entering the Point of Sale terminal": "POSレジ画面を開く前に、お好みのレジデザインを選択してください",
    "City": "市区町村",
    "City / Location": "市区町村 / 所在地",
    "Clean photo tiles, top category tabs, discounts bar & quick-charge pill.": "見やすい写真タイル、上部カテゴリータブ、割引バー、クイック会計ボタン。",
    "Clean photo-first tiles, Favorites / Library / Keypad tabs, discount presets & quick blue \"Charge\" pill.": "写真メインのタイル、お気に入り/ライブラリ/テンキータブ、割引プリセット、青いクイック「会計」ボタン。",
    "Clear All": "すべてクリア",
    "Clear Cart": "カートを空にする",
    "Clear Filter": "フィルターを解除",
    "Clear all items in this order?": "この注文のすべての商品をクリアしますか？",
    "Click any menu card on the left to add food.": "左側のメニューカードをクリックして商品を追加します。",
    "Click any table to immediately open POS and take order": "テーブルをクリックするとすぐにPOSが開き注文を取ることができます",
    "Click on any product to add it.": "商品をクリックして追加してください。",
    "Click to Insert Smart Placeholders:": "クリックしてスマートプレースホルダーを挿入:",
    "Clicking proceed will securely launch the Razorpay checkout dialog supporting Cards, UPI, Netbanking, Google Pay, Apple Pay & Wallets.": "「進む」をクリックすると、カード、UPI、ネットバンキング、Google Pay、Apple Pay、ウォレットに対応した安全な決済ダイアログが起動します。",
    "Client": "クライアント",
    "Client Name *": "クライアント名 *",
    "Client:": "クライアント:",
    "Close": "閉じる",
    "Close Register": "レジ締め",
    "Close Register & Generate Z-Report": "レジ締め & Zレポート(日締め)発行",
    "Closed": "営業終了 / 締め済み",
    "Closed By": "締め担当者",
    "Closing Notes": "締めメモ",
    "Closing Notes (Optional)": "締めメモ (任意)",
    "Cobalt Blue": "コバルトブルー",
    "Code": "コード",
    "Code / Key (Optional)": "コード / キー (任意)",
    "Code / SKU": "コード / SKU",
    "Code:": "コード:",
    "Collect Pay": "代金回収",
    "Collected This Month": "今月の回収額",
    "Collection Amount ($)": "回収金額 ($)",
    "Company / Store Name *": "会社名 / 店舗名 *",
    "Company mission card": "企業ミッションカード",
    "Complete & Print Receipt": "完了 & レシート印刷",
    "Complete Checkout": "会計を完了",
    "Configure fine-grained read, write, edit, delete, and export permissions per module.": "モジュールごとに閲覧、作成、編集、削除、エクスポートの権限を詳細に設定します。",
    "Configure global checkout processors for tenant subscription billing and renewals": "テナントのサブスクリプション請求と更新のためのグローバル決済プロセッサを設定",
    "Configure outbound email delivery for sending invoices, quotations, and staff invitations": "請求書、見積書、スタッフ招待状を送信するための送信メール設定",
    "Configure schedule frequency and retention lifecycle for database snapshots": "データベースバックアップの頻度と保持期間を設定",
    "Confirm & Complete Sale": "確認して販売を完了",
    "Confirm Collection Receipt": "入金領収書を確認",
    "Confirm Password": "パスワード (確認)",
    "Confirm Settlement Payment": "精算支払いを確認",
    "Connecting Gateway...": "決済ゲートウェイに接続中...",
    "Contact": "連絡先",
    "Contact Phone": "連絡先電話番号",
    "Control Center": "コントロールセンター",
    "Convert": "変換",
    "Convert quote #": "見積書 # を売上に変換",
    "Convert this quotation to an active Sale invoice and deduct inventory stock?": "この見積書を有効な売上請求書に変換し、在庫を引き落としますか？",
    "Convert to Sale": "売上に変換",
    "Converted": "変換済み",
    "Cost Price ($) *": "仕入原価 ($) *",
    "Counted": "実査額 (点検額)",
    "Counted Cash": "実査現金残高",
    "Counted Cash in Drawer ($)": "ドロワー内実査現金 ($)",
    "Counter Checkout": "カウンター会計",
    "Country (2-letter ISO)": "国コード (ISO 2文字)",
    "Country (ISO 2-letter) *": "国コード (ISO 2文字) *",
    "Create & Generate Invite": "招待状を作成して発行",
    "Create New Subscription Plan": "新規サブスクリプションプランを作成",
    "Create Quotation": "見積書を作成",
    "Create Vendor Bill / Expense": "仕入先請求書 / 経費を作成",
    "Create a public shareable digital menu or product showcase link": "共有可能な公開デジタルメニューまたは商品カタログリンクを作成",
    "Create and initialize an isolated tenant store environment with initial admin account": "初期管理者アカウントを使用して独立したテナント店舗環境を作成・初期化",
    "Create formal quotations and convert them to sales in 1-click": "正式な見積書を作成し、1クリックで売上に変換",
    "Created": "作成日時",
    "Credit / Receivable Sale:": "掛売上 / 売掛金販売:",
    "Credit Invoices Ledger": "売掛請求書台帳",
    "Crimson Red": "クリムゾンレッド",
    "Currency & Price Formatting": "通貨と金額の表示形式",
    "Currency Symbol": "通貨記号",
    "Current / Opening Stock *": "現在 / 期首在庫数 *",
    "Current Due": "現在の請求額",
    "Current Plan": "現在のプラン",
    "Current Store Plan": "現在の店舗プラン",
    "Current sale": "現在の販売",
    "Cust:": "顧客:",
    "Custom Charge Amount": "カスタム請求額",
    "Custom Domain Configuration": "カスタムドメイン設定",
    "Custom Hero Banner Image URL (Optional)": "カスタムメインバナー画像URL (任意)",
    "Custom WhatsApp Footer Note": "カスタムWhatsAppフッター注記",
    "Customer & Rewards": "顧客 & リワード",
    "Customer / Member": "顧客 / 会員",
    "Customer Directory Balances": "顧客台帳の残高一覧",
    "Customer Full Name *": "顧客氏名 *",
    "Customer Name *": "顧客名 *",
    "Customer Phone": "顧客電話番号",
    "Customer Testimonials": "お客様の声",
    "Customer credit & pending payments": "顧客の掛売残高 & 未払い金",
    "Customer credit & unpaid bills": "顧客の掛売 & 未払い請求",
    "Customer directory & loyalty points": "顧客台帳 & ポイント管理",
    "Customer history & contact list": "顧客履歴 & 連絡先リスト",
    "Customer name": "顧客名",
    "Customer:": "顧客:",
    "Customers & CRM": "顧客管理 (CRM)",
    "Customizable Text Message Body": "カスタマイズ可能なメッセージ本文",
    "Customize Phrases for Language:": "言語ごとの文言カスタマイズ:",
    "Customize phrases, POS terms, receipt titles, and tax invoice wording specifically for your store": "店舗専用にフレーズ、POS用語、レシートタイトル、インボイス文言をカスタマイズ",
    "Customized": "カスタマイズ済み",
    "DISCOUNT": "割引",
    "DISPATCHED": "送信済み",
    "Daily Automated Snapshot": "日次自動バックアップ",
    "Dashboard": "ダッシュボード",
    "Database Driver": "データベースドライバー",
    "Database Name": "データベース名",
    "Date:": "日付:",
    "Days": "日",
    "Debtor Customers": "売掛先顧客 (売掛金残高あり)",
    "Decimal Places": "小数点以下の桁数",
    "Default": "デフォルト",
    "Default Country Calling Code": "デフォルト国番号",
    "Default English Translation": "デフォルト英語翻訳",
    "Default POS Register Layout Design": "デフォルトPOSレジ画面レイアウト",
    "Default general walk-in sale": "通常のウォークイン(来店)販売",
    "Default language for customer receipts, table QR orders, and staff POS terminals": "顧客向けレシート、テーブルQR注文、スタッフPOSのデフォルト言語",
    "Default settings for 1-click WhatsApp receipts to customers": "顧客への1クリックWhatsAppレシート送信のデフォルト設定",
    "Default terms and notes auto-loaded into new Quotations": "新規見積書に自動挿入されるデフォルトの条件と備考",
    "Delete Bill": "請求書を削除",
    "Delete Selected": "選択項目を削除",
    "Delete this brand?": "このブランドを削除しますか？",
    "Delete this category?": "このカテゴリーを削除しますか？",
    "Delete this customer?": "この顧客を削除しますか？",
    "Delete this product?": "この商品を削除しますか？",
    "Delete this snapshot?": "このバックアップを削除しますか？",
    "Delete this supplier?": "この仕入先を削除しますか？",
    "Delete this unit?": "この単位を削除しますか？",
    "Delete translation key": "翻訳キーを削除",
    "Delivery": "配達 (デリバリー)",
    "Delivery Address": "配達先住所",
    "Delivery Address / Order Notes": "配達先住所 / 注文メモ",
    "Departments & tax rates": "部門 & 税率",
    "Description": "説明 / 摘要",
    "Description (Optional)": "説明 (任意)",
    "Description (optional)": "説明 (任意)",
    "Destination:": "宛先 / 移動先:",
    "Didn't receive code? Resend Code": "コードが届きませんか？ 再送信",
    "Difference": "差額",
    "Digital QR menu & WhatsApp store": "デジタルQRメニュー & WhatsAppストア",
    "Digital catalog & WhatsApp share": "デジタルカタログ & WhatsApp共有",
    "Dine-In": "店内飲食 (イートイン)",
    "Dine-In, Takeaway & Delivery": "店内飲食、テイクアウト、配達",
    "Dining History": "飲食・利用履歴",
    "Direct Invitation Link": "直接招待リンク",
    "Direct Proposal / Walk-in Client": "直接提案 / 来店クライアント",
    "Disable": "無効化",
    "Disabled": "無効",
    "Disabled — sends clean structured text email only.": "無効 — テキストメールのみ送信します。",
    "Discount ($)": "割引額 ($)",
    "Discount:": "割引:",
    "Discounts": "割引設定",
    "Dishes, ingredients & pricing": "料理、食材 & 価格設定",
    "Dispatch & Share Invoice:": "請求書を送信・共有:",
    "Dispatching...": "送信中...",
    "Displayed in browser tabs for your tenant store": "店舗のブラウザタブに表示されます",
    "Displayed in sidebar, PDF invoices, and online catalog header": "サイドバー、PDF請求書、オンラインカタログヘッダーに表示されます",
    "Docking Behavior": "ドッキング動作",
    "Docking Screen Position": "画面ドッキング位置",
    "Document / Tax ID": "適格請求書発行事業者番号 / 納税者番号",
    "Download & Print PDF Invoice": "PDF請求書をダウンロードして印刷",
    "Download / Stream PDF": "PDFをダウンロード / 表示",
    "Draft": "下書き",
    "Draft Proposal": "見積書案 (下書き)",
    "Driver / Courier": "配達員 / ドライバー",
    "Driver name": "配達員名",
    "Due Date": "支払期日",
    "Due Date:": "支払期日:",
    "EMV & NFC": "EMV & NFCタッチ決済",
    "EUR": "ユーロ (EUR)",
    "Edit": "編集",
    "Edit Bill": "請求書を編集",
    "Edit Category": "カテゴリーを編集",
    "Edit Customer": "顧客を編集",
    "Edit Floor Area": "フロアエリアを編集",
    "Edit Payment Method": "決済方法を編集",
    "Edit Plan": "プランを編集",
    "Edit Product": "商品を編集",
    "Edit Quotation": "見積書を編集",
    "Edit Supplier": "仕入先を編集",
    "Edit Table": "テーブルを編集",
    "Edit Unit": "単位を編集",
    "Edit Vendor Bill / Expense": "仕入先請求書 / 経費を編集",
    "Email": "メールアドレス",
    "Email & WhatsApp Invoice Sharing": "メールおよびWhatsAppでの請求書共有",
    "Email Address *": "メールアドレス *",
    "Email Dispatch (SMTP)": "メール送信 (SMTP)",
    "Email From Name (Sender Name) *": "差出人名 (Sender Name) *",
    "Email Invoice": "請求書をメール送信",
    "Email Invoice Receipt": "領収書・請求書をメール送信",
    "Email Us": "お問い合わせメール",
    "Email:": "メールアドレス:",
    "Emerald Green": "エメラルドグリーン",
    "Emerald Mint": "エメラルドミント",
    "Enable": "有効化",
    "Enable this payment method for POS checkout": "POS会計でこの決済方法を有効にする",
    "Enable, disable or add new multilingual languages to the system": "多言語の有効化、無効化、または新規言語の追加",
    "Encryption": "暗号化",
    "Encryption Protocol *": "暗号化プロトコル *",
    "English Name *": "英語名 *",
    "Enter a pre-purchased platform license key to activate this plan without card payment.": "カード決済なしでこのプランを有効化するには、購入済みのライセンスキーを入力してください。",
    "Enter bank accounts & payment instructions...": "銀行口座とお支払い案内を入力...",
    "Enter default quotation policy, deliverables & terms...": "見積書の基本方針、成果物、取引条件を入力...",
    "Enter invoice policy & terms...": "請求書のポリシーと取引条件を入力...",
    "Enter password": "パスワードを入力",
    "Enter your offline activation code or subscription license key to renew or upgrade your store.": "店舗の更新またはアップグレードのために、オフラインアクティベーションコードまたはライセンスキーを入力してください。",
    "Euro": "ユーロ",
    "Exchange rates against your base currency, for reporting and multi-currency displays": "レポートおよび多通貨表示用の基準通貨に対する為替レート",
    "Exit": "終了",
    "Exit Fullscreen": "全画面表示を終了",
    "Expected": "理論値 (システム計算額)",
    "Expected Cash": "理論現金残高",
    "Expected Cash (System)": "理論現金残高 (システム計算)",
    "Expected Cash in Drawer": "ドロワー内理論現金残高",
    "Expense Category": "経費科目・カテゴリー",
    "Expires": "有効期限",
    "Expires:": "有効期限:",
    "Expiry Date": "有効期限日",
    "Expiry Date (MM/YY) *": "有効期限 (月/年) *",
    "Fail": "不合格",
    "Fast barcode scan & cash checkout": "高速バーコードスキャン & 現金スピード会計",
    "Fast barcode scanning, 3-column product cards, category chips & right-side cart drawer.": "高速バーコードスキャン、3列商品カード、カテゴリーチップ、右側カートドロワー。",
    "Favicon URL": "ファビコンURL",
    "Favorites": "お気に入り",
    "Feature Modules Suite": "機能モジュールスイート",
    "Filter by Tenant / Company ID…": "テナント / 企業IDで絞り込み…",
    "Filter by event action (e.g. smtp.updated)…": "イベント操作で絞り込み (例: smtp.updated)…",
    "Financial & Currency": "財務 & 通貨設定",
    "Financial Management": "財務・会計管理",
    "Fixed ($)": "固定額 ($)",
    "Fixed Docked": "固定ドッキング",
    "Flag Emoji": "国旗絵文字",
    "Floating / Free Drag": "フローティング / ドラッグ移動",
    "Floor": "フロア",
    "Floor Area": "フロアエリア",
    "Floor plan is active. Take Dine-In orders, manage tables, monitor live kitchen tickets, and handle takeaway or deliveries.": "フロアマップが有効です。店内飲食の注文受付、テーブル管理、キッチン伝票の監視、テイクアウトや配達に対応します。",
    "Food & Restaurant": "飲食・レストラン",
    "Food & Restaurant Mode": "飲食・レストランモード",
    "Food & Restaurant Mode Active": "飲食・レストランモード有効中",
    "Food & Restaurant POS": "飲食店向けPOSレジ",
    "Food Item": "メニュー商品",
    "Food Items:": "メニュー商品:",
    "Food Menu": "フードメニュー",
    "Food Suppliers": "食材仕入先",
    "For restaurants, cafes, bars & food trucks. Includes floor plans & live tables, KOT tickets, Kitchen Display (KDS), Dine-In/Takeaway routing, and QR table ordering.": "レストラン、カフェ、居酒屋、キッチンカー向け。フロアマップ、注文伝票(KOT)、キッチンモニター(KDS)、店内/持帰対応、QRセルフ注文を完備。",
    "For supermarkets, clothing, electronics & retail shops. Includes barcode scanning, cash register, quotations, invoices, and standard stock management.": "スーパー、アパレル、雑貨、小売店向け。バーコードスキャン、レジ締め、見積書、請求書、標準在庫管理を完備。",
    "Forest Green": "フォレストグリーン",
    "Free Evaluation": "無料トライアル評価",
    "Free Floating": "フリーフローティング",
    "Full Access": "フルアクセス (全権限)",
    "Full Name *": "氏名 *",
    "Full Name as on Card": "カードに記載された氏名",
    "Fullscreen": "全画面表示",
    "Fully Settled": "全額精算済み (完済)",
    "Fully Settled (Paid)": "全額精算済み (支払完了)",
    "Function toolbar, vibrant department tiles & right receipt checkout slip.": "機能ツールバー、見やすい部門タイル、右側のレシート会計伝票。",
    "GRAND TOTAL": "総合計金額",
    "General": "一般",
    "General Retail": "一般小売 (物販)",
    "General Retail POS (Default)": "一般小売向けPOSレジ (標準)",
    "Generate Code": "コードを発行",
    "Generate Key": "キーを発行",
    "Generate Offline License Voucher": "オフラインライセンスを発行",
    "Generate and manage offline license vouchers for instant self-registration and renewals": "即時登録および更新用のオフラインライセンスバウチャーを発行・管理",
    "Generates and attaches clean stylized invoice PDF.": "整形されたPDF請求書を生成して添付します。",
    "Generates and attaches clean stylized proposal PDF.": "整形されたPDF見積書を生成して添付します。",
    "Global Audit Trail & Security Logs": "監査証跡 & セキュリティログ",
    "Global Platform SMTP Email Configuration": "プラットフォーム全体SMTPメール設定",
    "Global Tax Reference Matrix": "税率リファレンスマトリクス",
    "Grand Total:": "総合計:",
    "Guest Directory": "ゲスト台帳",
    "Guest name": "ゲスト名",
    "Guests": "人数 (ゲスト)",
    "HSN / SAC codes & VAT presets": "品目コード & 消費税区分プリセット",
    "Hardware Trust Bar": "対応周辺機器バー",
    "Hero Top Badge Text": "トップバッジテキスト",
    "Hero Value Proposition Subtitle": "バリュープロポジション副題",
    "History": "履歴",
    "History, print receipts & refunds": "売上履歴、レシート再発行 & 返金",
    "Host": "ホスト",
    "INV-": "INV-",
    "IP Address": "IPアドレス",
    "If you need access to this section, please request permission from your store": "このセクションへのアクセスが必要な場合は、店舗管理者に権限をリクエストしてください",
    "Immediate": "即時",
    "Immediate settlement": "即時精算",
    "Immutable event record of administrative actions, config mutations, and security events": "管理操作、設定変更、セキュリティイベントの改ざん不可能な記録",
    "Import all missing keys from English template": "英語テンプレートから未翻訳キーをすべてインポート",
    "In Cooking": "調理中",
    "Includes: Retail Counter • Barcode POS • Quotes": "含まれる機能: 小売カウンター • バーコードPOS • 見積管理",
    "Includes: Tables • KOT • Kitchen KDS • QR Menus": "含まれる機能: テーブル管理 • 調理伝票 • 厨房モニター • QRメニュー",
    "Initial Status": "初期ステータス",
    "Initial Subscription Plan": "初期サブスクリプションプラン",
    "Inquiry Contact Form": "お問い合わせフォーム",
    "Installation complete. The installer is now locked.": "インストールが完了しました。インストーラーはロックされました。",
    "Instant Tax Receipt Generated": "インボイス領収書が即時発行されました",
    "Internal Notes": "社内用メモ",
    "Inv:": "請求書:",
    "Inventory / Goods": "在庫 / 商品",
    "Inventory / Raw Materials": "在庫 / 原材料",
    "Invite New Team Member": "新しいチームメンバーを招待",
    "Invite User": "ユーザーを招待",
    "Invoice #": "請求書番号 #",
    "Invoice / Receipt Attachment (PDF, Image)": "請求書 / レシート添付ファイル (PDF, 画像)",
    "Invoice Prefix": "請求書番号の接頭辞",
    "Invoice Terms & Conditions (Rich-Text)": "請求書の取引条件 (リッチテキスト)",
    "Invoice Terms & Policy": "請求条件 & ポリシー",
    "Invoice prefixes, default quotation terms, and payment instructions": "請求書番号の接頭辞、見積基本条件、お支払い案内",
    "Item": "品目",
    "Item & Description": "品目 & 説明",
    "Item & Scope Description": "品目 & 業務範囲の説明",
    "Item Code": "商品コード",
    "Item or service name *": "品名またはサービス名 *",
    "Itemized GST/VAT Tax Invoices": "税率別明細付き適格請求書 (インボイス)",
    "Itemized tax receipts for store subscriptions, license activations, and renewals": "店舗プラン、ライセンス有効化、更新用の税別明細領収書",
    "Jurisdiction standards, default VAT rates, and GST/HSN classification guidelines": "管轄区域基準、標準税率、税区分ガイドライン",
    "Keep Order On Screen": "注文画面を保持",
    "Keep the navigation bar pinned in view while scrolling through long views and forms": "長いフォームや画面をスクロールしてもナビゲーションバーを固定表示",
    "Key Name (Exact String) *": "キー名 (完全一致文字列) *",
    "Keypad": "テンキー",
    "Keypad Entry": "テンキー入力",
    "Kitchen Display System": "キッチンディスプレイシステム (KDS)",
    "Kitchen Display System (KDS)": "キッチンディスプレイシステム (KDS)",
    "Kitchen KDS": "厨房KDS",
    "Kitchen Menu & Catalog": "厨房メニュー & カタログ",
    "Kitchen Note": "厨房への指示メモ",
    "Kitchen Note (Optional)": "厨房への指示メモ (任意)",
    "Landing Neon Lime Accent": "ランディング ネオンライムアクセント",
    "Landing Page Sections Controller": "ランディングページセクション管理",
    "Landing Primary Emerald": "ランディング プライマリエメラルド",
    "Language Code (ISO) *": "言語コード (ISO) *",
    "Language:": "言語:",
    "Launch Selected POS Register": "選択したPOSレジを起動",
    "Layout": "レイアウト",
    "Layout Direction:": "レイアウト方向:",
    "Lead capture form": "リード獲得フォーム",
    "Left Sidebar": "左サイドバー",
    "Left vertical function menu, vibrant department tiles, paginated grid & thermal receipt checkout slip.": "左側の垂直機能メニュー、部門タイル、ページ分けグリッド、レシート会計伝票。",
    "Left-to-Right (LTR)": "左から右 (LTR)",
    "Legal": "法的情報・規約",
    "Legal / Company Name": "法人名 / 会社名",
    "Library": "ライブラリ",
    "License Voucher": "ライセンスバウチャー",
    "Line Items & Scope Specifications": "明細行 & 仕様詳細",
    "Link Expiration": "リンクの有効期限",
    "Linked Supplier (Optional)": "関連仕入先 (任意)",
    "Live": "リアルタイム",
    "Live KDS": "リアルタイム厨房モニター (KDS)",
    "Live KOT preparation queue": "リアルタイム調理伝票キュー",
    "Live Kitchen Tickets": "リアルタイム厨房伝票",
    "Live Metric Counters": "リアルタイム指標カウンター",
    "Live POS": "リアルタイムPOS",
    "Live Status:": "現在のステータス:",
    "Live Table Status & QR Menus": "リアルタイム空席状況 & QRメニュー",
    "Location": "所在地 / ロケーション",
    "Logistics & Freight": "物流 & 運送費",
    "Logistics, Freight & Delivery": "物流、運送 & 配達",
    "Low Stock Warnings": "在庫僅少アラート",
    "Loyalty Points": "ポイント (ロイヤルティ)",
    "Main Headline Title *": "メイン見出し *",
    "Maintenance & Repairs": "保守 & 修繕費",
    "Maintenance Lockout Message": "メンテナンス中の表示メッセージ",
    "Manage": "管理",
    "Manage Floor Plan": "フロアマップを管理",
    "Manage manufacturers and brands": "メーカーおよびブランドを管理",
    "Manage seating floor areas, table occupancy statuses, and QR code digital menus": "座席フロア、テーブル利用状況、QRデジタルメニューを管理",
    "Manage signed-in sessions across browsers and POS registers": "ブラウザおよびPOSレジ全体のログインセッションを管理",
    "Manage supported platform languages, customize JSON translation files, and synchronize multilingual dictionaries": "プラットフォーム対応言語の管理、JSON翻訳ファイルの編集、多言語辞書の同期",
    "Manage units of measure for inventory and billing": "在庫および請求用の単位を管理",
    "Manage vendor bills, operational expenses, utility costs, supplier settlements, and payment proofs.": "仕入先請求書、運営経費、光熱費、買掛金精算、支払証憑を管理。",
    "Manage your store subscription plan, redeem activation keys, and access compliant tax invoices": "店舗プランの管理、ライセンスキーの適用、適格請求書の確認",
    "Manual movements this shift": "このシフトでの手動入出金",
    "Mark as Ready": "調理完了にする",
    "Mark as Served": "配膳済みにする",
    "Marketing & Ads": "マーケティング & 広告宣伝費",
    "Marketing & Promotions": "マーケティング & プロモーション",
    "Max POS Devices Limit": "POSレジ台数上限",
    "Max Users Limit": "最大ユーザー数上限",
    "Measurement Units": "計量単位",
    "Member:": "会員:",
    "Membership": "会員制度 (メンバーシップ)",
    "Menu": "メニュー",
    "Menu Dishes & Stock": "メニュー料理 & 在庫",
    "Menu sections & tax rates": "メニュー構成 & 適用税率",
    "Method": "支払方法",
    "Method Name": "支払方法名",
    "Method Name *": "支払方法名 *",
    "Method:": "支払方法:",
    "Midnight Slate": "ミッドナイトスレート",
    "Migration failed. Check the output above and try again.": "マイグレーションに失敗しました。上記出力を確認して再試行してください。",
    "Minimum Alert Stock *": "最低発注点 (アラート在庫数) *",
    "Minimum Client Build Version": "最小クライアントビルドバージョン",
    "Module": "モジュール",
    "Monthly": "月額 / 月次",
    "Monthly Snapshot": "月次自動バックアップ",
    "Multi-Language & Translation File Editor": "多言語 & 翻訳ファイルエディター",
    "N/A": "該当なし (N/A)",
    "Name": "名称",
    "Name *": "名称 *",
    "Native Name": "現地語名称",
    "Never": "なし (無制限)",
    "Never (Lifetime)": "無期限 (永久)",
    "Never (Permanent link)": "無期限 (恒久リンク)",
    "New": "新規",
    "New Brand": "新規ブランド",
    "New Category": "新規カテゴリー",
    "New Customer": "新規顧客",
    "New POS Credit Sale": "新規POS掛売上 (売掛)",
    "New Product": "新規商品",
    "New Quotation": "新規見積書",
    "New Sale": "新規売上",
    "New Supplier": "新規仕入先",
    "New Unit": "新規単位",
    "New orders from Dine-In tables, Takeaway, Delivery, or QR Digital Menu will appear here in real-time.": "店内テーブル、テイクアウト、配達、QRメニューからの新規注文がリアルタイムに表示されます。",
    "No Cash Register Open": "開いているレジがありません",
    "No Floor Assigned": "フロア未設定",
    "No Image": "画像なし",
    "No Plan (Unlimited / Manual)": "プラン未設定 (無制限 / 手動)",
    "No accounts receivable records match current filters.": "該当する売掛金レコードが見つかりません。",
    "No activation codes generated yet. Click \"+ Generate Key\" above.": "アクティベーションコードが未発行です。上の「+ キーを発行」をクリックしてください。",
    "No active products available.": "有効な商品がありません。",
    "No active sessions found.": "有効なセッションが見つかりません。",
    "No brands yet. Click \"+ New Brand\" to add one.": "ブランドが登録されていません。「+ 新規ブランド」をクリックして追加してください。",
    "No cash movements recorded yet.": "現金の出納履歴はありません。",
    "No catalogs published yet.": "公開されたカタログはありません。",
    "No categories yet. Click \"+ New Category\" to create one.": "カテゴリーがありません。「+ 新規カテゴリー」をクリックして作成してください。",
    "No closed registers yet.": "締め済みのレジ履歴はありません。",
    "No contact details": "連絡先情報なし",
    "No customer records found.": "顧客レコードが見つかりません。",
    "No customers found matching": "一致する顧客が見つかりません: ",
    "No customers registered yet.": "登録された顧客はいません。",
    "No dining floor areas created yet.": "飲食フロアエリアが作成されていません。",
    "No food items found. Use \"+ Add Product\" in Products menu to create items.": "商品が見つかりません。商品メニューの「+ 商品を追加」から作成してください。",
    "No items added to receipt yet.": "レシートに商品が追加されていません。",
    "No items found matching your search.": "検索条件に一致する商品が見つかりません。",
    "No items selected for this order.": "この注文に選択された商品がありません。",
    "No other currencies configured.": "他の通貨は設定されていません。",
    "No payment methods configured. Click \"+ Add Method\" to create one.": "決済方法が設定されていません。「+ 決済方法を追加」から作成してください。",
    "No products available in catalog.": "カタログに商品がありません。",
    "No products available in this department.": "この部門には商品がありません。",
    "No products in catalog yet.": "カタログに商品がまだありません。",
    "No products yet. Click \"+ New Product\" to add items.": "商品が登録されていません。「+ 新規商品」をクリックして追加してください。",
    "No quotations found matching the filter criteria.": "絞り込み条件に一致する見積書が見つかりません。",
    "No recent kitchen tickets.": "最近の厨房伝票はありません。",
    "No recent sales records found.": "最近の売上レコードが見つかりません。",
    "No sales found.": "売上が見つかりません。",
    "No sales recorded yet this shift.": "このシフトでの売上はまだ記録されていません。",
    "No sales recorded.": "売上は記録されていません。",
    "No subscription tax invoices generated yet.": "サブスクリプションの適格請求書はまだ発行されていません。",
    "No suppliers yet. Click \"+ New Supplier\" to add one.": "仕入先が登録されていません。「+ 新規仕入先」をクリックして追加してください。",
    "No tables registered for this floor. Click \"+ Add Table\" to start.": "このフロアにテーブルが登録されていません。「+ テーブルを追加」から始めてください。",
    "No team members found. Click \"+ Invite User\" to add staff.": "チームメンバーが見つかりません。「+ ユーザーを招待」からスタッフを追加してください。",
    "No units yet. Click \"+ New Unit\" to add one.": "単位が登録されていません。「+ 新規単位」をクリックして追加してください。",
    "No vendor bills or operational expenses match current filters.": "条件に一致する仕入請求書や経費は見つかりません。",
    "Non-Supplier / General Vendor": "一般業者 / 仕入先以外",
    "None": "なし",
    "None (Port 25)": "なし (ポート25)",
    "None (Use built-in modules only)": "なし (標準モジュールのみ使用)",
    "Not Set": "未設定",
    "Note:": "備考:",
    "Notes & Remarks": "備考 & メモ",
    "Notes regarding installment / settlement...": "分割払い・精算に関する特記事項...",
    "Notification & Dispatch": "通知 & 送信設定",
    "OFF": "オフ",
    "ON": "オン",
    "OVERDUE": "期限超過 (遅延)",
    "Occupied": "使用中 (満席)",
    "Ocean Sky": "オーシャンスカイ",
    "Office Supplies": "事務用品費",
    "Office Supplies & Software": "事務用品 & ソフトウェア",
    "Official Razorpay Payment Gateway": "公式Razorpay決済ゲートウェイ",
    "Official Tax Invoices & Payment Receipts": "公式適格請求書 & 領収書",
    "One-Time Invitation Code": "ワンタイム招待コード",
    "Online Catalog": "オンラインカタログ",
    "Online QR Menu": "オンラインQRメニュー",
    "Open Cash Register": "レジを開設 (釣銭準備金登録)",
    "Open KDS": "厨房モニター (KDS) を開く",
    "Open Link": "リンクを開く",
    "Open Register": "レジを開く",
    "Open Restaurant POS": "飲食店POSを開く",
    "Open Table POS": "テーブルPOSを開く",
    "Open WhatsApp & Send": "WhatsAppを開いて送信",
    "Open a register with a starting cash float to begin tracking today's shift.": "本日のシフトを開始するために、釣銭準備金を登録してレジを開設してください。",
    "Open/close the register, track cash in & out, and generate X/Z shift reports.": "レジの開設・点検・締め、現金の入出金管理、X/Zレポート(点検・精算)の発行。",
    "Opened": "開設済み (営業中)",
    "Opening": "開始",
    "Opening Float": "つり銭準備金 (開始残高)",
    "Opening Float ($)": "つり銭準備金 ($)",
    "Operating Mode": "動作モード",
    "Option:": "オプション:",
    "Optional": "任意",
    "Options": "オプション",
    "Or Direct Image URL": "または画像直接URL",
    "Order": "注文",
    "Order No.": "注文番号",
    "Order Notes & Remarks (Printed on Receipt)": "注文備考 (レシートに印字)",
    "Order Notes & Remarks:": "注文備考・伝言:",
    "Order Sent to Kitchen!": "注文を厨房に送信しました！",
    "Order Subtotal": "注文小計",
    "Order via WhatsApp": "WhatsApp経由で注文",
    "Orders & Cash": "注文 & レジ管理",
    "Orders & thermal receipts": "注文 & レシート印刷",
    "Organize products into POS categories": "商品をPOSカテゴリーに分類整理",
    "Other Currencies (Reference Rates)": "その他の通貨 (参考レート)",
    "Other Expenses": "その他の雑費",
    "Over": "超過 (過剰)",
    "Overdue Accounts": "支払期限超過アカウント",
    "Overdue Balance": "未払延滞残高",
    "Overdue Bills": "支払期日超過の請求書",
    "Override unit price": "単価を直接変更",
    "PARTIAL": "一部入金",
    "PDF": "PDF",
    "POS Checkout & Payment": "POS会計 & 決済",
    "POS Server": "POSサーバー",
    "POS, Inventory, KOT, Finance": "POS、在庫、厨房伝票、財務会計",
    "PROPOSAL PREPARED FOR:": "見積書提出先:",
    "Page Title *": "ページタイトル *",
    "Paid Amount:": "支払済金額:",
    "Paid so far": "これまでの支払総額",
    "Partially Paid": "一部支払済み",
    "Pass": "合格",
    "Password": "パスワード",
    "Pay": "支払う",
    "Pay & Settle Bill": "支払って請求書を精算",
    "Pay & Upgrade": "決済してアップグレード",
    "Pay Bill": "請求書を支払う",
    "Pay Method:": "支払方法:",
    "Payable To": "受取人名義",
    "Payment": "お支払い",
    "Payment Date": "支払日",
    "Payment Information": "支払情報",
    "Payment Method": "支払方法",
    "Payment Method:": "支払方法:",
    "Payment Proof / Bank Receipt (Optional)": "支払証憑 / 振込明細 (任意)",
    "Payment Remarks": "支払備考",
    "Payment required to activate services & generate tax invoice": "サービスの有効化と適格請求書発行にはお支払いが必要です",
    "Payment terms, bank details, purchase order #...": "支払条件、振込先口座、発注書番号...",
    "Payroll & Salaries": "給与・役員報酬",
    "Payroll & Staff Wages": "給与 & スタッフ賃金",
    "Pending / In Cooking": "調理待ち / 調理中",
    "Pending / Unpaid": "未払い / 保留中",
    "Pending Invoices": "未収請求書",
    "Pending Orders": "保留中の注文",
    "Percent (%)": "パーセント (%)",
    "Perfect for small retail stores": "小規模小売店・個人商店に最適",
    "Permissions Matrix": "権限マトリクス",
    "Perpetual / Lifetime": "買い切り / 永久ライセンス",
    "Phone / Contact": "電話 / 連絡先",
    "Phone / WhatsApp": "電話 / WhatsApp",
    "Phone / WhatsApp (Optional)": "電話 / WhatsApp (任意)",
    "Phone number (+1 555 0199)": "電話番号 (+1 555 0199)",
    "Phone:": "電話番号:",
    "Phrase Key *": "文言キー *",
    "Physical Address": "所在地住所",
    "Pickup Time": "受取希望時間",
    "Piece, Kilogram, Box…": "個、キログラム、箱…",
    "Pieces, kg, box, packs & liters": "個(pcs)、kg、箱、パック、リットル",
    "Plan": "プラン",
    "Plan / Description": "プラン / 内容",
    "Plan details & invoices": "プラン詳細 & 請求書",
    "Platform": "プラットフォーム",
    "Platform Application Version": "アプリバージョン",
    "Platform Brand Name *": "プラットフォームブランド名 *",
    "Platform GST / Tax (18% • CGST 9% + SGST 9%)": "プラットフォーム消費税 (18%)",
    "Platform Logo URL": "プラットフォームロゴURL",
    "Platform Payment Gateways": "決済ゲートウェイ設定",
    "Please provide a valid name for all items.": "すべての商品に有効な名称を入力してください。",
    "Point your domain's": "独自ドメインのDNS設定を向けてください",
    "Points Delta (+/-)": "ポイント増減 (+/-)",
    "Points:": "ポイント:",
    "Port": "ポート",
    "Port *": "ポート *",
    "Portions, kg, litres & grams": "人前、kg、リットル、グラム",
    "Postal Code": "郵便番号",
    "Prefix": "接頭辞 (プレフィックス)",
    "Prepared By:": "作成担当者:",
    "Preset Quick Discounts": "クイック割引プリセット",
    "Preview": "プレビュー",
    "Preview Landing Page": "ランディングページをプレビュー",
    "Price": "価格",
    "Price ($)": "単価 ($)",
    "Pricing Plans Grid": "料金プラン一覧",
    "Primary CTA Button Label": "メインCTAボタン文言",
    "Primary CTA URL": "メインCTA URL",
    "Primary Payment Method": "主たる決済方法",
    "Print Kitchen Ticket (KOT)": "厨房伝票 (KOT) を印刷",
    "Print Ticket": "伝票を印刷",
    "Print receipt/invoice": "レシート/領収書を印刷",
    "Processing Charge...": "請求処理中...",
    "Processing Sale...": "売上処理中...",
    "Processing Transaction...": "取引処理中...",
    "Processing...": "処理中...",
    "Product": "商品",
    "Product Brands": "商品ブランド",
    "Product Categories": "商品カテゴリー",
    "Product Name *": "商品名 *",
    "Product brands & food options": "商品ブランド & メニューオプション",
    "Production / Live Mode": "本番 (本番環境) モード",
    "Profile, printer, tax & domain": "店舗情報、プリンター、税設定 & ドメイン",
    "Profiles, history & loyalty": "顧客プロファイル、利用履歴 & ポイント",
    "Proof": "証憑",
    "Provision New Store": "新規店舗環境を開設",
    "Public / Publishable API Key": "公開用APIキー",
    "Publish Public Catalog": "公開カタログを発行",
    "Publish an Online Catalog": "オンラインカタログを公開",
    "Published Shareable Links": "公開中の共有リンク一覧",
    "QR Stand": "QRスタンド",
    "QUO-": "QUO-",
    "Qty": "数量",
    "Qty:": "数量:",
    "Quick Add Customer": "顧客クイック追加",
    "Quotation & Invoice Document Accent Color": "見積書・請求書のアクセントカラー",
    "Quotation Prefix": "見積書番号の接頭辞",
    "Quotations & Proposals": "見積書 & 提案書",
    "Quote #": "見積番号 #",
    "Quote No:": "見積番号:",
    "Quote Reference:": "見積参照:",
    "Quote Terms & Notes": "見積条件 & 備考",
    "Quote Terms & Notes (Rich-Text)": "見積条件 & 備考 (リッチテキスト)",
    "Quotes, estimates & 1-click sales conversion": "見積書、概算作成 & 1クリック売上化",
    "Quotes, proposals & estimates": "見積書、提案書 & 概算",
    "Rate": "レート / 税率",
    "Razorpay": "Razorpay",
    "Ready to Serve": "提供準備完了",
    "Real-Time": "リアルタイム",
    "Real-time live kitchen order tracker & ticket bump screen (Auto-refreshing every 5s)": "リアルタイム厨房注文トラッカー & 伝票完了画面 (5秒ごとに自動更新)",
    "Reason": "理由",
    "Reason / Note": "理由 / 備考",
    "Receipt Prefixes & Bank Terms": "レシート接頭辞 & 振込条件",
    "Recent POS Transactions": "直近のPOS取引",
    "Recipient Email Address": "受信者メールアドレス",
    "Recipient Email Address *": "受信者メールアドレス *",
    "Recipient WhatsApp Phone Number (with Country Code)": "受信者WhatsApp電話番号 (国番号付き)",
    "Record Bill Settlement Payment": "仕入代金の支払いを記録",
    "Record Cash In": "入金 (釣銭補充) を記録",
    "Record Cash Out": "出金 (現金引出) を記録",
    "Record Receivable Payment": "売掛金の入金を記録",
    "Redeem & Activate": "コードを適用して有効化",
    "Redeem License Key": "ライセンスキーを適用",
    "Ref #": "参照番号 #",
    "Ref / Card Last4": "参照 / カード下4桁",
    "Reference / Transaction / Check #": "参照番号 / 取引ID / 小切手番号 #",
    "Register": "レジ",
    "Register History (Closed Shifts / Z-Reports)": "レジ履歴 (過去のシフト / Zレポート日締め)",
    "Register users and define what each one can see and do.": "スタッフを登録し、各自の閲覧・操作権限を設定します。",
    "Registered on": "登録日",
    "Registration prompt": "登録プロンプト",
    "Rejected": "却下",
    "Remaining": "残高",
    "Remaining Balance": "未払残高",
    "Remaining Due": "残りの支払期限額",
    "Remove": "削除",
    "Remove split line": "分割行を削除",
    "Remove table": "テーブルを削除",
    "Rent & Facilities": "賃料 & 施設費",
    "Rent & Premises": "店舗・事務所家賃",
    "Rep:": "担当:",
    "Requires follow-up": "要フォローアップ",
    "Reserved": "予約済み",
    "Reset": "リセット",
    "Reset Template": "テンプレートを初期化",
    "Reset to system default": "システム標準に戻す",
    "Resolve the failed checks above before continuing.": "続行する前に上記のエラー項目を解決してください。",
    "Restaurant Mode": "飲食店モード",
    "Restock": "在庫補充",
    "Resume Fullscreen": "全画面表示を再開",
    "Retention Window (Days)": "データ保持期間 (日数)",
    "Return to my account": "マイアカウントに戻る",
    "Review & Place Order": "確認して注文を確定",
    "Revoke": "失効させる",
    "Revoke this license key?": "このライセンスキーを失効させますか？",
    "Revoke this link?": "このリンクを失効させますか？",
    "Revoked": "失効済み",
    "Right Sidebar": "右サイドバー",
    "Right-to-Left (RTL - Arabic, Hebrew)": "右から左 (RTL - アラビア語、ヘブライ語)",
    "Role & Profile *": "役割 & 権限プロファイル *",
    "Role Profile": "役割プロファイル",
    "Row": "行",
    "Royal Indigo": "ロイヤルインディゴ",
    "Royal Purple": "ロイヤルパープル",
    "Ruby Rose": "ルビーローズ",
    "SKU": "商品コード (SKU)",
    "SKU Scan": "SKUスキャン",
    "SKUs, pricing & inventory levels": "商品コード、価格 & 在庫数",
    "SMTP Email Settings": "SMTPメールサーバー設定",
    "SMTP Host": "SMTPホスト",
    "SMTP Host Server *": "SMTPサーバーホスト *",
    "SMTP Password": "SMTPパスワード",
    "SMTP Port": "SMTPポート",
    "SMTP Username": "SMTPユーザー名",
    "SMTP Username / API Key": "SMTPユーザー名 / APIキー",
    "SSL": "SSL",
    "SSL (Port 465)": "SSL (ポート465)",
    "SUB TOTAL": "小計",
    "Sale": "売上",
    "Sale #": "売上番号 #",
    "Sale / Inv #": "売上 / 請求番号 #",
    "Sale Completed!": "会計が完了しました！",
    "Sale Price ($) *": "販売価格 ($) *",
    "Sales Representative": "営業担当者",
    "Sales by Payment Method": "決済方法別売上",
    "Sales by Payment Method (This Shift)": "決済方法別売上 (現在のシフト)",
    "Sandbox / Test Mode": "テスト (サンドボックス) モード",
    "Save & Preview Quotation": "保存して見積書をプレビュー",
    "Save & Select Customer": "保存して顧客を選択",
    "Save All Custom Translations": "すべてのカスタム翻訳を保存",
    "Save All Settings": "すべての設定を保存",
    "Save Bill / Expense": "仕入請求書 / 経費を保存",
    "Save Category": "カテゴリーを保存",
    "Save Customer": "顧客を保存",
    "Save Financial Settings": "財務設定を保存",
    "Save Floor": "フロアを保存",
    "Save Method": "決済方法を保存",
    "Save Notification & Dispatch Settings": "通知・送信設定を保存",
    "Save Operating Mode": "動作モードを保存",
    "Save Permissions": "権限を保存",
    "Save Phrase": "フレーズを保存",
    "Save Plan": "プランを保存",
    "Save Product": "商品を保存",
    "Save Profile & Branding": "店舗情報 & ブランディングを保存",
    "Save Receipt Prefixes & Bank Terms": "レシート接頭辞 & 振込条件を保存",
    "Save SMTP Configuration": "SMTP設定を保存",
    "Save Store Overrides": "店舗個別設定を保存",
    "Save Supplier": "仕入先を保存",
    "Save Table": "テーブルを保存",
    "Save Unit": "単位を保存",
    "Saved securely": "安全に保存されました",
    "Saving...": "保存中...",
    "Scan barcode / SKU...": "バーコード / SKUをスキャン...",
    "Scan barcode or type product name / SKU...": "バーコードをスキャン、または商品名/SKUを入力...",
    "Scan to View Menu & Order": "スキャンしてメニュー閲覧 & ご注文",
    "Scheduled outgoings": "支払予定の経費",
    "Scope specifications / item deliverables description (optional)...": "業務範囲の仕様 / 成果物の説明 (任意)...",
    "Search and attach a customer to this sale": "顧客を検索してこの売上に紐付け",
    "Search bar, category chips, 3-column retail item cards with side cart.": "検索バー、カテゴリーチップ、3列商品カードと右側カート。",
    "Search bill #, vendor, title...": "請求書番号、業者名、タイトルで検索...",
    "Search by customer name, phone, or email...": "顧客名、電話番号、メールで検索...",
    "Search by name, code, barcode…": "商品名、コード、バーコードで検索…",
    "Search by name, email, phone…": "氏名、メール、電話番号で検索…",
    "Search by sale # or customer…": "売上番号または顧客名で検索…",
    "Search invoice #, customer...": "請求書番号、顧客名で検索...",
    "Search items...": "商品を検索...",
    "Search keys or translated phrases…": "キーまたは翻訳済み文言を検索…",
    "Search menu...": "メニューを検索...",
    "Search quotation # or client name...": "見積番号またはクライアント名で検索...",
    "Search stores by name, account ID, email, slug…": "店舗名、アカウントID、メール、スラッグで検索…",
    "Search suppliers by name…": "仕入先名で検索…",
    "Search team by name, email, or role...": "名前、メール、役割でスタッフを検索...",
    "Search terms or phrases…": "用語やフレーズを検索…",
    "Seat": "座席",
    "Secondary CTA Button Label": "サブCTAボタン文言",
    "Secondary CTA URL": "サブCTA URL",
    "Secure Subscription Checkout": "安全なサブスクリプション決済",
    "Select Available Table": "空いているテーブルを選択",
    "Select Brand": "ブランドを選択",
    "Select Category": "カテゴリーを選択",
    "Select Client / Customer": "クライアント / 顧客を選択",
    "Select Customer / Member": "顧客 / 会員を選択",
    "Select Destination Table": "移動先のテーブルを選択",
    "Select Dine-In Table": "店内テーブルを選択",
    "Select Extra Page to Embed": "埋め込む追加ページを選択",
    "Select Language File to Edit:": "編集する言語ファイルを選択:",
    "Select POS Layout & Interface Design": "POS画面のレイアウトとデザインを選択",
    "Select Payment Method": "決済方法を選択",
    "Select Products to Include": "対象商品を選択",
    "Select Table": "テーブルを選択",
    "Select User to Configure:": "設定するユーザーを選択:",
    "Select the primary accent color for your navigation sidebar, buttons, and badges": "サイドバー、ボタン、バッジのメインアクセントカラーを選択",
    "Selected": "選択中",
    "Selected ✓": "選択済み ✓",
    "Send": "送信",
    "Send Email": "メールを送信",
    "Send Email via SMTP": "SMTP経由でメールを送信",
    "Send Invoice Email": "請求書メールを送信",
    "Send Invoice via Email": "請求書をメールで送信",
    "Send Order to Kitchen": "注文を厨房に送信",
    "Send Quotation Email": "見積書メールを送信",
    "Send Quotation Proposal #": "見積提案書 # を送信",
    "Send Tax Invoice #": "適格請求書 # を送信",
    "Send Tax Invoice Receipt": "領収書メールを送信",
    "Send Test Email": "テストメールを送信",
    "Send a test email to verify your SMTP configuration": "SMTP設定を確認するためにテストメールを送信",
    "Send an immediate test dispatch to verify that your SMTP host credentials and sender address are working properly.": "SMTP接続と送信元アドレスが正常に動作しているか確認するため、即時テストメールを送信します。",
    "Send an invitation to join your store via WhatsApp or Email": "WhatsAppまたはメールで店舗への参加招待を送信",
    "Send invitation email automatically via store SMTP": "店舗のSMTPサーバー経由で招待メールを自動送信",
    "Sender Display Name": "送信者表示名",
    "Sender Email Address": "送信者メールアドレス",
    "Sending Test...": "テスト送信中...",
    "Sending...": "送信中...",
    "Sent": "送信済み",
    "Sent to Client": "クライアントに送信済み",
    "Setting": "設定",
    "Settle Bill & Print Receipt": "請求書を精算して領収書を印刷",
    "Settled": "精算完了",
    "Settled (Paid)": "精算完了 (支払済)",
    "Settled This Month": "今月の精算完了額",
    "Settlement Amount ($)": "精算金額 ($)",
    "Settlement Date": "精算日",
    "Settlement remarks or transfer notes...": "精算メモや振込備考...",
    "Share Invite": "招待を共有",
    "Share Receipt on WhatsApp": "WhatsAppでレシートを共有",
    "Share via WhatsApp": "WhatsAppで共有",
    "Shareable web catalog & WhatsApp store": "共有可能なWebカタログ & WhatsAppストア",
    "Shifts, float & cash balancing": "シフト管理、釣銭準備金 & レジ点検精算",
    "Short": "不足",
    "Sign out this device?": "この端末からログアウトしますか？",
    "Signed In": "ログイン中",
    "Size / Style": "サイズ / スタイル",
    "Smart Inventory Platform, SaaS Billing…": "スマート在庫管理、SaaS請求プラットフォーム…",
    "Solution Pillars": "ソリューションの柱",
    "Special Order Instructions": "特別な調理指示・カスタムオーダー",
    "Special instructions, cashier remarks...": "特別な指示、レジ担当者メモ...",
    "Split Payment Entries": "分割決済の内訳",
    "Split Payment:": "分割払い:",
    "Split:": "分割:",
    "Square Stand": "Squareスタンド",
    "Square Stand Register": "Squareスタンドレジ",
    "Staff": "スタッフ",
    "Staff User Accounts": "スタッフアカウント",
    "Staff accounts & access matrix": "スタッフアカウント & 権限マトリクス",
    "Stand:": "スタンド:",
    "Standard": "標準 (スタンダード)",
    "Standard Scanner": "標準バーコードスキャナー",
    "Standard Scanner POS": "標準スキャナーPOS",
    "Start Preparing": "調理開始",
    "State": "都道府県 / 州",
    "State / Province": "都道府県",
    "Status": "ステータス",
    "Status:": "ステータス:",
    "Step 1 — Requirements & Permissions": "ステップ 1 — 動作環境 & パーミッション",
    "Step 2 — Environment & Database": "ステップ 2 — 環境設定 & データベース",
    "Step 3 — Migrate & Seed": "ステップ 3 — マイグレーション & 初期データ",
    "Step 4 — Super Admin Account": "ステップ 4 — 最高管理者アカウント作成",
    "Step 5 — Finish": "ステップ 5 — 完了",
    "Sticky Navigation Bar": "固定ナビゲーションバー",
    "Stock": "在庫",
    "Store Account:": "店舗アカウント:",
    "Store Email": "店舗メールアドレス",
    "Store Invoicing & Billing": "店舗の請求 & サブスクリプション管理",
    "Store Languages & Custom Translation Editor": "店舗言語 & 文言エディター",
    "Store Operating Mode": "店舗動作モード",
    "Store Phone / WhatsApp": "店舗電話番号 / WhatsApp",
    "Store Primary Language": "店舗の標準言語",
    "Store Profile & Branding": "店舗プロファイル & ブランディング",
    "Store Profile & Location": "店舗情報 & 所在地",
    "Store Subdomain / Slug": "店舗サブドメイン / スラッグ",
    "Store Theme, Branding & POS Layout": "店舗テーマ、ロゴ & POS画面レイアウト",
    "Store Website URL": "店舗WebサイトURL",
    "Street & apt": "丁目・番地・建物名・部屋番号",
    "Stripe, PayPal, Mollie, Razorpay": "Stripe, PayPal, Mollie, Razorpay",
    "Subscription & Tax Billing": "サブスクリプション & 請求書管理",
    "Subscription Expiration Date": "サブスクリプション有効期限",
    "Subtotal": "小計",
    "Subtotal:": "小計:",
    "Suffix": "接尾辞 (サフィックス)",
    "Super Admin": "最高管理者 (スーパー管理者)",
    "SuperAdmin Sidebar Menu": "最高管理者サイドバーメニュー",
    "Supermarket Touch POS": "スーパーマーケット向けタッチPOS",
    "Supplier": "仕入先",
    "Supplier Name *": "仕入先名 *",
    "Supplier bills & expenses": "仕入先請求書 & 経費",
    "Supplier bills & food purchases": "仕入先請求書 & 食材仕入れ",
    "Supplier bills & purchase dues": "仕入請求書 & 買掛金",
    "Suppliers & Vendors": "仕入先 & 外注業者",
    "Support": "サポート",
    "Support Email": "サポートメールアドレス",
    "Support Phone": "サポート電話番号",
    "Supported Platform Languages": "対応言語一覧",
    "Suspended": "一時停止中",
    "Switch Account": "アカウント切り替え",
    "Switch Table": "テーブル移動",
    "Symbol Placement": "通貨記号の表示位置",
    "System Default": "システム標準",
    "System Health & Global Maintenance Mode": "システム稼働状況 & メンテナンスモード",
    "TAX ESTIMATE": "概算税額",
    "TLS": "TLS",
    "TLS (Port 587 - Recommended)": "TLS (ポート587 - 推奨)",
    "TXN / Auth #": "取引番号 / 承認番号 #",
    "Table Name / Number *": "テーブル名 / 番号 *",
    "Table Order Review": "テーブル注文内容の確認",
    "Tables & Floor Plan": "テーブル & フロアマップ",
    "Takeaway": "テイクアウト (お持ち帰り)",
    "Target Seat": "対象座席",
    "Tax (GST/VAT)": "消費税 (GST/VAT)",
    "Tax / GST:": "消費税:",
    "Tax Amount ($)": "税額 ($)",
    "Tax Exempt": "非課税 / 免税",
    "Tax ID": "事業者登録番号 / 法人番号",
    "Tax ID / Business Reg": "適格請求書発行事業者番号 / 会社登録番号",
    "Tax ID / VAT / Document": "登録番号 / 消費税 / 帳票",
    "Tax Rate (%)": "税率 (%)",
    "Tax rates & category hierarchy": "税率 & カテゴリー階層",
    "Tax/GSTIN:": "登録番号/税番号:",
    "Taxable": "課税対象",
    "Taxable Base": "課税標準額 (税抜金額)",
    "Taxes & Professional": "租税公課 & 専門家報酬",
    "Taxes & Professional Services": "税金 & 専門サービス費",
    "Tenant Brand Primary": "テナントブランドカラー (メイン)",
    "Tenant app fallback primary": "テナントアプリの代替カラー",
    "Term / Phrase": "用語 / フレーズ",
    "Terminals & Devices": "端末 & レジ機器",
    "Terms and Conditions:": "利用規約 & 取引条件:",
    "Test SMTP": "SMTPテスト送信",
    "Text Direction": "文字の表記方向",
    "Thank you for your business! All sales are final unless otherwise specified in your service contract.": "毎度ありがとうございます！ 契約書に特段の記載がない限り、商品の返品・交換はいたしかねます。",
    "The bar floats as an overlay above the UI, enabling free drag-and-drop placement anywhere across the viewport without altering page grid layout.": "バーがUI上のオーバーレイとして浮動し、画面レイアウトを崩すことなく自由にドラッグ＆ドロップで配置できます。",
    "The bar snaps rigidly into the screen structure (Left Sidebar, Right Sidebar, Top Header Bar, Bottom Dock Bar) and adjusts page padding accordingly so content never scrolls under or overlaps it.": "バーが画面端に固定スナップされ、コンテンツが重なったり隠れたりしないよう余白が自動調整されます。",
    "The remaining balance is payable upon delivery/project completion.": "残金は納品時またはプロジェクト完了時にお支払いいただきます。",
    "Thermal receipts & order history": "レシート印刷 & 注文履歴",
    "This email address will appear in the \"From:\" header of all outgoing system emails.": "このメールアドレスが送信メールの「差出人(From:)」に表示されます。",
    "This user has Administrator role and automatically enjoys full bypass access to all modules.": "このユーザーには管理者権限があり、すべてのモジュールに対するフルアクセス権が付与されています。",
    "Ticket Status:": "伝票ステータス:",
    "Ticket is now active in the Kitchen Display System (KDS) queue.": "伝票は厨房モニター (KDS) のキューに入りました。",
    "Time:": "時間:",
    "Toggle Fullscreen Mode": "全画面表示の切り替え",
    "Toggle Sticky Navigation": "固定ナビゲーションの切り替え",
    "Top Header Bar": "上部ヘッダーバー",
    "Total": "合計",
    "Total Active KOTs": "進行中の調理伝票合計",
    "Total Amount": "合計金額",
    "Total Amount Due": "ご請求合計額",
    "Total Amount Paid:": "お支払い済み総額:",
    "Total Bill": "請求総額",
    "Total Due Today": "本日のお支払期日額",
    "Total Order Amount:": "注文合計金額:",
    "Total Outstanding": "未回収残高合計",
    "Total Outstanding Balance": "未払残高合計",
    "Total Payable": "お支払い総額",
    "Total Sales": "総売上高",
    "Total Tables:": "テーブル総数:",
    "Total:": "合計:",
    "Touch Department": "タッチ部門",
    "Touch POS": "タッチパネルPOS",
    "Track customer balances, credit sales, partial payments, due dates, and overdue accounts.": "顧客残高、掛売上、一部入金、支払期日、期限超過アカウントを追跡管理。",
    "Trade / Brand Name": "屋号 / ブランド名",
    "Transaction & Sales": "取引 & 売上",
    "Transfer Order": "注文を移動",
    "Transfer Table": "テーブル移動",
    "Transfer Table Order": "テーブル注文を移動",
    "Type product name, SKU or barcode scan...": "商品名、SKUを入力、またはバーコードをスキャン...",
    "URL Slug *": "URLスラッグ *",
    "USD": "米ドル (USD)",
    "Unassign Customer": "顧客の割り当てを解除",
    "Unit": "単位",
    "Unit Name": "単位名",
    "Unit Name *": "単位名 *",
    "Unit Price": "単価",
    "Units of Measure": "計量単位",
    "Unlimited": "無制限",
    "Unlimited Inventory & Sales History": "無制限の在庫 & 売上履歴",
    "Upcoming (30 Days)": "直近30日以内の期日",
    "Upgrade or renew your plan with instant tax invoice generation": "適格請求書の即時発行でプランをアップグレードまたは更新",
    "Upload Product Photo": "商品写真をアップロード",
    "Uploading...": "アップロード中...",
    "Use \"Adjust Stock\" button on the table.": "表内の「在庫調整」ボタンを使用してください。",
    "User": "ユーザー",
    "User / Terminal": "ユーザー / レジ端末",
    "Username": "ユーザー名",
    "Utilities (Electricity, Water, Internet)": "水道光熱費 & 通信費",
    "Utilities (Power/Water)": "水道光熱費 (電気/水道)",
    "Valid Until:": "有効期限:",
    "Validity Expiry Date": "有効期限満了日",
    "Vendor / Supplier": "業者 / 仕入先",
    "Vendor Name (If not in suppliers)": "仕入先名 (仕入先リストにない場合)",
    "Vendor contacts & purchasing": "仕入先連絡先 & 発注管理",
    "Vendor directory & purchasing": "仕入先台帳 & 発注",
    "Verify Key & Upgrade": "キーを認証してアップグレード",
    "View": "表示",
    "View & Download PDF Tax Invoice": "適格請求書PDFを表示・ダウンロード",
    "View All": "すべて表示",
    "View All Sales": "すべての売上を表示",
    "View All Stores": "すべての店舗を表示",
    "View Invoices": "請求書一覧を表示",
    "View Only": "閲覧のみ",
    "View Z-Report": "Zレポート(日締め)を表示",
    "View attached bill file": "添付された請求書ファイルを表示",
    "Viewing as": "表示中アカウント:",
    "Violet Purple": "バイオレットパープル",
    "Volume, Outlets, Uptime": "処理件数、店舗数、稼働率",
    "Walk-in": "来店客 (ウォークイン)",
    "Walk-in Customer": "一見客 (ウォークイン顧客)",
    "Walk-in Member": "来店会員",
    "Walk-in Regular Customer": "来店常連客",
    "Warm Amber": "ウォームアンバー",
    "Weekly Automated Snapshot": "週次自動バックアップ",
    "WhatsApp": "WhatsApp",
    "WhatsApp & Messaging Settings": "WhatsApp & メッセージ設定",
    "WhatsApp Web / Mobile": "WhatsApp Web / モバイル",
    "With pending dues": "未払い残高あり",
    "X-Report (live)": "Xレポート (途中点検)",
    "Yearly": "年額 / 年次",
    "You": "あなた",
    "Your Custom Store Translation": "店舗専用カスタム翻訳",
    "Your Name (Optional)": "お名前 (任意)",
    "Your Name *": "お名前 *",
    "Your Order Cart": "ご注文カート",
    "Your Phone / WhatsApp Number": "お電話番号 / WhatsApp番号",
    "Your Store Custom Translation *": "店舗カスタム翻訳 *",
    "Your cart is currently empty.": "現在カートには何も入っていません。",
    "Your sale is currently empty. Tap items to add.": "現在売上伝票は空です。商品をタップして追加してください。",
    "Z-Report": "Zレポート (日締め)",
    "active invoices": "有効な請求書",
    "admin@yourcompany.com": "admin@yourcompany.com",
    "apikey, username@domain.com…": "apikey, username@domain.com…",
    "billing@yourstore.com": "billing@yourstore.com",
    "by": "作成者:",
    "days": "日",
    "discount": "割引",
    "e.g. 1 for US/CA, 91 for IN, 44 for UK, 62 for ID": "例: 日本は81、米国は1、英国は44",
    "e.g. 15 mins, 06:00 PM": "例: 15分後、18:00",
    "e.g. Change fund top-up, petty cash withdrawal": "例: 釣銭準備金補充、小口現金引出",
    "e.g. City Power Corp, Apex Landlord": "例: 東京電力、ビル管理会社",
    "e.g. Credit Card, UPI, PIX, Stripe": "例: クレジットカード、電子マネー、QR決済",
    "e.g. Dutch": "例: オランダ語",
    "e.g. For returns, keep this receipt within 7 days.": "例: 返品の際は7日以内に本レシートをお持ちください。",
    "e.g. Fresh Summer Produce, Special Deals…": "例: 夏の特選野菜、特別セール…",
    "e.g. Michael Scott": "例: 山田 太郎",
    "e.g. Monthly Warehouse Rent or Stock Restock Batch #4": "例: 月額倉庫賃料、第4回在庫仕入",
    "e.g. Nederlands": "例: 日本語",
    "e.g. No onion": "例: ネギ抜き",
    "e.g. Pay via terminal or contactless": "例: 決済端末またはタッチ決済でお支払い",
    "e.g. Política de Devoluciones": "例: 返品・交換ポリシー",
    "e.g. Restock, damaged, correction": "例: 仕入れ、破損廃棄、棚卸差異修正",
    "e.g. Return Policy": "例: 返品ポリシー",
    "e.g. Return Policy, Print Tax Invoice": "例: 返品ポリシー、インボイス領収書印刷",
    "e.g. Return Policy, Special Promo": "例: 返品ポリシー、特別キャンペーン",
    "e.g. Rooftop Patio, Bar, Hall": "例: テラス席、バーカウンター、メインホール",
    "e.g. Sarah Jenkins": "例: 佐藤 花子",
    "e.g. Scope deliverables, milestone payment terms, project phases...": "例: 納品成果物、マイルストーン支払条件、工程フェーズ...",
    "e.g. TAX-8891, VAT12345": "例: T1234567890123 (インボイス番号)",
    "e.g. TXN-998822 or Check #4401": "例: TXN-998822 または 振込番号 #4401",
    "e.g. Table 04, VIP-1, Bar-02": "例: テーブル04、個室VIP-1、カウンター02",
    "e.g. WIRE-884401 or Check #1002": "例: WIRE-884401 または 振込 #1002",
    "e.g. card, upi, pix, stripe": "例: クレジット、QR決済、現金、振込",
    "e.g. nl, ja, it": "例: ja, en, zh",
    "e.g. smtp.mailgun.org, smtp.gmail.com": "例: smtp.mailgun.org, smtp.gmail.com",
    "e.g. yourstore.com or https://yourstore.com": "例: yourstore.com または https://yourstore.com",
    "each": "個",
    "https://example.com/favicon.ico": "https://example.com/favicon.ico",
    "https://example.com/logo.png": "https://example.com/logo.png",
    "https://example.com/product-image.jpg": "https://example.com/product-image.jpg",
    "if CNAME isn't supported at your registrar for this name) to": "ドメイン管理会社でCNAMEが利用できない場合) 宛先:",
    "impersonated": "代理ログイン中",
    "items": "点",
    "line items": "明細行",
    "m ago": "分前",
    "month": "月",
    "my-store": "my-store",
    "no-reply@saas.zoomnearby.com, billing@yourdomain.com": "no-reply@saas.zoomnearby.com, billing@yourdomain.com",
    "of": "/",
    "or": "または",
    "pcs": "個",
    "pcs, kg, box…": "個、kg、箱…",
    "pcs, kg, bx…": "個、kg、箱…",
    "pos.yourdomain.com or mycompany.com": "pos.yourdomain.com または mycompany.com",
    "postmaster@yourdomain.com": "postmaster@yourdomain.com",
    "pts": "pt",
    "quotation(s) selected": "件の見積書を選択中",
    "sale(s) total, all methods": "売上合計 (全決済方法)",
    "sarah@store.com": "sarah@store.com",
    "save this form, then ask your platform admin to finish HTTPS setup for the domain — until that's done it may show a certificate warning.": "このフォームを保存後、管理者にドメインのHTTPS設定の完了を依頼してください(完了するまで証明書警告が表示される場合があります)。",
    "seats": "席",
    "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…": "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…",
    "subtotal": "小計",
    "tax": "消費税",
    "to Sale invoice?": "売上請求書に変換しますか？",
    "total": "合計",
    "will be logged to Accounts Receivable.": "売掛金として計上されます。",
    "with Razorpay": "Razorpayで決済",
    "year": "年",
    "your-email@example.com": "your-email@example.com"
}

def update_ja():
    with open('lang/ja.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    with open('scratch/to_translate/ja_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
        
    missing_count = 0
    for k in missing:
        if k in JAPANESE_TRANSLATIONS:
            existing[k] = JAPANESE_TRANSLATIONS[k]
        else:
            print(f"Missing translation for key: {k}")
            missing_count += 1
            
    if missing_count > 0:
        print(f"FAILED: {missing_count} keys missing in JAPANESE_TRANSLATIONS")
        return False
        
    with open('lang/ja.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
        f.write('\n')
        
    print(f"Successfully updated lang/ja.json! Total keys: {len(existing)}")
    return True

if __name__ == '__main__':
    update_ja()
