# Hindi translation dictionary for all missing keys
import json

HINDI_TRANSLATIONS = {
    "+1 555-0199": "+1 555-0199",
    "0% Exempt": "0% कर-मुक्त (छूट)",
    "1 day": "1 दिन",
    "10% Happy Hour": "10% हैप्पी ऑवर",
    "14-day zero-risk trial evaluation": "14-दिवसीय जोखिम-मुक्त परीक्षण मूल्यांकन",
    "15% Member VIP": "15% सदस्य वीआईपी",
    "20% Promo Clearance": "20% प्रोमो क्लीयरेंस",
    "256-Bit SSL Encrypted Payment": "256-बिट एसएसएल एन्क्रिप्टेड भुगतान",
    "30 days": "30 दिन",
    "40% advance milestone required upon quotation acceptance.": "कोटेशन स्वीकृति पर 40% अग्रिम राशि आवश्यक है।",
    "5% Staff Discount": "5% स्टाफ छूट",
    "7 days": "7 दिन",
    "80mm / 58mm": "80 मिमी / 58 मिमी",
    "Abbreviation": "संक्षिप्त नाम (शॉर्ट कोड)",
    "Accepted": "स्वीकृत",
    "Accepted / Approved": "स्वीकृत / अनुमोदित",
    "Access Control": "पहुँच नियंत्रण (एक्सेस कंट्रोल)",
    "Accounts Payable & Expense Management": "देय खाते और व्यय प्रबंधन",
    "Accounts Receivable (Customer Credit & Invoices)": "प्राप्य खाते (ग्राहक उधार व इनवॉइस)",
    "Action": "कार्रवाई",
    "Actions": "कार्रवाइयां",
    "Activate": "सक्रिय करें",
    "Activate Free Trial": "निःशुल्क परीक्षण सक्रिय करें",
    "Activation / License Key *": "सक्रियण / लाइसेंस कुंजी *",
    "Active (Visible in POS)": "सक्रिय (पीओएस में दृश्यमान)",
    "Active Account": "सक्रिय खाता",
    "Active Devices & POS Terminals": "सक्रिय उपकरण व पीओएस टर्मिनल",
    "Active Store": "सक्रिय स्टोर",
    "Active Store Plan": "सक्रिय स्टोर प्लान",
    "Active Supplier": "सक्रिय आपूर्तिकर्ता",
    "Active subscription plans": "सक्रिय सदस्यता योजनाएं",
    "Add Currency": "मुद्रा जोड़ें",
    "Add Custom Phrase": "कस्टम वाक्यांश जोड़ें",
    "Add Customer": "ग्राहक जोड़ें",
    "Add Floor": "फ्लोर जोड़ें",
    "Add Floor Area": "फ्लोर क्षेत्र जोड़ें",
    "Add Method": "विधि जोड़ें",
    "Add Method Split": "विभाजित भुगतान विधि जोड़ें",
    "Add New Category": "नई श्रेणी जोड़ें",
    "Add New Client": "नया क्लाइंट जोड़ें",
    "Add New Customer": "नया ग्राहक जोड़ें",
    "Add New Payment Method": "नई भुगतान विधि जोड़ें",
    "Add New Supplier": "नया आपूर्तिकर्ता जोड़ें",
    "Add New Unit": "नई इकाई (यूनिट) जोड़ें",
    "Add Row": "पंक्ति जोड़ें",
    "Add Split": "विभाजन जोड़ें",
    "Add Table": "टेबल जोड़ें",
    "Add Vendor Bill / Expense": "विक्रेता बिल / व्यय जोड़ें",
    "Add special instructions, client PO reference, warranty notes or cashier remarks...": "विशेष निर्देश, क्लाइंट पीओ संदर्भ, वारंटी नोट्स या कैशियर टिप्पणियां जोड़ें...",
    "Add to Cart": "कार्ट में जोड़ें",
    "Add to Order": "ऑर्डर में जोड़ें",
    "Add to Sale +": "बिक्री में जोड़ें +",
    "Add, edit, enable or remove custom payment methods for POS checkout": "पीओएस चेकआउट के लिए कस्टम भुगतान विधियां जोड़ें, संपादित करें, सक्षम या हटाएं",
    "Add-ons & Extras": "ऐड-ऑन और अतिरिक्त सामग्री",
    "Additional Custom Authored Content (Optional)": "अतिरिक्त कस्टम सामग्री (वैकल्पिक)",
    "Address": "पता",
    "Address:": "पता:",
    "Adjust": "समायोजित करें",
    "Adjust Points": "अंक समायोजित करें",
    "Adjustment (+/- Qty)": "समायोजन (+/- मात्रा)",
    "Admin Full Name *": "व्यवस्थापक का पूरा नाम *",
    "Admin Login / Username *": "व्यवस्थापक लॉगिन / उपयोगकर्ता नाम *",
    "Admin Login Email *": "व्यवस्थापक लॉगिन ईमेल *",
    "Administration & Settings": "प्रशासन एवं सेटिंग्स",
    "Administrator": "व्यवस्थापक (एडमिनिस्ट्रेटर)",
    "All": "सभी",
    "All Categories": "सभी श्रेणियां",
    "All Customers": "सभी ग्राहक",
    "All Floor Areas": "सभी फ्लोर क्षेत्र",
    "All Items": "सभी आइटम",
    "All Kitchen Orders Cleared!": "सभी किचन ऑर्डर पूरे हो चुके हैं!",
    "All Menu": "संपूर्ण मेनू",
    "All Quotes": "सभी कोटेशन",
    "All Statuses": "सभी स्थितियां",
    "All Suppliers": "सभी आपूर्तिकर्ता",
    "All inventory items are healthy and above minimum threshold.": "सभी इन्वेंट्री आइटम पर्याप्त हैं और न्यूनतम सीमा से ऊपर हैं।",
    "All rates quoted are valid for 15 days from issue date.": "उद्धृत सभी दरें जारी होने की तारीख से 15 दिनों के लिए वैध हैं।",
    "All unpaid bills": "सभी अवैतनिक बिल",
    "All-inclusive for growing businesses": "बढ़ते व्यवसायों के लिए सर्वसमावेशी",
    "Allocated": "आवंटित",
    "Amber Gold": "एम्बर गोल्ड",
    "Amount": "राशि",
    "Amount ($)": "राशि ($)",
    "App URL": "ऐप यूआरएल",
    "Application & Navigation Theme Color": "एप्लिकेशन एवं नेविगेशन थीम रंग",
    "Application primary theme color, default POS layout design, logo, and document colors": "एप्लिकेशन का मुख्य थीम रंग, डिफ़ॉल्ट पीओएस लेआउट, लोगो और दस्तावेज़ रंग",
    "Apply": "लागू करें",
    "Apply Primary Language": "प्राथमिक भाषा लागू करें",
    "Apply Role Profile Preset:": "भूमिका प्रोफ़ाइल प्रीसेट लागू करें:",
    "Are you sure you want to delete payment method": "क्या आप वाकई भुगतान विधि हटाना चाहते हैं",
    "Are you sure you want to delete the selected quotations?": "क्या आप वाकई चयनित कोटेशन हटाना चाहते हैं?",
    "Are you sure you want to delete this bill?": "क्या आप वाकई इस बिल को हटाना चाहते हैं?",
    "Are you sure you want to delete this quote?": "क्या आप वाकई इस कोटेशन को हटाना चाहते हैं?",
    "Are you sure you want to delete this translation key?": "क्या आप वाकई इस अनुवाद कुंजी को हटाना चाहते हैं?",
    "Area Name *": "क्षेत्र का नाम *",
    "Assigned Role": "असाइन की गई भूमिका",
    "Attach Official PDF Document": "आधिकारिक पीडीएफ दस्तावेज़ संलग्न करें",
    "Authorized POS Devices": "अधिकृत पीओएस डिवाइस",
    "Automated Database Backup & Retention Policy": "स्वचालित डेटाबेस बैकअप और प्रतिधारण नीति",
    "Available": "उपलब्ध",
    "Available Subscription Plans": "उपलब्ध सदस्यता योजनाएं",
    "Available database dumps stored on disk": "डिस्क पर संग्रहीत उपलब्ध डेटाबेस बैकअप डंप",
    "BACK / CLEAR": "वापस / साफ़ करें",
    "Back to Quotation Detail": "कोटेशन विवरण पर वापस जाएं",
    "Back to Quotes": "कोटेशन सूची पर वापस जाएं",
    "Back to Sales": "बिक्री सूची पर वापस जाएं",
    "Back to Users & Team": "उपयोगकर्ता एवं टीम पर वापस जाएं",
    "Backup Frequency": "बैकअप आवृत्ति",
    "Badge Color": "बैज का रंग",
    "Balance Due": "बकाया राशि",
    "Balance Due:": "बकाया राशि:",
    "Balance logged to Accounts Receivable": "प्राप्य खातों में दर्ज की गई शेष राशि",
    "Balanced": "संतुलित",
    "Bank & Payment Details (Rich-Text)": "बैंक और भुगतान विवरण (रिच-टेक्स्ट)",
    "Bank & Payment Instructions": "बैंक और भुगतान निर्देश",
    "Bank Reference / Wire TXN / Check #": "बैंक संदर्भ / वायर लेन-देन / चेक नं.",
    "Bar / Lounge": "बार / लाउंज",
    "Barcode": "बारकोड",
    "Barcode / SKU": "बारकोड / एसकेयू",
    "Base Amount ($)": "मूल राशि ($)",
    "Base Currency Code": "मूल मुद्रा कोड",
    "Base currency code, symbol, decimal precision, and placement used across POS, cart, checkout, and invoices": "पीओएस, कार्ट, चेकआउट और इनवॉइस में उपयोग किया जाने वाला मूल मुद्रा कोड, प्रतीक, दशमलव सटीकता और स्थिति",
    "Best Value": "सर्वोत्तम मूल्य",
    "Best for: General Retail, Supermarkets, Convenience stores": "उपयुक्त: सामान्य खुदरा, सुपरमार्केट, किराना स्टोर",
    "Best for: Modern tablet/iPad stands, boutique shops, cafes": "उपयुक्त: आधुनिक टैबलेट/आईपैड स्टैंड, बुटीक, कैफे",
    "Best for: Touch registers, high-traffic counters, department stores": "उपयुक्त: टच रजिस्टर, व्यस्त काउंटर, डिपार्टमेंट स्टोर",
    "Bill": "बिल",
    "Bill #": "बिल नं. #",
    "Bill / Invoice Reference #": "बिल / इनवॉइस संदर्भ नं. #",
    "Bill Amount": "बिल राशि",
    "Bill Date": "बिल दिनांक",
    "Bill Title / Description": "बिल शीर्षक / विवरण",
    "Billed": "बिल किया गया",
    "Bottom CTA Banner": "निचला सीटीए बैनर",
    "Bottom Dock Bar": "निचला डॉक बार",
    "Brand": "ब्रांड",
    "Brand Logo URL / Image Path": "ब्रांड लोगो यूआरएल / छवि पथ",
    "Brand Name *": "ब्रांड का नाम *",
    "Brand names & supplier labels": "ब्रांड नाम और आपूर्तिकर्ता लेबल",
    "Brand or company name displayed to recipients.": "प्राप्तकर्ताओं को प्रदर्शित ब्रांड या कंपनी का नाम।",
    "Brands & Manufacturers": "ब्रांड और निर्माता",
    "Brands & Modifiers": "ब्रांड और संशोधक (मॉडिफायर्स)",
    "Browser Favicon URL (.ico / .png)": "ब्राउज़र फेविकॉन यूआरएल (.ico / .png)",
    "Business Contact Email": "व्यवसाय संपर्क ईमेल",
    "Business details displayed on POS terminal, receipts, and invoices": "पीओएस टर्मिनल, रसीदों और इनवॉइस पर प्रदर्शित व्यावसायिक विवरण",
    "CVV / CVC *": "सीवीवी / सीवीसी *",
    "Call:": "कॉल करें:",
    "Cancel KOT": "केओटी (KOT) रद्द करें",
    "Cancel Sale & Restock": "बिक्री रद्द करें और स्टॉक पुनर्स्थापित करें",
    "Cancel [Esc]": "रद्द करें [Esc]",
    "Cancel this sale and restore stock?": "क्या इस बिक्री को रद्द करके स्टॉक पुनर्स्थापित करना है?",
    "Capacity (Seats)": "क्षमता (सीटें)",
    "Capacity:": "क्षमता:",
    "Card Number *": "कार्ड नंबर *",
    "Cardholder Name *": "कार्डधारक का नाम *",
    "Cart": "कार्ट",
    "Cart is empty. Tap products to add items.": "कार्ट खाली है। आइटम जोड़ने के लिए उत्पादों पर टैप करें।",
    "Cash In": "कैश इन (जमा)",
    "Cash In / Out": "कैश इन / आउट",
    "Cash Movement Log": "कैश संचलन लॉग",
    "Cash Out": "कैश आउट (निकासी)",
    "Cash Register (Daily Register Management)": "कैश रजिस्टर (दैनिक रजिस्टर प्रबंधन)",
    "Cash Sales": "नकद बिक्री",
    "Cash Tendered ($)": "दी गई नकद राशि ($)",
    "Cash Tendered by Customer ($)": "ग्राहक द्वारा दी गई नकद राशि ($)",
    "Casier POS": "कैशियर पीओएस",
    "Catalog Item...": "कैटलॉग आइटम...",
    "Catalog Title *": "कैटलॉग शीर्षक *",
    "Category": "श्रेणी",
    "Category & Title": "श्रेणी और शीर्षक",
    "Category Name *": "श्रेणी का नाम *",
    "Change": "छुट्टे (बचे पैसे)",
    "Change Due": "ग्राहक को देय छुट्टे",
    "Change Due to Customer": "ग्राहक को देय छुट्टे",
    "Changes apply immediately upon saving.": "सहेजते ही परिवर्तन तुरंत लागू हो जाते हैं।",
    "Charge": "चार्ज / भुगतान लें",
    "Choose Option": "विकल्प चुनें",
    "Choose a primary header & table theme color for Quotations and PDF Receipts": "कोटेशन और पीडीएफ रसीदों के लिए हेडर व टेबल का मुख्य थीम रंग चुनें",
    "Choose between General Retail POS vs Food & Restaurant Mode with strict UI & route isolation": "सामान्य खुदरा पीओएस या सख्त यूआई अलगाव वाले फूड एवं रेस्तरां मोड के बीच चयन करें",
    "Choose dispatch channel, configure message body, and toggle PDF attachment": "डिस्पैच चैनल चुनें, संदेश बॉडी कॉन्फ़िगर करें, और पीडीएफ अटैचमेंट टॉगल करें",
    "Choose the default interface style for your Point of Sale counter": "अपने पॉइंट ऑफ़ सेल काउंटर के लिए डिफ़ॉल्ट इंटरफ़ेस शैली चुनें",
    "Choose your preferred register design before entering the Point of Sale terminal": "पॉइंट ऑफ़ सेल टर्मिनल में प्रवेश करने से पहले अपना पसंदीदा रजिस्टर डिज़ाइन चुनें",
    "City": "शहर",
    "City / Location": "शहर / स्थान",
    "Clean photo tiles, top category tabs, discounts bar & quick-charge pill.": "स्वच्छ फोटो टाइल्स, शीर्ष श्रेणी टैब, छूट बार और त्वरित-चार्ज बटन।",
    "Clean photo-first tiles, Favorites / Library / Keypad tabs, discount presets & quick blue \"Charge\" pill.": "फोटो-प्रथम टाइलें, पसंदीदा / लाइब्रेरी / कीपैड टैब, डिस्काउंट प्रीसेट और त्वरित नीला \"चार्ज\" बटन।",
    "Clear All": "सभी साफ़ करें",
    "Clear Cart": "कार्ट साफ़ करें",
    "Clear Filter": "फ़िल्टर साफ़ करें",
    "Clear all items in this order?": "क्या इस ऑर्डर के सभी आइटम साफ़ करने हैं?",
    "Click any menu card on the left to add food.": "भोजन जोड़ने के लिए बाईं ओर किसी भी मेनू कार्ड पर क्लिक करें।",
    "Click any table to immediately open POS and take order": "तुरंत पीओएस खोलने और ऑर्डर लेने के लिए किसी भी टेबल पर क्लिक करें",
    "Click on any product to add it.": "उत्पाद जोड़ने के लिए उस पर क्लिक करें।",
    "Click to Insert Smart Placeholders:": "स्मार्ट प्लेसहोल्डर डालने के लिए क्लिक करें:",
    "Clicking proceed will securely launch the Razorpay checkout dialog supporting Cards, UPI, Netbanking, Google Pay, Apple Pay & Wallets.": "आगे बढ़ें पर क्लिक करने से कार्ड, यूपीआई, नेटबैंकिंग, गूगल पे, ऐप्पल पे और वॉलेट का समर्थन करने वाला सुरक्षित रेज़रपे चेकआउट संवाद खुलेगा।",
    "Client": "क्लाइंट",
    "Client Name *": "क्लाइंट का नाम *",
    "Client:": "क्लाइंट:",
    "Close": "बंद करें",
    "Close Register": "रजिस्टर बंद करें",
    "Close Register & Generate Z-Report": "रजिस्टर बंद करें और Z-रिपोर्ट जनरेट करें",
    "Closed": "बंद",
    "Closed By": "द्वारा बंद किया गया",
    "Closing Notes": "समापन टिप्पणियां (क्लोजिंग नोट्स)",
    "Closing Notes (Optional)": "समापन टिप्पणियां (वैकल्पिक)",
    "Cobalt Blue": "कोबाल्ट नीला",
    "Code": "कोड",
    "Code / Key (Optional)": "कोड / कुंजी (वैकल्पिक)",
    "Code / SKU": "कोड / एसकेयू",
    "Code:": "कोड:",
    "Collect Pay": "भुगतान एकत्र करें",
    "Collected This Month": "इस महीने एकत्र किया गया",
    "Collection Amount ($)": "संग्रह राशि ($)",
    "Company / Store Name *": "कंपनी / स्टोर का नाम *",
    "Company mission card": "कंपनी मिशन कार्ड",
    "Complete & Print Receipt": "पूर्ण करें और रसीद प्रिंट करें",
    "Complete Checkout": "चेकआउट पूरा करें",
    "Configure fine-grained read, write, edit, delete, and export permissions per module.": "प्रति मॉड्यूल विस्तृत पढ़ने, लिखने, संपादित करने, हटाने और निर्यात अनुमतियों को कॉन्फ़िगर करें।",
    "Configure global checkout processors for tenant subscription billing and renewals": "किरायेदार सदस्यता बिलिंग और नवीनीकरण के लिए वैश्विक चेकआउट प्रोसेसर कॉन्फ़िगर करें",
    "Configure outbound email delivery for sending invoices, quotations, and staff invitations": "इनवॉइस, कोटेशन और स्टाफ निमंत्रण भेजने के लिए आउटबाउंड ईमेल डिलीवरी कॉन्फ़िगर करें",
    "Configure schedule frequency and retention lifecycle for database snapshots": "डेटाबेस स्नैपशॉट के लिए शेड्यूल आवृत्ति और प्रतिधारण जीवनचक्र कॉन्फ़िगर करें",
    "Confirm & Complete Sale": "पुष्टि करें और बिक्री पूरी करें",
    "Confirm Collection Receipt": "संग्रह रसीद की पुष्टि करें",
    "Confirm Password": "पासवर्ड की पुष्टि करें",
    "Confirm Settlement Payment": "निपटान भुगतान की पुष्टि करें",
    "Connecting Gateway...": "गेटवे से कनेक्ट हो रहा है...",
    "Contact": "संपर्क",
    "Contact Phone": "संपर्क फ़ोन",
    "Control Center": "नियंत्रण केंद्र (कंट्रोल सेंटर)",
    "Convert": "परिवर्तित करें",
    "Convert quote #": "कोटेशन परिवर्तित करें #",
    "Convert this quotation to an active Sale invoice and deduct inventory stock?": "क्या इस कोटेशन को एक सक्रिय बिक्री इनवॉइस में बदलना है और इन्वेंट्री स्टॉक घटाना है?",
    "Convert to Sale": "बिक्री में बदलें",
    "Converted": "परिवर्तित",
    "Cost Price ($) *": "लागत मूल्य ($) *",
    "Counted": "गिना गया",
    "Counted Cash": "गिनी गई नकद राशि",
    "Counted Cash in Drawer ($)": "दराज में गिनी गई नकद राशि ($)",
    "Counter Checkout": "काउंटर चेकआउट",
    "Country (2-letter ISO)": "देश (2-अक्षरीय ISO कोड)",
    "Country (ISO 2-letter) *": "देश (ISO 2-अक्षर) *",
    "Create & Generate Invite": "बनाएं और निमंत्रण जनरेट करें",
    "Create New Subscription Plan": "नई सदस्यता योजना बनाएं",
    "Create Quotation": "कोटेशन बनाएं",
    "Create Vendor Bill / Expense": "विक्रेता बिल / व्यय बनाएं",
    "Create a public shareable digital menu or product showcase link": "सार्वजनिक रूप से साझा करने योग्य डिजिटल मेनू या उत्पाद शोकेस लिंक बनाएं",
    "Create and initialize an isolated tenant store environment with initial admin account": "प्रारंभिक व्यवस्थापक खाते के साथ एक पृथक किरायेदार स्टोर वातावरण बनाएं और प्रारंभ करें",
    "Create formal quotations and convert them to sales in 1-click": "औपचारिक कोटेशन बनाएं और उन्हें 1-क्लिक में बिक्री में बदलें",
    "Created": "निर्मित",
    "Credit / Receivable Sale:": "क्रेडिट / प्राप्य बिक्री:",
    "Credit Invoices Ledger": "क्रेडिट इनवॉइस बहीखाता (लेज़र)",
    "Crimson Red": "गहरा लाल (क्रिमसन)",
    "Currency & Price Formatting": "मुद्रा एवं मूल्य प्रारूपण",
    "Currency Symbol": "मुद्रा प्रतीक",
    "Current / Opening Stock *": "वर्तमान / प्रारंभिक स्टॉक *",
    "Current Due": "वर्तमान बकाया",
    "Current Plan": "वर्तमान प्लान",
    "Current Store Plan": "वर्तमान स्टोर प्लान",
    "Current sale": "वर्तमान बिक्री",
    "Cust:": "ग्राहक:",
    "Custom Charge Amount": "कस्टम शुल्क राशि",
    "Custom Domain Configuration": "कस्टम डोमेन कॉन्फ़िगरेशन",
    "Custom Hero Banner Image URL (Optional)": "कस्टम हीरो बैनर छवि यूआरएल (वैकल्पिक)",
    "Custom WhatsApp Footer Note": "कस्टम व्हाट्सएप फुटर नोट",
    "Customer & Rewards": "ग्राहक और पुरस्कार (रिवॉर्ड्स)",
    "Customer / Member": "ग्राहक / सदस्य",
    "Customer Directory Balances": "ग्राहक निर्देशिका शेष राशि",
    "Customer Full Name *": "ग्राहक का पूरा नाम *",
    "Customer Name *": "ग्राहक का नाम *",
    "Customer Phone": "ग्राहक का फ़ोन",
    "Customer Testimonials": "ग्राहक प्रशंसापत्र",
    "Customer credit & pending payments": "ग्राहक उधार और लंबित भुगतान",
    "Customer credit & unpaid bills": "ग्राहक उधार और अवैतनिक बिल",
    "Customer directory & loyalty points": "ग्राहक निर्देशिका और लॉयल्टी अंक",
    "Customer history & contact list": "ग्राहक इतिहास और संपर्क सूची",
    "Customer name": "ग्राहक का नाम",
    "Customer:": "ग्राहक:",
    "Customers & CRM": "ग्राहक और सीआरएम",
    "Customizable Text Message Body": "अनुकूलन योग्य पाठ संदेश बॉडी",
    "Customize Phrases for Language:": "भाषा के लिए वाक्यांश अनुकूलित करें:",
    "Customize phrases, POS terms, receipt titles, and tax invoice wording specifically for your store": "अपने स्टोर के लिए विशेष रूप से वाक्यांश, पीओएस शब्द, रसीद शीर्षक और टैक्स इनवॉइस शब्दों को अनुकूलित करें",
    "Customized": "अनुकूलित",
    "DISCOUNT": "छूट",
    "DISPATCHED": "भेजा गया (डिस्पैच हुआ)",
    "Daily Automated Snapshot": "दैनिक स्वचालित स्नैपशॉट",
    "Dashboard": "डैशबोर्ड",
    "Database Driver": "डेटाबेस ड्राइवर",
    "Database Name": "डेटाबेस का नाम",
    "Date:": "दिनांक:",
    "Days": "दिन",
    "Debtor Customers": "देनदार ग्राहक (उधार खाता)",
    "Decimal Places": "दशमलव स्थान",
    "Default": "डिफ़ॉल्ट",
    "Default Country Calling Code": "डिफ़ॉल्ट देश कॉलिंग कोड",
    "Default English Translation": "डिफ़ॉल्ट अंग्रेजी अनुवाद",
    "Default POS Register Layout Design": "डिफ़ॉल्ट पीओएस रजिस्टर लेआउट डिज़ाइन",
    "Default general walk-in sale": "डिफ़ॉल्ट सामान्य वॉक-इन बिक्री",
    "Default language for customer receipts, table QR orders, and staff POS terminals": "ग्राहक रसीदों, टेबल क्यूआर ऑर्डर और स्टाफ पीओएस टर्मिनलों के लिए डिफ़ॉल्ट भाषा",
    "Default settings for 1-click WhatsApp receipts to customers": "ग्राहकों को 1-क्लिक व्हाट्सएप रसीद भेजने के लिए डिफ़ॉल्ट सेटिंग्स",
    "Default terms and notes auto-loaded into new Quotations": "नए कोटेशन में स्वतः लोड होने वाले डिफ़ॉल्ट नियम और नोट्स",
    "Delete Bill": "बिल हटाएं",
    "Delete Selected": "चयनित हटाएं",
    "Delete this brand?": "क्या इस ब्रांड को हटाना है?",
    "Delete this category?": "क्या इस श्रेणी को हटाना है?",
    "Delete this customer?": "क्या इस ग्राहक को हटाना है?",
    "Delete this product?": "क्या इस उत्पाद को हटाना है?",
    "Delete this snapshot?": "क्या इस स्नैपशॉट को हटाना है?",
    "Delete this supplier?": "क्या इस आपूर्तिकर्ता को हटाना है?",
    "Delete this unit?": "क्या इस इकाई (यूनिट) को हटाना है?",
    "Delete translation key": "अनुवाद कुंजी हटाएं",
    "Delivery": "डिलीवरी",
    "Delivery Address": "डिलीवरी का पता",
    "Delivery Address / Order Notes": "डिलीवरी का पता / ऑर्डर नोट्स",
    "Departments & tax rates": "विभाग और कर दरें",
    "Description": "विवरण",
    "Description (Optional)": "विवरण (वैकल्पिक)",
    "Description (optional)": "विवरण (वैकल्पिक)",
    "Destination:": "गंतव्य:",
    "Didn't receive code? Resend Code": "कोड नहीं मिला? कोड पुनः भेजें",
    "Difference": "अंतर",
    "Digital QR menu & WhatsApp store": "डिजिटल क्यूआर मेनू और व्हाट्सएप स्टोर",
    "Digital catalog & WhatsApp share": "डिजिटल कैटलॉग और व्हाट्सएप शेयर",
    "Dine-In": "डाइन-इन (रेस्तरां में भोजन)",
    "Dine-In, Takeaway & Delivery": "डाइन-इन, टेकअवे और डिलीवरी",
    "Dining History": "भोजन इतिहास (डाइनिंग हिस्ट्री)",
    "Direct Invitation Link": "प्रत्यक्ष निमंत्रण लिंक",
    "Direct Proposal / Walk-in Client": "प्रत्यक्ष प्रस्ताव / वॉक-इन क्लाइंट",
    "Disable": "अक्षम करें",
    "Disabled": "अक्षम",
    "Disabled — sends clean structured text email only.": "अक्षम — केवल संरचित टेक्स्ट ईमेल भेजता है।",
    "Discount ($)": "छूट ($)",
    "Discount:": "छूट:",
    "Discounts": "छूट (डिस्काउंट्स)",
    "Dishes, ingredients & pricing": "व्यंजन, सामग्री और मूल्य निर्धारण",
    "Dispatch & Share Invoice:": "इनवॉइस भेजें और साझा करें:",
    "Dispatching...": "भेजा जा रहा है...",
    "Displayed in browser tabs for your tenant store": "आपके किरायेदार स्टोर के ब्राउज़र टैब में प्रदर्शित",
    "Displayed in sidebar, PDF invoices, and online catalog header": "साइडबार, पीडीएफ इनवॉइस और ऑनलाइन कैटलॉग हेडर में प्रदर्शित",
    "Docking Behavior": "डॉकिंग व्यवहार",
    "Docking Screen Position": "डॉकिंग स्क्रीन स्थिति",
    "Document / Tax ID": "दस्तावेज़ / टैक्स आईडी",
    "Download & Print PDF Invoice": "पीडीएफ इनवॉइस डाउनलोड और प्रिंट करें",
    "Download / Stream PDF": "पीडीएफ डाउनलोड / देखें",
    "Draft": "ड्राफ्ट (मसौदा)",
    "Draft Proposal": "ड्राफ्ट प्रस्ताव",
    "Driver / Courier": "ड्राइवर / कूरियर",
    "Driver name": "ड्राइवर का नाम",
    "Due Date": "नियत तारीख (ड्यू डेट)",
    "Due Date:": "नियत तारीख:",
    "EMV & NFC": "ईएमवी और एनएफसी",
    "EUR": "यूरो (EUR)",
    "Edit": "संपादित करें",
    "Edit Bill": "बिल संपादित करें",
    "Edit Category": "श्रेणी संपादित करें",
    "Edit Customer": "ग्राहक संपादित करें",
    "Edit Floor Area": "फ्लोर क्षेत्र संपादित करें",
    "Edit Payment Method": "भुगतान विधि संपादित करें",
    "Edit Plan": "योजना संपादित करें",
    "Edit Product": "उत्पाद संपादित करें",
    "Edit Quotation": "कोटेशन संपादित करें",
    "Edit Supplier": "आपूर्तिकर्ता संपादित करें",
    "Edit Table": "टेबल संपादित करें",
    "Edit Unit": "इकाई संपादित करें",
    "Edit Vendor Bill / Expense": "विक्रेता बिल / व्यय संपादित करें",
    "Email": "ईमेल",
    "Email & WhatsApp Invoice Sharing": "ईमेल और व्हाट्सएप इनवॉइस शेयरिंग",
    "Email Address *": "ईमेल पता *",
    "Email Dispatch (SMTP)": "ईमेल डिस्पैच (एसएमटीपी)",
    "Email From Name (Sender Name) *": "प्रेषक का नाम (Sender Name) *",
    "Email Invoice": "इनवॉइस ईमेल करें",
    "Email Invoice Receipt": "इनवॉइस रसीद ईमेल करें",
    "Email Us": "हमें ईमेल करें",
    "Email:": "ईमेल:",
    "Emerald Green": "पन्ना हरा (एमराल्ड)",
    "Emerald Mint": "एमराल्ड मिंट",
    "Enable": "सक्षम करें",
    "Enable this payment method for POS checkout": "पीओएस चेकआउट के लिए इस भुगतान विधि को सक्षम करें",
    "Enable, disable or add new multilingual languages to the system": "सिस्टम में नई बहुभाषी भाषाएं सक्षम, अक्षम या जोड़ें",
    "Encryption": "एन्क्रिप्शन",
    "Encryption Protocol *": "एन्क्रिप्शन प्रोटोकॉल *",
    "English Name *": "अंग्रेजी नाम *",
    "Enter a pre-purchased platform license key to activate this plan without card payment.": "कार्ड भुगतान के बिना इस योजना को सक्रिय करने के लिए पूर्व-खरीदी गई लाइसेंस कुंजी दर्ज करें।",
    "Enter bank accounts & payment instructions...": "बैंक खाते और भुगतान निर्देश दर्ज करें...",
    "Enter default quotation policy, deliverables & terms...": "डिफ़ॉल्ट कोटेशन नीति, डिलिवरेबल्स और शर्तें दर्ज करें...",
    "Enter invoice policy & terms...": "इनवॉइस नीति और शर्तें दर्ज करें...",
    "Enter password": "पासवर्ड दर्ज करें",
    "Enter your offline activation code or subscription license key to renew or upgrade your store.": "अपने स्टोर को नवीनीकृत या अपग्रेड करने के लिए ऑफ़लाइन सक्रियण कोड या लाइसेंस कुंजी दर्ज करें।",
    "Euro": "यूरो",
    "Exchange rates against your base currency, for reporting and multi-currency displays": "रिपोर्टिंग और बहु-मुद्रा प्रदर्शन के लिए मूल मुद्रा के मुकाबले विनिमय दरें",
    "Exit": "बाहर निकलें",
    "Exit Fullscreen": "फ़ुलस्क्रीन से बाहर निकलें",
    "Expected": "अपेक्षित",
    "Expected Cash": "अपेक्षित नकद राशि",
    "Expected Cash (System)": "अपेक्षित नकद राशि (सिस्टम)",
    "Expected Cash in Drawer": "दराज में अपेक्षित नकद राशि",
    "Expense Category": "व्यय श्रेणी",
    "Expires": "समाप्ति",
    "Expires:": "समाप्ति तिथि:",
    "Expiry Date": "समाप्ति तिथि (एक्सपायरी)",
    "Expiry Date (MM/YY) *": "समाप्ति तिथि (महीना/वर्ष) *",
    "Fail": "विफल",
    "Fast barcode scan & cash checkout": "त्वरित बारकोड स्कैन और नकद चेकआउट",
    "Fast barcode scanning, 3-column product cards, category chips & right-side cart drawer.": "फास्ट बारकोड स्कैनिंग, 3-कॉलम उत्पाद कार्ड, श्रेणी चिप्स और दाईं ओर कार्ट दराज।",
    "Favicon URL": "फेविकॉन यूआरएल",
    "Favorites": "पसंदीदा (फेवरिट्स)",
    "Feature Modules Suite": "फीचर मॉड्यूल सूट",
    "Filter by Tenant / Company ID…": "किरायेदार / कंपनी आईडी द्वारा फ़िल्टर करें…",
    "Filter by event action (e.g. smtp.updated)…": "इवेंट कार्रवाई द्वारा फ़िल्टर करें (उदा. smtp.updated)…",
    "Financial & Currency": "वित्तीय एवं मुद्रा",
    "Financial Management": "वित्तीय प्रबंधन",
    "Fixed ($)": "निश्चित राशि ($)",
    "Fixed Docked": "स्थिर डॉक किया गया",
    "Flag Emoji": "ध्वज इमोजी",
    "Floating / Free Drag": "फ्लोटिंग / स्वतंत्र ड्रैग",
    "Floor": "फ्लोर (तल)",
    "Floor Area": "फ्लोर क्षेत्र",
    "Floor plan is active. Take Dine-In orders, manage tables, monitor live kitchen tickets, and handle takeaway or deliveries.": "फ्लोर प्लान सक्रिय है। डाइन-इन ऑर्डर लें, टेबल प्रबंधित करें, लाइव किचन टिकटों की निगरानी करें, और टेकअवे या डिलीवरी संभालें।",
    "Food & Restaurant": "भोजन एवं रेस्तरां",
    "Food & Restaurant Mode": "फूड एवं रेस्तरां मोड",
    "Food & Restaurant Mode Active": "फूड एवं रेस्तरां मोड सक्रिय",
    "Food & Restaurant POS": "फूड एवं रेस्तरां पीओएस",
    "Food Item": "खाद्य पदार्थ",
    "Food Items:": "खाद्य पदार्थ:",
    "Food Menu": "फूड मेनू",
    "Food Suppliers": "खाद्य आपूर्तिकर्ता",
    "For restaurants, cafes, bars & food trucks. Includes floor plans & live tables, KOT tickets, Kitchen Display (KDS), Dine-In/Takeaway routing, and QR table ordering.": "रेस्तरां, कैफे, बार और फूड ट्रक के लिए। फ्लोर प्लान और लाइव टेबल, केओटी टिकट, किचन डिस्प्ले (केडीएस), डाइन-इन/टेकअवे और क्यूआर टेबल ऑर्डरिंग शामिल है।",
    "For supermarkets, clothing, electronics & retail shops. Includes barcode scanning, cash register, quotations, invoices, and standard stock management.": "सुपरमार्केट, कपड़ों, इलेक्ट्रॉनिक्स और खुदरा दुकानों के लिए। बारकोड स्कैनिंग, कैश रजिस्टर, कोटेशन, इनवॉइस और मानक स्टॉक प्रबंधन शामिल है।",
    "Forest Green": "गहरा वन हरा",
    "Free Evaluation": "निःशुल्क मूल्यांकन",
    "Free Floating": "मुक्त फ्लोटिंग",
    "Full Access": "पूर्ण पहुंच (फुल एक्सेस)",
    "Full Name *": "पूरा नाम *",
    "Full Name as on Card": "कार्ड पर अंकित पूरा नाम",
    "Fullscreen": "फ़ुलस्क्रीन",
    "Fully Settled": "पूर्णतः चुकता (सुलझा हुआ)",
    "Fully Settled (Paid)": "पूर्णतः चुकता (भुगतान किया गया)",
    "Function toolbar, vibrant department tiles & right receipt checkout slip.": "फ़ंक्शन टूलबार, जीवंत विभाग टाइलें और दाईं ओर रसीद चेकआउट पर्ची।",
    "GRAND TOTAL": "कुल योग (Grand Total)",
    "General": "सामान्य",
    "General Retail": "सामान्य खुदरा (रिटेल)",
    "General Retail POS (Default)": "सामान्य खुदरा पीओएस (डिफ़ॉल्ट)",
    "Generate Code": "कोड जनरेट करें",
    "Generate Key": "कुंजी जनरेट करें",
    "Generate Offline License Voucher": "ऑफ़लाइन लाइसेंस वाउचर जनरेट करें",
    "Generate and manage offline license vouchers for instant self-registration and renewals": "तत्काल स्व-पंजीकरण और नवीनीकरण के लिए ऑफ़लाइन लाइसेंस वाउचर जनरेट और प्रबंधित करें",
    "Generates and attaches clean stylized invoice PDF.": "स्वच्छ स्टाइलिश इनवॉइस पीडीएफ बनाता और संलग्न करता है।",
    "Generates and attaches clean stylized proposal PDF.": "स्वच्छ स्टाइलिश प्रस्ताव पीडीएफ बनाता और संलग्न करता है।",
    "Global Audit Trail & Security Logs": "वैश्विक ऑडिट ट्रेल और सुरक्षा लॉग",
    "Global Platform SMTP Email Configuration": "वैश्विक प्लेटफ़ॉर्म एसएमटीपी ईमेल कॉन्फ़िगरेशन",
    "Global Tax Reference Matrix": "वैश्विक कर संदर्भ मैट्रिक्स",
    "Grand Total:": "कुल योग:",
    "Guest Directory": "अतिथि निर्देशिका",
    "Guest name": "अतिथि का नाम",
    "Guests": "अतिथि",
    "HSN / SAC codes & VAT presets": "एचएसएन / एसएसी कोड और वैट प्रीसेट",
    "Hardware Trust Bar": "हार्डवेयर ट्रस्ट बार",
    "Hero Top Badge Text": "हीरो शीर्ष बैज पाठ",
    "Hero Value Proposition Subtitle": "हीरो वैल्यू प्रपोजीशन उपशीर्षक",
    "History": "इतिहास",
    "History, print receipts & refunds": "इतिहास, रसीद प्रिंट और रिफंड",
    "Host": "होस्ट",
    "INV-": "INV-",
    "IP Address": "आईपी पता",
    "If you need access to this section, please request permission from your store": "यदि आपको इस अनुभाग तक पहुंच की आवश्यकता है, तो कृपया अपने स्टोर से अनुमति का अनुरोध करें",
    "Immediate": "तत्काल",
    "Immediate settlement": "तत्काल निपटान",
    "Immutable event record of administrative actions, config mutations, and security events": "प्रशासनिक कार्यों, कॉन्फ़िग परिवर्तनों और सुरक्षा घटनाओं का अपरिवर्तनीय रिकॉर्ड",
    "Import all missing keys from English template": "अंग्रेजी टेम्पलेट से सभी अनुपलब्ध कुंजियाँ आयात करें",
    "In Cooking": "पक रहा है (तैयारी जारी)",
    "Includes: Retail Counter • Barcode POS • Quotes": "शामिल हैं: रिटेल काउंटर • बारकोड पीओएस • कोटेशन",
    "Includes: Tables • KOT • Kitchen KDS • QR Menus": "शामिल हैं: टेबल्स • केओटी • किचन केडीएस • क्यूआर मेनू",
    "Initial Status": "प्रारंभिक स्थिति",
    "Initial Subscription Plan": "प्रारंभिक सदस्यता योजना",
    "Inquiry Contact Form": "पूछताछ संपर्क फ़ॉर्म",
    "Installation complete. The installer is now locked.": "स्थापना पूर्ण। इंस्टॉलर अब लॉक है।",
    "Instant Tax Receipt Generated": "तत्काल टैक्स रसीद जनरेट की गई",
    "Internal Notes": "आंतरिक नोट्स",
    "Inv:": "इनवॉइस:",
    "Inventory / Goods": "इन्वेंट्री / माल",
    "Inventory / Raw Materials": "इन्वेंट्री / कच्चा माल",
    "Invite New Team Member": "नए टीम सदस्य को आमंत्रित करें",
    "Invite User": "उपयोगकर्ता को आमंत्रित करें",
    "Invoice #": "इनवॉइस नं. #",
    "Invoice / Receipt Attachment (PDF, Image)": "इनवॉइस / रसीद अनुलग्नक (पीडीएफ, छवि)",
    "Invoice Prefix": "इनवॉइस उपसर्ग (Prefix)",
    "Invoice Terms & Conditions (Rich-Text)": "इनवॉइस नियम एवं शर्तें (रिच-टेक्स्ट)",
    "Invoice Terms & Policy": "इनवॉइस नियम और नीति",
    "Invoice prefixes, default quotation terms, and payment instructions": "इनवॉइस उपसर्ग, डिफ़ॉल्ट कोटेशन शर्तें और भुगतान निर्देश",
    "Item": "आइटम",
    "Item & Description": "आइटम और विवरण",
    "Item & Scope Description": "आइटम और कार्यक्षेत्र विवरण",
    "Item Code": "आइटम कोड",
    "Item or service name *": "आइटम या सेवा का नाम *",
    "Itemized GST/VAT Tax Invoices": "मदवार जीएसटी/वैट टैक्स इनवॉइस",
    "Itemized tax receipts for store subscriptions, license activations, and renewals": "स्टोर सदस्यता, लाइसेंस सक्रियण और नवीनीकरण के लिए मदवार टैक्स रसीदें",
    "Jurisdiction standards, default VAT rates, and GST/HSN classification guidelines": "अधिकार क्षेत्र मानक, डिफ़ॉल्ट वैट दरें और जीएसटी/एचएसएन वर्गीकरण दिशानिर्देश",
    "Keep Order On Screen": "ऑर्डर को स्क्रीन पर रखें",
    "Keep the navigation bar pinned in view while scrolling through long views and forms": "लंबे दृश्यों और रूपों के माध्यम से स्क्रॉल करते समय नेविगेशन बार को स्क्रीन पर पिन रखें",
    "Key Name (Exact String) *": "कुंजी का नाम (सटीक स्ट्रिंग) *",
    "Keypad": "कीपैड",
    "Keypad Entry": "कीपैड प्रविष्टि",
    "Kitchen Display System": "किचन डिस्प्ले सिस्टम (केडीएस)",
    "Kitchen Display System (KDS)": "किचन डिस्प्ले सिस्टम (KDS)",
    "Kitchen KDS": "किचन केडीएस",
    "Kitchen Menu & Catalog": "किचन मेनू और कैटलॉग",
    "Kitchen Note": "किचन नोट",
    "Kitchen Note (Optional)": "किचन नोट (वैकल्पिक)",
    "Landing Neon Lime Accent": "लैंडिंग नियॉन लाइम एक्सेंट",
    "Landing Page Sections Controller": "लैंडिंग पेज अनुभाग नियंत्रक",
    "Landing Primary Emerald": "लैंडिंग प्राइमरी एमराल्ड",
    "Language Code (ISO) *": "भाषा कोड (ISO) *",
    "Language:": "भाषा:",
    "Launch Selected POS Register": "चयनित पीओएस रजिस्टर लॉन्च करें",
    "Layout": "लेआउट",
    "Layout Direction:": "लेआउट दिशा:",
    "Lead capture form": "लीड कैप्चर फ़ॉर्म",
    "Left Sidebar": "बायां साइडबार",
    "Left vertical function menu, vibrant department tiles, paginated grid & thermal receipt checkout slip.": "बायां लंबवत फ़ंक्शन मेनू, जीवंत विभाग टाइलें, पृष्ठबद्ध ग्रिड और थर्मल रसीद चेकआउट पर्ची।",
    "Left-to-Right (LTR)": "बाएं से दाएं (LTR)",
    "Legal": "कानूनी (लीगल)",
    "Legal / Company Name": "कानूनी / कंपनी का नाम",
    "Library": "लाइब्रेरी",
    "License Voucher": "लाइसेंस वाउचर",
    "Line Items & Scope Specifications": "लाइन आइटम और कार्यक्षेत्र विनिर्देश",
    "Link Expiration": "लिंक समाप्ति",
    "Linked Supplier (Optional)": "लिंक किया गया आपूर्तिकर्ता (वैकल्पिक)",
    "Live": "लाइव",
    "Live KDS": "लाइव केडीएस",
    "Live KOT preparation queue": "लाइव केओटी तैयारी कतार",
    "Live Kitchen Tickets": "लाइव किचन टिकट",
    "Live Metric Counters": "लाइव मीट्रिक काउंटर",
    "Live POS": "लाइव पीओएस",
    "Live Status:": "लाइव स्थिति:",
    "Live Table Status & QR Menus": "लाइव टेबल स्थिति और क्यूआर मेनू",
    "Location": "स्थान",
    "Logistics & Freight": "रसद और माल ढुलाई",
    "Logistics, Freight & Delivery": "रसद, माल ढुलाई और वितरण",
    "Low Stock Warnings": "कम स्टॉक की चेतावनी",
    "Loyalty Points": "लॉयल्टी अंक (पॉइंट्स)",
    "Main Headline Title *": "मुख्य शीर्षक *",
    "Maintenance & Repairs": "रखरखाव और मरम्मत",
    "Maintenance Lockout Message": "रखरखाव लॉकडाउन संदेश",
    "Manage": "प्रबंधित करें",
    "Manage Floor Plan": "फ्लोर प्लान प्रबंधित करें",
    "Manage manufacturers and brands": "निर्माताओं और ब्रांडों का प्रबंधन करें",
    "Manage seating floor areas, table occupancy statuses, and QR code digital menus": "बैठने के फर्श क्षेत्रों, टेबल अधिभोग स्थिति और क्यूआर कोड डिजिटल मेनू प्रबंधित करें",
    "Manage signed-in sessions across browsers and POS registers": "ब्राउज़र और पीओएस रजिस्टरों में साइन-इन सत्र प्रबंधित करें",
    "Manage supported platform languages, customize JSON translation files, and synchronize multilingual dictionaries": "समर्थित प्लेटफ़ॉर्म भाषाओं को प्रबंधित करें, जेएसओएन अनुवाद फ़ाइलों को अनुकूलित करें और शब्दकोशों को सिंक्रनाइज़ करें",
    "Manage units of measure for inventory and billing": "इन्वेंट्री और बिलिंग के लिए माप की इकाइयों का प्रबंधन करें",
    "Manage vendor bills, operational expenses, utility costs, supplier settlements, and payment proofs.": "विक्रेता बिल, परिचालन व्यय, उपयोगिता लागत, आपूर्तिकर्ता बस्तियों और भुगतान प्रमाणों का प्रबंधन करें।",
    "Manage your store subscription plan, redeem activation keys, and access compliant tax invoices": "अपने स्टोर सदस्यता योजना का प्रबंधन करें, सक्रियण कुंजी रिडीम करें, और कर इनवॉइस तक पहुंचें",
    "Manual movements this shift": "इस शिफ्ट में मैनुअल संचलन",
    "Mark as Ready": "तैयार के रूप में चिह्नित करें",
    "Mark as Served": "परोसा गया के रूप में चिह्नित करें",
    "Marketing & Ads": "मार्केटिंग और विज्ञापन",
    "Marketing & Promotions": "मार्केटिंग और प्रचार",
    "Max POS Devices Limit": "अधिकतम पीओएस डिवाइस सीमा",
    "Max Users Limit": "अधिकतम उपयोगकर्ता सीमा",
    "Measurement Units": "माप इकाइयाँ",
    "Member:": "सदस्य:",
    "Membership": "सदस्यता",
    "Menu": "मेनू",
    "Menu Dishes & Stock": "मेनू व्यंजन और स्टॉक",
    "Menu sections & tax rates": "मेनू अनुभाग और कर दरें",
    "Method": "विधि",
    "Method Name": "विधि का नाम",
    "Method Name *": "विधि का नाम *",
    "Method:": "विधि:",
    "Midnight Slate": "मिडनाइट स्लेट",
    "Migration failed. Check the output above and try again.": "माइग्रेशन विफल रहा। उपरोक्त आउटपुट जांचें और पुनः प्रयास करें।",
    "Minimum Alert Stock *": "न्यूनतम अलर्ट स्टॉक *",
    "Minimum Client Build Version": "न्यूनतम क्लाइंट बिल्ड संस्करण",
    "Module": "मॉड्यूल",
    "Monthly": "मासिक",
    "Monthly Snapshot": "मासिक स्नैपशॉट",
    "Multi-Language & Translation File Editor": "बहु-भाषा और अनुवाद फ़ाइल संपादक",
    "N/A": "लागू नहीं (N/A)",
    "Name": "नाम",
    "Name *": "नाम *",
    "Native Name": "मूल भाषा में नाम",
    "Never": "कभी नहीं",
    "Never (Lifetime)": "कभी नहीं (आजीवन)",
    "Never (Permanent link)": "कभी नहीं (स्थायी लिंक)",
    "New": "नया",
    "New Brand": "नया ब्रांड",
    "New Category": "नई श्रेणी",
    "New Customer": "नया ग्राहक",
    "New POS Credit Sale": "नई पीओएस क्रेडिट बिक्री",
    "New Product": "नया उत्पाद",
    "New Quotation": "नया कोटेशन",
    "New Sale": "नई बिक्री",
    "New Supplier": "नया आपूर्तिकर्ता",
    "New Unit": "नई इकाई",
    "New orders from Dine-In tables, Takeaway, Delivery, or QR Digital Menu will appear here in real-time.": "डाइन-इन टेबल, टेकअवे, डिलीवरी या क्यूआर डिजिटल मेनू से नए ऑर्डर वास्तविक समय में यहां दिखाई देंगे।",
    "No Cash Register Open": "कोई कैश रजिस्टर खुला नहीं है",
    "No Floor Assigned": "कोई फ्लोर असाइन नहीं किया गया",
    "No Image": "कोई छवि नहीं",
    "No Plan (Unlimited / Manual)": "कोई योजना नहीं (असीमित / मैनुअल)",
    "No accounts receivable records match current filters.": "वर्तमान फ़िल्टर से कोई प्राप्य खाता रिकॉर्ड मेल नहीं खाता।",
    "No activation codes generated yet. Click \"+ Generate Key\" above.": "अभी तक कोई सक्रियण कोड जनरेट नहीं हुआ है। ऊपर \"+ कुंजी जनरेट करें\" पर क्लिक करें।",
    "No active products available.": "कोई सक्रिय उत्पाद उपलब्ध नहीं है।",
    "No active sessions found.": "कोई सक्रिय सत्र नहीं मिला।",
    "No brands yet. Click \"+ New Brand\" to add one.": "अभी कोई ब्रांड नहीं है। एक जोड़ने के लिए \"+ नया ब्रांड\" पर क्लिक करें।",
    "No cash movements recorded yet.": "अभी तक कोई नकद संचलन दर्ज नहीं किया गया है।",
    "No catalogs published yet.": "अभी तक कोई कैटलॉग प्रकाशित नहीं हुआ है।",
    "No categories yet. Click \"+ New Category\" to create one.": "अभी कोई श्रेणी नहीं है। एक बनाने के लिए \"+ नई श्रेणी\" पर क्लिक करें।",
    "No closed registers yet.": "अभी तक कोई बंद रजिस्टर नहीं है।",
    "No contact details": "कोई संपर्क विवरण नहीं",
    "No customer records found.": "कोई ग्राहक रिकॉर्ड नहीं मिला।",
    "No customers found matching": "इससे मेल खाने वाला कोई ग्राहक नहीं मिला",
    "No customers registered yet.": "अभी तक कोई ग्राहक पंजीकृत नहीं हुआ है।",
    "No dining floor areas created yet.": "अभी तक कोई डाइनिंग फ्लोर क्षेत्र नहीं बनाया गया है।",
    "No food items found. Use \"+ Add Product\" in Products menu to create items.": "कोई खाद्य पदार्थ नहीं मिला। आइटम बनाने के लिए उत्पाद मेनू में \"+ उत्पाद जोड़ें\" का उपयोग करें।",
    "No items added to receipt yet.": "रसीद में अभी तक कोई आइटम नहीं जोड़ा गया है।",
    "No items found matching your search.": "आपकी खोज से मेल खाने वाला कोई आइटम नहीं मिला।",
    "No items selected for this order.": "इस ऑर्डर के लिए कोई आइटम नहीं चुना गया।",
    "No other currencies configured.": "कोई अन्य मुद्रा कॉन्फ़िगर नहीं की गई है।",
    "No payment methods configured. Click \"+ Add Method\" to create one.": "कोई भुगतान विधि कॉन्फ़िगर नहीं की गई है। एक बनाने के लिए \"+ विधि जोड़ें\" पर क्लिक करें।",
    "No products available in catalog.": "कैटलॉग में कोई उत्पाद उपलब्ध नहीं है।",
    "No products available in this department.": "इस विभाग में कोई उत्पाद उपलब्ध नहीं है।",
    "No products in catalog yet.": "कैटलॉग में अभी तक कोई उत्पाद नहीं है।",
    "No products yet. Click \"+ New Product\" to add items.": "अभी कोई उत्पाद नहीं है। आइटम जोड़ने के लिए \"+ नया उत्पाद\" पर क्लिक करें।",
    "No quotations found matching the filter criteria.": "फ़िल्टर मानदंडों से मेल खाने वाला कोई कोटेशन नहीं मिला।",
    "No recent kitchen tickets.": "हाल ही का कोई किचन टिकट नहीं है।",
    "No recent sales records found.": "हाल ही का कोई बिक्री रिकॉर्ड नहीं मिला।",
    "No sales found.": "कोई बिक्री नहीं मिली।",
    "No sales recorded yet this shift.": "इस शिफ्ट में अभी तक कोई बिक्री दर्ज नहीं की गई है।",
    "No sales recorded.": "कोई बिक्री दर्ज नहीं की गई।",
    "No subscription tax invoices generated yet.": "अभी तक कोई सदस्यता टैक्स इनवॉइस जनरेट नहीं हुआ है।",
    "No suppliers yet. Click \"+ New Supplier\" to add one.": "अभी कोई आपूर्तिकर्ता नहीं है। जोड़ने के लिए \"+ नया आपूर्तिकर्ता\" पर क्लिक करें।",
    "No tables registered for this floor. Click \"+ Add Table\" to start.": "इस तल के लिए कोई टेबल पंजीकृत नहीं है। शुरू करने के लिए \"+ टेबल जोड़ें\" पर क्लिक करें।",
    "No team members found. Click \"+ Invite User\" to add staff.": "कोई टीम सदस्य नहीं मिला। कर्मचारियों को जोड़ने के लिए \"+ उपयोगकर्ता को आमंत्रित करें\" पर क्लिक करें।",
    "No units yet. Click \"+ New Unit\" to add one.": "अभी कोई इकाई नहीं है। एक जोड़ने के लिए \"+ नई इकाई\" पर क्लिक करें।",
    "No vendor bills or operational expenses match current filters.": "वर्तमान फ़िल्टर से कोई विक्रेता बिल या परिचालन व्यय मेल नहीं खाता।",
    "Non-Supplier / General Vendor": "गैर-आपूर्तिकर्ता / सामान्य विक्रेता",
    "None": "कोई नहीं",
    "None (Port 25)": "कोई नहीं (पोर्ट 25)",
    "None (Use built-in modules only)": "कोई नहीं (केवल इन-बिल्ट मॉड्यूल का उपयोग करें)",
    "Not Set": "सेट नहीं है",
    "Note:": "नोट:",
    "Notes & Remarks": "नोट्स और टिप्पणियां",
    "Notes regarding installment / settlement...": "किस्त / निपटान से संबंधित नोट्स...",
    "Notification & Dispatch": "अधिसूचना और प्रेषण",
    "OFF": "बंद",
    "ON": "चालू",
    "OVERDUE": "अतिदेय (विलंबित)",
    "Occupied": "व्यस्त (अधिग्रहित)",
    "Ocean Sky": "ओशन स्काई",
    "Office Supplies": "कार्यालय आपूर्ति",
    "Office Supplies & Software": "कार्यालय आपूर्ति और सॉफ्टवेयर",
    "Official Razorpay Payment Gateway": "आधिकारिक रेज़रपे भुगतान गेटवे",
    "Official Tax Invoices & Payment Receipts": "आधिकारिक टैक्स इनवॉइस और भुगतान रसीदें",
    "One-Time Invitation Code": "एकमुश्त निमंत्रण कोड",
    "Online Catalog": "ऑनलाइन कैटलॉग",
    "Online QR Menu": "ऑनलाइन क्यूआर मेनू",
    "Open Cash Register": "कैश रजिस्टर खोलें",
    "Open KDS": "किचन डिस्प्ले (KDS) खोलें",
    "Open Link": "लिंक खोलें",
    "Open Register": "रजिस्टर खोलें",
    "Open Restaurant POS": "रेस्तरां पीओएस खोलें",
    "Open Table POS": "टेबल पीओएस खोलें",
    "Open WhatsApp & Send": "व्हाट्सएप खोलें और भेजें",
    "Open a register with a starting cash float to begin tracking today's shift.": "आज की शिफ्ट को ट्रैक करना शुरू करने के लिए शुरुआती कैश राशि के साथ एक रजिस्टर खोलें।",
    "Open/close the register, track cash in & out, and generate X/Z shift reports.": "रजिस्टर खोलें/बंद करें, कैश इन व आउट ट्रैक करें, और X/Z शिफ्ट रिपोर्ट जनरेट करें।",
    "Opened": "खुला हुआ",
    "Opening": "प्रारंभिक",
    "Opening Float": "प्रारंभिक कैश (ओपनिंग फ्लोट)",
    "Opening Float ($)": "प्रारंभिक कैश राशि ($)",
    "Operating Mode": "ऑपरेटिंग मोड",
    "Option:": "विकल्प:",
    "Optional": "वैकल्पिक",
    "Options": "विकल्प",
    "Or Direct Image URL": "या प्रत्यक्ष छवि यूआरएल",
    "Order": "ऑर्डर",
    "Order No.": "ऑर्डर संख्या",
    "Order Notes & Remarks (Printed on Receipt)": "ऑर्डर नोट्स और टिप्पणियां (रसीद पर मुद्रित)",
    "Order Notes & Remarks:": "ऑर्डर नोट्स और टिप्पणियां:",
    "Order Sent to Kitchen!": "ऑर्डर किचन में भेज दिया गया!",
    "Order Subtotal": "ऑर्डर उप-योग",
    "Order via WhatsApp": "व्हाट्सएप के जरिए ऑर्डर करें",
    "Orders & Cash": "ऑर्डर और नकद",
    "Orders & thermal receipts": "ऑर्डर और थर्मल रसीदें",
    "Organize products into POS categories": "उत्पादों को पीओएस श्रेणियों में व्यवस्थित करें",
    "Other Currencies (Reference Rates)": "अन्य मुद्राएं (संदर्भ दरें)",
    "Other Expenses": "अन्य व्यय",
    "Over": "अधिशेष (ज्यादा)",
    "Overdue Accounts": "अतिदेय खाते",
    "Overdue Balance": "अतिदेय बकाया",
    "Overdue Bills": "अतिदेय बिल",
    "Override unit price": "इकाई मूल्य ओवरराइड करें",
    "PARTIAL": "आंशिक",
    "PDF": "PDF",
    "POS Checkout & Payment": "पीओएस चेकआउट और भुगतान",
    "POS Server": "पीओएस सर्वर",
    "POS, Inventory, KOT, Finance": "पीओएस, इन्वेंट्री, केओटी, वित्त",
    "PROPOSAL PREPARED FOR:": "प्रस्ताव इनके लिए तैयार किया गया:",
    "Page Title *": "पृष्ठ शीर्षक *",
    "Paid Amount:": "भुगतान की गई राशि:",
    "Paid so far": "अब तक भुगतान किया गया",
    "Partially Paid": "आंशिक भुगतान किया गया",
    "Pass": "सफल",
    "Password": "पासवर्ड",
    "Pay": "भुगतान करें",
    "Pay & Settle Bill": "भुगतान करें और बिल निपटाएं",
    "Pay & Upgrade": "भुगतान करें और अपग्रेड करें",
    "Pay Bill": "बिल का भुगतान करें",
    "Pay Method:": "भुगतान विधि:",
    "Payable To": "इन्हें देय",
    "Payment": "भुगतान",
    "Payment Date": "भुगतान तिथि",
    "Payment Information": "भुगतान जानकारी",
    "Payment Method": "भुगतान विधि",
    "Payment Method:": "भुगतान विधि:",
    "Payment Proof / Bank Receipt (Optional)": "भुगतान प्रमाण / बैंक रसीद (वैकल्पिक)",
    "Payment Remarks": "भुगतान टिप्पणियां",
    "Payment required to activate services & generate tax invoice": "सेवाओं को सक्रिय करने और टैक्स इनवॉइस जनरेट करने के लिए भुगतान आवश्यक है",
    "Payment terms, bank details, purchase order #...": "भुगतान की शर्तें, बैंक विवरण, खरीद आदेश संख्या...",
    "Payroll & Salaries": "पेरोल और वेतन",
    "Payroll & Staff Wages": "पेरोल और स्टाफ मजदूरी",
    "Pending / In Cooking": "लंबित / तैयारी जारी",
    "Pending / Unpaid": "लंबित / अवैतनिक",
    "Pending Invoices": "लंबित इनवॉइस",
    "Pending Orders": "लंबित ऑर्डर",
    "Percent (%)": "प्रतिशत (%)",
    "Perfect for small retail stores": "छोटे खुदरा स्टोर के लिए बिल्कुल सही",
    "Permissions Matrix": "अनुमतियाँ मैट्रिक्स",
    "Perpetual / Lifetime": "स्थायी / आजीवन",
    "Phone / Contact": "फ़ोन / संपर्क",
    "Phone / WhatsApp": "फ़ोन / व्हाट्सएप",
    "Phone / WhatsApp (Optional)": "फ़ोन / व्हाट्सएप (वैकल्पिक)",
    "Phone number (+1 555 0199)": "फ़ोन नंबर (+1 555 0199)",
    "Phone:": "फ़ोन:",
    "Phrase Key *": "वाक्यांश कुंजी *",
    "Physical Address": "भौतिक पता",
    "Pickup Time": "पिकअप समय",
    "Piece, Kilogram, Box…": "टुकड़ा (पीस), किलोग्राम, डिब्बा…",
    "Pieces, kg, box, packs & liters": "पीस, किग्रा, डिब्बा, पैकेट और लीटर",
    "Plan": "प्लान",
    "Plan / Description": "प्लान / विवरण",
    "Plan details & invoices": "योजना विवरण और इनवॉइस",
    "Platform": "प्लेटफ़ॉर्म",
    "Platform Application Version": "प्लेटफ़ॉर्म एप्लिकेशन संस्करण",
    "Platform Brand Name *": "प्लेटफ़ॉर्म ब्रांड का नाम *",
    "Platform GST / Tax (18% • CGST 9% + SGST 9%)": "प्लेटफ़ॉर्म जीएसटी / टैक्स (18% • CGST 9% + SGST 9%)",
    "Platform Logo URL": "प्लेटफ़ॉर्म लोगो यूआरएल",
    "Platform Payment Gateways": "प्लेटफ़ॉर्म भुगतान गेटवे",
    "Please provide a valid name for all items.": "कृपया सभी मदों के लिए एक मान्य नाम प्रदान करें।",
    "Point your domain's": "अपने डोमेन को इंगित करें",
    "Points Delta (+/-)": "अंक अंतर (+/-)",
    "Points:": "अंक:",
    "Port": "पोर्ट",
    "Port *": "पोर्ट *",
    "Portions, kg, litres & grams": "हिस्से (पोर्शन), किग्रा, लीटर और ग्राम",
    "Postal Code": "पिन कोड / डाक कोड",
    "Prefix": "उपसर्ग (Prefix)",
    "Prepared By:": "द्वारा तैयार:",
    "Preset Quick Discounts": "प्रीसेट त्वरित छूट",
    "Preview": "पूर्वावलोकन",
    "Preview Landing Page": "लैंडिंग पेज का पूर्वावलोकन करें",
    "Price": "मूल्य",
    "Price ($)": "मूल्य ($)",
    "Pricing Plans Grid": "मूल्य निर्धारण योजना ग्रिड",
    "Primary CTA Button Label": "प्राथमिक सीटीए बटन लेबल",
    "Primary CTA URL": "प्राथमिक सीटीए यूआरएल",
    "Primary Payment Method": "प्राथमिक भुगतान विधि",
    "Print Kitchen Ticket (KOT)": "किचन टिकट (केओटी) प्रिंट करें",
    "Print Ticket": "टिकट प्रिंट करें",
    "Print receipt/invoice": "रसीद/इनवॉइस प्रिंट करें",
    "Processing Charge...": "शुल्क संसाधित हो रहा है...",
    "Processing Sale...": "बिक्री संसाधित हो रही है...",
    "Processing Transaction...": "लेन-देन संसाधित हो रहा है...",
    "Processing...": "प्रक्रिया जारी है...",
    "Product": "उत्पाद",
    "Product Brands": "उत्पाद ब्रांड",
    "Product Categories": "उत्पाद श्रेणियां",
    "Product Name *": "उत्पाद का नाम *",
    "Product brands & food options": "उत्पाद ब्रांड और खाद्य विकल्प",
    "Production / Live Mode": "उत्पादन / लाइव मोड",
    "Profile, printer, tax & domain": "प्रोफ़ाइल, प्रिंटर, टैक्स और डोमेन",
    "Profiles, history & loyalty": "प्रोफ़ाइल, इतिहास और लॉयल्टी",
    "Proof": "प्रमाण",
    "Provision New Store": "नया स्टोर तैयार करें",
    "Public / Publishable API Key": "सार्वजनिक / पब्लिश करने योग्य एपीआई कुंजी",
    "Publish Public Catalog": "सार्वजनिक कैटलॉग प्रकाशित करें",
    "Publish an Online Catalog": "एक ऑनलाइन कैटलॉग प्रकाशित करें",
    "Published Shareable Links": "प्रकाशित साझा करने योग्य लिंक",
    "QR Stand": "क्यूआर स्टैंड",
    "QUO-": "QUO-",
    "Qty": "मात्रा",
    "Qty:": "मात्रा:",
    "Quick Add Customer": "त्वरित ग्राहक जोड़ें",
    "Quotation & Invoice Document Accent Color": "कोटेशन और इनवॉइस दस्तावेज़ एक्सेंट रंग",
    "Quotation Prefix": "कोटेशन उपसर्ग (Prefix)",
    "Quotations & Proposals": "कोटेशन और प्रस्ताव",
    "Quote #": "कोटेशन नं. #",
    "Quote No:": "कोटेशन संख्या:",
    "Quote Reference:": "कोटेशन संदर्भ:",
    "Quote Terms & Notes": "कोटेशन नियम और नोट्स",
    "Quote Terms & Notes (Rich-Text)": "कोटेशन नियम और नोट्स (रिच-टेक्स्ट)",
    "Quotes, estimates & 1-click sales conversion": "कोटेशन, अनुमान और 1-क्लिक बिक्री रूपांतरण",
    "Quotes, proposals & estimates": "कोटेशन, प्रस्ताव और अनुमान",
    "Rate": "दर",
    "Razorpay": "Razorpay",
    "Ready to Serve": "परोसने के लिए तैयार",
    "Real-Time": "वास्तविक समय (रियल-टाइम)",
    "Real-time live kitchen order tracker & ticket bump screen (Auto-refreshing every 5s)": "वास्तविक समय लाइव किचन ऑर्डर ट्रैकर और टिकट स्क्रीन (हर 5 सेकंड में स्वतः रीफ़्रेश)",
    "Reason": "कारण",
    "Reason / Note": "कारण / नोट",
    "Receipt Prefixes & Bank Terms": "रसीद उपसर्ग और बैंक शर्तें",
    "Recent POS Transactions": "हाल ही के पीओएस लेन-देन",
    "Recipient Email Address": "प्राप्तकर्ता का ईमेल पता",
    "Recipient Email Address *": "प्राप्तकर्ता का ईमेल पता *",
    "Recipient WhatsApp Phone Number (with Country Code)": "प्राप्तकर्ता व्हाट्सएप फोन नंबर (देश कोड के साथ)",
    "Record Bill Settlement Payment": "बिल निपटान भुगतान दर्ज करें",
    "Record Cash In": "कैश इन (जमा) दर्ज करें",
    "Record Cash Out": "कैश आउट (निकासी) दर्ज करें",
    "Record Receivable Payment": "प्राप्य भुगतान दर्ज करें",
    "Redeem & Activate": "रिडीम और सक्रिय करें",
    "Redeem License Key": "लाइसेंस कुंजी रिडीम करें",
    "Ref #": "संदर्भ नं. #",
    "Ref / Card Last4": "संदर्भ / कार्ड के अंतिम 4 अंक",
    "Reference / Transaction / Check #": "संदर्भ / लेन-देन / चेक नं. #",
    "Register": "रजिस्टर",
    "Register History (Closed Shifts / Z-Reports)": "रजिस्टर इतिहास (बंद शिफ्ट / Z-रिपोर्ट्स)",
    "Register users and define what each one can see and do.": "उपयोगकर्ताओं को पंजीकृत करें और परिभाषित करें कि प्रत्येक क्या देख और कर सकता है।",
    "Registered on": "पंजीकृत दिनांक",
    "Registration prompt": "पंजीकरण संकेत",
    "Rejected": "अस्वीकृत",
    "Remaining": "शेष",
    "Remaining Balance": "शेष राशि",
    "Remaining Due": "शेष बकाया",
    "Remove": "हटाएं",
    "Remove split line": "विभाजित पंक्ति हटाएं",
    "Remove table": "टेबल हटाएं",
    "Rent & Facilities": "किराया और सुविधाएं",
    "Rent & Premises": "किराया और परिसर",
    "Rep:": "प्रतिनिधि:",
    "Requires follow-up": "फ़ॉलो-अप आवश्यक है",
    "Reserved": "आरक्षित",
    "Reset": "रीसेट करें",
    "Reset Template": "टेम्पलेट रीसेट करें",
    "Reset to system default": "सिस्टम डिफ़ॉल्ट पर रीसेट करें",
    "Resolve the failed checks above before continuing.": "जारी रखने से पहले उपरोक्त विफल जांचों का समाधान करें।",
    "Restaurant Mode": "रेस्तरां मोड",
    "Restock": "स्टॉक पुनः भरें",
    "Resume Fullscreen": "फ़ुलस्क्रीन फिर से शुरू करें",
    "Retention Window (Days)": "प्रतिधारण विंडो (दिन)",
    "Return to my account": "मेरे खाते पर वापस जाएं",
    "Review & Place Order": "समीक्षा करें और ऑर्डर दें",
    "Revoke": "रद्द करें",
    "Revoke this license key?": "क्या इस लाइसेंस कुंजी को रद्द करना है?",
    "Revoke this link?": "क्या इस लिंक को रद्द करना है?",
    "Revoked": "रद्द किया गया",
    "Right Sidebar": "दायां साइडबार",
    "Right-to-Left (RTL - Arabic, Hebrew)": "दाएं से बाएं (RTL - अरबी, हिब्रू)",
    "Role & Profile *": "भूमिका एवं प्रोफ़ाइल *",
    "Role Profile": "भूमिका प्रोफ़ाइल",
    "Row": "पंक्ति",
    "Royal Indigo": "रॉयल इंडिगो",
    "Royal Purple": "रॉयल पर्पल",
    "Ruby Rose": "रूबी रोज़",
    "SKU": "एसकेयू (SKU)",
    "SKU Scan": "एसकेयू स्कैन",
    "SKUs, pricing & inventory levels": "एसकेयू, मूल्य निर्धारण और इन्वेंट्री स्तर",
    "SMTP Email Settings": "एसएमटीपी ईमेल सेटिंग्स",
    "SMTP Host": "एसएमटीपी होस्ट",
    "SMTP Host Server *": "एसएमटीपी होस्ट सर्वर *",
    "SMTP Password": "एसएमटीपी पासवर्ड",
    "SMTP Port": "एसएमटीपी पोर्ट",
    "SMTP Username": "एसएमटीपी उपयोगकर्ता नाम",
    "SMTP Username / API Key": "एसएमटीपी उपयोगकर्ता नाम / एपीआई कुंजी",
    "SSL": "SSL",
    "SSL (Port 465)": "SSL (पोर्ट 465)",
    "SUB TOTAL": "उप-योग (सब-टोटल)",
    "Sale": "बिक्री",
    "Sale #": "बिक्री नं. #",
    "Sale / Inv #": "बिक्री / इनवॉइस नं. #",
    "Sale Completed!": "बिक्री पूरी हुई!",
    "Sale Price ($) *": "बिक्री मूल्य ($) *",
    "Sales Representative": "बिक्री प्रतिनिधि",
    "Sales by Payment Method": "भुगतान विधि द्वारा बिक्री",
    "Sales by Payment Method (This Shift)": "भुगतान विधि द्वारा बिक्री (इस शिफ्ट)",
    "Sandbox / Test Mode": "सैंडबॉक्स / टेस्ट मोड",
    "Save & Preview Quotation": "सहेजें और कोटेशन का पूर्वावलोकन करें",
    "Save & Select Customer": "सहेजें और ग्राहक चुनें",
    "Save All Custom Translations": "सभी कस्टम अनुवाद सहेजें",
    "Save All Settings": "सभी सेटिंग्स सहेजें",
    "Save Bill / Expense": "बिल / व्यय सहेजें",
    "Save Category": "श्रेणी सहेजें",
    "Save Customer": "ग्राहक सहेजें",
    "Save Financial Settings": "वित्तीय सेटिंग्स सहेजें",
    "Save Floor": "फ्लोर सहेजें",
    "Save Method": "विधि सहेजें",
    "Save Notification & Dispatch Settings": "अधिसूचना और प्रेषण सेटिंग्स सहेजें",
    "Save Operating Mode": "ऑपरेटिंग मोड सहेजें",
    "Save Permissions": "अनुमतियाँ सहेजें",
    "Save Phrase": "वाक्यांश सहेजें",
    "Save Plan": "योजना सहेजें",
    "Save Product": "उत्पाद सहेजें",
    "Save Profile & Branding": "प्रोफ़ाइल और ब्रांडिंग सहेजें",
    "Save Receipt Prefixes & Bank Terms": "रसीद उपसर्ग और बैंक शर्तें सहेजें",
    "Save SMTP Configuration": "एसएमटीपी कॉन्फ़िगरेशन सहेजें",
    "Save Store Overrides": "स्टोर ओवरराइड सहेजें",
    "Save Supplier": "आपूर्तिकर्ता सहेजें",
    "Save Table": "टेबल सहेजें",
    "Save Unit": "इकाई सहेजें",
    "Saved securely": "सुरक्षित रूप से सहेजा गया",
    "Saving...": "सहेजा जा रहा है...",
    "Scan barcode / SKU...": "बारकोड / एसकेयू स्कैन करें...",
    "Scan barcode or type product name / SKU...": "बारकोड स्कैन करें या उत्पाद का नाम / एसकेयू टाइप करें...",
    "Scan to View Menu & Order": "मेनू देखने और ऑर्डर करने के लिए स्कैन करें",
    "Scheduled outgoings": "अनुसूचित बहिर्वाह (खर्च)",
    "Scope specifications / item deliverables description (optional)...": "कार्यक्षेत्र विनिर्देश / मद वितरण विवरण (वैकल्पिक)...",
    "Search and attach a customer to this sale": "इस बिक्री में एक ग्राहक को खोजें और संलग्न करें",
    "Search bar, category chips, 3-column retail item cards with side cart.": "सर्च बार, श्रेणी चिप्स, साइड कार्ट के साथ 3-कॉलम रिटेल आइटम कार्ड।",
    "Search bill #, vendor, title...": "बिल नं., विक्रेता, शीर्षक खोजें...",
    "Search by customer name, phone, or email...": "ग्राहक के नाम, फ़ोन या ईमेल द्वारा खोजें...",
    "Search by name, code, barcode…": "नाम, कोड, बारकोड द्वारा खोजें…",
    "Search by name, email, phone…": "नाम, ईमेल, फ़ोन द्वारा खोजें…",
    "Search by sale # or customer…": "बिक्री संख्या या ग्राहक द्वारा खोजें…",
    "Search invoice #, customer...": "इनवॉइस नं., ग्राहक खोजें...",
    "Search items...": "आइटम खोजें...",
    "Search keys or translated phrases…": "कुंजियाँ या अनुवादित वाक्यांश खोजें…",
    "Search menu...": "मेनू खोजें...",
    "Search quotation # or client name...": "कोटेशन नं. या क्लाइंट नाम खोजें...",
    "Search stores by name, account ID, email, slug…": "नाम, खाता आईडी, ईमेल, स्लग द्वारा स्टोर खोजें…",
    "Search suppliers by name…": "नाम से आपूर्तिकर्ताओं को खोजें…",
    "Search team by name, email, or role...": "नाम, ईमेल या भूमिका द्वारा टीम खोजें...",
    "Search terms or phrases…": "शब्द या वाक्यांश खोजें…",
    "Seat": "सीट",
    "Secondary CTA Button Label": "द्वितीयक सीटीए बटन लेबल",
    "Secondary CTA URL": "द्वितीयक सीटीए यूआरएल",
    "Secure Subscription Checkout": "सुरक्षित सदस्यता चेकआउट",
    "Select Available Table": "उपलब्ध टेबल चुनें",
    "Select Brand": "ब्रांड चुनें",
    "Select Category": "श्रेणी चुनें",
    "Select Client / Customer": "क्लाइंट / ग्राहक चुनें",
    "Select Customer / Member": "ग्राहक / सदस्य चुनें",
    "Select Destination Table": "गंतव्य टेबल चुनें",
    "Select Dine-In Table": "डाइन-इन टेबल चुनें",
    "Select Extra Page to Embed": "एम्बेड करने के लिए अतिरिक्त पृष्ठ चुनें",
    "Select Language File to Edit:": "संपादित करने के लिए भाषा फ़ाइल चुनें:",
    "Select POS Layout & Interface Design": "पीओएस लेआउट और इंटरफ़ेस डिज़ाइन चुनें",
    "Select Payment Method": "भुगतान विधि चुनें",
    "Select Products to Include": "शामिल करने के लिए उत्पाद चुनें",
    "Select Table": "टेबल चुनें",
    "Select User to Configure:": "कॉन्फ़िगर करने के लिए उपयोगकर्ता चुनें:",
    "Select the primary accent color for your navigation sidebar, buttons, and badges": "अपने नेविगेशन साइडबार, बटन और बैज के लिए प्राथमिक एक्सेंट रंग चुनें",
    "Selected": "चयनित",
    "Selected ✓": "चयनित ✓",
    "Send": "भेजें",
    "Send Email": "ईमेल भेजें",
    "Send Email via SMTP": "एसएमटीपी के माध्यम से ईमेल भेजें",
    "Send Invoice Email": "इनवॉइस ईमेल भेजें",
    "Send Invoice via Email": "ईमेल द्वारा इनवॉइस भेजें",
    "Send Order to Kitchen": "किचन को ऑर्डर भेजें",
    "Send Quotation Email": "कोटेशन ईमेल भेजें",
    "Send Quotation Proposal #": "कोटेशन प्रस्ताव भेजें #",
    "Send Tax Invoice #": "टैक्स इनवॉइस भेजें #",
    "Send Tax Invoice Receipt": "टैक्स इनवॉइस रसीद भेजें",
    "Send Test Email": "टेस्ट ईमेल भेजें",
    "Send a test email to verify your SMTP configuration": "अपने एसएमटीपी कॉन्फ़िगरेशन को सत्यापित करने के लिए एक टेस्ट ईमेल भेजें",
    "Send an immediate test dispatch to verify that your SMTP host credentials and sender address are working properly.": "यह सत्यापित करने के लिए तत्काल परीक्षण प्रेषण भेजें कि आपके एसएमटीपी होस्ट क्रेडेंशियल और प्रेषक का पता ठीक से काम कर रहे हैं।",
    "Send an invitation to join your store via WhatsApp or Email": "व्हाट्सएप या ईमेल के माध्यम से अपने स्टोर में शामिल होने के लिए निमंत्रण भेजें",
    "Send invitation email automatically via store SMTP": "स्टोर एसएमटीपी के माध्यम से स्वचालित रूप से निमंत्रण ईमेल भेजें",
    "Sender Display Name": "प्रेषक का प्रदर्शन नाम",
    "Sender Email Address": "प्रेषक का ईमेल पता",
    "Sending Test...": "परीक्षण भेजा जा रहा है...",
    "Sending...": "भेजा जा रहा है...",
    "Sent": "भेजा गया",
    "Sent to Client": "क्लाइंट को भेजा गया",
    "Setting": "सेटिंग",
    "Settle Bill & Print Receipt": "बिल निपटाएं और रसीद प्रिंट करें",
    "Settled": "चुकता (निपटारा हुआ)",
    "Settled (Paid)": "चुकता (भुगतान किया गया)",
    "Settled This Month": "इस महीने निपटाया गया",
    "Settlement Amount ($)": "निपटान राशि ($)",
    "Settlement Date": "निपटान तिथि",
    "Settlement remarks or transfer notes...": "निपटान टिप्पणियां या स्थानांतरण नोट्स...",
    "Share Invite": "निमंत्रण साझा करें",
    "Share Receipt on WhatsApp": "व्हाट्सएप पर रसीद साझा करें",
    "Share via WhatsApp": "व्हाट्सएप के जरिए शेयर करें",
    "Shareable web catalog & WhatsApp store": "साझा करने योग्य वेब कैटलॉग और व्हाट्सएप स्टोर",
    "Shifts, float & cash balancing": "शिफ्ट, फ्लोट और नकद संतुलन",
    "Short": "छोटा (कम)",
    "Sign out this device?": "इस डिवाइस से साइन आउट करें?",
    "Signed In": "साइन इन किया गया",
    "Size / Style": "आकार / शैली",
    "Smart Inventory Platform, SaaS Billing…": "स्मार्ट इन्वेंट्री प्लेटफ़ॉर्म, सास बिलिंग…",
    "Solution Pillars": "समाधान के मुख्य स्तंभ",
    "Special Order Instructions": "विशेष ऑर्डर निर्देश",
    "Special instructions, cashier remarks...": "विशेष निर्देश, कैशियर टिप्पणियां...",
    "Split Payment Entries": "विभाजित भुगतान प्रविष्टियां",
    "Split Payment:": "विभाजित भुगतान:",
    "Split:": "विभाजन:",
    "Square Stand": "स्क्वायर स्टैंड",
    "Square Stand Register": "स्क्वायर स्टैंड रजिस्टर",
    "Staff": "कर्मचारी (स्टाफ)",
    "Staff User Accounts": "कर्मचारी उपयोगकर्ता खाते",
    "Staff accounts & access matrix": "कर्मचारी खाते और एक्सेस मैट्रिक्स",
    "Stand:": "स्टैंड:",
    "Standard": "मानक (स्टैंडर्ड)",
    "Standard Scanner": "मानक स्कैनर",
    "Standard Scanner POS": "मानक स्कैनर पीओएस",
    "Start Preparing": "तैयारी शुरू करें",
    "State": "राज्य",
    "State / Province": "राज्य / प्रांत",
    "Status": "स्थिति",
    "Status:": "स्थिति:",
    "Step 1 — Requirements & Permissions": "चरण 1 — आवश्यकताएं और अनुमतियां",
    "Step 2 — Environment & Database": "चरण 2 — पर्यावरण और डेटाबेस",
    "Step 3 — Migrate & Seed": "चरण 3 — माइग्रेट और सीड",
    "Step 4 — Super Admin Account": "चरण 4 — सुपर एडमिन खाता",
    "Step 5 — Finish": "चरण 5 — पूर्ण",
    "Sticky Navigation Bar": "स्टिकी नेविगेशन बार",
    "Stock": "स्टॉक",
    "Store Account:": "स्टोर खाता:",
    "Store Email": "स्टोर ईमेल",
    "Store Invoicing & Billing": "स्टोर इनवॉइसिंग और बिलिंग",
    "Store Languages & Custom Translation Editor": "स्टोर भाषाएं और कस्टम अनुवाद संपादक",
    "Store Operating Mode": "स्टोर ऑपरेटिंग मोड",
    "Store Phone / WhatsApp": "स्टोर फ़ोन / व्हाट्सएप",
    "Store Primary Language": "स्टोर की प्राथमिक भाषा",
    "Store Profile & Branding": "स्टोर प्रोफ़ाइल और ब्रांडिंग",
    "Store Profile & Location": "स्टोर प्रोफ़ाइल और स्थान",
    "Store Subdomain / Slug": "स्टोर सबडोमेन / स्लग",
    "Store Theme, Branding & POS Layout": "स्टोर थीम, ब्रांडिंग और पीओएस लेआउट",
    "Store Website URL": "स्टोर वेबसाइट यूआरएल",
    "Street & apt": "सड़क और फ्लैट नं.",
    "Stripe, PayPal, Mollie, Razorpay": "स्ट्राइप, पेपाल, मौली, रेज़रपे",
    "Subscription & Tax Billing": "सदस्यता और कर बिलिंग",
    "Subscription Expiration Date": "सदस्यता समाप्ति तिथि",
    "Subtotal": "उप-योग (सब-टोटल)",
    "Subtotal:": "उप-योग:",
    "Suffix": "प्रत्यय (Suffix)",
    "Super Admin": "सुपर एडमिन",
    "SuperAdmin Sidebar Menu": "सुपरएडमिन साइडबार मेनू",
    "Supermarket Touch POS": "सुपरमार्केट टच पीओएस",
    "Supplier": "आपूर्तिकर्ता (सप्लायर)",
    "Supplier Name *": "आपूर्तिकर्ता का नाम *",
    "Supplier bills & expenses": "आपूर्तिकर्ता बिल और व्यय",
    "Supplier bills & food purchases": "आपूर्तिकर्ता बिल और भोजन खरीद",
    "Supplier bills & purchase dues": "आपूर्तिकर्ता बिल और खरीद बकाया",
    "Suppliers & Vendors": "आपूर्तिकर्ता और विक्रेता",
    "Support": "सहायता (सपोर्ट)",
    "Support Email": "सहायता ईमेल",
    "Support Phone": "सहायता फ़ोन",
    "Supported Platform Languages": "समर्थित प्लेटफ़ॉर्म भाषाएं",
    "Suspended": "निलंबित",
    "Switch Account": "खाता बदलें",
    "Switch Table": "टेबल बदलें",
    "Symbol Placement": "प्रतीक की स्थिति",
    "System Default": "सिस्टम डिफ़ॉल्ट",
    "System Health & Global Maintenance Mode": "सिस्टम स्वास्थ्य और वैश्विक रखरखाव मोड",
    "TAX ESTIMATE": "कर अनुमान",
    "TLS": "TLS",
    "TLS (Port 587 - Recommended)": "TLS (पोर्ट 587 - अनुशंसित)",
    "TXN / Auth #": "लेन-देन / प्राधिकरण संख्या #",
    "Table Name / Number *": "टेबल का नाम / संख्या *",
    "Table Order Review": "टेबल ऑर्डर समीक्षा",
    "Tables & Floor Plan": "टेबल्स और फ्लोर प्लान",
    "Takeaway": "टेकअवे (पैक कराएं)",
    "Target Seat": "लक्षित सीट",
    "Tax (GST/VAT)": "कर (जीएसटी/वैट)",
    "Tax / GST:": "कर / जीएसटी:",
    "Tax Amount ($)": "कर राशि ($)",
    "Tax Exempt": "कर-मुक्त",
    "Tax ID": "टैक्स आईडी",
    "Tax ID / Business Reg": "टैक्स आईडी / व्यवसाय पंजीकरण",
    "Tax ID / VAT / Document": "टैक्स आईडी / वैट / दस्तावेज़",
    "Tax Rate (%)": "कर दर (%)",
    "Tax rates & category hierarchy": "कर दरें और श्रेणी पदानुक्रम",
    "Tax/GSTIN:": "टैक्स/जीएसटीआईएन:",
    "Taxable": "कर योग्य",
    "Taxable Base": "कर योग्य आधार",
    "Taxes & Professional": "कर और व्यावसायिक सेवाएं",
    "Taxes & Professional Services": "कर और व्यावसायिक सेवाएं",
    "Tenant Brand Primary": "किरायेदार ब्रांड प्राथमिक",
    "Tenant app fallback primary": "किरायेदार ऐप फ़ॉलबैक प्राथमिक",
    "Term / Phrase": "शब्द / वाक्यांश",
    "Terminals & Devices": "टर्मिनल्स और उपकरण",
    "Terms and Conditions:": "नियम एवं शर्तें:",
    "Test SMTP": "एसएमटीपी टेस्ट करें",
    "Text Direction": "पाठ दिशा",
    "Thank you for your business! All sales are final unless otherwise specified in your service contract.": "हमारे साथ व्यापार करने के लिए धन्यवाद! जब तक आपके सेवा अनुबंध में निर्दिष्ट न हो, सभी बिक्री अंतिम हैं।",
    "The bar floats as an overlay above the UI, enabling free drag-and-drop placement anywhere across the viewport without altering page grid layout.": "बार यूआई के ऊपर एक ओवरले के रूप में तैरता है, जिससे पेज ग्रिड लेआउट को बदले बिना व्यूपोर्ट में कहीं भी स्वतंत्र ड्रैग-एंड-ड्रॉप प्लेसमेंट सक्षम होता है।",
    "The bar snaps rigidly into the screen structure (Left Sidebar, Right Sidebar, Top Header Bar, Bottom Dock Bar) and adjusts page padding accordingly so content never scrolls under or overlaps it.": "बार स्क्रीन संरचना में मजबूती से स्नैप करता है और पेज पैडिंग को समायोजित करता है ताकि सामग्री कभी भी इसके नीचे न स्क्रॉल हो।",
    "The remaining balance is payable upon delivery/project completion.": "शेष राशि का भुगतान वितरण/परियोजना पूर्ण होने पर देय है।",
    "Thermal receipts & order history": "थर्मल रसीदें और ऑर्डर इतिहास",
    "This email address will appear in the \"From:\" header of all outgoing system emails.": "यह ईमेल पता सभी आउटगोइंग सिस्टम ईमेल के \"From:\" हेडर में दिखाई देगा।",
    "This user has Administrator role and automatically enjoys full bypass access to all modules.": "इस उपयोगकर्ता के पास व्यवस्थापक भूमिका है और यह स्वचालित रूप से सभी मॉड्यूल तक पूर्ण पहुंच प्राप्त करता है।",
    "Ticket Status:": "टिकट की स्थिति:",
    "Ticket is now active in the Kitchen Display System (KDS) queue.": "टिकट अब किचन डिस्प्ले सिस्टम (KDS) कतार में सक्रिय है।",
    "Time:": "समय:",
    "Toggle Fullscreen Mode": "फ़ुलस्क्रीन मोड टॉगल करें",
    "Toggle Sticky Navigation": "स्टिकी नेविगेशन टॉगल करें",
    "Top Header Bar": "शीर्ष हेडर बार",
    "Total": "कुल",
    "Total Active KOTs": "कुल सक्रिय केओटी",
    "Total Amount": "कुल राशि",
    "Total Amount Due": "कुल देय राशि",
    "Total Amount Paid:": "कुल भुगतान की गई राशि:",
    "Total Bill": "कुल बिल",
    "Total Due Today": "आज कुल देय",
    "Total Order Amount:": "कुल ऑर्डर राशि:",
    "Total Outstanding": "कुल बकाया",
    "Total Outstanding Balance": "कुल बकाया शेष",
    "Total Payable": "कुल देय",
    "Total Sales": "कुल बिक्री",
    "Total Tables:": "कुल टेबल्स:",
    "Total:": "कुल:",
    "Touch Department": "टच विभाग",
    "Touch POS": "टच पीओएस",
    "Track customer balances, credit sales, partial payments, due dates, and overdue accounts.": "ग्राहक शेष, क्रेडिट बिक्री, आंशिक भुगतान, देय तिथियां और अतिदेय खातों को ट्रैक करें।",
    "Trade / Brand Name": "व्यापार / ब्रांड का नाम",
    "Transaction & Sales": "लेन-देन और बिक्री",
    "Transfer Order": "ऑर्डर स्थानांतरित करें",
    "Transfer Table": "टेबल स्थानांतरित करें",
    "Transfer Table Order": "टेबल ऑर्डर स्थानांतरित करें",
    "Type product name, SKU or barcode scan...": "उत्पाद का नाम, एसकेयू टाइप करें या बारकोड स्कैन करें...",
    "URL Slug *": "यूआरएल स्लग *",
    "USD": "अमेरिकी डॉलर (USD)",
    "Unassign Customer": "ग्राहक अनअसाइन करें",
    "Unit": "इकाई (यूनिट)",
    "Unit Name": "इकाई का नाम",
    "Unit Name *": "इकाई का नाम *",
    "Unit Price": "इकाई मूल्य",
    "Units of Measure": "माप की इकाइयाँ",
    "Unlimited": "असीमित",
    "Unlimited Inventory & Sales History": "असीमित इन्वेंट्री और बिक्री इतिहास",
    "Upcoming (30 Days)": "आगामी (30 दिन)",
    "Upgrade or renew your plan with instant tax invoice generation": "तत्काल टैक्स इनवॉइस जनरेशन के साथ अपने प्लान को अपग्रेड या नवीनीकृत करें",
    "Upload Product Photo": "उत्पाद फ़ोटो अपलोड करें",
    "Uploading...": "अपलोड हो रहा है...",
    "Use \"Adjust Stock\" button on the table.": "तालिका पर \"स्टॉक समायोजित करें\" बटन का उपयोग करें।",
    "User": "उपयोगकर्ता",
    "User / Terminal": "उपयोगकर्ता / टर्मिनल",
    "Username": "उपयोगकर्ता नाम",
    "Utilities (Electricity, Water, Internet)": "उपयोगिताएँ (बिजली, पानी, इंटरनेट)",
    "Utilities (Power/Water)": "उपयोगिताएँ (बिजली/पानी)",
    "Valid Until:": "वैधता तिथि:",
    "Validity Expiry Date": "वैधता समाप्ति तिथि",
    "Vendor / Supplier": "विक्रेता / आपूर्तिकर्ता",
    "Vendor Name (If not in suppliers)": "विक्रेता का नाम (यदि आपूर्तिकर्ताओं में नहीं है)",
    "Vendor contacts & purchasing": "विक्रेता संपर्क और खरीद",
    "Vendor directory & purchasing": "विक्रेता निर्देशिका और खरीद",
    "Verify Key & Upgrade": "कुंजी सत्यापित करें और अपग्रेड करें",
    "View": "देखें",
    "View & Download PDF Tax Invoice": "पीडीएफ टैक्स इनवॉइस देखें और डाउनलोड करें",
    "View All": "सभी देखें",
    "View All Sales": "सभी बिक्री देखें",
    "View All Stores": "सभी स्टोर देखें",
    "View Invoices": "इनवॉइस देखें",
    "View Only": "केवल देखें",
    "View Z-Report": "Z-रिपोर्ट देखें",
    "View attached bill file": "संलग्न बिल फ़ाइल देखें",
    "Viewing as": "के रूप में देख रहे हैं",
    "Violet Purple": "बैंगनी (वायलेट)",
    "Volume, Outlets, Uptime": "मात्रा, आउटलेट्स, अपटाइम",
    "Walk-in": "वॉक-इन",
    "Walk-in Customer": "वॉक-इन ग्राहक",
    "Walk-in Member": "वॉक-इन सदस्य",
    "Walk-in Regular Customer": "वॉक-इन नियमित ग्राहक",
    "Warm Amber": "वार्म एम्बर",
    "Weekly Automated Snapshot": "साप्ताहिक स्वचालित स्नैपशॉट",
    "WhatsApp": "WhatsApp",
    "WhatsApp & Messaging Settings": "व्हाट्सएप और मैसेजिंग सेटिंग्स",
    "WhatsApp Web / Mobile": "व्हाट्सएप वेब / मोबाइल",
    "With pending dues": "लंबित बकाया के साथ",
    "X-Report (live)": "X-रिपोर्ट (लाइव)",
    "Yearly": "वार्षिक",
    "You": "आप",
    "Your Custom Store Translation": "आपका कस्टम स्टोर अनुवाद",
    "Your Name (Optional)": "आपका नाम (वैकल्पिक)",
    "Your Name *": "आपका नाम *",
    "Your Order Cart": "आपका ऑर्डर कार्ट",
    "Your Phone / WhatsApp Number": "आपका फ़ोन / व्हाट्सएप नंबर",
    "Your Store Custom Translation *": "आपके स्टोर का कस्टम अनुवाद *",
    "Your cart is currently empty.": "आपकी कार्ट वर्तमान में खाली है।",
    "Your sale is currently empty. Tap items to add.": "आपकी बिक्री वर्तमान में खाली है। जोड़ने के लिए आइटम पर टैप करें।",
    "Z-Report": "Z-रिपोर्ट",
    "active invoices": "सक्रिय इनवॉइस",
    "admin@yourcompany.com": "admin@yourcompany.com",
    "apikey, username@domain.com…": "apikey, username@domain.com…",
    "billing@yourstore.com": "billing@yourstore.com",
    "by": "द्वारा",
    "days": "दिन",
    "discount": "छूट",
    "e.g. 1 for US/CA, 91 for IN, 44 for UK, 62 for ID": "उदा. 91 भारत के लिए, 1 यूएस/कनाडा के लिए, 44 यूके के लिए",
    "e.g. 15 mins, 06:00 PM": "उदा. 15 मिनट, शाम 06:00 बजे",
    "e.g. Change fund top-up, petty cash withdrawal": "उदा. चेंज फंड टॉप-अप, पेटी कैश निकासी",
    "e.g. City Power Corp, Apex Landlord": "उदा. सिटी पावर कॉर्प, एपेक्स लैंडलॉर्ड",
    "e.g. Credit Card, UPI, PIX, Stripe": "उदा. क्रेडिट कार्ड, यूपीआई, नेटबैंकिंग",
    "e.g. Dutch": "उदा. डच",
    "e.g. For returns, keep this receipt within 7 days.": "उदा. वापसी के लिए, इस रसीद को 7 दिनों तक रखें।",
    "e.g. Fresh Summer Produce, Special Deals…": "उदा. ताज़ा ग्रीष्मकालीन उत्पाद, विशेष सौदे…",
    "e.g. Michael Scott": "उदा. राहुल शर्मा",
    "e.g. Monthly Warehouse Rent or Stock Restock Batch #4": "उदा. मासिक गोदाम किराया या स्टॉक पुनःपूर्ति बैच #4",
    "e.g. Nederlands": "उदा. हिंदी",
    "e.g. No onion": "उदा. बिना प्याज",
    "e.g. Pay via terminal or contactless": "उदा. टर्मिनल या संपर्क रहित भुगतान करें",
    "e.g. Política de Devoluciones": "उदा. वापसी नीति",
    "e.g. Restock, damaged, correction": "उदा. रीस्टॉक, क्षतिग्रस्त, सुधार",
    "e.g. Return Policy": "उदा. वापसी नीति",
    "e.g. Return Policy, Print Tax Invoice": "उदा. वापसी नीति, टैक्स इनवॉइस प्रिंट करें",
    "e.g. Return Policy, Special Promo": "उदा. वापसी नीति, विशेष प्रचार",
    "e.g. Rooftop Patio, Bar, Hall": "उदा. रूफटॉप आँगन, बार, मुख्य हॉल",
    "e.g. Sarah Jenkins": "उदा. प्रिया वर्मा",
    "e.g. Scope deliverables, milestone payment terms, project phases...": "उदा. कार्यक्षेत्र डिलिवरेबल्स, माइलस्टोन भुगतान शर्तें, परियोजना चरण...",
    "e.g. TAX-8891, VAT12345": "उदा. TAX-8891, GSTIN12345",
    "e.g. TXN-998822 or Check #4401": "उदा. TXN-998822 या चेक #4401",
    "e.g. Table 04, VIP-1, Bar-02": "उदा. टेबल 04, वीआईपी-1, बार-02",
    "e.g. WIRE-884401 or Check #1002": "उदा. WIRE-884401 या चेक #1002",
    "e.g. card, upi, pix, stripe": "उदा. कार्ड, यूपीआई, नकद, नेटबैंकिंग",
    "e.g. nl, ja, it": "उदा. hi, en, ja",
    "e.g. smtp.mailgun.org, smtp.gmail.com": "उदा. smtp.mailgun.org, smtp.gmail.com",
    "e.g. yourstore.com or https://yourstore.com": "उदा. yourstore.com या https://yourstore.com",
    "each": "प्रत्येक",
    "https://example.com/favicon.ico": "https://example.com/favicon.ico",
    "https://example.com/logo.png": "https://example.com/logo.png",
    "https://example.com/product-image.jpg": "https://example.com/product-image.jpg",
    "if CNAME isn't supported at your registrar for this name) to": "यदि इस नाम के लिए आपके रजिस्ट्रार पर CNAME समर्थित नहीं है) को",
    "impersonated": "रूप धारण किया",
    "items": "आइटम",
    "line items": "लाइन आइटम",
    "m ago": "मिनट पहले",
    "month": "माह",
    "my-store": "मेरा-स्टोर",
    "no-reply@saas.zoomnearby.com, billing@yourdomain.com": "no-reply@saas.zoomnearby.com, billing@yourdomain.com",
    "of": "का",
    "or": "या",
    "pcs": "पीस",
    "pcs, kg, box…": "पीस, किग्रा, बॉक्स…",
    "pcs, kg, bx…": "पीस, किग्रा, बॉक्स…",
    "pos.yourdomain.com or mycompany.com": "pos.yourdomain.com या mycompany.com",
    "postmaster@yourdomain.com": "postmaster@yourdomain.com",
    "pts": "अंक",
    "quotation(s) selected": "चयनित कोटेशन",
    "sale(s) total, all methods": "कुल बिक्री, सभी विधियां",
    "sarah@store.com": "sarah@store.com",
    "save this form, then ask your platform admin to finish HTTPS setup for the domain — until that's done it may show a certificate warning.": "इस फ़ॉर्म को सहेजें, फिर अपने प्लेटफ़ॉर्म व्यवस्थापक से डोमेन के लिए HTTPS सेटअप समाप्त करने के लिए कहें - जब तक ऐसा नहीं किया जाता है तब तक यह प्रमाणपत्र चेतावनी दिखा सकता है।",
    "seats": "सीटें",
    "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…": "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…",
    "subtotal": "उप-योग",
    "tax": "टैक्स",
    "to Sale invoice?": "को बिक्री इनवॉइस में?",
    "total": "कुल",
    "will be logged to Accounts Receivable.": "प्राप्य खातों में दर्ज किया जाएगा।",
    "with Razorpay": "Razorpay के साथ",
    "year": "वर्ष",
    "your-email@example.com": "your-email@example.com"
}

def update_hi():
    with open('lang/hi.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    with open('scratch/to_translate/hi_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
        
    missing_count = 0
    for k in missing:
        if k in HINDI_TRANSLATIONS:
            existing[k] = HINDI_TRANSLATIONS[k]
        else:
            print(f"Missing translation for key: {k}")
            missing_count += 1
            
    if missing_count > 0:
        print(f"FAILED: {missing_count} keys missing in HINDI_TRANSLATIONS")
        return False
        
    with open('lang/hi.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
        f.write('\n')
        
    print(f"Successfully updated lang/hi.json! Total keys: {len(existing)}")
    return True

if __name__ == '__main__':
    update_hi()
