# Arabic translation dictionary for all missing keys
import json

ARABIC_TRANSLATIONS = {
    "+1 555-0199": "+1 555-0199",
    "0% Exempt": "0% معفى",
    "1 day": "يوم واحد",
    "10% Happy Hour": "ساعة سعيدة 10%",
    "14-day zero-risk trial evaluation": "فترة تجريبية مجانية لمدة 14 يومًا بدون أي مخاطرة",
    "15% Member VIP": "عضوية VIP خصم 15%",
    "20% Promo Clearance": "تصفية ترويجية 20%",
    "256-Bit SSL Encrypted Payment": "دفع مشفر بحماية 256-بت SSL",
    "30 days": "30 يومًا",
    "40% advance milestone required upon quotation acceptance.": "دفعة مقدمة 40% مطلوبة عند قبول عرض السعر.",
    "5% Staff Discount": "خصم موظفين 5%",
    "7 days": "7 أيام",
    "80mm / 58mm": "80 مم / 58 مم",
    "Abbreviation": "الاختصار",
    "Accepted": "مقبول",
    "Accepted / Approved": "مقبول / معتمد",
    "Access Control": "التحكم بالوصول والصلاحيات",
    "Accounts Payable & Expense Management": "الذمم الدائنة وإدارة المصروفات",
    "Accounts Receivable (Customer Credit & Invoices)": "الذمم المدينة (مستحقات وفواتير العملاء)",
    "Action": "إجراء",
    "Actions": "إجراءات",
    "Activate": "تفعيل",
    "Activate Free Trial": "تفعيل التجربة المجانية",
    "Activation / License Key *": "مفتاح التفعيل / الترخيص *",
    "Active (Visible in POS)": "نشط (ظاهر في نقطة البيع)",
    "Active Account": "حساب نشط",
    "Active Devices & POS Terminals": "الأجهزة ونقاط البيع النشطة",
    "Active Store": "متجر نشط",
    "Active Store Plan": "خطة المتجر الحالية",
    "Active Supplier": "مورد نشط",
    "Active subscription plans": "خطط الاشتراك النشطة",
    "Add Currency": "إضافة عملة",
    "Add Custom Phrase": "إضافة عبارة مخصصة",
    "Add Customer": "إضافة عميل",
    "Add Floor": "إضافة طابق",
    "Add Floor Area": "إضافة منطقة طابق",
    "Add Method": "إضافة طريقة",
    "Add Method Split": "إضافة تقسيم طريقة دفع",
    "Add New Category": "إضافة فئة جديدة",
    "Add New Client": "إضافة عميل جديد",
    "Add New Customer": "إضافة عميل جديد",
    "Add New Payment Method": "إضافة طريقة دفع جديدة",
    "Add New Supplier": "إضافة مورد جديد",
    "Add New Unit": "إضافة وحدة جديدة",
    "Add Row": "إضافة صف",
    "Add Split": "إضافة تقسيم",
    "Add Table": "إضافة طاولة",
    "Add Vendor Bill / Expense": "إضافة فاتورة مورد / مصروف",
    "Add special instructions, client PO reference, warranty notes or cashier remarks...": "أضف تعليمات خاصة، مرجع أمر شراء العميل، ملاحظات الضمان أو ملاحظات الكاشير...",
    "Add to Cart": "إضافة إلى السلة",
    "Add to Order": "إضافة إلى الطلب",
    "Add to Sale +": "إضافة للبيع +",
    "Add, edit, enable or remove custom payment methods for POS checkout": "إضافة أو تعديل أو تمكين أو إزالة طرق الدفع المخصصة لنقطة البيع",
    "Add-ons & Extras": "إضافات وخيارات إضافية",
    "Additional Custom Authored Content (Optional)": "محتوى مخصص إضافي (اختياري)",
    "Address": "العنوان",
    "Address:": "العنوان:",
    "Adjust": "تعديل",
    "Adjust Points": "تعديل النقاط",
    "Adjustment (+/- Qty)": "تعديل (+/- الكمية)",
    "Admin Full Name *": "الاسم الكامل للمسؤول *",
    "Admin Login / Username *": "اسم مستخدم / تسجيل دخول المسؤول *",
    "Admin Login Email *": "البريد الإلكتروني لدخول المسؤول *",
    "Administration & Settings": "الإدارة والإعدادات",
    "Administrator": "مسؤول النظام",
    "All": "الكل",
    "All Categories": "جميع الفئات",
    "All Customers": "جميع العملاء",
    "All Floor Areas": "جميع مناطق الطوابق",
    "All Items": "جميع العناصر",
    "All Kitchen Orders Cleared!": "تم مسح جميع طلبات المطبخ!",
    "All Menu": "كامل القائمة",
    "All Quotes": "جميع عروض الأسعار",
    "All Statuses": "جميع الحالات",
    "All Suppliers": "جميع الموردين",
    "All inventory items are healthy and above minimum threshold.": "جميع عناصر المخزون بحالة جيدة وأعلى من الحد الأدنى.",
    "All rates quoted are valid for 15 days from issue date.": "جميع الأسعار المعروضة صالحة لمدة 15 يومًا من تاريخ الإصدار.",
    "All unpaid bills": "جميع الفواتير غير المدفوعة",
    "All-inclusive for growing businesses": "شامل كليًا للشركات النامية",
    "Allocated": "مخصص",
    "Amber Gold": "ذهبي عنبري",
    "Amount": "المبلغ",
    "Amount ($)": "المبلغ ($)",
    "App URL": "رابط التطبيق",
    "Application & Navigation Theme Color": "لون مظهر التطبيق والقائمة",
    "Application primary theme color, default POS layout design, logo, and document colors": "اللون الأساسي للتطبيق، تصميم واجهة نقطة البيع الافتراضية، الشعار، وألوان المستندات",
    "Apply": "تطبيق",
    "Apply Primary Language": "تطبيق اللغة الأساسية",
    "Apply Role Profile Preset:": "تطبيق قالب الصلاحيات الجاهز:",
    "Are you sure you want to delete payment method": "هل أنت متأكد من حذف طريقة الدفع",
    "Are you sure you want to delete the selected quotations?": "هل أنت متأكد من حذف عروض الأسعار المحددة؟",
    "Are you sure you want to delete this bill?": "هل أنت متأكد من حذف هذه الفاتورة؟",
    "Are you sure you want to delete this quote?": "هل أنت متأكد من حذف عرض السعر هذا؟",
    "Are you sure you want to delete this translation key?": "هل أنت متأكد من حذف مفتاح الترجمة هذا؟",
    "Area Name *": "اسم المنطقة *",
    "Assigned Role": "الدور المسند",
    "Attach Official PDF Document": "إرفاق مستند PDF رسمي",
    "Authorized POS Devices": "أجهزة نقاط البيع المصرح بها",
    "Automated Database Backup & Retention Policy": "النسخ الاحتياطي التلقائي لقاعدة البيانات وسياسة الاحتفاظ",
    "Available": "متاح",
    "Available Subscription Plans": "خطط الاشتراك المتاحة",
    "Available database dumps stored on disk": "نسخ قواعد البيانات الاحتياطية المتاحة المخزنة على القرص",
    "BACK / CLEAR": "رجوع / مسح",
    "Back to Quotation Detail": "العودة لتفاصيل عرض السعر",
    "Back to Quotes": "العودة لعروض الأسعار",
    "Back to Sales": "العودة للمبيعات",
    "Back to Users & Team": "العودة للمستخدمين وفريق العمل",
    "Backup Frequency": "تكرار النسخ الاحتياطي",
    "Badge Color": "لون الشارة",
    "Balance Due": "الرصيد المستحق",
    "Balance Due:": "الرصيد المستحق:",
    "Balance logged to Accounts Receivable": "الرصيد المسجل في حسابات الذمم المدينة",
    "Balanced": "متوازن",
    "Bank & Payment Details (Rich-Text)": "تفاصيل البنك والدفع (نص منسق)",
    "Bank & Payment Instructions": "تعليمات الدفع والتحويل البنكي",
    "Bank Reference / Wire TXN / Check #": "المرجع البنكي / رقم التحويل / رقم الشيك",
    "Bar / Lounge": "بار / صالة استراحة",
    "Barcode": "باركود",
    "Barcode / SKU": "باركود / رمز المنتج (SKU)",
    "Base Amount ($)": "المبلغ الأساسي ($)",
    "Base Currency Code": "رمز العملة الأساسية",
    "Base currency code, symbol, decimal precision, and placement used across POS, cart, checkout, and invoices": "رمز العملة الأساسية، الرمز، الدقة العشرية وموضعها في نقطة البيع والسلة والدفع والفواتير",
    "Best Value": "أفضل قيمة",
    "Best for: General Retail, Supermarkets, Convenience stores": "الأفضل لـ: المتاجر العامة، السوبرماركت، ومحلات البقالة",
    "Best for: Modern tablet/iPad stands, boutique shops, cafes": "الأفضل لـ: حوامل الأجهزة اللوحية/iPad الحديثة، المتاجر الأنيقة، والمقاهي",
    "Best for: Touch registers, high-traffic counters, department stores": "الأفضل لـ: شاشات اللمس، نقاط البيع المزدحمة، والمتاجر الكبرى",
    "Bill": "فاتورة شراء",
    "Bill #": "رقم فاتورة الشراء #",
    "Bill / Invoice Reference #": "مرجع الفاتورة #",
    "Bill Amount": "مبلغ الفاتورة",
    "Bill Date": "تاريخ الفاتورة",
    "Bill Title / Description": "عنوان / وصف الفاتورة",
    "Billed": "تمت الفوترة",
    "Bottom CTA Banner": "شريط الدعوة لاتخاذ إجراء السفلي",
    "Bottom Dock Bar": "شريط التثبيت السفلي",
    "Brand": "العلامة التجارية",
    "Brand Logo URL / Image Path": "رابط شعار العلامة التجارية / مسار الصورة",
    "Brand Name *": "اسم العلامة التجارية *",
    "Brand names & supplier labels": "أسماء العلامات التجارية وملصقات الموردين",
    "Brand or company name displayed to recipients.": "اسم العلامة التجارية أو الشركة المعروض للمستلمين.",
    "Brands & Manufacturers": "العلامات التجارية والمصنعين",
    "Brands & Modifiers": "العلامات التجارية والمعدلات",
    "Browser Favicon URL (.ico / .png)": "أيقونة المتصفح Favicon (.ico / .png)",
    "Business Contact Email": "البريد الإلكتروني للاتصال بالعمل",
    "Business details displayed on POS terminal, receipts, and invoices": "بيانات النشاط التجاري المعروضة على جهاز نقطة البيع والإيصالات والفواتير",
    "CVV / CVC *": "رمز الأمان CVV / CVC *",
    "Call:": "اتصال:",
    "Cancel KOT": "إلغاء تذكرة المطبخ (KOT)",
    "Cancel Sale & Restock": "إلغاء البيع وإعادة المخزون",
    "Cancel [Esc]": "إلغاء [Esc]",
    "Cancel this sale and restore stock?": "إلغاء عملية البيع هذه واستعادة المخزون؟",
    "Capacity (Seats)": "السعة (المقاعد)",
    "Capacity:": "السعة:",
    "Card Number *": "رقم البطاقة *",
    "Cardholder Name *": "اسم حامل البطاقة *",
    "Cart": "السلة",
    "Cart is empty. Tap products to add items.": "السلة فارغة. انقر على المنتجات لإضافة عناصر.",
    "Cash In": "إيداع نقدي",
    "Cash In / Out": "إيداع / سحب نقدي",
    "Cash Movement Log": "سجل حركات النقد",
    "Cash Out": "سحب نقدي",
    "Cash Register (Daily Register Management)": "سجل النقد (إدارة الوردية اليومية)",
    "Cash Sales": "مبيعات نقدية",
    "Cash Tendered ($)": "المبلغ النقدي المدفوع ($)",
    "Cash Tendered by Customer ($)": "المبلغ النقدي المستلم من العميل ($)",
    "Casier POS": "كاشير POS",
    "Catalog Item...": "عنصر في الكتالوج...",
    "Catalog Title *": "عنوان الكتالوج *",
    "Category": "الفئة",
    "Category & Title": "الفئة والعنوان",
    "Category Name *": "اسم الفئة *",
    "Change": "الباقي",
    "Change Due": "المبلغ المتبقي للعميل",
    "Change Due to Customer": "المبلغ المتبقي للعميل",
    "Changes apply immediately upon saving.": "تسري التغييرات فور الحفظ.",
    "Charge": "تحصيل",
    "Choose Option": "اختر خيارًا",
    "Choose a primary header & table theme color for Quotations and PDF Receipts": "اختر لون الترويسة والجدول الأساسي لعروض الأسعار وإيصالات PDF",
    "Choose between General Retail POS vs Food & Restaurant Mode with strict UI & route isolation": "اختر بين نقطة بيع التجزئة العامة أو وضع المطاعم والمأكولات مع فصل تام للواجهات والمسارات",
    "Choose dispatch channel, configure message body, and toggle PDF attachment": "اختر قناة الإرسال، واضبط نص الرسالة، وفعل إرفاق ملف PDF",
    "Choose the default interface style for your Point of Sale counter": "اختر نمط الواجهة الافتراضية لمنصة نقطة البيع الخاصة بك",
    "Choose your preferred register design before entering the Point of Sale terminal": "اختر تصميم السجل المفضل لديك قبل الدخول إلى شاشة نقطة البيع",
    "City": "المدينة",
    "City / Location": "المدينة / الموقع",
    "Clean photo tiles, top category tabs, discounts bar & quick-charge pill.": "بطاقات صور أنيقة، تبويبات الفئات العلوية، شريط الخصومات وزر التحصيل السريع.",
    "Clean photo-first tiles, Favorites / Library / Keypad tabs, discount presets & quick blue \"Charge\" pill.": "بطاقات تعتمد على الصور، تبويبات المفضلة / المكتبة / لوحة الأرقام، خيارات الخصم وزر \"تحصيل\" أزرق سريع.",
    "Clear All": "مسح الكل",
    "Clear Cart": "تفريغ السلة",
    "Clear Filter": "إلغاء التصفية",
    "Clear all items in this order?": "مسح جميع العناصر في هذا الطلب؟",
    "Click any menu card on the left to add food.": "انقر على أي صنف من القائمة على اليسار لإضافة الطعام.",
    "Click any table to immediately open POS and take order": "انقر على أي طاولة لفتح نقطة البيع فورًا واستلام الطلب",
    "Click on any product to add it.": "انقر على أي منتج لإضافته.",
    "Click to Insert Smart Placeholders:": "انقر لإدراج المتغيرات الذكية:",
    "Clicking proceed will securely launch the Razorpay checkout dialog supporting Cards, UPI, Netbanking, Google Pay, Apple Pay & Wallets.": "النقر على متابعة سيفتح نافذة دفع Razorpay الآمنة التي تدعم البطاقات وUPI والخدمات المصرفية عبر الإنترنت وGoogle Pay وApple Pay والمحافظ الرقمية.",
    "Client": "العميل",
    "Client Name *": "اسم العميل *",
    "Client:": "العميل:",
    "Close": "إغلاق",
    "Close Register": "إغلاق السجل",
    "Close Register & Generate Z-Report": "إغلاق السجل وإصدار تقرير Z",
    "Closed": "مغلق",
    "Closed By": "أغلق بواسطة",
    "Closing Notes": "ملاحظات الإغلاق",
    "Closing Notes (Optional)": "ملاحظات الإغلاق (اختياري)",
    "Cobalt Blue": "أزرق كوبالت",
    "Code": "الرمز",
    "Code / Key (Optional)": "الرمز / المفتاح (اختياري)",
    "Code / SKU": "الرمز / SKU",
    "Code:": "الرمز:",
    "Collect Pay": "تحصيل الدفع",
    "Collected This Month": "المحصل هذا الشهر",
    "Collection Amount ($)": "مبلغ التحصيل ($)",
    "Company / Store Name *": "اسم الشركة / المتجر *",
    "Company mission card": "بطاقة رسالة الشركة",
    "Complete & Print Receipt": "إتمام وطباعة الإيصال",
    "Complete Checkout": "إتمام عملية الدفع",
    "Configure fine-grained read, write, edit, delete, and export permissions per module.": "تكوين أذونات القراءة والكتابة والتعديل والحذف والتصدير الدقيقة لكل وحدة.",
    "Configure global checkout processors for tenant subscription billing and renewals": "تكوين بوابات الدفع العامة لاشتراكات المتاجر وتجديداتها",
    "Configure outbound email delivery for sending invoices, quotations, and staff invitations": "تكوين إرسال البريد الإلكتروني الصادر للفواتير وعروض الأسعار ودعوات الموظفين",
    "Configure schedule frequency and retention lifecycle for database snapshots": "تكوين تكرار الجدولة ودورة الاحتفاظ بالنسخ الاحتياطية لقاعدة البيانات",
    "Confirm & Complete Sale": "تأكيد وإتمام البيع",
    "Confirm Collection Receipt": "تأكيد إيصال التحصيل",
    "Confirm Password": "تأكيد كلمة المرور",
    "Confirm Settlement Payment": "تأكيد سداد التسوية",
    "Connecting Gateway...": "جارٍ الاتصال ببوابة الدفع...",
    "Contact": "جهة الاتصال",
    "Contact Phone": "هاتف الاتصال",
    "Control Center": "مركز التحكم",
    "Convert": "تحويل",
    "Convert quote #": "تحويل عرض السعر #",
    "Convert this quotation to an active Sale invoice and deduct inventory stock?": "تحويل عرض السعر هذا إلى فاتورة مبيعات نشطة وخصم المخزون؟",
    "Convert to Sale": "تحويل إلى مبيعات",
    "Converted": "تم التحويل",
    "Cost Price ($) *": "سعر التكلفة ($) *",
    "Counted": "المحسوب فعليًا",
    "Counted Cash": "النقد المحسوب فعليًا",
    "Counted Cash in Drawer ($)": "النقد المحسوب في الدرج ($)",
    "Counter Checkout": "دفع عند الكاشير",
    "Country (2-letter ISO)": "الدولة (رمز ISO من حرفين)",
    "Country (ISO 2-letter) *": "الدولة (رمز ISO المكون من حرفين) *",
    "Create & Generate Invite": "إنشاء وإصدار دعوة",
    "Create New Subscription Plan": "إنشاء خطة اشتراك جديدة",
    "Create Quotation": "إنشاء عرض سعر",
    "Create Vendor Bill / Expense": "إنشاء فاتورة مورد / مصروف",
    "Create a public shareable digital menu or product showcase link": "إنشاء رابط قائمة رقمية أو معرض منتجات عام قابل للمشاركة",
    "Create and initialize an isolated tenant store environment with initial admin account": "إنشاء وتهيئة بيئة متجر مستقلة بحساب مسؤول أولي",
    "Create formal quotations and convert them to sales in 1-click": "إنشاء عروض أسعار رسمية وتحويلها إلى مبيعات بنقرة واحدة",
    "Created": "تم الإنشاء",
    "Credit / Receivable Sale:": "بيع آجل / مستحق:",
    "Credit Invoices Ledger": "دفتر أستاذ الفواتير الآجلة",
    "Crimson Red": "أحمر قرمزي",
    "Currency & Price Formatting": "تنسيق العملة والأسعار",
    "Currency Symbol": "رمز العملة",
    "Current / Opening Stock *": "المخزون الحالي / الافتتاحي *",
    "Current Due": "المستحق الحالي",
    "Current Plan": "الخطة الحالية",
    "Current Store Plan": "خطة المتجر الحالية",
    "Current sale": "البيع الحالي",
    "Cust:": "العميل:",
    "Custom Charge Amount": "مبلغ رسوم مخصص",
    "Custom Domain Configuration": "إعداد النطاق المخصص",
    "Custom Hero Banner Image URL (Optional)": "رابط صورة البانر الرئيسي المخصص (اختياري)",
    "Custom WhatsApp Footer Note": "ملاحظة تذييل WhatsApp المخصصة",
    "Customer & Rewards": "العملاء والمكافآت",
    "Customer / Member": "العميل / العضو",
    "Customer Directory Balances": "أرصدة دليل العملاء",
    "Customer Full Name *": "الاسم الكامل للعميل *",
    "Customer Name *": "اسم العميل *",
    "Customer Phone": "هاتف العميل",
    "Customer Testimonials": "آراء وتوصيات العملاء",
    "Customer credit & pending payments": "ائتمان العملاء والمدفوعات المعلقة",
    "Customer credit & unpaid bills": "ائتمان العملاء والفواتير غير المدفوعة",
    "Customer directory & loyalty points": "دليل العملاء ونقاط الولاء",
    "Customer history & contact list": "سجل العميل وقائمة جهات الاتصال",
    "Customer name": "اسم العميل",
    "Customer:": "العميل:",
    "Customers & CRM": "العملاء وإدارة علاقات العملاء (CRM)",
    "Customizable Text Message Body": "نص الرسالة القابل للتخصيص",
    "Customize Phrases for Language:": "تخصيص العبارات للغة:",
    "Customize phrases, POS terms, receipt titles, and tax invoice wording specifically for your store": "تخصيص العبارات ومصطلحات نقطة البيع وعناوين الإيصالات وصيغ الفواتير الضريبية لمتجرك",
    "Customized": "مخصص",
    "DISCOUNT": "خصم",
    "DISPATCHED": "تم الإرسال",
    "Daily Automated Snapshot": "نسخة احتياطية آلية يومية",
    "Dashboard": "لوحة التحكم",
    "Database Driver": "مشغل قاعدة البيانات",
    "Database Name": "اسم قاعدة البيانات",
    "Date:": "التاريخ:",
    "Days": "أيام",
    "Debtor Customers": "العملاء المدينون",
    "Decimal Places": "الخانات العشرية",
    "Default": "الافتراضي",
    "Default Country Calling Code": "مفتاح الاتصال الدولي الافتراضي",
    "Default English Translation": "الترجمة الإنجليزية الافتراضية",
    "Default POS Register Layout Design": "تصميم واجهة نقطة البيع الافتراضية",
    "Default general walk-in sale": "بيع افتراضي لعميل عابر",
    "Default language for customer receipts, table QR orders, and staff POS terminals": "اللغة الافتراضية لإيصالات العملاء وطلبات QR للطاولات وأجهزة نقاط البيع",
    "Default settings for 1-click WhatsApp receipts to customers": "الإعدادات الافتراضية لإرسال إيصالات WhatsApp للعملاء بنقرة واحدة",
    "Default terms and notes auto-loaded into new Quotations": "الشروط والملاحظات الافتراضية المحملة تلقائيًا في عروض الأسعار الجديدة",
    "Delete Bill": "حذف الفاتورة",
    "Delete Selected": "حذف المحدد",
    "Delete this brand?": "حذف هذه العلامة التجارية؟",
    "Delete this category?": "حذف هذه الفئة؟",
    "Delete this customer?": "حذف هذا العميل؟",
    "Delete this product?": "حذف هذا المنتج؟",
    "Delete this snapshot?": "حذف هذه النسخة الاحتياطية؟",
    "Delete this supplier?": "حذف هذا المورد؟",
    "Delete this unit?": "حذف هذه الوحدة؟",
    "Delete translation key": "حذف مفتاح الترجمة",
    "Delivery": "توصيل",
    "Delivery Address": "عنوان التوصيل",
    "Delivery Address / Order Notes": "عنوان التوصيل / ملاحظات الطلب",
    "Departments & tax rates": "الأقسام ونسب الضرائب",
    "Description": "الوصف",
    "Description (Optional)": "الوصف (اختياري)",
    "Description (optional)": "الوصف (اختياري)",
    "Destination:": "الوجهة:",
    "Didn't receive code? Resend Code": "لم تستلم الرمز؟ إعادة إرسال الرمز",
    "Difference": "الفرق",
    "Digital QR menu & WhatsApp store": "قائمة QR الرقمية ومتجر WhatsApp",
    "Digital catalog & WhatsApp share": "الكتالوج الرقمي ومشاركة WhatsApp",
    "Dine-In": "صالة (تناول بالمطعم)",
    "Dine-In, Takeaway & Delivery": "صالة، سفري، وتوصيل",
    "Dining History": "سجل الطلبات السابقة",
    "Direct Invitation Link": "رابط الدعوة المباشر",
    "Direct Proposal / Walk-in Client": "عرض مباشر / عميل مباشر",
    "Disable": "تعطيل",
    "Disabled": "معطل",
    "Disabled — sends clean structured text email only.": "معطل — يرسل بريدًا إلكترونيًا نصيًا منسقًا فقط.",
    "Discount ($)": "الخصم ($)",
    "Discount:": "الخصم:",
    "Discounts": "الخصومات",
    "Dishes, ingredients & pricing": "الأطباق والمكونات والأسعار",
    "Dispatch & Share Invoice:": "إرسال ومشاركة الفاتورة:",
    "Dispatching...": "جارٍ الإرسال...",
    "Displayed in browser tabs for your tenant store": "يظهر في تبويبات المتصفح لمتجرك",
    "Displayed in sidebar, PDF invoices, and online catalog header": "يظهر في الشريط الجانبي وفواتير PDF وترويسة الكتالوج الإلكتروني",
    "Docking Behavior": "سلوك التثبيت والرسو",
    "Docking Screen Position": "موضع التثبيت على الشاشة",
    "Document / Tax ID": "المستند / الرقم الضريبي",
    "Download & Print PDF Invoice": "تنزيل وطباعة فاتورة PDF",
    "Download / Stream PDF": "تنزيل / عرض PDF",
    "Draft": "مسودة",
    "Draft Proposal": "مسودة عرض",
    "Driver / Courier": "السائق / مندوب التوصيل",
    "Driver name": "اسم السائق",
    "Due Date": "تاريخ الاستحقاق",
    "Due Date:": "تاريخ الاستحقاق:",
    "EMV & NFC": "EMV و NFC",
    "EUR": "يورو (EUR)",
    "Edit": "تعديل",
    "Edit Bill": "تعديل الفاتورة",
    "Edit Category": "تعديل الفئة",
    "Edit Customer": "تعديل العميل",
    "Edit Floor Area": "تعديل منطقة الطابق",
    "Edit Payment Method": "تعديل طريقة الدفع",
    "Edit Plan": "تعديل الخطة",
    "Edit Product": "تعديل المنتج",
    "Edit Quotation": "تعديل عرض السعر",
    "Edit Supplier": "تعديل المورد",
    "Edit Table": "تعديل الطاولة",
    "Edit Unit": "تعديل الوحدة",
    "Edit Vendor Bill / Expense": "تعديل فاتورة المورد / المصروف",
    "Email": "البريد الإلكتروني",
    "Email & WhatsApp Invoice Sharing": "مشاركة الفواتير عبر البريد الإلكتروني وWhatsApp",
    "Email Address *": "البريد الإلكتروني *",
    "Email Dispatch (SMTP)": "إرسال البريد الإلكتروني (SMTP)",
    "Email From Name (Sender Name) *": "اسم المرسل في البريد *",
    "Email Invoice": "إرسال الفاتورة بالبريد",
    "Email Invoice Receipt": "إرسال إيصال الفاتورة بالبريد",
    "Email Us": "راسلنا عبر البريد",
    "Email:": "البريد الإلكتروني:",
    "Emerald Green": "أخضر زمردي",
    "Emerald Mint": "نعناعي زمردي",
    "Enable": "تمكين",
    "Enable this payment method for POS checkout": "تمكين طريقة الدفع هذه لنقطة البيع",
    "Enable, disable or add new multilingual languages to the system": "تمكين أو تعطيل أو إضافة لغات جديدة للنظام",
    "Encryption": "التشفير",
    "Encryption Protocol *": "بروتوكول التشفير *",
    "English Name *": "الاسم بالإنجليزية *",
    "Enter a pre-purchased platform license key to activate this plan without card payment.": "أدخل مفتاح ترخيص المنصة الذي تم شراؤه مسبقًا لتفعيل هذه الخطة بدون دفع بالبطاقة.",
    "Enter bank accounts & payment instructions...": "أدخل الحسابات البنكية وتعليمات الدفع...",
    "Enter default quotation policy, deliverables & terms...": "أدخل سياسة عروض الأسعار الافتراضية والبنود والشروط...",
    "Enter invoice policy & terms...": "أدخل سياسة الفواتير والشروط...",
    "Enter password": "أدخل كلمة المرور",
    "Enter your offline activation code or subscription license key to renew or upgrade your store.": "أدخل رمز التفعيل غير المتصل أو مفتاح ترخيص الاشتراك لتجديد متجرك أو ترقيته.",
    "Euro": "يورو",
    "Exchange rates against your base currency, for reporting and multi-currency displays": "أسعار الصرف مقابل العملة الأساسية للتقارير وعرض العملات المتعددة",
    "Exit": "خروج",
    "Exit Fullscreen": "إنهاء ملء الشاشة",
    "Expected": "المتوقع",
    "Expected Cash": "النقد المتوقع",
    "Expected Cash (System)": "النقد المتوقع (النظام)",
    "Expected Cash in Drawer": "النقد المتوقع في الدرج",
    "Expense Category": "فئة المصروف",
    "Expires": "تنتهي الصلاحية",
    "Expires:": "ينتهي في:",
    "Expiry Date": "تاريخ انتهاء الصلاحية",
    "Expiry Date (MM/YY) *": "تاريخ الانتهاء (شهر/سنة) *",
    "Fail": "فشل",
    "Fast barcode scan & cash checkout": "مسح باركود سريع ودفع نقدي فوري",
    "Fast barcode scanning, 3-column product cards, category chips & right-side cart drawer.": "مسح باركود سريع، بطاقات منتجات بـ 3 أعمدة، تصنيفات وسلة جانبية باليمين.",
    "Favicon URL": "رابط أيقونة Favicon",
    "Favorites": "المفضلة",
    "Feature Modules Suite": "حزمة الوحدات والميزات",
    "Filter by Tenant / Company ID…": "تصفية حسب معرف المتجر / الشركة…",
    "Filter by event action (e.g. smtp.updated)…": "تصفية حسب نوع الحدث (مثل smtp.updated)…",
    "Financial & Currency": "المالية والعملة",
    "Financial Management": "الإدارة المالية",
    "Fixed ($)": "مبلغ ثابت ($)",
    "Fixed Docked": "مثبت ومثبت بالموقع",
    "Flag Emoji": "إيموجي العلم",
    "Floating / Free Drag": "عائم / سحب حر",
    "Floor": "الطابق",
    "Floor Area": "منطقة الطابق",
    "Floor plan is active. Take Dine-In orders, manage tables, monitor live kitchen tickets, and handle takeaway or deliveries.": "مخطط الصالة نشط. استقبل طلبات الصالة، وأدر الطاولات، وتابع تذاكر المطبخ المباشرة، وتول طلبات السفري والتوصيل.",
    "Food & Restaurant": "المأكولات والمطاعم",
    "Food & Restaurant Mode": "وضع المأكولات والمطاعم",
    "Food & Restaurant Mode Active": "وضع المأكولات والمطاعم نشط",
    "Food & Restaurant POS": "نقطة بيع المأكولات والمطاعم",
    "Food Item": "عنصر طعام",
    "Food Items:": "أصناف الطعام:",
    "Food Menu": "قائمة الطعام",
    "Food Suppliers": "موردو الأغذية",
    "For restaurants, cafes, bars & food trucks. Includes floor plans & live tables, KOT tickets, Kitchen Display (KDS), Dine-In/Takeaway routing, and QR table ordering.": "للمطاعم والمقاهي والكافيهات وعربات الطعام. تشمل مخططات الصالة والطاولات المباشرة وتذاكر KOT وشاشة المطبخ KDS وطلبات الصالة/السفري وقائمة QR.",
    "For supermarkets, clothing, electronics & retail shops. Includes barcode scanning, cash register, quotations, invoices, and standard stock management.": "للسوبرماركت ومحلات الملابس والإلكترونيات ومتاجر التجزئة. تشمل مسح الباركود، سجل النقد، عروض الأسعار، الفواتير، وإدارة المخزون القياسية.",
    "Forest Green": "أخضر غابي",
    "Free Evaluation": "تقييم مجاني",
    "Free Floating": "عائم حر",
    "Full Access": "وصول كامل",
    "Full Name *": "الاسم الكامل *",
    "Full Name as on Card": "الاسم الكامل كما يظهر على البطاقة",
    "Fullscreen": "ملء الشاشة",
    "Fully Settled": "مسدد بالكامل",
    "Fully Settled (Paid)": "مسدد بالكامل (مدفوع)",
    "Function toolbar, vibrant department tiles & right receipt checkout slip.": "شريط أدوات الوظائف، بطاقات أقسام حيوية، وقسيمة إيصال بالجانب الأيمن.",
    "GRAND TOTAL": "الإجمالي الكلي",
    "General": "عام",
    "General Retail": "التجزئة العامة",
    "General Retail POS (Default)": "نقطة بيع التجزئة العامة (الافتراضي)",
    "Generate Code": "توليد الرمز",
    "Generate Key": "توليد المفتاح",
    "Generate Offline License Voucher": "توليد قسيمة ترخيص بدون اتصال",
    "Generate and manage offline license vouchers for instant self-registration and renewals": "توليد وإدارة قسائم التراخيص بدون اتصال للتسجيل الذاتي والتجديد الفوري",
    "Generates and attaches clean stylized invoice PDF.": "توليد وإرفاق فاتورة PDF منسقة وأنيقة.",
    "Generates and attaches clean stylized proposal PDF.": "توليد وإرفاق عرض أسعار PDF منسق وأنيق.",
    "Global Audit Trail & Security Logs": "سجل التدقيق الشامل وسجلات الأمان",
    "Global Platform SMTP Email Configuration": "إعدادات بريد SMTP العام للمنصة",
    "Global Tax Reference Matrix": "مصفوفة مراجع الضرائب العامة",
    "Grand Total:": "الإجمالي الكلي:",
    "Guest Directory": "دليل الضيوف",
    "Guest name": "اسم الضيف",
    "Guests": "الضيوف",
    "HSN / SAC codes & VAT presets": "رموز HSN / SAC وإعدادات ضريبة القيمة المضافة",
    "Hardware Trust Bar": "شريط الأجهزة المعتمدة",
    "Hero Top Badge Text": "نص الشارة العلوية الرئيسية",
    "Hero Value Proposition Subtitle": "العنوان الفرعي للقيمة المميزة",
    "History": "السجل",
    "History, print receipts & refunds": "السجل، طباعة الإيصالات والمرتجعات",
    "Host": "المضيف",
    "INV-": "INV-",
    "IP Address": "عنوان IP",
    "If you need access to this section, please request permission from your store": "إذا كنت بحاجة إلى الوصول لهذا القسم، يرجى طلب الإذن من متجرك",
    "Immediate": "فوري",
    "Immediate settlement": "تسوية فورية",
    "Immutable event record of administrative actions, config mutations, and security events": "سجل أحداث غير قابل للتعديل للإجراءات الإدارية وتغييرات التكوين والأحداث الأمنية",
    "Import all missing keys from English template": "استيراد جميع المفاتيح المفقودة من النموذج الإنجليزي",
    "In Cooking": "قيد الطهي",
    "Includes: Retail Counter • Barcode POS • Quotes": "يشمل: كاونتر التجزئة • نقطة بيع باركود • عروض أسعار",
    "Includes: Tables • KOT • Kitchen KDS • QR Menus": "يشمل: طاولات • تذاكر KOT • شاشة مطبخ KDS • قوائم QR",
    "Initial Status": "الحالة الأولية",
    "Initial Subscription Plan": "خطة الاشتراك المبدئية",
    "Inquiry Contact Form": "نموذج استفسار وتواصل",
    "Installation complete. The installer is now locked.": "اكتمل التثبيت. تم قفل المثبت الآن.",
    "Instant Tax Receipt Generated": "تم إصدار إيصال ضريبي فوري",
    "Internal Notes": "ملاحظات داخلية",
    "Inv:": "فاتورة:",
    "Inventory / Goods": "المخزون / البضائع",
    "Inventory / Raw Materials": "المخزون / المواد الخام",
    "Invite New Team Member": "دعوة عضو جديد للفريق",
    "Invite User": "دعوة مستخدم",
    "Invoice #": "رقم الفاتورة #",
    "Invoice / Receipt Attachment (PDF, Image)": "مرفق الفاتورة / الإيصال (PDF، صورة)",
    "Invoice Prefix": "بادئة الفاتورة",
    "Invoice Terms & Conditions (Rich-Text)": "شروط وأحكام الفاتورة (نص منسق)",
    "Invoice Terms & Policy": "شروط وسياسة الفواتير",
    "Invoice prefixes, default quotation terms, and payment instructions": "بادئات الفواتير، شروط عروض الأسعار الافتراضية، وتعليمات الدفع",
    "Item": "العنصر",
    "Item & Description": "العنصر والوصف",
    "Item & Scope Description": "العنصر ونطاق الوصف",
    "Item Code": "رمز العنصر",
    "Item or service name *": "اسم العنصر أو الخدمة *",
    "Itemized GST/VAT Tax Invoices": "فواتير ضريبية مفصلة (GST/VAT)",
    "Itemized tax receipts for store subscriptions, license activations, and renewals": "إيصالات ضريبية مفصلة لاشتراكات المتجر وتفعيل التراخيص والتجديدات",
    "Jurisdiction standards, default VAT rates, and GST/HSN classification guidelines": "معايير النطاق القضائي، والنسب الافتراضية لضريبة القيمة المضافة وإرشادات GST/HSN",
    "Keep Order On Screen": "إبقاء الطلب على الشاشة",
    "Keep the navigation bar pinned in view while scrolling through long views and forms": "تثبيت شريط التنقل في العرض أثناء التمرير في النماذج الطويلة",
    "Key Name (Exact String) *": "اسم المفتاح (النص الدقيق) *",
    "Keypad": "لوحة الأرقام",
    "Keypad Entry": "إدخال بلوحة الأرقام",
    "Kitchen Display System": "نظام شاشة المطبخ (KDS)",
    "Kitchen Display System (KDS)": "نظام شاشة المطبخ (KDS)",
    "Kitchen KDS": "شاشة المطبخ KDS",
    "Kitchen Menu & Catalog": "قائمة وكتالوج المطبخ",
    "Kitchen Note": "ملاحظة للمطبخ",
    "Kitchen Note (Optional)": "ملاحظة للمطبخ (اختياري)",
    "Landing Neon Lime Accent": "لون لمسة الليمون النيوني للصفحة الرئيسية",
    "Landing Page Sections Controller": "التحكم في أقسام الصفحة الرئيسية",
    "Landing Primary Emerald": "الزمردي الأساسي للصفحة الرئيسية",
    "Language Code (ISO) *": "رمز اللغة (ISO) *",
    "Language:": "اللغة:",
    "Launch Selected POS Register": "تشغيل سجل نقطة البيع المحدد",
    "Layout": "المخطط والتصميم",
    "Layout Direction:": "اتجاه الواجهة:",
    "Lead capture form": "نموذج جذب العملاء المحتملين",
    "Left Sidebar": "الشريط الجانبي الأيسر",
    "Left vertical function menu, vibrant department tiles, paginated grid & thermal receipt checkout slip.": "قائمة وظائف عمودية على اليسار، بطاقات أقسام واضحة، شبكة مقسمة لصفحات وإيصال حراري.",
    "Left-to-Right (LTR)": "من اليسار إلى اليمين (LTR)",
    "Legal": "قانوني",
    "Legal / Company Name": "الاسم القانوني / اسم الشركة",
    "Library": "المكتبة",
    "License Voucher": "قسيمة الترخيص",
    "Line Items & Scope Specifications": "عناصر البنود وتفاصيل النطاق",
    "Link Expiration": "انتهاء صلاحية الرابط",
    "Linked Supplier (Optional)": "المورد المرتبط (اختياري)",
    "Live": "مباشر",
    "Live KDS": "شاشة المطبخ المباشرة",
    "Live KOT preparation queue": "طابور تحضير تذاكر KOT المباشر",
    "Live Kitchen Tickets": "تذاكر المطبخ الحية",
    "Live Metric Counters": "عدادات المقاييس المباشرة",
    "Live POS": "نقطة البيع المباشرة",
    "Live Status:": "الحالة المباشرة:",
    "Live Table Status & QR Menus": "حالة الطاولات المباشرة وقوائم QR",
    "Location": "الموقع",
    "Logistics & Freight": "الخدمات اللوجستية والشحن",
    "Logistics, Freight & Delivery": "اللوجستيات والشحن والتوصيل",
    "Low Stock Warnings": "تنبيهات انخفاض المخزون",
    "Loyalty Points": "نقاط الولاء",
    "Main Headline Title *": "العنوان الرئيسي *",
    "Maintenance & Repairs": "الصيانة والإصلاحات",
    "Maintenance Lockout Message": "رسالة قفل الصيانة",
    "Manage": "إدارة",
    "Manage Floor Plan": "إدارة مخطط الصالة",
    "Manage manufacturers and brands": "إدارة المصنعين والعلامات التجارية",
    "Manage seating floor areas, table occupancy statuses, and QR code digital menus": "إدارة مناطق الجلوس، وحالات إشغال الطاولات، وقوائم QR الرقمية",
    "Manage signed-in sessions across browsers and POS registers": "إدارة الجلسات المسجلة عبر المتصفحات وأجهزة نقاط البيع",
    "Manage supported platform languages, customize JSON translation files, and synchronize multilingual dictionaries": "إدارة لغات المنصة المدعومة، وتخصيص ملفات ترجمة JSON ومزامنة القواميس",
    "Manage units of measure for inventory and billing": "إدارة وحدات القياس للمخزون والفوترة",
    "Manage vendor bills, operational expenses, utility costs, supplier settlements, and payment proofs.": "إدارة فواتير الموردين، المصروفات التشغيلية، فواتير الخدمات، تسويات الموردين وإثباتات الدفع.",
    "Manage your store subscription plan, redeem activation keys, and access compliant tax invoices": "إدارة خطة اشتراك متجرك، واسترداد مفاتيح التفعيل، والوصول للفواتير الضريبية المعتمدة",
    "Manual movements this shift": "الحركات اليدوية لهذه الوردية",
    "Mark as Ready": "تحديد كجاهز",
    "Mark as Served": "تحديد كتم التقديم",
    "Marketing & Ads": "التسويق والإعلانات",
    "Marketing & Promotions": "التسويق والعروض الترويجية",
    "Max POS Devices Limit": "الحد الأقصى لأجهزة نقاط البيع",
    "Max Users Limit": "الحد الأقصى لعدد المستخدمين",
    "Measurement Units": "وحدات القياس",
    "Member:": "العضو:",
    "Membership": "العضوية",
    "Menu": "القائمة",
    "Menu Dishes & Stock": "أطباق القائمة والمخزون",
    "Menu sections & tax rates": "أقسام القائمة ونسب الضرائب",
    "Method": "الطريقة",
    "Method Name": "اسم الطريقة",
    "Method Name *": "اسم الطريقة *",
    "Method:": "الطريقة:",
    "Midnight Slate": "أردواز منتصف الليل",
    "Migration failed. Check the output above and try again.": "فشلت عملية الترحيل. تحقق من المخرجات أعلاه وحاول مجددًا.",
    "Minimum Alert Stock *": "حد التنبيه الأدنى للمخزون *",
    "Minimum Client Build Version": "الحد الأدنى لإصدار تطبيق العميل",
    "Module": "الوحدة",
    "Monthly": "شهريًا",
    "Monthly Snapshot": "نسخة احتياطية شهرية",
    "Multi-Language & Translation File Editor": "محرر اللغات المتعددة وملفات الترجمة",
    "N/A": "غير متوفر",
    "Name": "الاسم",
    "Name *": "الاسم *",
    "Native Name": "الاسم باللغة الأصلية",
    "Never": "أبدًا",
    "Never (Lifetime)": "دائم (مدى الحياة)",
    "Never (Permanent link)": "دائم (رابط دائم)",
    "New": "جديد",
    "New Brand": "علامة تجارية جديدة",
    "New Category": "فئة جديدة",
    "New Customer": "عميل جديد",
    "New POS Credit Sale": "بيع آجل جديد في نقطة البيع",
    "New Product": "منتج جديد",
    "New Quotation": "عرض سعر جديد",
    "New Sale": "عملية بيع جديدة",
    "New Supplier": "مورد جديد",
    "New Unit": "وحدة جديدة",
    "New orders from Dine-In tables, Takeaway, Delivery, or QR Digital Menu will appear here in real-time.": "ستظهر هنا الطلبات الجديدة من طاولات الصالة، السفري، التوصيل، أو قائمة QR الرقمية فورًا ومباشرة.",
    "No Cash Register Open": "لا يوجد سجل نقد مفتوح",
    "No Floor Assigned": "لم يتم تعيين طابق",
    "No Image": "لا توجد صورة",
    "No Plan (Unlimited / Manual)": "بدون خطة (غير محدود / يدوي)",
    "No accounts receivable records match current filters.": "لا توجد سجلات ذمم مدينة مطابقة لعوامل التصفية الحالية.",
    "No activation codes generated yet. Click \"+ Generate Key\" above.": "لم يتم إنشاء رموز تفعيل بعد. انقر على \"+ توليد المفتاح\" أعلاه.",
    "No active products available.": "لا توجد منتجات نشطة متاحة.",
    "No active sessions found.": "لا توجد جلسات نشطة.",
    "No brands yet. Click \"+ New Brand\" to add one.": "لا توجد علامات تجارية بعد. انقر على \"+ علامة تجارية جديدة\" لإضافة واحدة.",
    "No cash movements recorded yet.": "لم يتم تسجيل أي حركات نقدية بعد.",
    "No catalogs published yet.": "لم يتم نشر أي كتالوج بعد.",
    "No categories yet. Click \"+ New Category\" to create one.": "لا توجد فئات بعد. انقر على \"+ فئة جديدة\" لإنشاء واحدة.",
    "No closed registers yet.": "لا توجد سجلات مغلقة بعد.",
    "No contact details": "لا توجد بيانات اتصال",
    "No customer records found.": "لم يتم العثور على سجلات عملاء.",
    "No customers found matching": "لم يتم العثور على عملاء مطابقين لـ",
    "No customers registered yet.": "لم يتم تسجيل أي عملاء بعد.",
    "No dining floor areas created yet.": "لم يتم إنشاء مناطق طوابق طعام بعد.",
    "No food items found. Use \"+ Add Product\" in Products menu to create items.": "لم يتم العثور على أصناف طعام. استخدم \"+ إضافة منتج\" في قائمة المنتجات لإنشاء أصناف.",
    "No items added to receipt yet.": "لم تتم إضافة أي عناصر إلى الإيصال بعد.",
    "No items found matching your search.": "لم يتم العثور على عناصر تطابق بحثك.",
    "No items selected for this order.": "لم يتم تحديد أي عناصر لهذا الطلب.",
    "No other currencies configured.": "لم يتم ضبط أي عملات أخرى.",
    "No payment methods configured. Click \"+ Add Method\" to create one.": "لم يتم ضبط طرق دفع بعد. انقر على \"+ إضافة طريقة\" لإنشاء واحدة.",
    "No products available in catalog.": "لا توجد منتجات متاحة في الكتالوج.",
    "No products available in this department.": "لا توجد منتجات متاحة في هذا القسم.",
    "No products in catalog yet.": "لا توجد منتجات في الكتالوج بعد.",
    "No products yet. Click \"+ New Product\" to add items.": "لا توجد منتجات بعد. انقر على \"+ منتج جديد\" لإضافة عناصر.",
    "No quotations found matching the filter criteria.": "لم يتم العثور على عروض أسعار تطابق معايير التصفية.",
    "No recent kitchen tickets.": "لا توجد تذاكر مطبخ حديثة.",
    "No recent sales records found.": "لم يتم العثور على سجلات مبيعات حديثة.",
    "No sales found.": "لم يتم العثور على مبيعات.",
    "No sales recorded yet this shift.": "لم يتم تسجيل أي مبيعات بعد في هذه الوردية.",
    "No sales recorded.": "لم يتم تسجيل أي مبيعات.",
    "No subscription tax invoices generated yet.": "لم يتم إصدار أي فواتير ضريبية للاشتراك بعد.",
    "No suppliers yet. Click \"+ New Supplier\" to add one.": "لا يوجد موردون بعد. انقر على \"+ مورد جديد\" لإضافة واحد.",
    "No tables registered for this floor. Click \"+ Add Table\" to start.": "لا توجد طاولات مسجلة لهذا الطابق. انقر على \"+ إضافة طاولة\" للبدء.",
    "No team members found. Click \"+ Invite User\" to add staff.": "لم يتم العثور على أعضاء فريق. انقر على \"+ دعوة مستخدم\" لإضافة موظفين.",
    "No units yet. Click \"+ New Unit\" to add one.": "لا توجد وحدات بعد. انقر على \"+ وحدة جديدة\" لإضافة واحدة.",
    "No vendor bills or operational expenses match current filters.": "لا توجد فواتير موردين أو مصروفات تشغيلية تطابق عوامل التصفية الحالية.",
    "Non-Supplier / General Vendor": "بائع عام / غير مسجل كمورد",
    "None": "لا يوجد",
    "None (Port 25)": "بدون (المنفذ 25)",
    "None (Use built-in modules only)": "بدون (استخدام الوحدات المضمنة فقط)",
    "Not Set": "غير محدد",
    "Note:": "ملاحظة:",
    "Notes & Remarks": "ملاحظات وتعليقات",
    "Notes regarding installment / settlement...": "ملاحظات حول القسط / التسوية...",
    "Notification & Dispatch": "الإشعارات والإرسال",
    "OFF": "معطل",
    "ON": "مفعل",
    "OVERDUE": "متأخر السداد",
    "Occupied": "مشغول",
    "Ocean Sky": "أزرق سماوي محيطي",
    "Office Supplies": "مستلزمات مكتبية",
    "Office Supplies & Software": "مستلزمات مكتبية وبرمجيات",
    "Official Razorpay Payment Gateway": "بوابة دفع Razorpay الرسمية",
    "Official Tax Invoices & Payment Receipts": "الفواتير الضريبية وإيصالات الدفع الرسمية",
    "One-Time Invitation Code": "رمز دعوة لمرة واحدة",
    "Online Catalog": "الكتالوج الإلكتروني",
    "Online QR Menu": "قائمة QR الإلكترونية",
    "Open Cash Register": "فتح سجل النقد",
    "Open KDS": "فتح شاشة المطبخ (KDS)",
    "Open Link": "فتح الرابط",
    "Open Register": "فتح السجل",
    "Open Restaurant POS": "فتح نقطة بيع المطعم",
    "Open Table POS": "فتح نقطة بيع الطاولة",
    "Open WhatsApp & Send": "فتح WhatsApp والإرسال",
    "Open a register with a starting cash float to begin tracking today's shift.": "افتح السجل بمبلغ عهدة افتتاحي لبدء تتبع وردية اليوم.",
    "Open/close the register, track cash in & out, and generate X/Z shift reports.": "فتح/إغلاق السجل، تتبع النقد الداخل والخارج، وإصدار تقارير الوردية X و Z.",
    "Opened": "مفتوح",
    "Opening": "افتتاح",
    "Opening Float": "المبلغ الافتتاحي (العهدة)",
    "Opening Float ($)": "المبلغ الافتتاحي ($)",
    "Operating Mode": "وضع التشغيل",
    "Option:": "الخيار:",
    "Optional": "اختياري",
    "Options": "الخيارات",
    "Or Direct Image URL": "أو رابط مباشر للصورة",
    "Order": "طلب",
    "Order No.": "رقم الطلب",
    "Order Notes & Remarks (Printed on Receipt)": "ملاحظات الطلب (تطبع على الإيصال)",
    "Order Notes & Remarks:": "ملاحظات وتعليقات الطلب:",
    "Order Sent to Kitchen!": "تم إرسال الطلب إلى المطبخ!",
    "Order Subtotal": "المجموع الفرعي للطلب",
    "Order via WhatsApp": "الطلب عبر WhatsApp",
    "Orders & Cash": "الطلبات والنقد",
    "Orders & thermal receipts": "الطلبات والإيصالات الحرارية",
    "Organize products into POS categories": "تنظيم المنتجات في فئات لنقطة البيع",
    "Other Currencies (Reference Rates)": "عملات أخرى (أسعار مرجعية)",
    "Other Expenses": "مصروفات أخرى",
    "Over": "فائض",
    "Overdue Accounts": "الحسابات المتأخرة",
    "Overdue Balance": "الرصيد المتأخر",
    "Overdue Bills": "الفواتير المتأخرة",
    "Override unit price": "تجاوز سعر الوحدة",
    "PARTIAL": "جزئي",
    "PDF": "PDF",
    "POS Checkout & Payment": "دفع وتسوية نقطة البيع",
    "POS Server": "خادم نقطة البيع",
    "POS, Inventory, KOT, Finance": "نقطة البيع، المخزون، KOT، والمالية",
    "PROPOSAL PREPARED FOR:": "تم إعداد العرض لـ:",
    "Page Title *": "عنوان الصفحة *",
    "Paid Amount:": "المبلغ المدفوع:",
    "Paid so far": "المدفوع حتى الآن",
    "Partially Paid": "مدفوع جزئيًا",
    "Pass": "ناجح",
    "Password": "كلمة المرور",
    "Pay": "دفع",
    "Pay & Settle Bill": "دفع وتسوية الفاتورة",
    "Pay & Upgrade": "الدفع والترقية",
    "Pay Bill": "دفع الفاتورة",
    "Pay Method:": "طريقة الدفع:",
    "Payable To": "مستحق الدفع لـ",
    "Payment": "الدفع",
    "Payment Date": "تاريخ الدفع",
    "Payment Information": "معلومات الدفع",
    "Payment Method": "طريقة الدفع",
    "Payment Method:": "طريقة الدفع:",
    "Payment Proof / Bank Receipt (Optional)": "إثبات الدفع / الإيصال البنكي (اختياري)",
    "Payment Remarks": "ملاحظات الدفع",
    "Payment required to activate services & generate tax invoice": "الدفع مطلوب لتفعيل الخدمات وإصدار الفاتورة الضريبية",
    "Payment terms, bank details, purchase order #...": "شروط الدفع، التفاصيل البنكية، رقم أمر الشراء...",
    "Payroll & Salaries": "الرواتب والأجور",
    "Payroll & Staff Wages": "جدول الرواتب وأجور الموظفين",
    "Pending / In Cooking": "قيد الانتظار / قيد الطهي",
    "Pending / Unpaid": "معلق / غير مدفوع",
    "Pending Invoices": "فواتير معلقة",
    "Pending Orders": "طلبات معلقة",
    "Percent (%)": "نسبة مئوية (%)",
    "Perfect for small retail stores": "مثالي لمتاجر التجزئة الصغيرة",
    "Permissions Matrix": "مصفوفة الصلاحيات",
    "Perpetual / Lifetime": "دائم / مدى الحياة",
    "Phone / Contact": "الهاتف / الاتصال",
    "Phone / WhatsApp": "الهاتف / WhatsApp",
    "Phone / WhatsApp (Optional)": "الهاتف / WhatsApp (اختياري)",
    "Phone number (+1 555 0199)": "رقم الهاتف (+1 555 0199)",
    "Phone:": "الهاتف:",
    "Phrase Key *": "مفتاح العبارة *",
    "Physical Address": "العنوان الفعلي",
    "Pickup Time": "وقت الاستلام",
    "Piece, Kilogram, Box…": "قطعة، كيلوغرام، صندوق…",
    "Pieces, kg, box, packs & liters": "قطع، كجم، صندوق، عبوات ولترات",
    "Plan": "الخطة",
    "Plan / Description": "الخطة / الوصف",
    "Plan details & invoices": "تفاصيل الخطة والفواتير",
    "Platform": "المنصة",
    "Platform Application Version": "إصدار تطبيق المنصة",
    "Platform Brand Name *": "اسم العلامة التجارية للمنصة *",
    "Platform GST / Tax (18% • CGST 9% + SGST 9%)": "ضريبة المنصة (18% • CGST 9% + SGST 9%)",
    "Platform Logo URL": "رابط شعار المنصة",
    "Platform Payment Gateways": "بوابات الدفع للمنصة",
    "Please provide a valid name for all items.": "يرجى تقديم اسم صالح لجميع العناصر.",
    "Point your domain's": "وجّه نطاقك",
    "Points Delta (+/-)": "تغير النقاط (+/-)",
    "Points:": "النقاط:",
    "Port": "المنفذ",
    "Port *": "المنفذ *",
    "Portions, kg, litres & grams": "حصص، كجم، لتر وجرام",
    "Postal Code": "الرمز البريدي",
    "Prefix": "البادئة",
    "Prepared By:": "أُعد بواسطة:",
    "Preset Quick Discounts": "خصومات سريعة جاهزة",
    "Preview": "معاينة",
    "Preview Landing Page": "معاينة الصفحة الرئيسية",
    "Price": "السعر",
    "Price ($)": "السعر ($)",
    "Pricing Plans Grid": "شبكة خطط الأسعار",
    "Primary CTA Button Label": "نص زر الدعوة للإجراء الأساسي",
    "Primary CTA URL": "رابط زر الدعوة للإجراء الأساسي",
    "Primary Payment Method": "طريقة الدفع الأساسية",
    "Print Kitchen Ticket (KOT)": "طباعة تذكرة المطبخ (KOT)",
    "Print Ticket": "طباعة التذكرة",
    "Print receipt/invoice": "طباعة الإيصال/الفاتورة",
    "Processing Charge...": "جارٍ معالجة الرسوم...",
    "Processing Sale...": "جارٍ معالجة البيع...",
    "Processing Transaction...": "جارٍ معالجة المعاملة...",
    "Processing...": "جارٍ المعالجة...",
    "Product": "المنتج",
    "Product Brands": "العلامات التجارية للمنتجات",
    "Product Categories": "فئات المنتجات",
    "Product Name *": "اسم المنتج *",
    "Product brands & food options": "علامات المنتجات وخيارات الطعام",
    "Production / Live Mode": "وضع الإنتاج / المباشر",
    "Profile, printer, tax & domain": "الملف الشخصي، الطابعة، الضريبة والنطاق",
    "Profiles, history & loyalty": "الملفات الشخصية، السجل ونقاط الولاء",
    "Proof": "الإثبات",
    "Provision New Store": "تهيئة متجر جديد",
    "Public / Publishable API Key": "مفتاح API العام / القابل للنشر",
    "Publish Public Catalog": "نشر كتالوج عام",
    "Publish an Online Catalog": "نشر كتالوج إلكتروني",
    "Published Shareable Links": "الروابط القابلة للمشاركة المنشورة",
    "QR Stand": "حامل QR",
    "QUO-": "QUO-",
    "Qty": "الكمية",
    "Qty:": "الكمية:",
    "Quick Add Customer": "إضافة عميل سريعة",
    "Quotation & Invoice Document Accent Color": "لون تمييز مستندات عروض الأسعار والفواتير",
    "Quotation Prefix": "بادئة عروض الأسعار",
    "Quotations & Proposals": "عروض الأسعار والمقترحات",
    "Quote #": "رقم عرض السعر #",
    "Quote No:": "رقم عرض السعر:",
    "Quote Reference:": "مرجع عرض السعر:",
    "Quote Terms & Notes": "شروط وملاحظات عرض السعر",
    "Quote Terms & Notes (Rich-Text)": "شروط وملاحظات عرض السعر (نص منسق)",
    "Quotes, estimates & 1-click sales conversion": "عروض الأسعار والتقديرات وتحويلها للبيع بنقرة واحدة",
    "Quotes, proposals & estimates": "عروض الأسعار والمقترحات والتقديرات",
    "Rate": "السعر / النسبة",
    "Razorpay": "Razorpay",
    "Ready to Serve": "جاهز للتقديم",
    "Real-Time": "في الوقت الفعلي",
    "Real-time live kitchen order tracker & ticket bump screen (Auto-refreshing every 5s)": "شاشة تتبع أوامر المطبخ الحية في الوقت الفعلي وتحديث التذاكر (تحديث تلقائي كل 5 ثوانٍ)",
    "Reason": "السبب",
    "Reason / Note": "السبب / الملاحظة",
    "Receipt Prefixes & Bank Terms": "بادئات الإيصالات والشروط البنكية",
    "Recent POS Transactions": "معاملات نقطة البيع الأخيرة",
    "Recipient Email Address": "البريد الإلكتروني للمستلم",
    "Recipient Email Address *": "البريد الإلكتروني للمستلم *",
    "Recipient WhatsApp Phone Number (with Country Code)": "رقم هاتف المستلم على WhatsApp (مع رمز الدولة)",
    "Record Bill Settlement Payment": "تسجيل سداد تسوية الفاتورة",
    "Record Cash In": "تسجيل إيداع نقدي",
    "Record Cash Out": "تسجيل سحب نقدي",
    "Record Receivable Payment": "تسجيل سداد مستحقات",
    "Redeem & Activate": "استرداد وتفعيل",
    "Redeem License Key": "استرداد مفتاح الترخيص",
    "Ref #": "رقم المرجع #",
    "Ref / Card Last4": "المرجع / آخر 4 أرقام من البطاقة",
    "Reference / Transaction / Check #": "المرجع / المعاملة / رقم الشيك #",
    "Register": "سجل النقد",
    "Register History (Closed Shifts / Z-Reports)": "سجل الورديات (الورديات المغلقة / تقارير Z)",
    "Register users and define what each one can see and do.": "تسجيل المستخدمين وتحديد ما يمكن لكل منهم رؤيته وفعله.",
    "Registered on": "مسجل في",
    "Registration prompt": "رسالة التسجيل",
    "Rejected": "مرفوض",
    "Remaining": "المتبقي",
    "Remaining Balance": "الرصيد المتبقي",
    "Remaining Due": "المتبقي المستحق",
    "Remove": "إزالة",
    "Remove split line": "إزالة سطر التقسيم",
    "Remove table": "إزالة الطاولة",
    "Rent & Facilities": "الإيجار والمرافق",
    "Rent & Premises": "الإيجار والمباني",
    "Rep:": "المندوب:",
    "Requires follow-up": "يتطلب متابعة",
    "Reserved": "محجوز",
    "Reset": "إعادة ضبط",
    "Reset Template": "إعادة ضبط النموذج",
    "Reset to system default": "إعادة التعيين إلى الافتراضي للنظام",
    "Resolve the failed checks above before continuing.": "يرجى حل الفحوصات الفاشلة أعلاه قبل المتابعة.",
    "Restaurant Mode": "وضع المطاعم",
    "Restock": "إعادة التخزين",
    "Resume Fullscreen": "استئناف ملء الشاشة",
    "Retention Window (Days)": "فترة الاحتفاظ (بالأيام)",
    "Return to my account": "العودة إلى حسابي",
    "Review & Place Order": "مراجعة وتأكيد الطلب",
    "Revoke": "إلغاء الترخيص",
    "Revoke this license key?": "إلغاء مفتاح الترخيص هذا؟",
    "Revoke this link?": "إلغاء هذا الرابط؟",
    "Revoked": "ملغى",
    "Right Sidebar": "الشريط الجانبي الأيمن",
    "Right-to-Left (RTL - Arabic, Hebrew)": "من اليمين إلى اليسار (RTL - العربية، العبرية)",
    "Role & Profile *": "الدور والملف التعريفي *",
    "Role Profile": "ملف الدور والصلاحيات",
    "Row": "صف",
    "Royal Indigo": "نيلي ملكي",
    "Royal Purple": "أرجواني ملكي",
    "Ruby Rose": "وردي ياقوتي",
    "SKU": "رمز المنتج (SKU)",
    "SKU Scan": "مسح رمز المنتج (SKU)",
    "SKUs, pricing & inventory levels": "رموز SKU والأسعار ومستويات المخزون",
    "SMTP Email Settings": "إعدادات بريد SMTP",
    "SMTP Host": "مضيف SMTP",
    "SMTP Host Server *": "خادم مضيف SMTP *",
    "SMTP Password": "كلمة مرور SMTP",
    "SMTP Port": "منفذ SMTP",
    "SMTP Username": "اسم مستخدم SMTP",
    "SMTP Username / API Key": "اسم مستخدم SMTP / مفتاح API",
    "SSL": "SSL",
    "SSL (Port 465)": "SSL (المنفذ 465)",
    "SUB TOTAL": "المجموع الفرعي",
    "Sale": "البيع",
    "Sale #": "رقم البيع #",
    "Sale / Inv #": "رقم البيع / الفاتورة #",
    "Sale Completed!": "اكتمل البيع بنجاح!",
    "Sale Price ($) *": "سعر البيع ($) *",
    "Sales Representative": "ممثل المبيعات",
    "Sales by Payment Method": "المبيعات حسب طريقة الدفع",
    "Sales by Payment Method (This Shift)": "المبيعات حسب طريقة الدفع (هذه الوردية)",
    "Sandbox / Test Mode": "وضع الاختبار / التجريبي",
    "Save & Preview Quotation": "حفظ ومعاينة عرض السعر",
    "Save & Select Customer": "حفظ واختيار العميل",
    "Save All Custom Translations": "حفظ جميع الترجمات المخصصة",
    "Save All Settings": "حفظ جميع الإعدادات",
    "Save Bill / Expense": "حفظ الفاتورة / المصروف",
    "Save Category": "حفظ الفئة",
    "Save Customer": "حفظ العميل",
    "Save Financial Settings": "حفظ الإعدادات المالية",
    "Save Floor": "حفظ الطابق",
    "Save Method": "حفظ الطريقة",
    "Save Notification & Dispatch Settings": "حفظ إعدادات الإشعارات والإرسال",
    "Save Operating Mode": "حفظ وضع التشغيل",
    "Save Permissions": "حفظ الصلاحيات",
    "Save Phrase": "حفظ العبارة",
    "Save Plan": "حفظ الخطة",
    "Save Product": "حفظ المنتج",
    "Save Profile & Branding": "حفظ الملف التعريفي والهوية",
    "Save Receipt Prefixes & Bank Terms": "حفظ بادئات الإيصالات والشروط البنكية",
    "Save SMTP Configuration": "حفظ تكوين SMTP",
    "Save Store Overrides": "حفظ تخصيصات المتجر",
    "Save Supplier": "حفظ المورد",
    "Save Table": "حفظ الطاولة",
    "Save Unit": "حفظ الوحدة",
    "Saved securely": "تم الحفظ بأمان",
    "Saving...": "جارٍ الحفظ...",
    "Scan barcode / SKU...": "امسح الباركود / رمز المنتج...",
    "Scan barcode or type product name / SKU...": "امسح الباركود أو اكتب اسم المنتج / SKU...",
    "Scan to View Menu & Order": "امسح لعرض القائمة والطلب",
    "Scheduled outgoings": "المصروفات المجدولة",
    "Scope specifications / item deliverables description (optional)...": "مواصفات النطاق / وصف مخرجات البنود (اختياري)...",
    "Search and attach a customer to this sale": "ابحث عن عميل واربطه بعملية البيع هذه",
    "Search bar, category chips, 3-column retail item cards with side cart.": "شريط بحث، تصنيفات، بطاقات عناصر تجزئة بـ 3 أعمدة مع سلة جانبية.",
    "Search bill #, vendor, title...": "ابحث برقم الفاتورة، المورد، العنوان...",
    "Search by customer name, phone, or email...": "ابحث باسم العميل، الهاتف، أو البريد الإلكتروني...",
    "Search by name, code, barcode…": "ابحث بالاسم، الرمز، الباركود…",
    "Search by name, email, phone…": "ابحث بالاسم، البريد الإلكتروني، الهاتف…",
    "Search by sale # or customer…": "ابحث برقم البيع أو العميل…",
    "Search invoice #, customer...": "ابحث برقم الفاتورة، العميل...",
    "Search items...": "ابحث عن عناصر...",
    "Search keys or translated phrases…": "ابحث في المفاتيح أو العبارات المترجمة…",
    "Search menu...": "ابحث في القائمة...",
    "Search quotation # or client name...": "ابحث برقم عرض السعر أو اسم العميل...",
    "Search stores by name, account ID, email, slug…": "ابحث في المتاجر بالاسم، معرف الحساب، البريد، الاسم المختصر…",
    "Search suppliers by name…": "ابحث في الموردين بالاسم…",
    "Search team by name, email, or role...": "ابحث في الفريق بالاسم، البريد، أو الدور...",
    "Search terms or phrases…": "ابحث في المصطلحات أو العبارات…",
    "Seat": "مقعد",
    "Secondary CTA Button Label": "نص زر الدعوة للإجراء الثانوي",
    "Secondary CTA URL": "رابط زر الدعوة للإجراء الثانوي",
    "Secure Subscription Checkout": "الدفع الآمن للاشتراك",
    "Select Available Table": "اختر طاولة متاحة",
    "Select Brand": "اختر العلامة التجارية",
    "Select Category": "اختر الفئة",
    "Select Client / Customer": "اختر العميل",
    "Select Customer / Member": "اختر العميل / العضو",
    "Select Destination Table": "اختر الطاولة المقصودة",
    "Select Dine-In Table": "اختر طاولة الصالة",
    "Select Extra Page to Embed": "اختر صفحة إضافية لتضمينها",
    "Select Language File to Edit:": "اختر ملف اللغة للتعديل:",
    "Select POS Layout & Interface Design": "اختر تصميم واجهة وتخطيط نقطة البيع",
    "Select Payment Method": "اختر طريقة الدفع",
    "Select Products to Include": "اختر المنتجات لتضمينها",
    "Select Table": "اختر طاولة",
    "Select User to Configure:": "اختر المستخدم للضبط:",
    "Select the primary accent color for your navigation sidebar, buttons, and badges": "اختر اللون التمييزي الأساسي للشريط الجانبي والأزرار والشارات",
    "Selected": "المحدد",
    "Selected ✓": "تم التحديد ✓",
    "Send": "إرسال",
    "Send Email": "إرسال بريد إلكتروني",
    "Send Email via SMTP": "إرسال بريد إلكتروني عبر SMTP",
    "Send Invoice Email": "إرسال الفاتورة عبر البريد",
    "Send Invoice via Email": "إرسال الفاتورة عبر البريد الإلكتروني",
    "Send Order to Kitchen": "إرسال الطلب إلى المطبخ",
    "Send Quotation Email": "إرسال عرض السعر بالبريد",
    "Send Quotation Proposal #": "إرسال مقترح عرض السعر #",
    "Send Tax Invoice #": "إرسال الفاتورة الضريبية #",
    "Send Tax Invoice Receipt": "إرسال إيصال الفاتورة الضريبية",
    "Send Test Email": "إرسال بريد اختباري",
    "Send a test email to verify your SMTP configuration": "إرسال بريد اختباري للتحقق من إعدادات SMTP",
    "Send an immediate test dispatch to verify that your SMTP host credentials and sender address are working properly.": "إرسال رسالة اختبار فورية للتأكد من أن بيانات اعتماد مضيف SMTP وعنوان المرسل تعمل بشكل صحيح.",
    "Send an invitation to join your store via WhatsApp or Email": "إرسال دعوة للانضمام إلى متجرك عبر WhatsApp أو البريد الإلكتروني",
    "Send invitation email automatically via store SMTP": "إرسال بريد الدعوة تلقائيًا عبر SMTP الخاص بالمتجر",
    "Sender Display Name": "اسم عرض المرسل",
    "Sender Email Address": "عنوان بريد المرسل",
    "Sending Test...": "جارٍ إرسال الاختبار...",
    "Sending...": "جارٍ الإرسال...",
    "Sent": "تم الإرسال",
    "Sent to Client": "أُرسل إلى العميل",
    "Setting": "الإعداد",
    "Settle Bill & Print Receipt": "تسوية الفاتورة وطباعة الإيصال",
    "Settled": "مسدد",
    "Settled (Paid)": "مسدد (مدفوع)",
    "Settled This Month": "المسدد هذا الشهر",
    "Settlement Amount ($)": "مبلغ التسوية ($)",
    "Settlement Date": "تاريخ التسوية",
    "Settlement remarks or transfer notes...": "ملاحظات التسوية أو التحويل...",
    "Share Invite": "مشاركة الدعوة",
    "Share Receipt on WhatsApp": "مشاركة الإيصال على WhatsApp",
    "Share via WhatsApp": "مشاركة عبر WhatsApp",
    "Shareable web catalog & WhatsApp store": "كتالوج ويب قابل للمشاركة ومتجر WhatsApp",
    "Shifts, float & cash balancing": "الورديات والعهدة وموازنة النقد",
    "Short": "قصير",
    "Sign out this device?": "تسجيل الخروج من هذا الجهاز؟",
    "Signed In": "مسجل الدخول",
    "Size / Style": "الحجم / النمط",
    "Smart Inventory Platform, SaaS Billing…": "منصة مخزون ذكية، فوترة سحابية SaaS…",
    "Solution Pillars": "ركائز الحلول",
    "Special Order Instructions": "تعليمات خاصة بالطلب",
    "Special instructions, cashier remarks...": "تعليمات خاصة، ملاحظات الكاشير...",
    "Split Payment Entries": "بنود الدفع المجزأ",
    "Split Payment:": "دفع مجزأ:",
    "Split:": "مجزأ:",
    "Square Stand": "حامل Square",
    "Square Stand Register": "سجل حامل Square",
    "Staff": "الموظفون",
    "Staff User Accounts": "حسابات موظفي المتجر",
    "Staff accounts & access matrix": "حسابات الموظفين ومصفوفة الوصول",
    "Stand:": "حامل:",
    "Standard": "قياسي",
    "Standard Scanner": "ماسح قياسي",
    "Standard Scanner POS": "نقطة بيع بالماسح القياسي",
    "Start Preparing": "بدء التحضير",
    "State": "المحافظة / الولاية",
    "State / Province": "الولاية / المقاطعة",
    "Status": "الحالة",
    "Status:": "الحالة:",
    "Step 1 — Requirements & Permissions": "الخطوة 1 — المتطلبات والأذونات",
    "Step 2 — Environment & Database": "الخطوة 2 — البيئة وقاعدة البيانات",
    "Step 3 — Migrate & Seed": "الخطوة 3 — الترحيل والتهيئة الأولية",
    "Step 4 — Super Admin Account": "الخطوة 4 — حساب المسؤول العام",
    "Step 5 — Finish": "الخطوة 5 — الانتهاء",
    "Sticky Navigation Bar": "شريط تنقل مثبت في الأعلى",
    "Stock": "المخزون",
    "Store Account:": "حساب المتجر:",
    "Store Email": "بريد المتجر الإلكتروني",
    "Store Invoicing & Billing": "فواتير ومستحقات المتجر",
    "Store Languages & Custom Translation Editor": "لغات المتجر ومحرر الترجمة المخصص",
    "Store Operating Mode": "وضع تشغيل المتجر",
    "Store Phone / WhatsApp": "هاتف المتجر / WhatsApp",
    "Store Primary Language": "اللغة الأساسية للمتجر",
    "Store Profile & Branding": "ملف المتجر والهوية البصرية",
    "Store Profile & Location": "ملف المتجر والموقع",
    "Store Subdomain / Slug": "النطاق الفرعي للمتجر / الاسم اللطيف",
    "Store Theme, Branding & POS Layout": "مظهر المتجر، الهوية وتصميم نقطة البيع",
    "Store Website URL": "رابط موقع المتجر الإلكتروني",
    "Street & apt": "الشارع ورقم الشقة",
    "Stripe, PayPal, Mollie, Razorpay": "Stripe، PayPal، Mollie، Razorpay",
    "Subscription & Tax Billing": "الاشتراك والفوترة الضريبية",
    "Subscription Expiration Date": "تاريخ انتهاء الاشتراك",
    "Subtotal": "المجموع الفرعي",
    "Subtotal:": "المجموع الفرعي:",
    "Suffix": "اللاحقة",
    "Super Admin": "المسؤول العام",
    "SuperAdmin Sidebar Menu": "قائمة الشريط الجانبي للمسؤول العام",
    "Supermarket Touch POS": "نقطة بيع لمس للسوبرماركت",
    "Supplier": "المورد",
    "Supplier Name *": "اسم المورد *",
    "Supplier bills & expenses": "فواتير الموردين والمصروفات",
    "Supplier bills & food purchases": "فواتير الموردين ومشتريات الأغذية",
    "Supplier bills & purchase dues": "فواتير الموردين ومستحقات المشتريات",
    "Suppliers & Vendors": "الموردون والبائعون",
    "Support": "الدعم الفني",
    "Support Email": "البريد الإلكتروني للدعم الفني",
    "Support Phone": "هاتف الدعم الفني",
    "Supported Platform Languages": "لغات المنصة المدعومة",
    "Suspended": "معلق",
    "Switch Account": "تبديل الحساب",
    "Switch Table": "تبديل الطاولة",
    "Symbol Placement": "موضع رمز العملة",
    "System Default": "الافتراضي للنظام",
    "System Health & Global Maintenance Mode": "صحة النظام ووضع الصيانة العام",
    "TAX ESTIMATE": "تقدير الضريبة",
    "TLS": "TLS",
    "TLS (Port 587 - Recommended)": "TLS (المنفذ 587 - موصى به)",
    "TXN / Auth #": "رقم المعاملة / التفويض #",
    "Table Name / Number *": "اسم / رقم الطاولة *",
    "Table Order Review": "مراجعة طلب الطاولة",
    "Tables & Floor Plan": "الطاولات ومخطط الصالة",
    "Takeaway": "سفري (استلام)",
    "Target Seat": "المقعد المستهدف",
    "Tax (GST/VAT)": "الضريبة (GST/VAT)",
    "Tax / GST:": "الضريبة / GST:",
    "Tax Amount ($)": "مبلغ الضريبة ($)",
    "Tax Exempt": "معفى من الضريبة",
    "Tax ID": "الرقم الضريبي",
    "Tax ID / Business Reg": "الرقم الضريبي / السجل التجاري",
    "Tax ID / VAT / Document": "الرقم الضريبي / القيمة المضافة / المستند",
    "Tax Rate (%)": "نسبة الضريبة (%)",
    "Tax rates & category hierarchy": "نسب الضرائب وتدرج الفئات",
    "Tax/GSTIN:": "الضريبة/GSTIN:",
    "Taxable": "خاضع للضريبة",
    "Taxable Base": "الوعاء الضريبي",
    "Taxes & Professional": "الضرائب والخدمات المهنية",
    "Taxes & Professional Services": "الضرائب والخدمات المهنية",
    "Tenant Brand Primary": "اللون الأساسي لعلامة المتجر",
    "Tenant app fallback primary": "اللون الأساسي البديل لتطبيق المتجر",
    "Term / Phrase": "المصطلح / العبارة",
    "Terminals & Devices": "الأجهزة ونقاط البيع",
    "Terms and Conditions:": "الشروط والأحكام:",
    "Test SMTP": "اختبار SMTP",
    "Text Direction": "اتجاه النص",
    "Thank you for your business! All sales are final unless otherwise specified in your service contract.": "شكرًا لتعاملكم معنا! جميع المبيعات نهائية ما لم ينص عقد الخدمة على خلاف ذلك.",
    "The bar floats as an overlay above the UI, enabling free drag-and-drop placement anywhere across the viewport without altering page grid layout.": "يطفو الشريط كطبقة علوية فوق الواجهة، مما يتيح السحب والإفلات في أي مكان دون تغيير تخطيط شبكة الصفحة.",
    "The bar snaps rigidly into the screen structure (Left Sidebar, Right Sidebar, Top Header Bar, Bottom Dock Bar) and adjusts page padding accordingly so content never scrolls under or overlaps it.": "يثبت الشريط بإحكام في هيكل الشاشة (شريط جانبي أيسر، شريط جانبي أيمن، ترويسة علوية، شريط سفلي) ويعدل الهوامش لضمان عدم التداخل مع المحتوى.",
    "The remaining balance is payable upon delivery/project completion.": "الرصيد المتبقي مستحق الدفع عند التسليم/اكتمال المشروع.",
    "Thermal receipts & order history": "الإيصالات الحرارية وسجل الطلبات",
    "This email address will appear in the \"From:\" header of all outgoing system emails.": "سيظهر عنوان البريد الإلكتروني هذا في خانة \"من:\" لجميع رسائل النظام الصادرة.",
    "This user has Administrator role and automatically enjoys full bypass access to all modules.": "يمتلك هذا المستخدم دور مسؤول ويتمتع تلقائيًا بالوصول الكامل لجميع الوحدات.",
    "Ticket Status:": "حالة التذكرة:",
    "Ticket is now active in the Kitchen Display System (KDS) queue.": "التذكرة نشطة الآن في طابور شاشة المطبخ (KDS).",
    "Time:": "الوقت:",
    "Toggle Fullscreen Mode": "تبديل وضع ملء الشاشة",
    "Toggle Sticky Navigation": "تبديل شريط التنقل المثبت",
    "Top Header Bar": "شريط الترويسة العلوي",
    "Total": "الإجمالي",
    "Total Active KOTs": "إجمالي تذاكر المطبخ النشطة",
    "Total Amount": "المبلغ الإجمالي",
    "Total Amount Due": "إجمالي المبلغ المستحق",
    "Total Amount Paid:": "إجمالي المبلغ المدفوع:",
    "Total Bill": "إجمالي الفاتورة",
    "Total Due Today": "إجمالي المستحق اليوم",
    "Total Order Amount:": "إجمالي مبلغ الطلب:",
    "Total Outstanding": "إجمالي المتبقي غير المسدد",
    "Total Outstanding Balance": "إجمالي الرصيد المستحق",
    "Total Payable": "إجمالي مستحق الدفع",
    "Total Sales": "إجمالي المبيعات",
    "Total Tables:": "إجمالي الطاولات:",
    "Total:": "الإجمالي:",
    "Touch Department": "قسم اللمس",
    "Touch POS": "نقطة بيع باللمس",
    "Track customer balances, credit sales, partial payments, due dates, and overdue accounts.": "تتبع أرصدة العملاء، المبيعات الآجلة، الدفعات الجزئية، تواريخ الاستحقاق، والحسابات المتأخرة.",
    "Trade / Brand Name": "الاسم التجاري / اسم العلامة",
    "Transaction & Sales": "المعاملات والمبيعات",
    "Transfer Order": "تحويل الطلب",
    "Transfer Table": "تحويل الطاولة",
    "Transfer Table Order": "تحويل طلب الطاولة",
    "Type product name, SKU or barcode scan...": "اكتب اسم المنتج، SKU أو امسح الباركود...",
    "URL Slug *": "الاسم اللطيف للرابط (Slug) *",
    "USD": "دولار أمريكي (USD)",
    "Unassign Customer": "إلغاء تعيين العميل",
    "Unit": "الوحدة",
    "Unit Name": "اسم الوحدة",
    "Unit Name *": "اسم الوحدة *",
    "Unit Price": "سعر الوحدة",
    "Units of Measure": "وحدات القياس",
    "Unlimited": "غير محدود",
    "Unlimited Inventory & Sales History": "مخزون وسجل مبيعات غير محدود",
    "Upcoming (30 Days)": "القادمة (30 يومًا)",
    "Upgrade or renew your plan with instant tax invoice generation": "قم بترقية خطتك أو تجديدها مع إصدار فاتورة ضريبية فورية",
    "Upload Product Photo": "رفع صورة المنتج",
    "Uploading...": "جارٍ الرفع...",
    "Use \"Adjust Stock\" button on the table.": "استخدم زر \"تعديل المخزون\" في الجدول.",
    "User": "المستخدم",
    "User / Terminal": "المستخدم / نقطة البيع",
    "Username": "اسم المستخدم",
    "Utilities (Electricity, Water, Internet)": "الخدمات والمرافق (كهرباء، مياه، إنترنت)",
    "Utilities (Power/Water)": "الخدمات (كهرباء/مياه)",
    "Valid Until:": "صالح حتى:",
    "Validity Expiry Date": "تاريخ انتهاء الصلاحية",
    "Vendor / Supplier": "المورد / البائع",
    "Vendor Name (If not in suppliers)": "اسم المورد (إذا لم يكن في قائمة الموردين)",
    "Vendor contacts & purchasing": "جهات اتصال الموردين والمشتريات",
    "Vendor directory & purchasing": "دليل الموردين والمشتريات",
    "Verify Key & Upgrade": "التحقق من المفتاح والترقية",
    "View": "عرض",
    "View & Download PDF Tax Invoice": "عرض وتنزيل الفاتورة الضريبية PDF",
    "View All": "عرض الكل",
    "View All Sales": "عرض جميع المبيعات",
    "View All Stores": "عرض جميع المتاجر",
    "View Invoices": "عرض الفواتير",
    "View Only": "عرض فقط",
    "View Z-Report": "عرض تقرير Z",
    "View attached bill file": "عرض ملف الفاتورة المرفق",
    "Viewing as": "تصفح بصفتك",
    "Violet Purple": "بنفسجي",
    "Volume, Outlets, Uptime": "الحجم، الفروع، ووقت التشغيل",
    "Walk-in": "عميل عابر",
    "Walk-in Customer": "عميل عابر",
    "Walk-in Member": "عضو عابر",
    "Walk-in Regular Customer": "عميل عادي عابر",
    "Warm Amber": "عنبري دافئ",
    "Weekly Automated Snapshot": "نسخة احتياطية آلية أسبوعية",
    "WhatsApp": "WhatsApp",
    "WhatsApp & Messaging Settings": "إعدادات WhatsApp والمراسلة",
    "WhatsApp Web / Mobile": "WhatsApp ويب / الجوال",
    "With pending dues": "مع مستحقات معلقة",
    "X-Report (live)": "تقرير X (مباشر)",
    "Yearly": "سنويًا",
    "You": "أنت",
    "Your Custom Store Translation": "ترجمة متجرك المخصصة",
    "Your Name (Optional)": "اسمك (اختياري)",
    "Your Name *": "اسمك *",
    "Your Order Cart": "سلة طلبك",
    "Your Phone / WhatsApp Number": "رقم هاتفك / WhatsApp",
    "Your Store Custom Translation *": "الترجمة المخصصة لمتجرك *",
    "Your cart is currently empty.": "سلتك فارغة حاليًا.",
    "Your sale is currently empty. Tap items to add.": "عملية البيع فارغة حاليًا. انقر على العناصر لإضافتها.",
    "Z-Report": "تقرير Z",
    "active invoices": "فواتير نشطة",
    "admin@yourcompany.com": "admin@yourcompany.com",
    "apikey, username@domain.com…": "apikey, username@domain.com…",
    "billing@yourstore.com": "billing@yourstore.com",
    "by": "بواسطة",
    "days": "أيام",
    "discount": "خصم",
    "e.g. 1 for US/CA, 91 for IN, 44 for UK, 62 for ID": "مثل 1 لأمريكا/كندا، 91 للهند، 44 لبريطانيا، 966 للسعودية",
    "e.g. 15 mins, 06:00 PM": "مثل: 15 دقيقة، 06:00 مساءً",
    "e.g. Change fund top-up, petty cash withdrawal": "مثل: تزويد رصيد الفكة، سحب عهدة نثرية",
    "e.g. City Power Corp, Apex Landlord": "مثل: شركة الكهرباء الوطنية، المالك العقاري",
    "e.g. Credit Card, UPI, PIX, Stripe": "مثل: بطاقة ائتمان، مدى، تحويل بنكي، كاش",
    "e.g. Dutch": "مثل: الهولندية",
    "e.g. For returns, keep this receipt within 7 days.": "مثل: للإرجاع يرجى الاحتفاظ بهذا الإيصال خلال 7 أيام.",
    "e.g. Fresh Summer Produce, Special Deals…": "مثل: عروض الصيف الطازجة، خصومات خاصة…",
    "e.g. Michael Scott": "مثل: أحمد محمد",
    "e.g. Monthly Warehouse Rent or Stock Restock Batch #4": "مثل: إيجار المستودع الشهري أو دفعة تجديد المخزون رقم 4",
    "e.g. Nederlands": "مثل: Nederlands",
    "e.g. No onion": "مثل: بدون بصل",
    "e.g. Pay via terminal or contactless": "مثل: الدفع عبر الجهاز أو بدون تلامس",
    "e.g. Política de Devoluciones": "مثل: سياسة الاسترجاع والاستبدال",
    "e.g. Restock, damaged, correction": "مثل: تجديد مخزون، تالف، تصحيح جرد",
    "e.g. Return Policy": "مثل: سياسة الإرجاع",
    "e.g. Return Policy, Print Tax Invoice": "مثل: سياسة الإرجاع، طباعة فاتورة ضريبية",
    "e.g. Return Policy, Special Promo": "مثل: سياسة الإرجاع، عرض خاص",
    "e.g. Rooftop Patio, Bar, Hall": "مثل: التراس العلوي، البار، الصالة الرئيسية",
    "e.g. Sarah Jenkins": "مثل: سارة أحمد",
    "e.g. Scope deliverables, milestone payment terms, project phases...": "مثل: مخرجات النطاق، شروط دفع المراحل، مراحل المشروع...",
    "e.g. TAX-8891, VAT12345": "مثل: TAX-8891, VAT12345",
    "e.g. TXN-998822 or Check #4401": "مثل: TXN-998822 أو شيك رقم 4401",
    "e.g. Table 04, VIP-1, Bar-02": "مثل: طاولة 04، VIP-1، بار-02",
    "e.g. WIRE-884401 or Check #1002": "مثل: WIRE-884401 أو شيك رقم 1002",
    "e.g. card, upi, pix, stripe": "مثل: بطاقة، مدى، كاش، تحويل",
    "e.g. nl, ja, it": "مثل: ar, en, fr",
    "e.g. smtp.mailgun.org, smtp.gmail.com": "مثل: smtp.mailgun.org, smtp.gmail.com",
    "e.g. yourstore.com or https://yourstore.com": "مثل: yourstore.com أو https://yourstore.com",
    "each": "لكل قطعة",
    "https://example.com/favicon.ico": "https://example.com/favicon.ico",
    "https://example.com/logo.png": "https://example.com/logo.png",
    "https://example.com/product-image.jpg": "https://example.com/product-image.jpg",
    "if CNAME isn't supported at your registrar for this name) to": "إذا لم يكن CNAME مدعومًا لدى مسجل النطاق لهذا الاسم) إلى",
    "impersonated": "تم انتحال الشخصية",
    "items": "عناصر",
    "line items": "بنود الفاتورة",
    "m ago": "د مضت",
    "month": "شهر",
    "my-store": "متجري",
    "no-reply@saas.zoomnearby.com, billing@yourdomain.com": "no-reply@saas.zoomnearby.com, billing@yourdomain.com",
    "of": "من",
    "or": "أو",
    "pcs": "قطعة",
    "pcs, kg, box…": "قطعة، كجم، صندوق…",
    "pcs, kg, bx…": "قطعة، كجم، صندوق…",
    "pos.yourdomain.com or mycompany.com": "pos.yourdomain.com أو mycompany.com",
    "postmaster@yourdomain.com": "postmaster@yourdomain.com",
    "pts": "نقطة",
    "quotation(s) selected": "عرض/عروض أسعار محددة",
    "sale(s) total, all methods": "إجمالي المبيعات، بجميع الطرق",
    "sarah@store.com": "sarah@store.com",
    "save this form, then ask your platform admin to finish HTTPS setup for the domain — until that's done it may show a certificate warning.": "احفظ هذا النموذج، ثم اطلب من مسؤول المنصة إكمال إعداد HTTPS للنطاق — حتى يتم ذلك قد يظهر تحذير الشهادة.",
    "seats": "مقاعد",
    "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…": "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…",
    "subtotal": "المجموع الفرعي",
    "tax": "الضريبة",
    "to Sale invoice?": "إلى فاتورة مبيعات؟",
    "total": "الإجمالي",
    "will be logged to Accounts Receivable.": "سيتم تسجيلها في حسابات الذمم المدينة.",
    "with Razorpay": "بواسطة Razorpay",
    "year": "سنة",
    "your-email@example.com": "your-email@example.com"
}

def update_ar():
    with open('lang/ar.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    with open('scratch/to_translate/ar_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
        
    missing_count = 0
    for k in missing:
        if k in ARABIC_TRANSLATIONS:
            existing[k] = ARABIC_TRANSLATIONS[k]
        else:
            print(f"Missing translation for key: {k}")
            missing_count += 1
            
    if missing_count > 0:
        print(f"FAILED: {missing_count} keys missing in ARABIC_TRANSLATIONS")
        return False
        
    with open('lang/ar.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
        f.write('\n')
        
    print(f"Successfully updated lang/ar.json! Total keys: {len(existing)}")
    return True

if __name__ == '__main__':
    update_ar()
