# Indonesian translation dictionary for all missing keys
import json

INDONESIAN_TRANSLATIONS = {
    "+1 555-0199": "+1 555-0199",
    "0% Exempt": "0% Bebas Pajak",
    "1 day": "1 hari",
    "10% Happy Hour": "10% Happy Hour",
    "14-day zero-risk trial evaluation": "Evaluasi uji coba gratis 14 hari tanpa risiko",
    "15% Member VIP": "15% Member VIP",
    "20% Promo Clearance": "20% Cuci Gudang Promo",
    "256-Bit SSL Encrypted Payment": "Pembayaran Terenkripsi SSL 256-Bit",
    "30 days": "30 hari",
    "40% advance milestone required upon quotation acceptance.": "Uang muka 40% diperlukan setelah penerimaan penawaran.",
    "5% Staff Discount": "Diskon Staf 5%",
    "7 days": "7 hari",
    "80mm / 58mm": "80mm / 58mm",
    "Abbreviation": "Singkatan",
    "Accepted": "Diterima",
    "Accepted / Approved": "Diterima / Disetujui",
    "Access Control": "Kontrol Akses",
    "Accounts Payable & Expense Management": "Hutang Usaha & Manajemen Biaya",
    "Accounts Receivable (Customer Credit & Invoices)": "Piutang Usaha (Kredit & Faktur Pelanggan)",
    "Action": "Aksi",
    "Actions": "Tindakan",
    "Activate": "Aktifkan",
    "Activate Free Trial": "Aktifkan Uji Coba Gratis",
    "Activation / License Key *": "Kunci Aktivasi / Lisensi *",
    "Active (Visible in POS)": "Aktif (Terlihat di POS)",
    "Active Account": "Akun Aktif",
    "Active Devices & POS Terminals": "Perangkat & Terminal POS Aktif",
    "Active Store": "Toko Aktif",
    "Active Store Plan": "Paket Toko Aktif",
    "Active Supplier": "Pemasok Aktif",
    "Active subscription plans": "Paket langganan aktif",
    "Add Currency": "Tambah Mata Uang",
    "Add Custom Phrase": "Tambah Frasa Kustom",
    "Add Customer": "Tambah Pelanggan",
    "Add Floor": "Tambah Lantai",
    "Add Floor Area": "Tambah Area Lantai",
    "Add Method": "Tambah Metode",
    "Add Method Split": "Tambah Pemisahan Metode",
    "Add New Category": "Tambah Kategori Baru",
    "Add New Client": "Tambah Klien Baru",
    "Add New Customer": "Tambah Pelanggan Baru",
    "Add New Payment Method": "Tambah Metode Pembayaran Baru",
    "Add New Supplier": "Tambah Pemasok Baru",
    "Add New Unit": "Tambah Satuan Baru",
    "Add Row": "Tambah Baris",
    "Add Split": "Tambah Pemisahan",
    "Add Table": "Tambah Meja",
    "Add Vendor Bill / Expense": "Tambah Tagihan Pemasok / Pengeluaran",
    "Add special instructions, client PO reference, warranty notes or cashier remarks...": "Tambahkan instruksi khusus, referensi PO klien, catatan garansi atau catatan kasir...",
    "Add to Cart": "Tambah ke Keranjang",
    "Add to Order": "Tambah ke Pesanan",
    "Add to Sale +": "Tambah ke Penjualan +",
    "Add, edit, enable or remove custom payment methods for POS checkout": "Tambah, edit, aktifkan, atau hapus metode pembayaran kustom untuk pembayaran POS",
    "Add-ons & Extras": "Tambahan & Ekstra",
    "Additional Custom Authored Content (Optional)": "Konten Khusus Tambahan (Opsional)",
    "Address": "Alamat",
    "Address:": "Alamat:",
    "Adjust": "Sesuaikan",
    "Adjust Points": "Sesuaikan Poin",
    "Adjustment (+/- Qty)": "Penyesuaian (+/- Jml)",
    "Admin Full Name *": "Nama Lengkap Admin *",
    "Admin Login / Username *": "Login / Nama Pengguna Admin *",
    "Admin Login Email *": "Email Login Admin *",
    "Administration & Settings": "Administrasi & Pengaturan",
    "Administrator": "Administrator",
    "All": "Semua",
    "All Categories": "Semua Kategori",
    "All Customers": "Semua Pelanggan",
    "All Floor Areas": "Semua Area Lantai",
    "All Items": "Semua Item",
    "All Kitchen Orders Cleared!": "Semua Pesanan Dapur Selesai!",
    "All Menu": "Semua Menu",
    "All Quotes": "Semua Penawaran",
    "All Statuses": "Semua Status",
    "All Suppliers": "Semua Pemasok",
    "All inventory items are healthy and above minimum threshold.": "Semua item inventaris aman dan di atas batas minimum.",
    "All rates quoted are valid for 15 days from issue date.": "Semua tarif yang dikutip berlaku selama 15 hari dari tanggal penerbitan.",
    "All unpaid bills": "Semua tagihan belum dibayar",
    "All-inclusive for growing businesses": "Lengkap untuk bisnis yang berkembang",
    "Allocated": "Dialokasikan",
    "Amber Gold": "Kuning Emas Amber",
    "Amount": "Jumlah",
    "Amount ($)": "Jumlah ($)",
    "App URL": "URL Aplikasi",
    "Application & Navigation Theme Color": "Warna Tema Aplikasi & Navigasi",
    "Application primary theme color, default POS layout design, logo, and document colors": "Warna tema utama aplikasi, desain tata letak POS default, logo, dan warna dokumen",
    "Apply": "Terapkan",
    "Apply Primary Language": "Terapkan Bahasa Utama",
    "Apply Role Profile Preset:": "Terapkan Preset Profil Peran:",
    "Are you sure you want to delete payment method": "Apakah Anda yakin ingin menghapus metode pembayaran",
    "Are you sure you want to delete the selected quotations?": "Apakah Anda yakin ingin menghapus penawaran yang dipilih?",
    "Are you sure you want to delete this bill?": "Apakah Anda yakin ingin menghapus tagihan ini?",
    "Are you sure you want to delete this quote?": "Apakah Anda yakin ingin menghapus penawaran ini?",
    "Are you sure you want to delete this translation key?": "Apakah Anda yakin ingin menghapus kunci terjemahan ini?",
    "Area Name *": "Nama Area *",
    "Assigned Role": "Peran yang Ditugaskan",
    "Attach Official PDF Document": "Lampirkan Dokumen PDF Resmi",
    "Authorized POS Devices": "Perangkat POS Resmi",
    "Automated Database Backup & Retention Policy": "Pencadangan Basis Data Otomatis & Kebijakan Retensi",
    "Available": "Tersedia",
    "Available Subscription Plans": "Paket Langganan yang Tersedia",
    "Available database dumps stored on disk": "Dump basis data yang tersedia dan disimpan di disk",
    "BACK / CLEAR": "KEMBALI / BERSIHKAN",
    "Back to Quotation Detail": "Kembali ke Detail Penawaran",
    "Back to Quotes": "Kembali ke Penawaran",
    "Back to Sales": "Kembali ke Penjualan",
    "Back to Users & Team": "Kembali ke Pengguna & Tim",
    "Backup Frequency": "Frekuensi Pencadangan",
    "Badge Color": "Warna Lencana",
    "Balance Due": "Sisa Tagihan",
    "Balance Due:": "Sisa Tagihan:",
    "Balance logged to Accounts Receivable": "Saldo dicatat ke Piutang Usaha",
    "Balanced": "Seimbang",
    "Bank & Payment Details (Rich-Text)": "Detail Bank & Pembayaran (Rich-Text)",
    "Bank & Payment Instructions": "Instruksi Bank & Pembayaran",
    "Bank Reference / Wire TXN / Check #": "Referensi Bank / No. Transfer / Cek #",
    "Bar / Lounge": "Bar / Lounge",
    "Barcode": "Kode Batang (Barcode)",
    "Barcode / SKU": "Barcode / SKU",
    "Base Amount ($)": "Jumlah Dasar ($)",
    "Base Currency Code": "Kode Mata Uang Dasar",
    "Base currency code, symbol, decimal precision, and placement used across POS, cart, checkout, and invoices": "Kode mata uang dasar, simbol, presisi desimal, dan penempatan yang digunakan di POS, keranjang, kasir, dan faktur",
    "Best Value": "Nilai Terbaik",
    "Best for: General Retail, Supermarkets, Convenience stores": "Terbaik untuk: Ritel Umum, Supermarket, Minimarket",
    "Best for: Modern tablet/iPad stands, boutique shops, cafes": "Terbaik untuk: Dudukan tablet/iPad modern, butik, kafe",
    "Best for: Touch registers, high-traffic counters, department stores": "Terbaik untuk: Kasir layar sentuh, konter ramai, department store",
    "Bill": "Tagihan",
    "Bill #": "No. Tagihan #",
    "Bill / Invoice Reference #": "No. Referensi Tagihan / Faktur #",
    "Bill Amount": "Jumlah Tagihan",
    "Bill Date": "Tanggal Tagihan",
    "Bill Title / Description": "Judul / Deskripsi Tagihan",
    "Billed": "Ditagih",
    "Bottom CTA Banner": "Banner CTA Bawah",
    "Bottom Dock Bar": "Bilah Dock Bawah",
    "Brand": "Merek",
    "Brand Logo URL / Image Path": "URL Logo Merek / Jalur Gambar",
    "Brand Name *": "Nama Merek *",
    "Brand names & supplier labels": "Nama merek & label pemasok",
    "Brand or company name displayed to recipients.": "Nama merek atau perusahaan yang ditampilkan kepada penerima.",
    "Brands & Manufacturers": "Merek & Produsen",
    "Brands & Modifiers": "Merek & Pengubah",
    "Browser Favicon URL (.ico / .png)": "URL Favicon Browser (.ico / .png)",
    "Business Contact Email": "Email Kontak Bisnis",
    "Business details displayed on POS terminal, receipts, and invoices": "Detail bisnis yang ditampilkan di terminal POS, struk, dan faktur",
    "CVV / CVC *": "CVV / CVC *",
    "Call:": "Telepon:",
    "Cancel KOT": "Batalkan KOT",
    "Cancel Sale & Restock": "Batalkan Penjualan & Kembalikan Stok",
    "Cancel [Esc]": "Batal [Esc]",
    "Cancel this sale and restore stock?": "Batalkan penjualan ini dan pulihkan stok?",
    "Capacity (Seats)": "Kapasitas (Kursi)",
    "Capacity:": "Kapasitas:",
    "Card Number *": "Nomor Kartu *",
    "Cardholder Name *": "Nama Pemegang Kartu *",
    "Cart": "Keranjang",
    "Cart is empty. Tap products to add items.": "Keranjang kosong. Ketuk produk untuk menambahkan item.",
    "Cash In": "Kas Masuk",
    "Cash In / Out": "Kas Masuk / Keluar",
    "Cash Movement Log": "Log Pergerakan Kas",
    "Cash Out": "Kas Keluar",
    "Cash Register (Daily Register Management)": "Mesin Kasir (Manajemen Kasir Harian)",
    "Cash Sales": "Penjualan Tunai",
    "Cash Tendered ($)": "Uang Tunai Diterima ($)",
    "Cash Tendered by Customer ($)": "Uang Tunai Diterima dari Pelanggan ($)",
    "Casier POS": "Kasir POS",
    "Catalog Item...": "Item Katalog...",
    "Catalog Title *": "Judul Katalog *",
    "Category": "Kategori",
    "Category & Title": "Kategori & Judul",
    "Category Name *": "Nama Kategori *",
    "Change": "Kembalian",
    "Change Due": "Kembalian",
    "Change Due to Customer": "Kembalian untuk Pelanggan",
    "Changes apply immediately upon saving.": "Perubahan langsung berlaku setelah disimpan.",
    "Charge": "Bayar",
    "Choose Option": "Pilih Opsi",
    "Choose a primary header & table theme color for Quotations and PDF Receipts": "Pilih warna tema header & tabel utama untuk Penawaran dan Struk PDF",
    "Choose between General Retail POS vs Food & Restaurant Mode with strict UI & route isolation": "Pilih antara POS Ritel Umum vs Mode Makanan & Restoran dengan isolasi antarmuka dan rute yang ketat",
    "Choose dispatch channel, configure message body, and toggle PDF attachment": "Pilih saluran pengiriman, konfigurasikan isi pesan, dan aktifkan lampiran PDF",
    "Choose the default interface style for your Point of Sale counter": "Pilih gaya antarmuka default untuk konter Point of Sale Anda",
    "Choose your preferred register design before entering the Point of Sale terminal": "Pilih desain kasir yang Anda sukai sebelum masuk ke terminal Point of Sale",
    "City": "Kota",
    "City / Location": "Kota / Lokasi",
    "Clean photo tiles, top category tabs, discounts bar & quick-charge pill.": "Ubin foto bersih, tab kategori atas, bilah diskon & tombol bayar cepat.",
    "Clean photo-first tiles, Favorites / Library / Keypad tabs, discount presets & quick blue \"Charge\" pill.": "Ubin berbasis foto, tab Favorit / Galeri / Keypad, preset diskon & tombol biru \"Bayar\" cepat.",
    "Clear All": "Bersihkan Semua",
    "Clear Cart": "Kosongkan Keranjang",
    "Clear Filter": "Hapus Filter",
    "Clear all items in this order?": "Hapus semua item dalam pesanan ini?",
    "Click any menu card on the left to add food.": "Klik kartu menu mana saja di sebelah kiri untuk menambahkan makanan.",
    "Click any table to immediately open POS and take order": "Klik meja mana saja untuk langsung membuka POS dan mengambil pesanan",
    "Click on any product to add it.": "Klik pada produk apa saja untuk menambahkannya.",
    "Click to Insert Smart Placeholders:": "Klik untuk Menyisipkan Placeholder Cerdas:",
    "Clicking proceed will securely launch the Razorpay checkout dialog supporting Cards, UPI, Netbanking, Google Pay, Apple Pay & Wallets.": "Mengklik lanjutkan akan membuka dialog pembayaran Razorpay dengan aman yang mendukung Kartu, UPI, Netbanking, Google Pay, Apple Pay & Dompet Digital.",
    "Client": "Klien",
    "Client Name *": "Nama Klien *",
    "Client:": "Klien:",
    "Close": "Tutup",
    "Close Register": "Tutup Kasir",
    "Close Register & Generate Z-Report": "Tutup Kasir & Buat Laporan Z",
    "Closed": "Ditutup",
    "Closed By": "Ditutup Oleh",
    "Closing Notes": "Catatan Penutupan",
    "Closing Notes (Optional)": "Catatan Penutupan (Opsional)",
    "Cobalt Blue": "Biru Kobalt",
    "Code": "Kode",
    "Code / Key (Optional)": "Kode / Kunci (Opsional)",
    "Code / SKU": "Kode / SKU",
    "Code:": "Kode:",
    "Collect Pay": "Terima Pembayaran",
    "Collected This Month": "Terkumpul Bulan Ini",
    "Collection Amount ($)": "Jumlah Pembayaran ($)",
    "Company / Store Name *": "Nama Perusahaan / Toko *",
    "Company mission card": "Kartu misi perusahaan",
    "Complete & Print Receipt": "Selesaikan & Cetak Struk",
    "Complete Checkout": "Selesaikan Pembayaran",
    "Configure fine-grained read, write, edit, delete, and export permissions per module.": "Konfigurasikan izin baca, tulis, edit, hapus, dan ekspor terperinci per modul.",
    "Configure global checkout processors for tenant subscription billing and renewals": "Konfigurasikan pemroses pembayaran global untuk penagihan langganan dan perpanjangan penyewa",
    "Configure outbound email delivery for sending invoices, quotations, and staff invitations": "Konfigurasikan pengiriman email keluar untuk mengirim faktur, penawaran, dan undangan staf",
    "Configure schedule frequency and retention lifecycle for database snapshots": "Konfigurasikan frekuensi jadwal dan siklus retensi untuk snapshot basis data",
    "Confirm & Complete Sale": "Konfirmasi & Selesaikan Penjualan",
    "Confirm Collection Receipt": "Konfirmasi Tanda Terima Pembayaran",
    "Confirm Password": "Konfirmasi Kata Sandi",
    "Confirm Settlement Payment": "Konfirmasi Pembayaran Pelunasan",
    "Connecting Gateway...": "Menghubungkan Gateway...",
    "Contact": "Kontak",
    "Contact Phone": "Telepon Kontak",
    "Control Center": "Pusat Kontrol",
    "Convert": "Konversi",
    "Convert quote #": "Konversi penawaran #",
    "Convert this quotation to an active Sale invoice and deduct inventory stock?": "Konversi penawaran ini ke faktur Penjualan aktif dan kurangi stok inventaris?",
    "Convert to Sale": "Konversi ke Penjualan",
    "Converted": "Dikonversi",
    "Cost Price ($) *": "Harga Pokok ($) *",
    "Counted": "Dihitung",
    "Counted Cash": "Uang Fisik Dihitung",
    "Counted Cash in Drawer ($)": "Uang Tunai di Laci Kasir ($)",
    "Counter Checkout": "Pembayaran di Konter",
    "Country (2-letter ISO)": "Negara (ISO 2 huruf)",
    "Country (ISO 2-letter) *": "Negara (ISO 2 huruf) *",
    "Create & Generate Invite": "Buat & Buat Undangan",
    "Create New Subscription Plan": "Buat Paket Langganan Baru",
    "Create Quotation": "Buat Penawaran",
    "Create Vendor Bill / Expense": "Buat Tagihan Pemasok / Pengeluaran",
    "Create a public shareable digital menu or product showcase link": "Buat tautan menu digital atau etalase produk publik yang dapat dibagikan",
    "Create and initialize an isolated tenant store environment with initial admin account": "Buat dan inisialisasi lingkungan toko penyewa terisolasi dengan akun admin awal",
    "Create formal quotations and convert them to sales in 1-click": "Buat penawaran formal dan konversi menjadi penjualan dalam 1 klik",
    "Created": "Dibuat",
    "Credit / Receivable Sale:": "Penjualan Kredit / Piutang:",
    "Credit Invoices Ledger": "Buku Besar Faktur Kredit",
    "Crimson Red": "Merah Merona (Crimson)",
    "Currency & Price Formatting": "Format Mata Uang & Harga",
    "Currency Symbol": "Simbol Mata Uang",
    "Current / Opening Stock *": "Stok Saat Ini / Stok Awal *",
    "Current Due": "Jatuh Tempo Saat Ini",
    "Current Plan": "Paket Saat Ini",
    "Current Store Plan": "Paket Toko Saat Ini",
    "Current sale": "Penjualan saat ini",
    "Cust:": "Pelanggan:",
    "Custom Charge Amount": "Jumlah Biaya Kustom",
    "Custom Domain Configuration": "Konfigurasi Domain Kustom",
    "Custom Hero Banner Image URL (Optional)": "URL Gambar Spanduk Hero Kustom (Opsional)",
    "Custom WhatsApp Footer Note": "Catatan Footer WhatsApp Kustom",
    "Customer & Rewards": "Pelanggan & Hadiah",
    "Customer / Member": "Pelanggan / Member",
    "Customer Directory Balances": "Saldo Direktori Pelanggan",
    "Customer Full Name *": "Nama Lengkap Pelanggan *",
    "Customer Name *": "Nama Pelanggan *",
    "Customer Phone": "Telepon Pelanggan",
    "Customer Testimonials": "Testimoni Pelanggan",
    "Customer credit & pending payments": "Kredit pelanggan & pembayaran tertunda",
    "Customer credit & unpaid bills": "Kredit pelanggan & tagihan belum dibayar",
    "Customer directory & loyalty points": "Direktori pelanggan & poin loyalitas",
    "Customer history & contact list": "Riwayat pelanggan & daftar kontak",
    "Customer name": "Nama pelanggan",
    "Customer:": "Pelanggan:",
    "Customers & CRM": "Pelanggan & CRM",
    "Customizable Text Message Body": "Isi Pesan Teks yang Dapat Disesuaikan",
    "Customize Phrases for Language:": "Sesuaikan Frasa untuk Bahasa:",
    "Customize phrases, POS terms, receipt titles, and tax invoice wording specifically for your store": "Sesuaikan frasa, istilah POS, judul struk, dan susunan kata faktur pajak khusus untuk toko Anda",
    "Customized": "Disesuaikan",
    "DISCOUNT": "DISKON",
    "DISPATCHED": "DIKIRIM",
    "Daily Automated Snapshot": "Pencadangan Otomatis Harian",
    "Dashboard": "Dasbor",
    "Database Driver": "Driver Basis Data",
    "Database Name": "Nama Basis Data",
    "Date:": "Tanggal:",
    "Days": "Hari",
    "Debtor Customers": "Pelanggan Debitur",
    "Decimal Places": "Tempat Desimal",
    "Default": "Default",
    "Default Country Calling Code": "Kode Panggilan Negara Default",
    "Default English Translation": "Terjemahan Bahasa Inggris Default",
    "Default POS Register Layout Design": "Desain Tata Letak Kasir POS Default",
    "Default general walk-in sale": "Penjualan umum pelanggan langsung default",
    "Default language for customer receipts, table QR orders, and staff POS terminals": "Bahasa default untuk struk pelanggan, pesanan QR meja, dan terminal POS staf",
    "Default settings for 1-click WhatsApp receipts to customers": "Pengaturan default untuk kirim struk WhatsApp 1-klik ke pelanggan",
    "Default terms and notes auto-loaded into new Quotations": "Syarat dan ketentuan default yang dimuat otomatis ke dalam Penawaran baru",
    "Delete Bill": "Hapus Tagihan",
    "Delete Selected": "Hapus yang Dipilih",
    "Delete this brand?": "Hapus merek ini?",
    "Delete this category?": "Hapus kategori ini?",
    "Delete this customer?": "Hapus pelanggan ini?",
    "Delete this product?": "Hapus produk ini?",
    "Delete this snapshot?": "Hapus snapshot ini?",
    "Delete this supplier?": "Hapus pemasok ini?",
    "Delete this unit?": "Hapus satuan ini?",
    "Delete translation key": "Hapus kunci terjemahan",
    "Delivery": "Pengantaran (Delivery)",
    "Delivery Address": "Alamat Pengiriman",
    "Delivery Address / Order Notes": "Alamat Pengiriman / Catatan Pesanan",
    "Departments & tax rates": "Departemen & tarif pajak",
    "Description": "Deskripsi",
    "Description (Optional)": "Deskripsi (Opsional)",
    "Description (optional)": "Deskripsi (opsional)",
    "Destination:": "Tujuan:",
    "Didn't receive code? Resend Code": "Tidak menerima kode? Kirim Ulang Kode",
    "Difference": "Selisih",
    "Digital QR menu & WhatsApp store": "Menu QR digital & toko WhatsApp",
    "Digital catalog & WhatsApp share": "Katalog digital & berbagi WhatsApp",
    "Dine-In": "Makan di Tempat (Dine-In)",
    "Dine-In, Takeaway & Delivery": "Makan di Tempat, Bawa Pulang & Pengantaran",
    "Dining History": "Riwayat Makan",
    "Direct Invitation Link": "Tautan Undangan Langsung",
    "Direct Proposal / Walk-in Client": "Proposal Langsung / Klien Walk-in",
    "Disable": "Nonaktifkan",
    "Disabled": "Dinonaktifkan",
    "Disabled — sends clean structured text email only.": "Dinonaktifkan — hanya mengirim email teks terstruktur bersih.",
    "Discount ($)": "Diskon ($)",
    "Discount:": "Diskon:",
    "Discounts": "Diskon",
    "Dishes, ingredients & pricing": "Hidangan, bahan & penetapan harga",
    "Dispatch & Share Invoice:": "Kirim & Bagikan Faktur:",
    "Dispatching...": "Mengirim...",
    "Displayed in browser tabs for your tenant store": "Ditampilkan di tab browser untuk toko Anda",
    "Displayed in sidebar, PDF invoices, and online catalog header": "Ditampilkan di bilah samping, faktur PDF, dan tajuk katalog online",
    "Docking Behavior": "Perilaku Docking",
    "Docking Screen Position": "Posisi Layar Docking",
    "Document / Tax ID": "Dokumen / NPWP",
    "Download & Print PDF Invoice": "Unduh & Cetak Faktur PDF",
    "Download / Stream PDF": "Unduh / Lihat PDF",
    "Draft": "Draf",
    "Draft Proposal": "Draf Proposal",
    "Driver / Courier": "Pengemudi / Kurir",
    "Driver name": "Nama pengemudi",
    "Due Date": "Jatuh Tempo",
    "Due Date:": "Tanggal Jatuh Tempo:",
    "EMV & NFC": "EMV & NFC",
    "EUR": "EUR",
    "Edit": "Edit",
    "Edit Bill": "Edit Tagihan",
    "Edit Category": "Edit Kategori",
    "Edit Customer": "Edit Pelanggan",
    "Edit Floor Area": "Edit Area Lantai",
    "Edit Payment Method": "Edit Metode Pembayaran",
    "Edit Plan": "Edit Paket",
    "Edit Product": "Edit Produk",
    "Edit Quotation": "Edit Penawaran",
    "Edit Supplier": "Edit Pemasok",
    "Edit Table": "Edit Meja",
    "Edit Unit": "Edit Satuan",
    "Edit Vendor Bill / Expense": "Edit Tagihan Pemasok / Pengeluaran",
    "Email": "Email",
    "Email & WhatsApp Invoice Sharing": "Berbagi Faktur melalui Email & WhatsApp",
    "Email Address *": "Alamat Email *",
    "Email Dispatch (SMTP)": "Pengiriman Email (SMTP)",
    "Email From Name (Sender Name) *": "Nama Pengirim Email *",
    "Email Invoice": "Kirim Faktur via Email",
    "Email Invoice Receipt": "Kirim Struk Faktur via Email",
    "Email Us": "Kirim Email kepada Kami",
    "Email:": "Email:",
    "Emerald Green": "Hijau Zamrud",
    "Emerald Mint": "Mint Zamrud",
    "Enable": "Aktifkan",
    "Enable this payment method for POS checkout": "Aktifkan metode pembayaran ini untuk pembayaran POS",
    "Enable, disable or add new multilingual languages to the system": "Aktifkan, nonaktifkan, atau tambahkan bahasa multibahasa baru ke sistem",
    "Encryption": "Enkripsi",
    "Encryption Protocol *": "Protokol Enkripsi *",
    "English Name *": "Nama Bahasa Inggris *",
    "Enter a pre-purchased platform license key to activate this plan without card payment.": "Masukkan kunci lisensi platform yang telah dibeli sebelumnya untuk mengaktifkan paket ini tanpa pembayaran kartu.",
    "Enter bank accounts & payment instructions...": "Masukkan rekening bank & instruksi pembayaran...",
    "Enter default quotation policy, deliverables & terms...": "Masukkan kebijakan penawaran default, hasil kerja & ketentuan...",
    "Enter invoice policy & terms...": "Masukkan kebijakan & ketentuan faktur...",
    "Enter password": "Masukkan kata sandi",
    "Enter your offline activation code or subscription license key to renew or upgrade your store.": "Masukkan kode aktivasi offline atau kunci lisensi langganan Anda untuk memperbarui atau meningkatkan toko Anda.",
    "Euro": "Euro",
    "Exchange rates against your base currency, for reporting and multi-currency displays": "Nilai tukar terhadap mata uang dasar Anda, untuk pelaporan dan tampilan multi-mata uang",
    "Exit": "Keluar",
    "Exit Fullscreen": "Keluar dari Layar Penuh",
    "Expected": "Diharapkan",
    "Expected Cash": "Kas yang Diharapkan",
    "Expected Cash (System)": "Kas yang Diharapkan (Sistem)",
    "Expected Cash in Drawer": "Kas yang Diharapkan di Laci",
    "Expense Category": "Kategori Pengeluaran",
    "Expires": "Kadaluarsa",
    "Expires:": "Kadaluarsa Pada:",
    "Expiry Date": "Tanggal Kadaluarsa",
    "Expiry Date (MM/YY) *": "Tanggal Kadaluarsa (BB/TT) *",
    "Fail": "Gagal",
    "Fast barcode scan & cash checkout": "Pemindaian barcode cepat & pembayaran tunai",
    "Fast barcode scanning, 3-column product cards, category chips & right-side cart drawer.": "Pemindaian barcode cepat, kartu produk 3 kolom, tab kategori & laci keranjang kanan.",
    "Favicon URL": "URL Favicon",
    "Favorites": "Favorit",
    "Feature Modules Suite": "Rangkaian Modul Fitur",
    "Filter by Tenant / Company ID…": "Filter berdasarkan ID Toko / Perusahaan…",
    "Filter by event action (e.g. smtp.updated)…": "Filter berdasarkan aksi (mis. smtp.updated)…",
    "Financial & Currency": "Keuangan & Mata Uang",
    "Financial Management": "Manajemen Keuangan",
    "Fixed ($)": "Tetap ($)",
    "Fixed Docked": "Ditempelkan Tetap",
    "Flag Emoji": "Emoji Bendera",
    "Floating / Free Drag": "Mengambang / Seret Bebas",
    "Floor": "Lantai",
    "Floor Area": "Area Lantai",
    "Floor plan is active. Take Dine-In orders, manage tables, monitor live kitchen tickets, and handle takeaway or deliveries.": "Denah lantai aktif. Terima pesanan Makan di Tempat, kelola meja, pantau tiket dapur langsung, dan tangani bawa pulang atau pengiriman.",
    "Food & Restaurant": "Makanan & Restoran",
    "Food & Restaurant Mode": "Mode Makanan & Restoran",
    "Food & Restaurant Mode Active": "Mode Makanan & Restoran Aktif",
    "Food & Restaurant POS": "POS Makanan & Restoran",
    "Food Item": "Item Makanan",
    "Food Items:": "Item Makanan:",
    "Food Menu": "Menu Makanan",
    "Food Suppliers": "Pemasok Makanan",
    "For restaurants, cafes, bars & food trucks. Includes floor plans & live tables, KOT tickets, Kitchen Display (KDS), Dine-In/Takeaway routing, and QR table ordering.": "Untuk restoran, kafe, bar & food truck. Termasuk denah lantai & meja langsung, tiket KOT, Kitchen Display (KDS), pesanan Makan di Tempat/Bawa Pulang, dan pesanan QR meja.",
    "For supermarkets, clothing, electronics & retail shops. Includes barcode scanning, cash register, quotations, invoices, and standard stock management.": "Untuk supermarket, pakaian, elektronik & toko ritel. Termasuk pemindaian barcode, mesin kasir, penawaran harga, faktur, dan manajemen stok standar.",
    "Forest Green": "Hijau Hutan",
    "Free Evaluation": "Evaluasi Gratis",
    "Free Floating": "Mengambang Bebas",
    "Full Access": "Akses Penuh",
    "Full Name *": "Nama Lengkap *",
    "Full Name as on Card": "Nama Lengkap sesuai pada Kartu",
    "Fullscreen": "Layar Penuh",
    "Fully Settled": "Lunas Sepenuhnya",
    "Fully Settled (Paid)": "Lunas Sepenuhnya (Dibayar)",
    "Function toolbar, vibrant department tiles & right receipt checkout slip.": "Bilah alat fungsi, ubin departemen berwarna cerah & struk kasir di sebelah kanan.",
    "GRAND TOTAL": "TOTAL KESELURUHAN",
    "General": "Umum",
    "General Retail": "Ritel Umum",
    "General Retail POS (Default)": "POS Ritel Umum (Default)",
    "Generate Code": "Buat Kode",
    "Generate Key": "Buat Kunci",
    "Generate Offline License Voucher": "Buat Voucher Lisensi Offline",
    "Generate and manage offline license vouchers for instant self-registration and renewals": "Buat dan kelola voucher lisensi offline untuk pendaftaran mandiri dan perpanjangan instan",
    "Generates and attaches clean stylized invoice PDF.": "Membuat dan melampirkan PDF faktur bergaya rapi.",
    "Generates and attaches clean stylized proposal PDF.": "Membuat dan melampirkan PDF proposal bergaya rapi.",
    "Global Audit Trail & Security Logs": "Jejak Audit Global & Log Keamanan",
    "Global Platform SMTP Email Configuration": "Konfigurasi Email SMTP Platform Global",
    "Global Tax Reference Matrix": "Matriks Referensi Pajak Global",
    "Grand Total:": "Total Keseluruhan:",
    "Guest Directory": "Direktori Tamu",
    "Guest name": "Nama tamu",
    "Guests": "Tamu",
    "HSN / SAC codes & VAT presets": "Kode HSN / SAC & preset PPN",
    "Hardware Trust Bar": "Bilah Perangkat Keras Tepercaya",
    "Hero Top Badge Text": "Teks Lencana Atas Hero",
    "Hero Value Proposition Subtitle": "Subjudul Proposisi Nilai Hero",
    "History": "Riwayat",
    "History, print receipts & refunds": "Riwayat, cetak struk & pengembalian dana",
    "Host": "Host",
    "INV-": "INV-",
    "IP Address": "Alamat IP",
    "If you need access to this section, please request permission from your store": "Jika Anda memerlukan akses ke bagian ini, silakan minta izin dari toko Anda",
    "Immediate": "Segera",
    "Immediate settlement": "Penyelesaian langsung",
    "Immutable event record of administrative actions, config mutations, and security events": "Catatan peristiwa yang tidak dapat diubah dari tindakan administratif, mutasi konfigurasi, dan peristiwa keamanan",
    "Import all missing keys from English template": "Impor semua kunci yang hilang dari template Bahasa Inggris",
    "In Cooking": "Sedang Dimasak",
    "Includes: Retail Counter • Barcode POS • Quotes": "Termasuk: Kasir Ritel • POS Barcode • Penawaran",
    "Includes: Tables • KOT • Kitchen KDS • QR Menus": "Termasuk: Meja • KOT • Dapur KDS • Menu QR",
    "Initial Status": "Status Awal",
    "Initial Subscription Plan": "Paket Langganan Awal",
    "Inquiry Contact Form": "Formulir Kontak Pertanyaan",
    "Installation complete. The installer is now locked.": "Instalasi selesai. Penginstal sekarang dikunci.",
    "Instant Tax Receipt Generated": "Struk Pajak Instan Dihasilkan",
    "Internal Notes": "Catatan Internal",
    "Inv:": "Faktur:",
    "Inventory / Goods": "Inventaris / Barang",
    "Inventory / Raw Materials": "Inventaris / Bahan Baku",
    "Invite New Team Member": "Undang Anggota Tim Baru",
    "Invite User": "Undang Pengguna",
    "Invoice #": "No. Faktur #",
    "Invoice / Receipt Attachment (PDF, Image)": "Lampiran Faktur / Struk (PDF, Gambar)",
    "Invoice Prefix": "Prefiks Faktur",
    "Invoice Terms & Conditions (Rich-Text)": "Syarat & Ketentuan Faktur (Rich-Text)",
    "Invoice Terms & Policy": "Syarat & Kebijakan Faktur",
    "Invoice prefixes, default quotation terms, and payment instructions": "Prefiks faktur, syarat penawaran default, dan instruksi pembayaran",
    "Item": "Item",
    "Item & Description": "Item & Deskripsi",
    "Item & Scope Description": "Item & Deskripsi Ruang Lingkup",
    "Item Code": "Kode Item",
    "Item or service name *": "Nama item atau layanan *",
    "Itemized GST/VAT Tax Invoices": "Faktur Pajak PPN Terperinci",
    "Itemized tax receipts for store subscriptions, license activations, and renewals": "Kwitansi pajak terperinci untuk langganan toko, aktivasi lisensi, dan perpanjangan",
    "Jurisdiction standards, default VAT rates, and GST/HSN classification guidelines": "Standar yurisdiksi, tarif PPN default, dan panduan klasifikasi GST/HSN",
    "Keep Order On Screen": "Pertahankan Pesanan di Layar",
    "Keep the navigation bar pinned in view while scrolling through long views and forms": "Pertahankan bilah navigasi tetap tersemat dalam tampilan saat menggulir tampilan dan formulir yang panjang",
    "Key Name (Exact String) *": "Nama Kunci (String Tepat) *",
    "Keypad": "Keypad",
    "Keypad Entry": "Input Keypad",
    "Kitchen Display System": "Sistem Tampilan Dapur (KDS)",
    "Kitchen Display System (KDS)": "Sistem Tampilan Dapur (KDS)",
    "Kitchen KDS": "Dapur KDS",
    "Kitchen Menu & Catalog": "Menu & Katalog Dapur",
    "Kitchen Note": "Catatan Dapur",
    "Kitchen Note (Optional)": "Catatan Dapur (Opsional)",
    "Landing Neon Lime Accent": "Aksen Lime Neon Halaman Depan",
    "Landing Page Sections Controller": "Pengontrol Bagian Halaman Depan",
    "Landing Primary Emerald": "Emerald Utama Halaman Depan",
    "Language Code (ISO) *": "Kode Bahasa (ISO) *",
    "Language:": "Bahasa:",
    "Launch Selected POS Register": "Buka Kasir POS yang Dipilih",
    "Layout": "Tata Letak",
    "Layout Direction:": "Arah Tata Letak:",
    "Lead capture form": "Formulir penangkapan prospek",
    "Left Sidebar": "Bilah Sisi Kiri",
    "Left vertical function menu, vibrant department tiles, paginated grid & thermal receipt checkout slip.": "Menu fungsi vertikal kiri, ubin departemen cerah, kisi berpaginasi & struk kasir termal.",
    "Left-to-Right (LTR)": "Kiri-ke-Kanan (LTR)",
    "Legal": "Legal",
    "Legal / Company Name": "Nama Legal / Perusahaan",
    "Library": "Galeri / Pustaka",
    "License Voucher": "Voucher Lisensi",
    "Line Items & Scope Specifications": "Item Baris & Spesifikasi Ruang Lingkup",
    "Link Expiration": "Kedaluwarsa Tautan",
    "Linked Supplier (Optional)": "Pemasok Tertaut (Opsional)",
    "Live": "Langsung (Live)",
    "Live KDS": "KDS Langsung",
    "Live KOT preparation queue": "Antrean persiapan KOT langsung",
    "Live Kitchen Tickets": "Tiket Dapur Langsung",
    "Live Metric Counters": "Penghitung Metrik Langsung",
    "Live POS": "POS Langsung",
    "Live Status:": "Status Langsung:",
    "Live Table Status & QR Menus": "Status Meja Langsung & Menu QR",
    "Location": "Lokasi",
    "Logistics & Freight": "Logistik & Pengangkutan",
    "Logistics, Freight & Delivery": "Logistik, Pengangkutan & Pengiriman",
    "Low Stock Warnings": "Peringatan Stok Rendah",
    "Loyalty Points": "Poin Loyalitas",
    "Main Headline Title *": "Judul Utama *",
    "Maintenance & Repairs": "Pemeliharaan & Perbaikan",
    "Maintenance Lockout Message": "Pesan Penguncian Pemeliharaan",
    "Manage": "Kelola",
    "Manage Floor Plan": "Kelola Denah Lantai",
    "Manage manufacturers and brands": "Kelola produsen dan merek",
    "Manage seating floor areas, table occupancy statuses, and QR code digital menus": "Kelola area lantai tempat duduk, status okupansi meja, dan menu digital kode QR",
    "Manage signed-in sessions across browsers and POS registers": "Kelola sesi masuk di seluruh browser dan kasir POS",
    "Manage supported platform languages, customize JSON translation files, and synchronize multilingual dictionaries": "Kelola bahasa platform yang didukung, sesuaikan file terjemahan JSON, dan sinkronkan kamus multibahasa",
    "Manage units of measure for inventory and billing": "Kelola satuan ukuran untuk inventaris dan penagihan",
    "Manage vendor bills, operational expenses, utility costs, supplier settlements, and payment proofs.": "Kelola tagihan pemasok, biaya operasional, biaya utilitas, penyelesaian pemasok, dan bukti pembayaran.",
    "Manage your store subscription plan, redeem activation keys, and access compliant tax invoices": "Kelola paket langganan toko Anda, tukarkan kunci aktivasi, dan akses faktur pajak",
    "Manual movements this shift": "Pergerakan manual shift ini",
    "Mark as Ready": "Tandai Siap",
    "Mark as Served": "Tandai Disajikan",
    "Marketing & Ads": "Pemasaran & Iklan",
    "Marketing & Promotions": "Pemasaran & Promosi",
    "Max POS Devices Limit": "Batas Maks Perangkat POS",
    "Max Users Limit": "Batas Maks Pengguna",
    "Measurement Units": "Satuan Ukuran",
    "Member:": "Member:",
    "Membership": "Keanggotaan",
    "Menu": "Menu",
    "Menu Dishes & Stock": "Hidangan Menu & Stok",
    "Menu sections & tax rates": "Bagian menu & tarif pajak",
    "Method": "Metode",
    "Method Name": "Nama Metode",
    "Method Name *": "Nama Metode *",
    "Method:": "Metode:",
    "Midnight Slate": "Batu Tulis Tengah Malam (Midnight Slate)",
    "Migration failed. Check the output above and try again.": "Migrasi gagal. Periksa keluaran di atas dan coba lagi.",
    "Minimum Alert Stock *": "Stok Peringatan Minimum *",
    "Minimum Client Build Version": "Versi Build Klien Minimum",
    "Module": "Modul",
    "Monthly": "Bulanan",
    "Monthly Snapshot": "Pencadangan Bulanan",
    "Multi-Language & Translation File Editor": "Editor File Terjemahan & Multibahasa",
    "N/A": "T/A",
    "Name": "Nama",
    "Name *": "Nama *",
    "Native Name": "Nama Asli (Bahasa Asli)",
    "Never": "Tidak Pernah",
    "Never (Lifetime)": "Tidak Pernah (Seumur Hidup)",
    "Never (Permanent link)": "Tidak Pernah (Tautan Permanen)",
    "New": "Baru",
    "New Brand": "Merek Baru",
    "New Category": "Kategori Baru",
    "New Customer": "Pelanggan Baru",
    "New POS Credit Sale": "Penjualan Kredit POS Baru",
    "New Product": "Produk Baru",
    "New Quotation": "Penawaran Baru",
    "New Sale": "Penjualan Baru",
    "New Supplier": "Pemasok Baru",
    "New Unit": "Satuan Baru",
    "New orders from Dine-In tables, Takeaway, Delivery, or QR Digital Menu will appear here in real-time.": "Pesanan baru dari meja Makan di Tempat, Bawa Pulang, Pengantaran, atau Menu Digital QR akan muncul di sini secara real-time.",
    "No Cash Register Open": "Tidak Ada Mesin Kasir yang Terbuka",
    "No Floor Assigned": "Tidak Ada Lantai yang Ditugaskan",
    "No Image": "Tidak Ada Gambar",
    "No Plan (Unlimited / Manual)": "Tanpa Paket (Tidak Terbatas / Manual)",
    "No accounts receivable records match current filters.": "Tidak ada catatan piutang yang cocok dengan filter saat ini.",
    "No activation codes generated yet. Click \"+ Generate Key\" above.": "Belum ada kode aktivasi yang dibuat. Klik \"+ Buat Kunci\" di atas.",
    "No active products available.": "Tidak ada produk aktif yang tersedia.",
    "No active sessions found.": "Tidak ada sesi aktif yang ditemukan.",
    "No brands yet. Click \"+ New Brand\" to add one.": "Belum ada merek. Klik \"+ Merek Baru\" untuk menambahkannya.",
    "No cash movements recorded yet.": "Belum ada pergerakan kas yang dicatat.",
    "No catalogs published yet.": "Belum ada katalog yang diterbitkan.",
    "No categories yet. Click \"+ New Category\" to create one.": "Belum ada kategori. Klik \"+ Kategori Baru\" untuk membuatnya.",
    "No closed registers yet.": "Belum ada kasir yang ditutup.",
    "No contact details": "Tidak ada detail kontak",
    "No customer records found.": "Tidak ada data pelanggan yang ditemukan.",
    "No customers found matching": "Tidak ada pelanggan yang cocok ditemukan",
    "No customers registered yet.": "Belum ada pelanggan yang terdaftar.",
    "No dining floor areas created yet.": "Belum ada area lantai makan yang dibuat.",
    "No food items found. Use \"+ Add Product\" in Products menu to create items.": "Tidak ada item makanan yang ditemukan. Gunakan \"+ Tambah Produk\" di menu Produk untuk membuat item.",
    "No items added to receipt yet.": "Belum ada item yang ditambahkan ke struk.",
    "No items found matching your search.": "Tidak ada item yang cocok dengan pencarian Anda.",
    "No items selected for this order.": "Tidak ada item yang dipilih untuk pesanan ini.",
    "No other currencies configured.": "Tidak ada mata uang lain yang dikonfigurasi.",
    "No payment methods configured. Click \"+ Add Method\" to create one.": "Belum ada metode pembayaran yang dikonfigurasi. Klik \"+ Tambah Metode\" untuk membuatnya.",
    "No products available in catalog.": "Tidak ada produk yang tersedia di katalog.",
    "No products available in this department.": "Tidak ada produk yang tersedia di departemen ini.",
    "No products in catalog yet.": "Belum ada produk di katalog.",
    "No products yet. Click \"+ New Product\" to add items.": "Belum ada produk. Klik \"+ Produk Baru\" untuk menambahkan item.",
    "No quotations found matching the filter criteria.": "Tidak ada penawaran yang cocok dengan kriteria filter.",
    "No recent kitchen tickets.": "Tidak ada tiket dapur terbaru.",
    "No recent sales records found.": "Tidak ada catatan penjualan terbaru yang ditemukan.",
    "No sales found.": "Tidak ada penjualan yang ditemukan.",
    "No sales recorded yet this shift.": "Belum ada penjualan yang dicatat pada shift ini.",
    "No sales recorded.": "Tidak ada penjualan yang dicatat.",
    "No subscription tax invoices generated yet.": "Belum ada faktur pajak langganan yang dibuat.",
    "No suppliers yet. Click \"+ New Supplier\" to add one.": "Belum ada pemasok. Klik \"+ Pemasok Baru\" untuk menambahkannya.",
    "No tables registered for this floor. Click \"+ Add Table\" to start.": "Tidak ada meja yang terdaftar untuk lantai ini. Klik \"+ Tambah Meja\" untuk memulai.",
    "No team members found. Click \"+ Invite User\" to add staff.": "Tidak ada anggota tim yang ditemukan. Klik \"+ Undang Pengguna\" untuk menambahkan staf.",
    "No units yet. Click \"+ New Unit\" to add one.": "Belum ada satuan. Klik \"+ Satuan Baru\" untuk menambahkannya.",
    "No vendor bills or operational expenses match current filters.": "Tidak ada tagihan pemasok atau biaya operasional yang cocok dengan filter saat ini.",
    "Non-Supplier / General Vendor": "Bukan Pemasok / Vendor Umum",
    "None": "Tidak Ada",
    "None (Port 25)": "Tidak Ada (Port 25)",
    "None (Use built-in modules only)": "Tidak Ada (Hanya gunakan modul bawaan)",
    "Not Set": "Belum Diatur",
    "Note:": "Catatan:",
    "Notes & Remarks": "Catatan & Komentar",
    "Notes regarding installment / settlement...": "Catatan mengenai angsuran / pelunasan...",
    "Notification & Dispatch": "Notifikasi & Pengiriman",
    "OFF": "MATI",
    "ON": "HIDUP",
    "OVERDUE": "TERLAMBAT",
    "Occupied": "Terisi",
    "Ocean Sky": "Biru Langit Samudra",
    "Office Supplies": "Perlengkapan Kantor",
    "Office Supplies & Software": "Perlengkapan Kantor & Perangkat Lunak",
    "Official Razorpay Payment Gateway": "Payment Gateway Resmi Razorpay",
    "Official Tax Invoices & Payment Receipts": "Faktur Pajak Resmi & Kuitansi Pembayaran",
    "One-Time Invitation Code": "Kode Undangan Sekali Pakai",
    "Online Catalog": "Katalog Online",
    "Online QR Menu": "Menu QR Online",
    "Open Cash Register": "Buka Mesin Kasir",
    "Open KDS": "Buka KDS",
    "Open Link": "Buka Tautan",
    "Open Register": "Buka Kasir",
    "Open Restaurant POS": "Buka POS Restoran",
    "Open Table POS": "Buka POS Meja",
    "Open WhatsApp & Send": "Buka WhatsApp & Kirim",
    "Open a register with a starting cash float to begin tracking today's shift.": "Buka kasir dengan uang modal awal untuk mulai melacak shift hari ini.",
    "Open/close the register, track cash in & out, and generate X/Z shift reports.": "Buka/tutup kasir, lacak kas masuk & keluar, dan buat laporan shift X/Z.",
    "Opened": "Dibuka",
    "Opening": "Pembukaan",
    "Opening Float": "Modal Awal Kasir",
    "Opening Float ($)": "Modal Awal Kasir ($)",
    "Operating Mode": "Mode Operasi",
    "Option:": "Opsi:",
    "Optional": "Opsional",
    "Options": "Opsi",
    "Or Direct Image URL": "Atau URL Gambar Langsung",
    "Order": "Pesanan",
    "Order No.": "No. Pesanan",
    "Order Notes & Remarks (Printed on Receipt)": "Catatan & Komentar Pesanan (Dicetak pada Struk)",
    "Order Notes & Remarks:": "Catatan & Komentar Pesanan:",
    "Order Sent to Kitchen!": "Pesanan Dikirim ke Dapur!",
    "Order Subtotal": "Subtotal Pesanan",
    "Order via WhatsApp": "Pesan via WhatsApp",
    "Orders & Cash": "Pesanan & Uang Tunai",
    "Orders & thermal receipts": "Pesanan & struk termal",
    "Organize products into POS categories": "Atur produk ke dalam kategori POS",
    "Other Currencies (Reference Rates)": "Mata Uang Lainnya (Tarif Referensi)",
    "Other Expenses": "Pengeluaran Lainnya",
    "Over": "Kelebihan",
    "Overdue Accounts": "Akun Jatuh Tempo",
    "Overdue Balance": "Saldo Terlambat",
    "Overdue Bills": "Tagihan Terlambat",
    "Override unit price": "Ganti harga satuan",
    "PARTIAL": "SEBAGIAN",
    "PDF": "PDF",
    "POS Checkout & Payment": "Pembayaran & Kasir POS",
    "POS Server": "Server POS",
    "POS, Inventory, KOT, Finance": "POS, Inventaris, KOT, Keuangan",
    "PROPOSAL PREPARED FOR:": "PROPOSAL DISIAPKAN UNTUK:",
    "Page Title *": "Judul Halaman *",
    "Paid Amount:": "Jumlah yang Dibayar:",
    "Paid so far": "Dibayar sejauh ini",
    "Partially Paid": "Dibayar Sebagian",
    "Pass": "Lulus",
    "Password": "Kata Sandi",
    "Pay": "Bayar",
    "Pay & Settle Bill": "Bayar & Lunasi Tagihan",
    "Pay & Upgrade": "Bayar & Tingkatkan",
    "Pay Bill": "Bayar Tagihan",
    "Pay Method:": "Metode Pembayaran:",
    "Payable To": "Dibayarkan Kepada",
    "Payment": "Pembayaran",
    "Payment Date": "Tanggal Pembayaran",
    "Payment Information": "Informasi Pembayaran",
    "Payment Method": "Metode Pembayaran",
    "Payment Method:": "Metode Pembayaran:",
    "Payment Proof / Bank Receipt (Optional)": "Bukti Pembayaran / Struk Bank (Opsional)",
    "Payment Remarks": "Catatan Pembayaran",
    "Payment required to activate services & generate tax invoice": "Pembayaran diperlukan untuk mengaktifkan layanan & menghasilkan faktur pajak",
    "Payment terms, bank details, purchase order #...": "Ketentuan pembayaran, detail bank, no. pesanan pembelian...",
    "Payroll & Salaries": "Penggajian & Gaji",
    "Payroll & Staff Wages": "Penggajian & Upah Staf",
    "Pending / In Cooking": "Tertunda / Sedang Dimasak",
    "Pending / Unpaid": "Tertunda / Belum Dibayar",
    "Pending Invoices": "Faktur Tertunda",
    "Pending Orders": "Pesanan Tertunda",
    "Percent (%)": "Persen (%)",
    "Perfect for small retail stores": "Sempurna untuk toko ritel kecil",
    "Permissions Matrix": "Matriks Izin",
    "Perpetual / Lifetime": "Permanen / Seumur Hidup",
    "Phone / Contact": "Telepon / Kontak",
    "Phone / WhatsApp": "Telepon / WhatsApp",
    "Phone / WhatsApp (Optional)": "Telepon / WhatsApp (Opsional)",
    "Phone number (+1 555 0199)": "Nomor telepon (+1 555 0199)",
    "Phone:": "Telepon:",
    "Phrase Key *": "Kunci Frasa *",
    "Physical Address": "Alamat Fisik",
    "Pickup Time": "Waktu Pengambilan",
    "Piece, Kilogram, Box…": "Buah (Pcs), Kilogram, Kotak…",
    "Pieces, kg, box, packs & liters": "Pcs, kg, kotak, bungkus & liter",
    "Plan": "Paket",
    "Plan / Description": "Paket / Deskripsi",
    "Plan details & invoices": "Detail paket & faktur",
    "Platform": "Platform",
    "Platform Application Version": "Versi Aplikasi Platform",
    "Platform Brand Name *": "Nama Merek Platform *",
    "Platform GST / Tax (18% • CGST 9% + SGST 9%)": "Pajak Platform (18% • CGST 9% + SGST 9%)",
    "Platform Logo URL": "URL Logo Platform",
    "Platform Payment Gateways": "Gateway Pembayaran Platform",
    "Please provide a valid name for all items.": "Harap berikan nama yang valid untuk semua item.",
    "Point your domain's": "Arahkan domain Anda",
    "Points Delta (+/-)": "Perubahan Poin (+/-)",
    "Points:": "Poin:",
    "Port": "Port",
    "Port *": "Port *",
    "Portions, kg, litres & grams": "Porsi, kg, liter & gram",
    "Postal Code": "Kode Pos",
    "Prefix": "Prefiks",
    "Prepared By:": "Disiapkan Oleh:",
    "Preset Quick Discounts": "Preset Diskon Cepat",
    "Preview": "Pratinjau",
    "Preview Landing Page": "Pratinjau Halaman Depan",
    "Price": "Harga",
    "Price ($)": "Harga ($)",
    "Pricing Plans Grid": "Kisi Paket Harga",
    "Primary CTA Button Label": "Label Tombol CTA Utama",
    "Primary CTA URL": "URL CTA Utama",
    "Primary Payment Method": "Metode Pembayaran Utama",
    "Print Kitchen Ticket (KOT)": "Cetak Tiket Dapur (KOT)",
    "Print Ticket": "Cetak Tiket",
    "Print receipt/invoice": "Cetak struk/faktur",
    "Processing Charge...": "Memproses Pembayaran...",
    "Processing Sale...": "Memproses Penjualan...",
    "Processing Transaction...": "Memproses Transaksi...",
    "Processing...": "Memproses...",
    "Product": "Produk",
    "Product Brands": "Merek Produk",
    "Product Categories": "Kategori Produk",
    "Product Name *": "Nama Produk *",
    "Product brands & food options": "Merek produk & opsi makanan",
    "Production / Live Mode": "Mode Produksi / Langsung",
    "Profile, printer, tax & domain": "Profil, printer, pajak & domain",
    "Profiles, history & loyalty": "Profil, riwayat & loyalitas",
    "Proof": "Bukti",
    "Provision New Store": "Sediakan Toko Baru",
    "Public / Publishable API Key": "Kunci API Publik / Dapat Dipublikasikan",
    "Publish Public Catalog": "Terbitkan Katalog Publik",
    "Publish an Online Catalog": "Terbitkan Katalog Online",
    "Published Shareable Links": "Tautan yang Dapat Dibagikan yang Diterbitkan",
    "QR Stand": "Dudukan QR",
    "QUO-": "QUO-",
    "Qty": "Jml",
    "Qty:": "Jml:",
    "Quick Add Customer": "Tambah Pelanggan Cepat",
    "Quotation & Invoice Document Accent Color": "Warna Aksen Dokumen Penawaran & Faktur",
    "Quotation Prefix": "Prefiks Penawaran",
    "Quotations & Proposals": "Penawaran & Proposal",
    "Quote #": "No. Penawaran #",
    "Quote No:": "No. Penawaran:",
    "Quote Reference:": "Referensi Penawaran:",
    "Quote Terms & Notes": "Syarat & Catatan Penawaran",
    "Quote Terms & Notes (Rich-Text)": "Syarat & Catatan Penawaran (Rich-Text)",
    "Quotes, estimates & 1-click sales conversion": "Penawaran, estimasi & konversi penjualan 1-klik",
    "Quotes, proposals & estimates": "Penawaran, proposal & estimasi",
    "Rate": "Tarif / Kurs",
    "Razorpay": "Razorpay",
    "Ready to Serve": "Siap Disajikan",
    "Real-Time": "Waktu Nyata (Real-Time)",
    "Real-time live kitchen order tracker & ticket bump screen (Auto-refreshing every 5s)": "Pelacak pesanan dapur langsung waktu nyata & layar tiket (Segarkan otomatis setiap 5 dtk)",
    "Reason": "Alasan",
    "Reason / Note": "Alasan / Catatan",
    "Receipt Prefixes & Bank Terms": "Prefiks Struk & Ketentuan Bank",
    "Recent POS Transactions": "Transaksi POS Terbaru",
    "Recipient Email Address": "Alamat Email Penerima",
    "Recipient Email Address *": "Alamat Email Penerima *",
    "Recipient WhatsApp Phone Number (with Country Code)": "Nomor Telepon WhatsApp Penerima (dengan Kode Negara)",
    "Record Bill Settlement Payment": "Catat Pembayaran Pelunasan Tagihan",
    "Record Cash In": "Catat Kas Masuk",
    "Record Cash Out": "Catat Kas Keluar",
    "Record Receivable Payment": "Catat Pembayaran Piutang",
    "Redeem & Activate": "Tukarkan & Aktifkan",
    "Redeem License Key": "Tukarkan Kunci Lisensi",
    "Ref #": "No. Ref #",
    "Ref / Card Last4": "Ref / 4 Digit Terakhir Kartu",
    "Reference / Transaction / Check #": "Referensi / Transaksi / No. Cek #",
    "Register": "Kasir",
    "Register History (Closed Shifts / Z-Reports)": "Riwayat Kasir (Shift Ditutup / Laporan Z)",
    "Register users and define what each one can see and do.": "Daftarkan pengguna dan tentukan apa yang dapat dilihat dan dilakukan masing-masing pengguna.",
    "Registered on": "Terdaftar pada",
    "Registration prompt": "Permintaan pendaftaran",
    "Rejected": "Ditolak",
    "Remaining": "Tersisa",
    "Remaining Balance": "Sisa Saldo",
    "Remaining Due": "Sisa Jatuh Tempo",
    "Remove": "Hapus",
    "Remove split line": "Hapus baris pemisahan",
    "Remove table": "Hapus meja",
    "Rent & Facilities": "Sewa & Fasilitas",
    "Rent & Premises": "Sewa & Tempat",
    "Rep:": "Staf:",
    "Requires follow-up": "Memerlukan tindak lanjut",
    "Reserved": "Dipesan (Reserved)",
    "Reset": "Atur Ulang",
    "Reset Template": "Atur Ulang Template",
    "Reset to system default": "Atur ulang ke default sistem",
    "Resolve the failed checks above before continuing.": "Selesaikan pemeriksaan yang gagal di atas sebelum melanjutkan.",
    "Restaurant Mode": "Mode Restoran",
    "Restock": "Stok Ulang",
    "Resume Fullscreen": "Lanjutkan Layar Penuh",
    "Retention Window (Days)": "Jendela Retensi (Hari)",
    "Return to my account": "Kembali ke akun saya",
    "Review & Place Order": "Tinjau & Buat Pesanan",
    "Revoke": "Cabut",
    "Revoke this license key?": "Cabut kunci lisensi ini?",
    "Revoke this link?": "Cabut tautan ini?",
    "Revoked": "Dicabut",
    "Right Sidebar": "Bilah Sisi Kanan",
    "Right-to-Left (RTL - Arabic, Hebrew)": "Kanan-ke-Kiri (RTL - Arab, Ibrani)",
    "Role & Profile *": "Peran & Profil *",
    "Role Profile": "Profil Peran",
    "Row": "Baris",
    "Royal Indigo": "Indigo Kerajaan",
    "Royal Purple": "Ungu Kerajaan",
    "Ruby Rose": "Merah Mawar Delima",
    "SKU": "SKU",
    "SKU Scan": "Pemindaian SKU",
    "SKUs, pricing & inventory levels": "SKU, harga & tingkat inventaris",
    "SMTP Email Settings": "Pengaturan Email SMTP",
    "SMTP Host": "Host SMTP",
    "SMTP Host Server *": "Server Host SMTP *",
    "SMTP Password": "Kata Sandi SMTP",
    "SMTP Port": "Port SMTP",
    "SMTP Username": "Nama Pengguna SMTP",
    "SMTP Username / API Key": "Nama Pengguna SMTP / Kunci API",
    "SSL": "SSL",
    "SSL (Port 465)": "SSL (Port 465)",
    "SUB TOTAL": "SUB TOTAL",
    "Sale": "Penjualan",
    "Sale #": "No. Penjualan #",
    "Sale / Inv #": "No. Penjualan / Faktur #",
    "Sale Completed!": "Penjualan Selesai!",
    "Sale Price ($) *": "Harga Jual ($) *",
    "Sales Representative": "Perwakilan Penjualan",
    "Sales by Payment Method": "Penjualan berdasarkan Metode Pembayaran",
    "Sales by Payment Method (This Shift)": "Penjualan berdasarkan Metode Pembayaran (Shift Ini)",
    "Sandbox / Test Mode": "Mode Sandbox / Uji Coba",
    "Save & Preview Quotation": "Simpan & Pratinjau Penawaran",
    "Save & Select Customer": "Simpan & Pilih Pelanggan",
    "Save All Custom Translations": "Simpan Semua Terjemahan Kustom",
    "Save All Settings": "Simpan Semua Pengaturan",
    "Save Bill / Expense": "Simpan Tagihan / Pengeluaran",
    "Save Category": "Simpan Kategori",
    "Save Customer": "Simpan Pelanggan",
    "Save Financial Settings": "Simpan Pengaturan Keuangan",
    "Save Floor": "Simpan Lantai",
    "Save Method": "Simpan Metode",
    "Save Notification & Dispatch Settings": "Simpan Pengaturan Notifikasi & Pengiriman",
    "Save Operating Mode": "Simpan Mode Operasi",
    "Save Permissions": "Simpan Izin",
    "Save Phrase": "Simpan Frasa",
    "Save Plan": "Simpan Paket",
    "Save Product": "Simpan Produk",
    "Save Profile & Branding": "Simpan Profil & Branding",
    "Save Receipt Prefixes & Bank Terms": "Simpan Prefiks Struk & Ketentuan Bank",
    "Save SMTP Configuration": "Simpan Konfigurasi SMTP",
    "Save Store Overrides": "Simpan Penyesuaian Toko",
    "Save Supplier": "Simpan Pemasok",
    "Save Table": "Simpan Meja",
    "Save Unit": "Simpan Satuan",
    "Saved securely": "Disimpan dengan aman",
    "Saving...": "Menyimpan...",
    "Scan barcode / SKU...": "Pindai barcode / SKU...",
    "Scan barcode or type product name / SKU...": "Pindai barcode atau ketik nama produk / SKU...",
    "Scan to View Menu & Order": "Pindai untuk Melihat Menu & Memesan",
    "Scheduled outgoings": "Pengeluaran terjadwal",
    "Scope specifications / item deliverables description (optional)...": "Spesifikasi ruang lingkup / deskripsi hasil kerja (opsional)...",
    "Search and attach a customer to this sale": "Cari dan lampirkan pelanggan ke penjualan ini",
    "Search bar, category chips, 3-column retail item cards with side cart.": "Bilah pencarian, tab kategori, kartu item ritel 3 kolom dengan keranjang samping.",
    "Search bill #, vendor, title...": "Cari no. tagihan, vendor, judul...",
    "Search by customer name, phone, or email...": "Cari berdasarkan nama pelanggan, telepon, atau email...",
    "Search by name, code, barcode…": "Cari berdasarkan nama, kode, barcode…",
    "Search by name, email, phone…": "Cari berdasarkan nama, email, telepon…",
    "Search by sale # or customer…": "Cari berdasarkan no. penjualan atau pelanggan…",
    "Search invoice #, customer...": "Cari no. faktur, pelanggan...",
    "Search items...": "Cari item...",
    "Search keys or translated phrases…": "Cari kunci atau frasa terjemahan…",
    "Search menu...": "Cari menu...",
    "Search quotation # or client name...": "Cari no. penawaran atau nama klien...",
    "Search stores by name, account ID, email, slug…": "Cari toko berdasarkan nama, ID akun, email, slug…",
    "Search suppliers by name…": "Cari pemasok berdasarkan nama…",
    "Search team by name, email, or role...": "Cari tim berdasarkan nama, email, atau peran...",
    "Search terms or phrases…": "Cari istilah atau frasa…",
    "Seat": "Kursi",
    "Secondary CTA Button Label": "Label Tombol CTA Sekunder",
    "Secondary CTA URL": "URL CTA Sekunder",
    "Secure Subscription Checkout": "Pembayaran Langganan Aman",
    "Select Available Table": "Pilih Meja yang Tersedia",
    "Select Brand": "Pilih Merek",
    "Select Category": "Pilih Kategori",
    "Select Client / Customer": "Pilih Klien / Pelanggan",
    "Select Customer / Member": "Pilih Pelanggan / Member",
    "Select Destination Table": "Pilih Meja Tujuan",
    "Select Dine-In Table": "Pilih Meja Makan di Tempat",
    "Select Extra Page to Embed": "Pilih Halaman Tambahan untuk Disematkan",
    "Select Language File to Edit:": "Pilih File Bahasa untuk Diedit:",
    "Select POS Layout & Interface Design": "Pilih Tata Letak POS & Desain Antarmuka",
    "Select Payment Method": "Pilih Metode Pembayaran",
    "Select Products to Include": "Pilih Produk untuk Disertakan",
    "Select Table": "Pilih Meja",
    "Select User to Configure:": "Pilih Pengguna untuk Dikonfigurasi:",
    "Select the primary accent color for your navigation sidebar, buttons, and badges": "Pilih warna aksen utama untuk bilah navigasi, tombol, dan lencana Anda",
    "Selected": "Dipilih",
    "Selected ✓": "Dipilih ✓",
    "Send": "Kirim",
    "Send Email": "Kirim Email",
    "Send Email via SMTP": "Kirim Email via SMTP",
    "Send Invoice Email": "Kirim Email Faktur",
    "Send Invoice via Email": "Kirim Faktur melalui Email",
    "Send Order to Kitchen": "Kirim Pesanan ke Dapur",
    "Send Quotation Email": "Kirim Email Penawaran",
    "Send Quotation Proposal #": "Kirim Proposal Penawaran #",
    "Send Tax Invoice #": "Kirim Faktur Pajak #",
    "Send Tax Invoice Receipt": "Kirim Struk Faktur Pajak",
    "Send Test Email": "Kirim Email Uji Coba",
    "Send a test email to verify your SMTP configuration": "Kirim email uji coba untuk memverifikasi konfigurasi SMTP Anda",
    "Send an immediate test dispatch to verify that your SMTP host credentials and sender address are working properly.": "Kirim pengiriman uji coba langsung untuk memverifikasi bahwa kredensial host SMTP dan alamat pengirim Anda berfungsi dengan baik.",
    "Send an invitation to join your store via WhatsApp or Email": "Kirim undangan untuk bergabung dengan toko Anda melalui WhatsApp atau Email",
    "Send invitation email automatically via store SMTP": "Kirim email undangan secara otomatis melalui SMTP toko",
    "Sender Display Name": "Nama Tampilan Pengirim",
    "Sender Email Address": "Alamat Email Pengirim",
    "Sending Test...": "Mengirim Uji Coba...",
    "Sending...": "Mengirim...",
    "Sent": "Terkirim",
    "Sent to Client": "Terkirim ke Klien",
    "Setting": "Pengaturan",
    "Settle Bill & Print Receipt": "Lunasi Tagihan & Cetak Struk",
    "Settled": "Lunas",
    "Settled (Paid)": "Lunas (Dibayar)",
    "Settled This Month": "Dilunasi Bulan Ini",
    "Settlement Amount ($)": "Jumlah Pelunasan ($)",
    "Settlement Date": "Tanggal Pelunasan",
    "Settlement remarks or transfer notes...": "Catatan pelunasan atau transfer...",
    "Share Invite": "Bagikan Undangan",
    "Share Receipt on WhatsApp": "Bagikan Struk di WhatsApp",
    "Share via WhatsApp": "Bagikan via WhatsApp",
    "Shareable web catalog & WhatsApp store": "Katalog web yang dapat dibagikan & toko WhatsApp",
    "Shifts, float & cash balancing": "Shift, modal awal & penyeimbangan kas",
    "Short": "Kurang",
    "Sign out this device?": "Keluar dari perangkat ini?",
    "Signed In": "Sudah Masuk",
    "Size / Style": "Ukuran / Gaya",
    "Smart Inventory Platform, SaaS Billing…": "Platform Inventaris Cerdas, Penagihan SaaS…",
    "Solution Pillars": "Pilar Solusi",
    "Special Order Instructions": "Instruksi Khusus Pesanan",
    "Special instructions, cashier remarks...": "Instruksi khusus, catatan kasir...",
    "Split Payment Entries": "Entri Pembayaran Terpisah",
    "Split Payment:": "Pembayaran Terpisah:",
    "Split:": "Pisah:",
    "Square Stand": "Square Stand",
    "Square Stand Register": "Kasir Square Stand",
    "Staff": "Staf",
    "Staff User Accounts": "Akun Pengguna Staf",
    "Staff accounts & access matrix": "Akun staf & matriks akses",
    "Stand:": "Stand:",
    "Standard": "Standar",
    "Standard Scanner": "Pemindai Standar",
    "Standard Scanner POS": "POS Pemindai Standar",
    "Start Preparing": "Mulai Mempersiapkan",
    "State": "Negara Bagian / Provinsi",
    "State / Province": "Provinsi",
    "Status": "Status",
    "Status:": "Status:",
    "Step 1 — Requirements & Permissions": "Langkah 1 — Persyaratan & Izin",
    "Step 2 — Environment & Database": "Langkah 2 — Lingkungan & Basis Data",
    "Step 3 — Migrate & Seed": "Langkah 3 — Migrasi & Seed",
    "Step 4 — Super Admin Account": "Langkah 4 — Akun Super Admin",
    "Step 5 — Finish": "Langkah 5 — Selesai",
    "Sticky Navigation Bar": "Bilah Navigasi Lengket (Sticky)",
    "Stock": "Stok",
    "Store Account:": "Akun Toko:",
    "Store Email": "Email Toko",
    "Store Invoicing & Billing": "Faktur & Penagihan Toko",
    "Store Languages & Custom Translation Editor": "Bahasa Toko & Editor Terjemahan Kustom",
    "Store Operating Mode": "Mode Operasi Toko",
    "Store Phone / WhatsApp": "Telepon / WhatsApp Toko",
    "Store Primary Language": "Bahasa Utama Toko",
    "Store Profile & Branding": "Profil & Branding Toko",
    "Store Profile & Location": "Profil & Lokasi Toko",
    "Store Subdomain / Slug": "Subdomain / Slug Toko",
    "Store Theme, Branding & POS Layout": "Tema Toko, Branding & Tata Letak POS",
    "Store Website URL": "URL Situs Web Toko",
    "Street & apt": "Jalan & no. unit/apartemen",
    "Stripe, PayPal, Mollie, Razorpay": "Stripe, PayPal, Mollie, Razorpay",
    "Subscription & Tax Billing": "Langganan & Penagihan Pajak",
    "Subscription Expiration Date": "Tanggal Kedaluwarsa Langganan",
    "Subtotal": "Subtotal",
    "Subtotal:": "Subtotal:",
    "Suffix": "Sufiks",
    "Super Admin": "Super Admin",
    "SuperAdmin Sidebar Menu": "Menu Bilah Sisi SuperAdmin",
    "Supermarket Touch POS": "POS Layar Sentuh Supermarket",
    "Supplier": "Pemasok",
    "Supplier Name *": "Nama Pemasok *",
    "Supplier bills & expenses": "Tagihan & pengeluaran pemasok",
    "Supplier bills & food purchases": "Tagihan pemasok & pembelian makanan",
    "Supplier bills & purchase dues": "Tagihan pemasok & kewajiban pembelian",
    "Suppliers & Vendors": "Pemasok & Vendor",
    "Support": "Dukungan",
    "Support Email": "Email Dukungan",
    "Support Phone": "Telepon Dukungan",
    "Supported Platform Languages": "Bahasa Platform yang Didukung",
    "Suspended": "Ditangguhkan",
    "Switch Account": "Ganti Akun",
    "Switch Table": "Pindah Meja",
    "Symbol Placement": "Penempatan Simbol",
    "System Default": "Default Sistem",
    "System Health & Global Maintenance Mode": "Kesehatan Sistem & Mode Pemeliharaan Global",
    "TAX ESTIMATE": "ESTIMASI PAJAK",
    "TLS": "TLS",
    "TLS (Port 587 - Recommended)": "TLS (Port 587 - Direkomendasikan)",
    "TXN / Auth #": "No. Transaksi / Otorisasi #",
    "Table Name / Number *": "Nama / Nomor Meja *",
    "Table Order Review": "Tinjauan Pesanan Meja",
    "Tables & Floor Plan": "Meja & Denah Lantai",
    "Takeaway": "Bawa Pulang (Takeaway)",
    "Target Seat": "Kursi Target",
    "Tax (GST/VAT)": "Pajak (PPN/VAT)",
    "Tax / GST:": "Pajak / PPN:",
    "Tax Amount ($)": "Jumlah Pajak ($)",
    "Tax Exempt": "Bebas Pajak",
    "Tax ID": "NPWP / ID Pajak",
    "Tax ID / Business Reg": "NPWP / Registrasi Bisnis",
    "Tax ID / VAT / Document": "NPWP / PPN / Dokumen",
    "Tax Rate (%)": "Tarif Pajak (%)",
    "Tax rates & category hierarchy": "Tarif pajak & hierarki kategori",
    "Tax/GSTIN:": "Pajak/NPWP:",
    "Taxable": "Kena Pajak",
    "Taxable Base": "Dasar Pengenaan Pajak",
    "Taxes & Professional": "Pajak & Profesional",
    "Taxes & Professional Services": "Pajak & Layanan Profesional",
    "Tenant Brand Primary": "Warna Utama Merek Toko",
    "Tenant app fallback primary": "Warna Cadangan Aplikasi Toko",
    "Term / Phrase": "Istilah / Frasa",
    "Terminals & Devices": "Terminal & Perangkat",
    "Terms and Conditions:": "Syarat dan Ketentuan:",
    "Test SMTP": "Uji SMTP",
    "Text Direction": "Arah Teks",
    "Thank you for your business! All sales are final unless otherwise specified in your service contract.": "Terima kasih atas kerja sama Anda! Semua penjualan bersifat final kecuali ditentukan lain dalam kontrak layanan Anda.",
    "The bar floats as an overlay above the UI, enabling free drag-and-drop placement anywhere across the viewport without altering page grid layout.": "Bilah mengambang di atas UI, memungkinkan penempatan bebas dengan seret-dan-lepas tanpa mengubah tata letak kisi halaman.",
    "The bar snaps rigidly into the screen structure (Left Sidebar, Right Sidebar, Top Header Bar, Bottom Dock Bar) and adjusts page padding accordingly so content never scrolls under or overlaps it.": "Bilah menempel erat ke struktur layar dan menyesuaikan bantalan halaman sehingga konten tidak pernah terpotong.",
    "The remaining balance is payable upon delivery/project completion.": "Sisa saldo harus dibayar saat pengiriman/penyelesaian proyek.",
    "Thermal receipts & order history": "Struk termal & riwayat pesanan",
    "This email address will appear in the \"From:\" header of all outgoing system emails.": "Alamat email ini akan muncul di header \"From:\" dari semua email sistem keluar.",
    "This user has Administrator role and automatically enjoys full bypass access to all modules.": "Pengguna ini memiliki peran Administrator dan secara otomatis menikmati akses penuh ke semua modul.",
    "Ticket Status:": "Status Tiket:",
    "Ticket is now active in the Kitchen Display System (KDS) queue.": "Tiket sekarang aktif dalam antrean Kitchen Display System (KDS).",
    "Time:": "Waktu:",
    "Toggle Fullscreen Mode": "Alihkan Mode Layar Penuh",
    "Toggle Sticky Navigation": "Alihkan Navigasi Sticky",
    "Top Header Bar": "Bilah Header Atas",
    "Total": "Total",
    "Total Active KOTs": "Total KOT Aktif",
    "Total Amount": "Jumlah Total",
    "Total Amount Due": "Total Jumlah Jatuh Tempo",
    "Total Amount Paid:": "Total Jumlah yang Dibayar:",
    "Total Bill": "Total Tagihan",
    "Total Due Today": "Total Jatuh Tempo Hari Ini",
    "Total Order Amount:": "Total Jumlah Pesanan:",
    "Total Outstanding": "Total Belum Dibayar",
    "Total Outstanding Balance": "Total Sisa Saldo Belum Dibayar",
    "Total Payable": "Total yang Harus Dibayar",
    "Total Sales": "Total Penjualan",
    "Total Tables:": "Total Meja:",
    "Total:": "Total:",
    "Touch Department": "Departemen Sentuh",
    "Touch POS": "POS Layar Sentuh",
    "Track customer balances, credit sales, partial payments, due dates, and overdue accounts.": "Lacak saldo pelanggan, penjualan kredit, pembayaran sebagian, tanggal jatuh tempo, dan akun terlambat.",
    "Trade / Brand Name": "Nama Dagang / Merek",
    "Transaction & Sales": "Transaksi & Penjualan",
    "Transfer Order": "Transfer Pesanan",
    "Transfer Table": "Pindah Meja",
    "Transfer Table Order": "Transfer Pesanan Meja",
    "Type product name, SKU or barcode scan...": "Ketik nama produk, SKU atau pindai barcode...",
    "URL Slug *": "Slug URL *",
    "USD": "USD",
    "Unassign Customer": "Batalkan Penetapan Pelanggan",
    "Unit": "Satuan",
    "Unit Name": "Nama Satuan",
    "Unit Name *": "Nama Satuan *",
    "Unit Price": "Harga Satuan",
    "Units of Measure": "Satuan Ukuran",
    "Unlimited": "Tanpa Batas",
    "Unlimited Inventory & Sales History": "Inventaris & Riwayat Penjualan Tanpa Batas",
    "Upcoming (30 Days)": "Mendatang (30 Hari)",
    "Upgrade or renew your plan with instant tax invoice generation": "Tingkatkan atau perbarui paket Anda dengan pembuatan faktur pajak instan",
    "Upload Product Photo": "Unggah Foto Produk",
    "Uploading...": "Mengunggah...",
    "Use \"Adjust Stock\" button on the table.": "Gunakan tombol \"Sesuaikan Stok\" pada tabel.",
    "User": "Pengguna",
    "User / Terminal": "Pengguna / Terminal",
    "Username": "Nama Pengguna",
    "Utilities (Electricity, Water, Internet)": "Utilitas (Listrik, Air, Internet)",
    "Utilities (Power/Water)": "Utilitas (Listrik/Air)",
    "Valid Until:": "Berlaku Hingga:",
    "Validity Expiry Date": "Tanggal Kedaluwarsa Validitas",
    "Vendor / Supplier": "Vendor / Pemasok",
    "Vendor Name (If not in suppliers)": "Nama Vendor (Jika tidak ada di daftar pemasok)",
    "Vendor contacts & purchasing": "Kontak vendor & pembelian",
    "Vendor directory & purchasing": "Direktori vendor & pembelian",
    "Verify Key & Upgrade": "Verifikasi Kunci & Tingkatkan",
    "View": "Lihat",
    "View & Download PDF Tax Invoice": "Lihat & Unduh Faktur Pajak PDF",
    "View All": "Lihat Semua",
    "View All Sales": "Lihat Semua Penjualan",
    "View All Stores": "Lihat Semua Toko",
    "View Invoices": "Lihat Faktur",
    "View Only": "Hanya Lihat",
    "View Z-Report": "Lihat Laporan Z",
    "View attached bill file": "Lihat file tagihan terlampir",
    "Viewing as": "Melihat sebagai",
    "Violet Purple": "Ungu Violet",
    "Volume, Outlets, Uptime": "Volume, Gerai, Waktu Operasional",
    "Walk-in": "Walk-in",
    "Walk-in Customer": "Pelanggan Walk-in",
    "Walk-in Member": "Member Walk-in",
    "Walk-in Regular Customer": "Pelanggan Reguler Walk-in",
    "Warm Amber": "Amber Hangat",
    "Weekly Automated Snapshot": "Pencadangan Otomatis Mingguan",
    "WhatsApp": "WhatsApp",
    "WhatsApp & Messaging Settings": "Pengaturan WhatsApp & Pesan",
    "WhatsApp Web / Mobile": "WhatsApp Web / Seluler",
    "With pending dues": "Dengan tunggakan tertunda",
    "X-Report (live)": "Laporan X (langsung)",
    "Yearly": "Tahunan",
    "You": "Anda",
    "Your Custom Store Translation": "Terjemahan Kustom Toko Anda",
    "Your Name (Optional)": "Nama Anda (Opsional)",
    "Your Name *": "Nama Anda *",
    "Your Order Cart": "Keranjang Pesanan Anda",
    "Your Phone / WhatsApp Number": "Nomor Telepon / WhatsApp Anda",
    "Your Store Custom Translation *": "Terjemahan Kustom Toko Anda *",
    "Your cart is currently empty.": "Keranjang Anda saat ini kosong.",
    "Your sale is currently empty. Tap items to add.": "Penjualan Anda saat ini kosong. Ketuk item untuk menambahkan.",
    "Z-Report": "Laporan Z",
    "active invoices": "faktur aktif",
    "admin@yourcompany.com": "admin@yourcompany.com",
    "apikey, username@domain.com…": "apikey, username@domain.com…",
    "billing@yourstore.com": "billing@yourstore.com",
    "by": "oleh",
    "days": "hari",
    "discount": "diskon",
    "e.g. 1 for US/CA, 91 for IN, 44 for UK, 62 for ID": "mis. 62 untuk ID, 1 untuk US/CA, 91 untuk IN",
    "e.g. 15 mins, 06:00 PM": "mis. 15 menit, 18:00",
    "e.g. Change fund top-up, petty cash withdrawal": "mis. Pengisian kas kecil, penarikan kas kecil",
    "e.g. City Power Corp, Apex Landlord": "mis. PLN, Pengelola Gedung",
    "e.g. Credit Card, UPI, PIX, Stripe": "mis. Kartu Kredit, QRIS, Transfer Bank",
    "e.g. Dutch": "mis. Belanda",
    "e.g. For returns, keep this receipt within 7 days.": "mis. Untuk pengembalian, simpan struk ini dalam 7 hari.",
    "e.g. Fresh Summer Produce, Special Deals…": "mis. Produk Musim Panas Segar, Promo Spesial…",
    "e.g. Michael Scott": "mis. Budi Santoso",
    "e.g. Monthly Warehouse Rent or Stock Restock Batch #4": "mis. Sewa Gudang Bulanan atau Restok Barang Batch #4",
    "e.g. Nederlands": "mis. Bahasa Indonesia",
    "e.g. No onion": "mis. Tanpa bawang",
    "e.g. Pay via terminal or contactless": "mis. Bayar via EDC atau nirsentuh",
    "e.g. Política de Devoluciones": "mis. Kebijakan Pengembalian",
    "e.g. Restock, damaged, correction": "mis. Restok, rusak, koreksi",
    "e.g. Return Policy": "mis. Kebijakan Pengembalian",
    "e.g. Return Policy, Print Tax Invoice": "mis. Kebijakan Pengembalian, Cetak Faktur Pajak",
    "e.g. Return Policy, Special Promo": "mis. Kebijakan Pengembalian, Promo Spesial",
    "e.g. Rooftop Patio, Bar, Hall": "mis. Teras Atap, Bar, Aula Utama",
    "e.g. Sarah Jenkins": "mis. Siti Rahma",
    "e.g. Scope deliverables, milestone payment terms, project phases...": "mis. Hasil kerja, termin pembayaran bertahap, tahapan proyek...",
    "e.g. TAX-8891, VAT12345": "mis. NPWP-8891, PPN12345",
    "e.g. TXN-998822 or Check #4401": "mis. TXN-998822 atau Cek #4401",
    "e.g. Table 04, VIP-1, Bar-02": "mis. Meja 04, VIP-1, Bar-02",
    "e.g. WIRE-884401 or Check #1002": "mis. TRF-884401 atau Cek #1002",
    "e.g. card, upi, pix, stripe": "mis. kartu, qris, tunai, transfer",
    "e.g. nl, ja, it": "mis. id, en, ja",
    "e.g. smtp.mailgun.org, smtp.gmail.com": "mis. smtp.mailgun.org, smtp.gmail.com",
    "e.g. yourstore.com or https://yourstore.com": "mis. tokoanda.com atau https://tokoanda.com",
    "each": "setiap",
    "https://example.com/favicon.ico": "https://example.com/favicon.ico",
    "https://example.com/logo.png": "https://example.com/logo.png",
    "https://example.com/product-image.jpg": "https://example.com/product-image.jpg",
    "if CNAME isn't supported at your registrar for this name) to": "jika CNAME tidak didukung pada registrar Anda untuk nama ini) ke",
    "impersonated": "ditiru",
    "items": "item",
    "line items": "item baris",
    "m ago": "menit lalu",
    "month": "bulan",
    "my-store": "toko-saya",
    "no-reply@saas.zoomnearby.com, billing@yourdomain.com": "no-reply@saas.zoomnearby.com, billing@yourdomain.com",
    "of": "dari",
    "or": "atau",
    "pcs": "pcs",
    "pcs, kg, box…": "pcs, kg, dus…",
    "pcs, kg, bx…": "pcs, kg, dus…",
    "pos.yourdomain.com or mycompany.com": "pos.domainanda.com atau perusahaananda.com",
    "postmaster@yourdomain.com": "postmaster@yourdomain.com",
    "pts": "poin",
    "quotation(s) selected": "penawaran dipilih",
    "sale(s) total, all methods": "total penjualan, semua metode",
    "sarah@store.com": "sarah@store.com",
    "save this form, then ask your platform admin to finish HTTPS setup for the domain — until that's done it may show a certificate warning.": "simpan formulir ini, lalu minta admin platform Anda untuk menyelesaikan penyiapan HTTPS untuk domain — sampai selesai, peringatan sertifikat mungkin muncul.",
    "seats": "kursi",
    "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…": "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…",
    "subtotal": "subtotal",
    "tax": "pajak",
    "to Sale invoice?": "ke faktur Penjualan?",
    "total": "total",
    "will be logged to Accounts Receivable.": "akan dicatat ke Piutang Usaha.",
    "with Razorpay": "dengan Razorpay",
    "year": "tahun",
    "your-email@example.com": "your-email@example.com"
}

def update_id():
    with open('lang/id.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    with open('scratch/to_translate/id_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
        
    missing_count = 0
    for k in missing:
        if k in INDONESIAN_TRANSLATIONS:
            existing[k] = INDONESIAN_TRANSLATIONS[k]
        else:
            print(f"Missing translation for key: {k}")
            missing_count += 1
            
    if missing_count > 0:
        print(f"FAILED: {missing_count} keys missing in INDONESIAN_TRANSLATIONS")
        return False
        
    with open('lang/id.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
        f.write('\n')
        
    print(f"Successfully updated lang/id.json! Total keys: {len(existing)}")
    return True

if __name__ == '__main__':
    update_id()
