# Simplified Chinese translation dictionary for all missing keys
import json

CHINESE_TRANSLATIONS = {
    "+1 555-0199": "+1 555-0199",
    "0% Exempt": "0% 免税",
    "1 day": "1天",
    "10% Happy Hour": "10% 欢乐时光优惠",
    "14-day zero-risk trial evaluation": "14天零风险免费试用评估",
    "15% Member VIP": "15% VIP会员折扣",
    "20% Promo Clearance": "20% 清仓特惠",
    "256-Bit SSL Encrypted Payment": "256位SSL加密支付",
    "30 days": "30天",
    "40% advance milestone required upon quotation acceptance.": "确认报价单后需预付40%阶段款项。",
    "5% Staff Discount": "5% 员工专属折扣",
    "7 days": "7天",
    "80mm / 58mm": "80mm / 58mm",
    "Abbreviation": "缩写 / 代码",
    "Accepted": "已接受",
    "Accepted / Approved": "已接受 / 已批准",
    "Access Control": "权限控制",
    "Accounts Payable & Expense Management": "应付账款与费用管理",
    "Accounts Receivable (Customer Credit & Invoices)": "应收账款 (客户赊账与发票)",
    "Action": "操作",
    "Actions": "操作",
    "Activate": "激活",
    "Activate Free Trial": "激活免费试用",
    "Activation / License Key *": "激活码 / 许可证密钥 *",
    "Active (Visible in POS)": "启用 (在POS中显示)",
    "Active Account": "正常账户",
    "Active Devices & POS Terminals": "已激活设备与POS终端",
    "Active Store": "活跃店铺",
    "Active Store Plan": "当前店铺套餐",
    "Active Supplier": "合作中供应商",
    "Active subscription plans": "生效中的订阅套餐",
    "Add Currency": "添加币种",
    "Add Custom Phrase": "添加自定义词条",
    "Add Customer": "添加客户",
    "Add Floor": "添加楼层",
    "Add Floor Area": "添加楼层区域",
    "Add Method": "添加方式",
    "Add Method Split": "添加组合支付方式",
    "Add New Category": "添加新分类",
    "Add New Client": "添加新客户",
    "Add New Customer": "添加新客户",
    "Add New Payment Method": "添加新支付方式",
    "Add New Supplier": "添加新供应商",
    "Add New Unit": "添加新单位",
    "Add Row": "添加行",
    "Add Split": "添加分拆",
    "Add Table": "添加餐桌",
    "Add Vendor Bill / Expense": "添加供应商账单 / 支出",
    "Add special instructions, client PO reference, warranty notes or cashier remarks...": "添加特殊要求、客户采购单号、保修条款或收银员备注...",
    "Add to Cart": "加入购物车",
    "Add to Order": "加入订单",
    "Add to Sale +": "添加至销售 +",
    "Add, edit, enable or remove custom payment methods for POS checkout": "添加、编辑、启用或删除POS收银的自定义支付方式",
    "Add-ons & Extras": "加料与附加项",
    "Additional Custom Authored Content (Optional)": "额外自定义内容 (可选)",
    "Address": "地址",
    "Address:": "地址:",
    "Adjust": "调整",
    "Adjust Points": "调整积分",
    "Adjustment (+/- Qty)": "库存调整 (+/- 数量)",
    "Admin Full Name *": "管理员姓名 *",
    "Admin Login / Username *": "管理员登录名 / 用户名 *",
    "Admin Login Email *": "管理员登录邮箱 *",
    "Administration & Settings": "管理与设置",
    "Administrator": "系统管理员",
    "All": "全部",
    "All Categories": "全部分类",
    "All Customers": "全部客户",
    "All Floor Areas": "全部楼层区域",
    "All Items": "全部商品",
    "All Kitchen Orders Cleared!": "所有厨房订单已出餐完毕！",
    "All Menu": "全部菜单",
    "All Quotes": "全部报价单",
    "All Statuses": "全部状态",
    "All Suppliers": "全部供应商",
    "All inventory items are healthy and above minimum threshold.": "所有商品库存充足，均高于预警安全线。",
    "All rates quoted are valid for 15 days from issue date.": "所有报价自出具之日起15天内有效。",
    "All unpaid bills": "所有未付账单",
    "All-inclusive for growing businesses": "成长型企业全功能一站式方案",
    "Allocated": "已分配",
    "Amber Gold": "琥珀金",
    "Amount": "金额",
    "Amount ($)": "金额 ($)",
    "App URL": "应用网址 (URL)",
    "Application & Navigation Theme Color": "应用与导航栏主题色",
    "Application primary theme color, default POS layout design, logo, and document colors": "系统主色调、默认POS收银界面、Logo以及单据打印色彩",
    "Apply": "应用",
    "Apply Primary Language": "应用主语言",
    "Apply Role Profile Preset:": "套用角色权限模板:",
    "Are you sure you want to delete payment method": "确定要删除该支付方式吗",
    "Are you sure you want to delete the selected quotations?": "确定要删除所选的报价单吗？",
    "Are you sure you want to delete this bill?": "确定要删除此账单吗？",
    "Are you sure you want to delete this quote?": "确定要删除此报价单吗？",
    "Are you sure you want to delete this translation key?": "确定要删除此翻译词条吗？",
    "Area Name *": "区域名称 *",
    "Assigned Role": "所属角色",
    "Attach Official PDF Document": "附带官方PDF文档",
    "Authorized POS Devices": "已授权POS设备",
    "Automated Database Backup & Retention Policy": "数据库自动备份与保留策略",
    "Available": "可用",
    "Available Subscription Plans": "可订购套餐",
    "Available database dumps stored on disk": "磁盘上现有的数据库备份文件",
    "BACK / CLEAR": "返回 / 清空",
    "Back to Quotation Detail": "返回报价详情",
    "Back to Quotes": "返回报价单列表",
    "Back to Sales": "返回销售列表",
    "Back to Users & Team": "返回用户与团队",
    "Backup Frequency": "备份频率",
    "Badge Color": "徽章颜色",
    "Balance Due": "尚欠余额",
    "Balance Due:": "尚欠金额:",
    "Balance logged to Accounts Receivable": "已记入应收账款余额",
    "Balanced": "账实相符",
    "Bank & Payment Details (Rich-Text)": "银行与付款账户信息 (富文本)",
    "Bank & Payment Instructions": "银行转账与支付说明",
    "Bank Reference / Wire TXN / Check #": "银行流水号 / 电汇交易号 / 支票号 #",
    "Bar / Lounge": "酒吧 / 休息区",
    "Barcode": "条形码",
    "Barcode / SKU": "条形码 / SKU",
    "Base Amount ($)": "基准金额 ($)",
    "Base Currency Code": "基准货币代码",
    "Base currency code, symbol, decimal precision, and placement used across POS, cart, checkout, and invoices": "在POS收银、购物车、结账和发票中通用的基准货币代码、符号、小数位数和显示格式",
    "Best Value": "性价比之选",
    "Best for: General Retail, Supermarkets, Convenience stores": "适用于: 通用零售、大型超市、便利店",
    "Best for: Modern tablet/iPad stands, boutique shops, cafes": "适用于: 平板/iPad收银支架、精品小店、咖啡厅",
    "Best for: Touch registers, high-traffic counters, department stores": "适用于: 触屏收银一体机、高频收银台、百货商场",
    "Bill": "账单",
    "Bill #": "账单号 #",
    "Bill / Invoice Reference #": "账单 / 发票参考号 #",
    "Bill Amount": "账单金额",
    "Bill Date": "账单日期",
    "Bill Title / Description": "账单标题 / 描述",
    "Billed": "已计费",
    "Bottom CTA Banner": "底部行动号召横幅",
    "Bottom Dock Bar": "底部悬浮停靠栏",
    "Brand": "品牌",
    "Brand Logo URL / Image Path": "品牌Logo链接 / 图像路径",
    "Brand Name *": "品牌名称 *",
    "Brand names & supplier labels": "品牌名称与供应商标识",
    "Brand or company name displayed to recipients.": "向接收方展示的品牌或公司名称。",
    "Brands & Manufacturers": "品牌与生产商",
    "Brands & Modifiers": "品牌与规格修饰符",
    "Browser Favicon URL (.ico / .png)": "浏览器标签页图标 (.ico / .png)",
    "Business Contact Email": "商务联系邮箱",
    "Business details displayed on POS terminal, receipts, and invoices": "POS终端、收银小票和发票上展示的企业商户信息",
    "CVV / CVC *": "安全码 (CVV/CVC) *",
    "Call:": "电话:",
    "Cancel KOT": "取消厨房出菜单 (KOT)",
    "Cancel Sale & Restock": "取消订单并归还库存",
    "Cancel [Esc]": "取消 [Esc]",
    "Cancel this sale and restore stock?": "确定要取消这笔销售并还原商品库存吗？",
    "Capacity (Seats)": "容纳人数 (座位数)",
    "Capacity:": "容纳人数:",
    "Card Number *": "银行卡号 *",
    "Cardholder Name *": "持卡人姓名 *",
    "Cart": "购物车",
    "Cart is empty. Tap products to add items.": "购物车空空如也。点击商品即可添加。",
    "Cash In": "钱箱存入 (备用金补充)",
    "Cash In / Out": "现金存取",
    "Cash Movement Log": "现金流水日志",
    "Cash Out": "钱箱支出 (现金提取)",
    "Cash Register (Daily Register Management)": "收银机管理 (日结与班次交接)",
    "Cash Sales": "现金销售额",
    "Cash Tendered ($)": "实收现金 ($)",
    "Cash Tendered by Customer ($)": "顾客支付现金 ($)",
    "Casier POS": "POS收银台",
    "Catalog Item...": "商品目录项...",
    "Catalog Title *": "商品目录标题 *",
    "Category": "分类",
    "Category & Title": "分类与标题",
    "Category Name *": "分类名称 *",
    "Change": "找零",
    "Change Due": "应找零金额",
    "Change Due to Customer": "应找零给顾客",
    "Changes apply immediately upon saving.": "保存后更改立即生效。",
    "Charge": "结账收款",
    "Choose Option": "选择选项",
    "Choose a primary header & table theme color for Quotations and PDF Receipts": "选择报价单和PDF小票的主题配色",
    "Choose between General Retail POS vs Food & Restaurant Mode with strict UI & route isolation": "在通用零售POS与餐饮模式之间切换（具备独立的UI界面与路由体系）",
    "Choose dispatch channel, configure message body, and toggle PDF attachment": "选择发送渠道、编辑消息内容并配置PDF附件",
    "Choose the default interface style for your Point of Sale counter": "选择收银台默认的界面展示风格",
    "Choose your preferred register design before entering the Point of Sale terminal": "进入POS收银前选择您偏好的收银界面布局",
    "City": "城市",
    "City / Location": "城市 / 地区",
    "Clean photo tiles, top category tabs, discounts bar & quick-charge pill.": "清晰图片方块、顶部类目标签、快捷折扣条及一键收款按钮。",
    "Clean photo-first tiles, Favorites / Library / Keypad tabs, discount presets & quick blue \"Charge\" pill.": "图文并茂的商品网格、收藏/商品库/数字键盘选项卡、预设折扣及醒目的蓝色收款按钮。",
    "Clear All": "清空全部",
    "Clear Cart": "清空购物车",
    "Clear Filter": "清除筛选",
    "Clear all items in this order?": "确定清空当前订单的所有商品吗？",
    "Click any menu card on the left to add food.": "点击左侧菜单卡片即可点餐。",
    "Click any table to immediately open POS and take order": "点击任意餐桌即可快速打开POS进行点单",
    "Click on any product to add it.": "点击任意商品进行添加。",
    "Click to Insert Smart Placeholders:": "点击插入动态变量占位符:",
    "Clicking proceed will securely launch the Razorpay checkout dialog supporting Cards, UPI, Netbanking, Google Pay, Apple Pay & Wallets.": "点击继续将安全启动支付弹窗，支持银行卡、移动支付、网银及电子钱包。",
    "Client": "客户",
    "Client Name *": "客户名称 *",
    "Client:": "客户:",
    "Close": "关闭",
    "Close Register": "结班关机",
    "Close Register & Generate Z-Report": "结班并生成日结Z报表",
    "Closed": "已结班 / 已关闭",
    "Closed By": "结班人",
    "Closing Notes": "结班交接备注",
    "Closing Notes (Optional)": "结班备注 (可选)",
    "Cobalt Blue": "钴蓝色",
    "Code": "代码",
    "Code / Key (Optional)": "代码 / 标识符 (可选)",
    "Code / SKU": "编码 / SKU",
    "Code:": "编码:",
    "Collect Pay": "收款",
    "Collected This Month": "本月已收",
    "Collection Amount ($)": "收款金额 ($)",
    "Company / Store Name *": "公司 / 店铺名称 *",
    "Company mission card": "企业使命卡片",
    "Complete & Print Receipt": "完成并打印小票",
    "Complete Checkout": "完成结账",
    "Configure fine-grained read, write, edit, delete, and export permissions per module.": "为各功能模块细化配置查看、新增、编辑、删除和导出权限。",
    "Configure global checkout processors for tenant subscription billing and renewals": "配置租户订阅计费与续费的全局在线支付通道",
    "Configure outbound email delivery for sending invoices, quotations, and staff invitations": "配置用于发送发票、报价单及员工邀请的邮件服务(SMTP)",
    "Configure schedule frequency and retention lifecycle for database snapshots": "配置文件备份周期及数据库快照的保留天数",
    "Confirm & Complete Sale": "确认并完成销售",
    "Confirm Collection Receipt": "确认收款收据",
    "Confirm Password": "确认密码",
    "Confirm Settlement Payment": "确认结算款项",
    "Connecting Gateway...": "正在连接支付网关...",
    "Contact": "联系方式",
    "Contact Phone": "联系电话",
    "Control Center": "控制中心",
    "Convert": "转换",
    "Convert quote #": "转换报价单 #",
    "Convert this quotation to an active Sale invoice and deduct inventory stock?": "将此报价单转换为正式销售订单并发货扣减库存？",
    "Convert to Sale": "转为销售单",
    "Converted": "已转换",
    "Cost Price ($) *": "进货成本价 ($) *",
    "Counted": "实点金额",
    "Counted Cash": "实点现金",
    "Counted Cash in Drawer ($)": "钱箱实点现金 ($)",
    "Counter Checkout": "柜台收银",
    "Country (2-letter ISO)": "国家 (2位ISO代码)",
    "Country (ISO 2-letter) *": "国家代码 (ISO 两位字母) *",
    "Create & Generate Invite": "创建并生成邀请",
    "Create New Subscription Plan": "创建新订阅套餐",
    "Create Quotation": "创建报价单",
    "Create Vendor Bill / Expense": "登记供应商账单 / 支出",
    "Create a public shareable digital menu or product showcase link": "生成公开可分享的数字菜单或商品展示链接",
    "Create and initialize an isolated tenant store environment with initial admin account": "创建并初始化包含初始管理账号的独立租户店铺环境",
    "Create formal quotations and convert them to sales in 1-click": "快速制作标准商务报价单，一键转为销售出库单",
    "Created": "创建时间",
    "Credit / Receivable Sale:": "赊销 / 应收销售:",
    "Credit Invoices Ledger": "赊销应收发票账簿",
    "Crimson Red": "绯红",
    "Currency & Price Formatting": "货币与价格格式化",
    "Currency Symbol": "货币符号",
    "Current / Opening Stock *": "当前库存 / 期初库存 *",
    "Current Due": "当前应付 / 应收",
    "Current Plan": "当前套餐",
    "Current Store Plan": "当前店铺套餐",
    "Current sale": "当前销售",
    "Cust:": "客户:",
    "Custom Charge Amount": "自定义收款金额",
    "Custom Domain Configuration": "自定义独立域名配置",
    "Custom Hero Banner Image URL (Optional)": "自定义首屏横幅图片地址 (可选)",
    "Custom WhatsApp Footer Note": "自定义WhatsApp页脚信息",
    "Customer & Rewards": "客户与会员权益",
    "Customer / Member": "客户 / 会员",
    "Customer Directory Balances": "客户通讯录账面余额",
    "Customer Full Name *": "客户全名 *",
    "Customer Name *": "客户姓名 *",
    "Customer Phone": "客户手机号",
    "Customer Testimonials": "客户口碑评价",
    "Customer credit & pending payments": "客户信用额度与待结清账款",
    "Customer credit & unpaid bills": "客户赊账与未付账单",
    "Customer directory & loyalty points": "客户档案与会员积分",
    "Customer history & contact list": "客户消费记录与联系人名册",
    "Customer name": "客户姓名",
    "Customer:": "客户:",
    "Customers & CRM": "客户与CRM管理",
    "Customizable Text Message Body": "可自定义的短信/通知文本内容",
    "Customize Phrases for Language:": "自定义该语言的文言词条:",
    "Customize phrases, POS terms, receipt titles, and tax invoice wording specifically for your store": "为您的店铺量身定制界面文案、POS收银用语、小票标题以及发票用词",
    "Customized": "已定制",
    "DISCOUNT": "折扣",
    "DISPATCHED": "已发货 / 已送达",
    "Daily Automated Snapshot": "每日自动快照备份",
    "Dashboard": "仪表盘",
    "Database Driver": "数据库驱动",
    "Database Name": "数据库名",
    "Date:": "日期:",
    "Days": "天数",
    "Debtor Customers": "赊账客户 (借方账目)",
    "Decimal Places": "小数位数",
    "Default": "默认",
    "Default Country Calling Code": "默认国际电话区号",
    "Default English Translation": "默认英文译文",
    "Default POS Register Layout Design": "默认POS收银布局模式",
    "Default general walk-in sale": "默认散客上门消费",
    "Default language for customer receipts, table QR orders, and staff POS terminals": "小票打印、扫码点餐及收银终端的默认显示语言",
    "Default settings for 1-click WhatsApp receipts to customers": "向客户一键发送电子小票的默认设置",
    "Default terms and notes auto-loaded into new Quotations": "新建报价单时自动带入的默认条款与声明",
    "Delete Bill": "删除账单",
    "Delete Selected": "删除所选项",
    "Delete this brand?": "确定删除该品牌？",
    "Delete this category?": "确定删除该分类？",
    "Delete this customer?": "确定删除该客户？",
    "Delete this product?": "确定删除该商品？",
    "Delete this snapshot?": "确定删除该备份快照？",
    "Delete this supplier?": "确定删除该供应商？",
    "Delete this unit?": "确定删除该计量单位？",
    "Delete translation key": "删除翻译词条",
    "Delivery": "外卖 / 配送",
    "Delivery Address": "配送地址",
    "Delivery Address / Order Notes": "配送地址 / 订单备注",
    "Departments & tax rates": "部门与税率",
    "Description": "描述 / 说明",
    "Description (Optional)": "描述 (可选)",
    "Description (optional)": "描述 (可选)",
    "Destination:": "目标餐桌 / 目的地:",
    "Didn't receive code? Resend Code": "未收到验证码？重新发送",
    "Difference": "差额",
    "Digital QR menu & WhatsApp store": "扫码点餐与线上微店",
    "Digital catalog & WhatsApp share": "数字商品画册与社交分享",
    "Dine-In": "堂食",
    "Dine-In, Takeaway & Delivery": "堂食、外带与外卖配送",
    "Dining History": "就餐历史记录",
    "Direct Invitation Link": "直接邀请链接",
    "Direct Proposal / Walk-in Client": "现场提案 / 到店客户",
    "Disable": "禁用",
    "Disabled": "已禁用",
    "Disabled — sends clean structured text email only.": "已停用 — 仅发送简洁的纯文本邮件。",
    "Discount ($)": "优惠金额 ($)",
    "Discount:": "折扣优惠:",
    "Discounts": "折扣与优惠",
    "Dishes, ingredients & pricing": "菜品、原料配方与定价",
    "Dispatch & Share Invoice:": "发送与分享发票:",
    "Dispatching...": "正在发送...",
    "Displayed in browser tabs for your tenant store": "展示在店铺浏览器标签页标题中",
    "Displayed in sidebar, PDF invoices, and online catalog header": "展示在侧边栏、PDF发票及在线目录页头",
    "Docking Behavior": "停靠固定模式",
    "Docking Screen Position": "屏幕停靠位置",
    "Document / Tax ID": "纳税人识别号 / 证件号",
    "Download & Print PDF Invoice": "下载并打印PDF发票",
    "Download / Stream PDF": "下载 / 查看PDF",
    "Draft": "草稿",
    "Draft Proposal": "草稿提案",
    "Driver / Courier": "配送骑手 / 快递员",
    "Driver name": "配送员姓名",
    "Due Date": "到期日 / 截止日期",
    "Due Date:": "到期日:",
    "EMV & NFC": "EMV芯片卡与NFC触碰支付",
    "EUR": "欧元 (EUR)",
    "Edit": "编辑",
    "Edit Bill": "编辑账单",
    "Edit Category": "编辑分类",
    "Edit Customer": "编辑客户",
    "Edit Floor Area": "编辑楼层区域",
    "Edit Payment Method": "编辑支付方式",
    "Edit Plan": "编辑套餐",
    "Edit Product": "编辑商品",
    "Edit Quotation": "编辑报价单",
    "Edit Supplier": "编辑供应商",
    "Edit Table": "编辑餐桌",
    "Edit Unit": "编辑单位",
    "Edit Vendor Bill / Expense": "编辑供应商账单 / 支出",
    "Email": "电子邮箱",
    "Email & WhatsApp Invoice Sharing": "发票邮件与社交分享",
    "Email Address *": "电子邮箱 *",
    "Email Dispatch (SMTP)": "邮件发送服务 (SMTP)",
    "Email From Name (Sender Name) *": "发件人显示名称 *",
    "Email Invoice": "邮件发送发票",
    "Email Invoice Receipt": "发送电子发票凭证",
    "Email Us": "联系我们",
    "Email:": "电子邮箱:",
    "Emerald Green": "祖母绿",
    "Emerald Mint": "薄荷绿",
    "Enable": "启用",
    "Enable this payment method for POS checkout": "在POS结账中启用该支付方式",
    "Enable, disable or add new multilingual languages to the system": "启用、停用或为系统添加新的多语言支持",
    "Encryption": "加密方式",
    "Encryption Protocol *": "加密协议 *",
    "English Name *": "英文名称 *",
    "Enter a pre-purchased platform license key to activate this plan without card payment.": "输入已购激活码直接开通套餐，无需绑定银行卡。",
    "Enter bank accounts & payment instructions...": "输入开户行账号与汇款指南...",
    "Enter default quotation policy, deliverables & terms...": "输入默认报价政策、交付物与商务条款...",
    "Enter invoice policy & terms...": "输入开票须知与退换货声明...",
    "Enter password": "输入密码",
    "Enter your offline activation code or subscription license key to renew or upgrade your store.": "输入离线激活码或许可证密钥来续费或升级您的店铺。",
    "Euro": "欧元",
    "Exchange rates against your base currency, for reporting and multi-currency displays": "基于本位币的实时汇率折算，用于报表统计与多币种展示",
    "Exit": "退出",
    "Exit Fullscreen": "退出全屏",
    "Expected": "账面应有",
    "Expected Cash": "账面应有现金",
    "Expected Cash (System)": "账面应有现金 (系统计算)",
    "Expected Cash in Drawer": "钱箱应有现金",
    "Expense Category": "支出费用科目",
    "Expires": "到期时间",
    "Expires:": "有效期至:",
    "Expiry Date": "有效期至",
    "Expiry Date (MM/YY) *": "有效期 (月/年) *",
    "Fail": "未通过",
    "Fast barcode scan & cash checkout": "极速条码扫码与现金收银",
    "Fast barcode scanning, 3-column product cards, category chips & right-side cart drawer.": "极速扫码、三列商品卡片、类别快速切换及右侧购物车抽屉。",
    "Favicon URL": "网站图标URL",
    "Favorites": "常用收藏",
    "Feature Modules Suite": "功能模块套件",
    "Filter by Tenant / Company ID…": "按商户 / 企业ID筛选…",
    "Filter by event action (e.g. smtp.updated)…": "按操作事件筛选 (例如 smtp.updated)…",
    "Financial & Currency": "财务与货币",
    "Financial Management": "财务与资金管理",
    "Fixed ($)": "固定金额 ($)",
    "Fixed Docked": "固定贴边",
    "Flag Emoji": "国旗图标",
    "Floating / Free Drag": "悬浮 / 自由拖拽",
    "Floor": "楼层",
    "Floor Area": "楼层区域",
    "Floor plan is active. Take Dine-In orders, manage tables, monitor live kitchen tickets, and handle takeaway or deliveries.": "桌位平面图已就绪。支持堂食点单、桌位管理、厨房大屏联动以及外卖打包。",
    "Food & Restaurant": "餐饮美食",
    "Food & Restaurant Mode": "餐饮行业模式",
    "Food & Restaurant Mode Active": "餐饮模式已开启",
    "Food & Restaurant POS": "餐饮收银系统",
    "Food Item": "菜品项目",
    "Food Items:": "菜品明细:",
    "Food Menu": "餐饮菜单",
    "Food Suppliers": "食材供应商",
    "For restaurants, cafes, bars & food trucks. Includes floor plans & live tables, KOT tickets, Kitchen Display (KDS), Dine-In/Takeaway routing, and QR table ordering.": "适用于餐厅、咖啡厅、酒吧及餐车。包含桌台平面图、后厨出菜单(KOT)、厨房大屏(KDS)、堂食外带流转与扫码点餐。",
    "For supermarkets, clothing, electronics & retail shops. Includes barcode scanning, cash register, quotations, invoices, and standard stock management.": "适用于商超、服饰、数码及便利店。包含条码扫码、收银钱箱、报价单、发票及标准化进销存管理。",
    "Forest Green": "森林绿",
    "Free Evaluation": "免费评估体验",
    "Free Floating": "全屏浮动",
    "Full Access": "完全访问权限",
    "Full Name *": "姓名 *",
    "Full Name as on Card": "持卡人完整姓名",
    "Fullscreen": "全屏显示",
    "Fully Settled": "已全额结清",
    "Fully Settled (Paid)": "已全额结清 (已付)",
    "Function toolbar, vibrant department tiles & right receipt checkout slip.": "多功能工具栏、醒目的商品大类及右侧收银小票联。",
    "GRAND TOTAL": "总计应付金额",
    "General": "通用",
    "General Retail": "通用零售 (商超进销存)",
    "General Retail POS (Default)": "通用零售POS收银 (默认)",
    "Generate Code": "生成兑换码",
    "Generate Key": "生成密钥",
    "Generate Offline License Voucher": "生成离线授权凭证",
    "Generate and manage offline license vouchers for instant self-registration and renewals": "生成与管理离线激活券，用于用户自助注册与快速续费",
    "Generates and attaches clean stylized invoice PDF.": "自动生成并附带标准排版的PDF发票。",
    "Generates and attaches clean stylized proposal PDF.": "自动生成并附带精美的PDF方案报价单。",
    "Global Audit Trail & Security Logs": "全局审计追踪与安全日志",
    "Global Platform SMTP Email Configuration": "平台级全局SMTP邮件服务配置",
    "Global Tax Reference Matrix": "全局税率对照矩阵",
    "Grand Total:": "总计金额:",
    "Guest Directory": "宾客通讯录",
    "Guest name": "宾客姓名",
    "Guests": "就餐人数",
    "HSN / SAC codes & VAT presets": "税收分类编码与税率预设",
    "Hardware Trust Bar": "收银硬件适配认证",
    "Hero Top Badge Text": "首页顶部徽章文案",
    "Hero Value Proposition Subtitle": "核心价值主张副标题",
    "History": "历史记录",
    "History, print receipts & refunds": "销售流水、重打小票与退款管理",
    "Host": "主机地址",
    "INV-": "INV-",
    "IP Address": "IP地址",
    "If you need access to this section, please request permission from your store": "如需访问此板块，请联系店铺主管理员分配权限",
    "Immediate": "即时",
    "Immediate settlement": "即时到账结清",
    "Immutable event record of administrative actions, config mutations, and security events": "不可篡改的管理操作、配置变更及安全事件追踪日志",
    "Import all missing keys from English template": "从英文模板导入全部缺失的翻译词条",
    "In Cooking": "后厨制作中",
    "Includes: Retail Counter • Barcode POS • Quotes": "包含: 零售收银台 • 条码POS • 商务报价",
    "Includes: Tables • KOT • Kitchen KDS • QR Menus": "包含: 桌位管理 • 厨房小票 • 厨显大屏 • 扫码点餐",
    "Initial Status": "初始状态",
    "Initial Subscription Plan": "初始开通套餐",
    "Inquiry Contact Form": "意向咨询表单",
    "Installation complete. The installer is now locked.": "系统安装完成。安装向导已自动锁定。",
    "Instant Tax Receipt Generated": "已即时生成电子开票凭证",
    "Internal Notes": "内部备忘录",
    "Inv:": "发票:",
    "Inventory / Goods": "库存商品 / 货物",
    "Inventory / Raw Materials": "物料 / 原材料库存",
    "Invite New Team Member": "邀请新团队成员",
    "Invite User": "邀请员工",
    "Invoice #": "发票号 #",
    "Invoice / Receipt Attachment (PDF, Image)": "发票 / 收据附件 (PDF或图片)",
    "Invoice Prefix": "发票号码前缀",
    "Invoice Terms & Conditions (Rich-Text)": "发票条款与说明 (富文本)",
    "Invoice Terms & Policy": "发票须知与售后政策",
    "Invoice prefixes, default quotation terms, and payment instructions": "发票前缀编号、默认报价单声明及转账汇款信息",
    "Item": "项目",
    "Item & Description": "项目与规格说明",
    "Item & Scope Description": "项目及服务范围描述",
    "Item Code": "商品代码",
    "Item or service name *": "品名或服务名称 *",
    "Itemized GST/VAT Tax Invoices": "税率明细增值税发票",
    "Itemized tax receipts for store subscriptions, license activations, and renewals": "适用于店铺订阅、授权激活及续费的税控电子凭证",
    "Jurisdiction standards, default VAT rates, and GST/HSN classification guidelines": "税务管辖区标准、标准增值税率与税收分类编码指南",
    "Keep Order On Screen": "点单后保持在当前界面",
    "Keep the navigation bar pinned in view while scrolling through long views and forms": "在浏览长页面或表单时将顶部导航栏固定置顶",
    "Key Name (Exact String) *": "键名 (完全一致字符) *",
    "Keypad": "数字键盘",
    "Keypad Entry": "数字键盘输码",
    "Kitchen Display System": "厨房显示系统 (KDS)",
    "Kitchen Display System (KDS)": "厨房显示系统 (KDS)",
    "Kitchen KDS": "后厨KDS",
    "Kitchen Menu & Catalog": "后厨菜单与菜品库",
    "Kitchen Note": "后厨备注 (口味要求)",
    "Kitchen Note (Optional)": "后厨备注 (可选)",
    "Landing Neon Lime Accent": "着陆页荧光绿点缀色",
    "Landing Page Sections Controller": "着陆页版块内容管理",
    "Landing Primary Emerald": "着陆页翡翠绿主色",
    "Language Code (ISO) *": "语言代码 (ISO) *",
    "Language:": "语言:",
    "Launch Selected POS Register": "打开选定的收银台",
    "Layout": "界面布局",
    "Layout Direction:": "排版布局方向:",
    "Lead capture form": "线索收集表单",
    "Left Sidebar": "左侧导航栏",
    "Left vertical function menu, vibrant department tiles, paginated grid & thermal receipt checkout slip.": "左侧纵向功能菜单、彩色分类方块、分页式商品网格及右侧小票栏。",
    "Left-to-Right (LTR)": "从左到右 (LTR)",
    "Legal": "法律合规与条款",
    "Legal / Company Name": "公司法定全称",
    "Library": "商品库",
    "License Voucher": "授权激活凭证",
    "Line Items & Scope Specifications": "明细项目与工作范围说明",
    "Link Expiration": "链接失效时间",
    "Linked Supplier (Optional)": "关联合同供应商 (可选)",
    "Live": "实时",
    "Live KDS": "实时厨房大屏",
    "Live KOT preparation queue": "后厨待出餐实时队列",
    "Live Kitchen Tickets": "后厨实时出菜单",
    "Live Metric Counters": "实时业务指标看板",
    "Live POS": "在线收银台",
    "Live Status:": "实时状态:",
    "Live Table Status & QR Menus": "实时桌况与扫码点餐",
    "Location": "地址位置",
    "Logistics & Freight": "物流与运费支出",
    "Logistics, Freight & Delivery": "仓储物流与同城配送",
    "Low Stock Warnings": "库存不足预警",
    "Loyalty Points": "会员积分",
    "Main Headline Title *": "主标题内容 *",
    "Maintenance & Repairs": "维修与保养费",
    "Maintenance Lockout Message": "系统维护暂停服务提示",
    "Manage": "管理",
    "Manage Floor Plan": "管理餐厅楼层平面图",
    "Manage manufacturers and brands": "维护生产厂家与品牌名录",
    "Manage seating floor areas, table occupancy statuses, and QR code digital menus": "管理就餐区域、餐桌开台入座状态及扫码点餐二维码",
    "Manage signed-in sessions across browsers and POS registers": "管理各浏览器与收银终端的在线登录会话",
    "Manage supported platform languages, customize JSON translation files, and synchronize multilingual dictionaries": "管理多语言体系、定制JSON翻译词条并同步多语言词典",
    "Manage units of measure for inventory and billing": "维护进销存及销售计费的计量单位",
    "Manage vendor bills, operational expenses, utility costs, supplier settlements, and payment proofs.": "统一管理供应商进货单、水电租金杂费、货款结算及付款水单凭证。",
    "Manage your store subscription plan, redeem activation keys, and access compliant tax invoices": "管理店铺套餐订阅、兑换授权密钥并下载合规发票",
    "Manual movements this shift": "本班次手动现金出纳",
    "Mark as Ready": "标记为制作完成",
    "Mark as Served": "标记为已上菜",
    "Marketing & Ads": "市场营销与广告费",
    "Marketing & Promotions": "营销推广与促销活动",
    "Max POS Devices Limit": "允许最大POS终端数",
    "Max Users Limit": "允许最大员工账号数",
    "Measurement Units": "计量单位",
    "Member:": "会员:",
    "Membership": "会员体系",
    "Menu": "菜单",
    "Menu Dishes & Stock": "菜单菜品与库存联动",
    "Menu sections & tax rates": "菜单品类与对应税率",
    "Method": "方式",
    "Method Name": "支付方式名称",
    "Method Name *": "支付方式名称 *",
    "Method:": "方式:",
    "Midnight Slate": "午夜石板灰",
    "Migration failed. Check the output above and try again.": "数据库迁移失败。请检查上方错误输出并重试。",
    "Minimum Alert Stock *": "最低库存预警值 *",
    "Minimum Client Build Version": "最低客户端版本要求",
    "Module": "功能模块",
    "Monthly": "按月",
    "Monthly Snapshot": "每月自动快照",
    "Multi-Language & Translation File Editor": "多语言管理与翻译编辑器",
    "N/A": "不适用 (N/A)",
    "Name": "名称",
    "Name *": "名称 *",
    "Native Name": "母语名称",
    "Never": "永不",
    "Never (Lifetime)": "永久 (终身有效)",
    "Never (Permanent link)": "永久 (长期有效链接)",
    "New": "新建",
    "New Brand": "新建品牌",
    "New Category": "新建分类",
    "New Customer": "新建客户",
    "New POS Credit Sale": "新建POS赊销交易",
    "New Product": "新建商品",
    "New Quotation": "新建报价单",
    "New Sale": "新建销售单",
    "New Supplier": "新建供应商",
    "New Unit": "新建计量单位",
    "New orders from Dine-In tables, Takeaway, Delivery, or QR Digital Menu will appear here in real-time.": "来自堂食桌台、外带打包、外卖或扫码点餐的新订单将实时展示在此处。",
    "No Cash Register Open": "当前尚无已开班的收银机",
    "No Floor Assigned": "未指定楼层",
    "No Image": "暂无图片",
    "No Plan (Unlimited / Manual)": "无套餐限制 (无限量 / 手动授权)",
    "No accounts receivable records match current filters.": "没有符合当前筛选条件的应收账款记录。",
    "No activation codes generated yet. Click \"+ Generate Key\" above.": "尚未生成激活码。请点击上方的 \"+ 生成密钥\"。",
    "No active products available.": "暂无上架销售的商品。",
    "No active sessions found.": "未发现活跃的登录会话。",
    "No brands yet. Click \"+ New Brand\" to add one.": "暂无品牌。点击 \"+ 新建品牌\" 添加。",
    "No cash movements recorded yet.": "暂无现金存取流水记录。",
    "No catalogs published yet.": "尚未发布任何商品画册。",
    "No categories yet. Click \"+ New Category\" to create one.": "暂无商品分类。点击 \"+ 新建分类\" 创建。",
    "No closed registers yet.": "暂无结班交接记录。",
    "No contact details": "暂无联系信息",
    "No customer records found.": "未找到客户记录。",
    "No customers found matching": "未找到匹配的客户: ",
    "No customers registered yet.": "尚未登记任何客户。",
    "No dining floor areas created yet.": "尚未规划就餐楼层区域。",
    "No food items found. Use \"+ Add Product\" in Products menu to create items.": "未找到菜品。请在商品菜单中使用 \"+ 添加商品\" 进行录入。",
    "No items added to receipt yet.": "账单小票中尚未添加任何商品。",
    "No items found matching your search.": "未搜索到匹配的项目。",
    "No items selected for this order.": "该订单未选择任何商品。",
    "No other currencies configured.": "未配置其他外币币种。",
    "No payment methods configured. Click \"+ Add Method\" to create one.": "未配置支付方式。点击 \"+ 添加方式\" 进行创建。",
    "No products available in catalog.": "该目录内暂无商品。",
    "No products available in this department.": "该部门/品类下暂无商品。",
    "No products in catalog yet.": "画册中暂无商品内容。",
    "No products yet. Click \"+ New Product\" to add items.": "暂无商品。点击 \"+ 新建商品\" 即可录入。",
    "No quotations found matching the filter criteria.": "未找到符合筛选条件的报价单。",
    "No recent kitchen tickets.": "近期无后厨出餐小票。",
    "No recent sales records found.": "未检索到近期的销售流水。",
    "No sales found.": "未查询到销售记录。",
    "No sales recorded yet this shift.": "当前班次尚未产生销售流水。",
    "No sales recorded.": "暂无销售记录。",
    "No subscription tax invoices generated yet.": "尚未生成套餐订阅发票凭证。",
    "No suppliers yet. Click \"+ New Supplier\" to add one.": "暂无供应商。点击 \"+ 新建供应商\" 添加。",
    "No tables registered for this floor. Click \"+ Add Table\" to start.": "此楼层尚未添加餐桌。点击 \"+ 添加餐桌\" 开始布置。",
    "No team members found. Click \"+ Invite User\" to add staff.": "暂无员工。点击 \"+ 邀请员工\" 添加团队成员。",
    "No units yet. Click \"+ New Unit\" to add one.": "暂无计量单位。点击 \"+ 新建单位\" 添加。",
    "No vendor bills or operational expenses match current filters.": "未检索到符合条件的应付账单或运营支出。",
    "Non-Supplier / General Vendor": "非物料供应商 / 综合服务商",
    "None": "无",
    "None (Port 25)": "无加密 (端口25)",
    "None (Use built-in modules only)": "无 (仅使用内置标准模块)",
    "Not Set": "未设置",
    "Note:": "备注:",
    "Notes & Remarks": "备注与说明",
    "Notes regarding installment / settlement...": "分期付款 / 结算说明备注...",
    "Notification & Dispatch": "通知与消息推送",
    "OFF": "关闭",
    "ON": "开启",
    "OVERDUE": "已逾期",
    "Occupied": "使用中 (已入座)",
    "Ocean Sky": "天海蓝",
    "Office Supplies": "办公用品",
    "Office Supplies & Software": "办公用品与软件订阅",
    "Official Razorpay Payment Gateway": "Razorpay官方支付网关",
    "Official Tax Invoices & Payment Receipts": "合规财税发票与付款收据",
    "One-Time Invitation Code": "一次性员工邀请码",
    "Online Catalog": "线上数字画册",
    "Online QR Menu": "扫码点餐在线菜单",
    "Open Cash Register": "开班 (钱箱备用金录入)",
    "Open KDS": "打开厨房大屏 (KDS)",
    "Open Link": "打开链接",
    "Open Register": "开班收银",
    "Open Restaurant POS": "进入餐饮收银系统",
    "Open Table POS": "进入桌台点餐收银",
    "Open WhatsApp & Send": "调起WhatsApp并发送",
    "Open a register with a starting cash float to begin tracking today's shift.": "录入开班备用金并开启收银机，开始记录当班流水。",
    "Open/close the register, track cash in & out, and generate X/Z shift reports.": "开班与结班、钱箱现金出纳管理，并生成中途X报表与日结Z报表。",
    "Opened": "已开班 (营业中)",
    "Opening": "期初 / 开班",
    "Opening Float": "开班备用金",
    "Opening Float ($)": "开班备用金金额 ($)",
    "Operating Mode": "运行行业模式",
    "Option:": "选项:",
    "Optional": "可选",
    "Options": "选项",
    "Or Direct Image URL": "或直接输入图片URL",
    "Order": "订单",
    "Order No.": "订单号",
    "Order Notes & Remarks (Printed on Receipt)": "订单备注 (打印在小票上)",
    "Order Notes & Remarks:": "订单备注说明:",
    "Order Sent to Kitchen!": "订单已成功下发至厨房！",
    "Order Subtotal": "订单小计",
    "Order via WhatsApp": "通过WhatsApp下单",
    "Orders & Cash": "订单与现金管理",
    "Orders & thermal receipts": "订单流水与热敏小票",
    "Organize products into POS categories": "将商品归类至收银分类中",
    "Other Currencies (Reference Rates)": "其他币种 (参考汇率)",
    "Other Expenses": "其他杂项支出",
    "Over": "长款 (钱箱盈余)",
    "Overdue Accounts": "逾期未结账户",
    "Overdue Balance": "逾期欠款余额",
    "Overdue Bills": "逾期应付账单",
    "Override unit price": "修改单价",
    "PARTIAL": "部分已付",
    "PDF": "PDF",
    "POS Checkout & Payment": "POS收银与结算",
    "POS Server": "POS终端服务器",
    "POS, Inventory, KOT, Finance": "收银、进销存、后厨出单、财务",
    "PROPOSAL PREPARED FOR:": "方案报价呈报对象:",
    "Page Title *": "页面标题 *",
    "Paid Amount:": "已支付金额:",
    "Paid so far": "累计已付",
    "Partially Paid": "部分付款",
    "Pass": "正常通过",
    "Password": "密码",
    "Pay": "付款",
    "Pay & Settle Bill": "付款并结清账单",
    "Pay & Upgrade": "支付并升级",
    "Pay Bill": "支付账单",
    "Pay Method:": "支付方式:",
    "Payable To": "收款方全称",
    "Payment": "支付结算",
    "Payment Date": "付款日期",
    "Payment Information": "支付信息",
    "Payment Method": "支付方式",
    "Payment Method:": "支付方式:",
    "Payment Proof / Bank Receipt (Optional)": "付款凭证 / 银行水单 (可选)",
    "Payment Remarks": "付款备注",
    "Payment required to activate services & generate tax invoice": "付款完成后即可开通服务并开具发票",
    "Payment terms, bank details, purchase order #...": "付款条件、银行对公账号、采购单号...",
    "Payroll & Salaries": "员工薪酬与工资",
    "Payroll & Staff Wages": "工资薪金与劳务报酬",
    "Pending / In Cooking": "待处理 / 烹饪中",
    "Pending / Unpaid": "待结款 / 未支付",
    "Pending Invoices": "待处理发票",
    "Pending Orders": "待处理订单",
    "Percent (%)": "百分比 (%)",
    "Perfect for small retail stores": "非常适合小型独立零售门店",
    "Permissions Matrix": "权限控制矩阵",
    "Perpetual / Lifetime": "终身买断制",
    "Phone / Contact": "电话 / 联系方式",
    "Phone / WhatsApp": "手机号 / WhatsApp",
    "Phone / WhatsApp (Optional)": "手机号 / WhatsApp (可选)",
    "Phone number (+1 555 0199)": "手机号码 (+1 555 0199)",
    "Phone:": "电话:",
    "Phrase Key *": "词条标识键名 *",
    "Physical Address": "实际经营地址",
    "Pickup Time": "自提时间",
    "Piece, Kilogram, Box…": "件、千克、箱…",
    "Pieces, kg, box, packs & liters": "件(pcs)、公斤、箱、包、升",
    "Plan": "套餐计划",
    "Plan / Description": "套餐 / 说明",
    "Plan details & invoices": "套餐详情与账单发票",
    "Platform": "平台系统",
    "Platform Application Version": "平台应用版本号",
    "Platform Brand Name *": "平台品牌名称 *",
    "Platform GST / Tax (18% • CGST 9% + SGST 9%)": "平台增值税 (18%)",
    "Platform Logo URL": "平台Logo链接",
    "Platform Payment Gateways": "平台在线支付网关",
    "Please provide a valid name for all items.": "请为所有明细项目填写有效名称。",
    "Point your domain's": "将您域名的DNS解析指向",
    "Points Delta (+/-)": "积分变动值 (+/-)",
    "Points:": "会员积分:",
    "Port": "端口号",
    "Port *": "端口号 *",
    "Portions, kg, litres & grams": "份、公斤、升、克",
    "Postal Code": "邮政编码",
    "Prefix": "单据前缀",
    "Prepared By:": "制单人:",
    "Preset Quick Discounts": "常用快捷折扣",
    "Preview": "预览",
    "Preview Landing Page": "预览门户首页",
    "Price": "单价",
    "Price ($)": "价格 ($)",
    "Pricing Plans Grid": "价格套餐一览表",
    "Primary CTA Button Label": "主行动按钮文字",
    "Primary CTA URL": "主行动按钮跳转链接",
    "Primary Payment Method": "主支付通道",
    "Print Kitchen Ticket (KOT)": "打印厨房出菜单 (KOT)",
    "Print Ticket": "打印单据",
    "Print receipt/invoice": "打印小票/发票",
    "Processing Charge...": "正在扣款处理中...",
    "Processing Sale...": "正在处理订单交易...",
    "Processing Transaction...": "交易处理中...",
    "Processing...": "正在处理...",
    "Product": "商品",
    "Product Brands": "商品品牌",
    "Product Categories": "商品类目",
    "Product Name *": "商品名称 *",
    "Product brands & food options": "商品品牌与口味规格",
    "Production / Live Mode": "生产 / 正式运行模式",
    "Profile, printer, tax & domain": "店铺信息、打印机、税率及域名",
    "Profiles, history & loyalty": "会员档案、消费记录与积分",
    "Proof": "支付凭据",
    "Provision New Store": "开通部署新店铺",
    "Public / Publishable API Key": "公钥 / 前端公开API密钥",
    "Publish Public Catalog": "发布公开商品画册",
    "Publish an Online Catalog": "发布线上数字目录",
    "Published Shareable Links": "已发布的公共分享链接",
    "QR Stand": "立牌二维码",
    "QUO-": "QUO-",
    "Qty": "数量",
    "Qty:": "数量:",
    "Quick Add Customer": "快捷添加新客户",
    "Quotation & Invoice Document Accent Color": "报价单与发票文档强调色",
    "Quotation Prefix": "报价单编号前缀",
    "Quotations & Proposals": "商务报价与提案",
    "Quote #": "报价单号 #",
    "Quote No:": "报价单号:",
    "Quote Reference:": "报价参考号:",
    "Quote Terms & Notes": "报价条款与说明",
    "Quote Terms & Notes (Rich-Text)": "报价条款与说明 (富文本)",
    "Quotes, estimates & 1-click sales conversion": "商务报价、费用预估与一键销售转单",
    "Quotes, proposals & estimates": "报价单、商务提案与预算评估",
    "Rate": "费率 / 税率",
    "Razorpay": "Razorpay",
    "Ready to Serve": "出餐完毕，可上菜",
    "Real-Time": "实时",
    "Real-time live kitchen order tracker & ticket bump screen (Auto-refreshing every 5s)": "后厨实时订单追踪与划单大屏 (每5秒自动刷新)",
    "Reason": "原因",
    "Reason / Note": "原因 / 备注",
    "Receipt Prefixes & Bank Terms": "小票单号前缀与银行条款",
    "Recent POS Transactions": "近期POS收银流水",
    "Recipient Email Address": "收件人电子邮箱",
    "Recipient Email Address *": "收件人电子邮箱 *",
    "Recipient WhatsApp Phone Number (with Country Code)": "接收方WhatsApp手机号 (含国家代码)",
    "Record Bill Settlement Payment": "登记供应商付讫记录",
    "Record Cash In": "登记钱箱存入",
    "Record Cash Out": "登记钱箱支取",
    "Record Receivable Payment": "登记应收账款收款",
    "Redeem & Activate": "兑换并激活",
    "Redeem License Key": "兑换激活码",
    "Ref #": "参考号 #",
    "Ref / Card Last4": "参考号 / 卡号末4位",
    "Reference / Transaction / Check #": "参考单号 / 交易流水号 / 支票号 #",
    "Register": "收银机",
    "Register History (Closed Shifts / Z-Reports)": "交班结账历史 (历史班次 / Z日结单)",
    "Register users and define what each one can see and do.": "录入员工并分配各自的模块访问与操作权限。",
    "Registered on": "注册日期",
    "Registration prompt": "注册提示语",
    "Rejected": "已拒绝",
    "Remaining": "剩余",
    "Remaining Balance": "未结余额",
    "Remaining Due": "剩余应收/应付金额",
    "Remove": "移除",
    "Remove split line": "移除该拆分行",
    "Remove table": "删除餐桌",
    "Rent & Facilities": "场地租金与物业设施费",
    "Rent & Premises": "房租与物业费",
    "Rep:": "销售员:",
    "Requires follow-up": "需跟进处理",
    "Reserved": "已预订",
    "Reset": "重置",
    "Reset Template": "重置模板",
    "Reset to system default": "恢复为系统默认",
    "Resolve the failed checks above before continuing.": "请先修复上述未通过的检查项再继续。",
    "Restaurant Mode": "餐饮模式",
    "Restock": "补货入库",
    "Resume Fullscreen": "恢复全屏模式",
    "Retention Window (Days)": "备份数据保留天数",
    "Return to my account": "返回我的账户",
    "Review & Place Order": "核对并提交订单",
    "Revoke": "作废吊销",
    "Revoke this license key?": "确定作废该激活密钥吗？",
    "Revoke this link?": "确定注销此分享链接吗？",
    "Revoked": "已作废",
    "Right Sidebar": "右侧边栏",
    "Right-to-Left (RTL - Arabic, Hebrew)": "从右到左 (RTL - 阿拉伯语、希伯来语)",
    "Role & Profile *": "角色与权限模板 *",
    "Role Profile": "角色权限模板",
    "Row": "行",
    "Royal Indigo": "皇家靛蓝",
    "Royal Purple": "高贵紫",
    "Ruby Rose": "红宝石玫瑰",
    "SKU": "商品编码 (SKU)",
    "SKU Scan": "扫码识别SKU",
    "SKUs, pricing & inventory levels": "商品编码、售价及实时库存量",
    "SMTP Email Settings": "SMTP邮件服务器设置",
    "SMTP Host": "SMTP主机地址",
    "SMTP Host Server *": "SMTP服务器主机 *",
    "SMTP Password": "SMTP密码",
    "SMTP Port": "SMTP端口",
    "SMTP Username": "SMTP登录账号",
    "SMTP Username / API Key": "SMTP用户名 / API密钥",
    "SSL": "SSL",
    "SSL (Port 465)": "SSL (端口 465)",
    "SUB TOTAL": "小计金额",
    "Sale": "销售订单",
    "Sale #": "销售单号 #",
    "Sale / Inv #": "销售 / 发票单号 #",
    "Sale Completed!": "收银结算完成！",
    "Sale Price ($) *": "零售售价 ($) *",
    "Sales Representative": "销售代表",
    "Sales by Payment Method": "各支付方式销售汇总",
    "Sales by Payment Method (This Shift)": "本班次各支付方式销售汇总",
    "Sandbox / Test Mode": "沙箱 / 测试环境模式",
    "Save & Preview Quotation": "保存并预览报价单",
    "Save & Select Customer": "保存并选定客户",
    "Save All Custom Translations": "保存全部自定义翻译",
    "Save All Settings": "保存全部设置",
    "Save Bill / Expense": "保存账单 / 支出",
    "Save Category": "保存分类",
    "Save Customer": "保存客户",
    "Save Financial Settings": "保存财务配置",
    "Save Floor": "保存楼层",
    "Save Method": "保存支付方式",
    "Save Notification & Dispatch Settings": "保存通知与发送配置",
    "Save Operating Mode": "保存行业模式",
    "Save Permissions": "保存权限配置",
    "Save Phrase": "保存词条",
    "Save Plan": "保存套餐",
    "Save Product": "保存商品",
    "Save Profile & Branding": "保存商户资料与品牌",
    "Save Receipt Prefixes & Bank Terms": "保存单号前缀与银行条款",
    "Save SMTP Configuration": "保存SMTP邮件配置",
    "Save Store Overrides": "保存店铺自定义配置",
    "Save Supplier": "保存供应商",
    "Save Table": "保存餐桌",
    "Save Unit": "保存单位",
    "Saved securely": "已安全保存",
    "Saving...": "正在保存...",
    "Scan barcode / SKU...": "扫描条形码 / 输入SKU...",
    "Scan barcode or type product name / SKU...": "扫描条码或输入商品品名 / SKU...",
    "Scan to View Menu & Order": "扫码查看菜单并点单",
    "Scheduled outgoings": "计划内周期支出",
    "Scope specifications / item deliverables description (optional)...": "工作范围说明 / 项目交付要求 (可选)...",
    "Search and attach a customer to this sale": "搜索并为当前销售单关联客户",
    "Search bar, category chips, 3-column retail item cards with side cart.": "顶部搜索、分类标签卡、三列商品展示及右侧常驻购物车。",
    "Search bill #, vendor, title...": "搜索账单号、供应商、标题...",
    "Search by customer name, phone, or email...": "按客户姓名、手机号或邮箱搜索...",
    "Search by name, code, barcode…": "按名称、编号、条形码搜索…",
    "Search by name, email, phone…": "按姓名、邮箱、电话搜索…",
    "Search by sale # or customer…": "按销售单号或客户搜索…",
    "Search invoice #, customer...": "搜索发票号、客户姓名...",
    "Search items...": "搜索商品...",
    "Search keys or translated phrases…": "搜索键名或翻译文本…",
    "Search menu...": "搜索菜单菜品...",
    "Search quotation # or client name...": "搜索报价单号或客户名称...",
    "Search stores by name, account ID, email, slug…": "按名称、账号ID、邮箱、短链搜索店铺…",
    "Search suppliers by name…": "按供应商名称搜索…",
    "Search team by name, email, or role...": "按姓名、邮箱或角色搜索员工...",
    "Search terms or phrases…": "搜索关键词或词组…",
    "Seat": "座位",
    "Secondary CTA Button Label": "副行动按钮文案",
    "Secondary CTA URL": "副行动按钮链接",
    "Secure Subscription Checkout": "安全订购套餐结算",
    "Select Available Table": "选择空闲餐桌",
    "Select Brand": "选择品牌",
    "Select Category": "选择分类",
    "Select Client / Customer": "选择客户",
    "Select Customer / Member": "选择客户 / 会员",
    "Select Destination Table": "选择目标转移餐桌",
    "Select Dine-In Table": "选择堂食桌台",
    "Select Extra Page to Embed": "选择要嵌入的附加页面",
    "Select Language File to Edit:": "选择要编辑的语言文件:",
    "Select POS Layout & Interface Design": "选择收银终端布局与交互界面",
    "Select Payment Method": "选择支付方式",
    "Select Products to Include": "选择包含的商品",
    "Select Table": "选择餐桌",
    "Select User to Configure:": "选择要配置权限的员工:",
    "Select the primary accent color for your navigation sidebar, buttons, and badges": "为侧边导航栏、按钮及标签选择主强调色",
    "Selected": "已选",
    "Selected ✓": "已选中 ✓",
    "Send": "发送",
    "Send Email": "发送邮件",
    "Send Email via SMTP": "通过SMTP发送邮件",
    "Send Invoice Email": "邮件发送发票单",
    "Send Invoice via Email": "通过电子邮箱发送发票",
    "Send Order to Kitchen": "发送订单至后厨",
    "Send Quotation Email": "邮件发送报价单",
    "Send Quotation Proposal #": "发送报价方案 #",
    "Send Tax Invoice #": "发送发票 #",
    "Send Tax Invoice Receipt": "发送电子发票凭证",
    "Send Test Email": "发送测试邮件",
    "Send a test email to verify your SMTP configuration": "发送一封测试邮件以验证SMTP设置是否正确",
    "Send an immediate test dispatch to verify that your SMTP host credentials and sender address are working properly.": "立即发起测试投递，检查SMTP服务器连接与发件人邮箱是否正常。",
    "Send an invitation to join your store via WhatsApp or Email": "通过WhatsApp或电子邮件邀请加入店铺",
    "Send invitation email automatically via store SMTP": "通过店铺SMTP配置自动向员工发送邀请邮件",
    "Sender Display Name": "发件人显示姓名",
    "Sender Email Address": "发件人邮箱地址",
    "Sending Test...": "正在发送测试邮件...",
    "Sending...": "正在发送...",
    "Sent": "已发送",
    "Sent to Client": "已发送给客户",
    "Setting": "设置",
    "Settle Bill & Print Receipt": "结清账单并打印收据",
    "Settled": "已结清",
    "Settled (Paid)": "已结清 (已付讫)",
    "Settled This Month": "本月已结算",
    "Settlement Amount ($)": "结算金额 ($)",
    "Settlement Date": "结算日期",
    "Settlement remarks or transfer notes...": "结算说明或转账凭证备注...",
    "Share Invite": "分享邀请链接",
    "Share Receipt on WhatsApp": "在WhatsApp上分享小票",
    "Share via WhatsApp": "通过WhatsApp分享",
    "Shareable web catalog & WhatsApp store": "网页端分享画册与线上微店",
    "Shifts, float & cash balancing": "班次交接、备用金及钱箱核对",
    "Short": "短款 (钱箱亏损)",
    "Sign out this device?": "确认在当前设备上退出登录？",
    "Signed In": "已登录",
    "Size / Style": "尺码 / 款式",
    "Smart Inventory Platform, SaaS Billing…": "智能进销存系统、SaaS计费平台…",
    "Solution Pillars": "核心解决方案",
    "Special Order Instructions": "特殊点单要求说明",
    "Special instructions, cashier remarks...": "特殊要求、收银员备注...",
    "Split Payment Entries": "组合支付拆分明细",
    "Split Payment:": "组合支付:",
    "Split:": "拆分:",
    "Square Stand": "Square收银支架",
    "Square Stand Register": "Square支架收银台",
    "Staff": "员工",
    "Staff User Accounts": "员工用户账号",
    "Staff accounts & access matrix": "员工账号与模块权限矩阵",
    "Stand:": "支架:",
    "Standard": "标准版",
    "Standard Scanner": "标准扫码枪收银",
    "Standard Scanner POS": "标准扫码POS收银",
    "Start Preparing": "开始制作",
    "State": "省份 / 州",
    "State / Province": "省份 / 地区",
    "Status": "状态",
    "Status:": "状态:",
    "Step 1 — Requirements & Permissions": "第 1 步 — 环境与目录权限检测",
    "Step 2 — Environment & Database": "第 2 步 — 环境变量与数据库配置",
    "Step 3 — Migrate & Seed": "第 3 步 — 数据库迁移与初始化",
    "Step 4 — Super Admin Account": "第 4 步 — 创建超级管理员账号",
    "Step 5 — Finish": "第 5 步 — 完成部署",
    "Sticky Navigation Bar": "顶部吸顶悬浮导航栏",
    "Stock": "库存",
    "Store Account:": "店铺账号:",
    "Store Email": "店铺电子邮箱",
    "Store Invoicing & Billing": "店铺开票与计费",
    "Store Languages & Custom Translation Editor": "店铺多语言与翻译词条编辑器",
    "Store Operating Mode": "店铺经营行业模式",
    "Store Phone / WhatsApp": "店铺电话 / WhatsApp",
    "Store Primary Language": "店铺默认主语言",
    "Store Profile & Branding": "店铺资料与品牌形象",
    "Store Profile & Location": "店铺档案与经营地址",
    "Store Subdomain / Slug": "店铺二级域名 / 短链别名",
    "Store Theme, Branding & POS Layout": "店铺主题色、品牌标识与POS布局",
    "Store Website URL": "店铺官方网址",
    "Street & apt": "街道、门牌号及楼层房间",
    "Stripe, PayPal, Mollie, Razorpay": "Stripe, PayPal, Mollie, Razorpay",
    "Subscription & Tax Billing": "套餐订阅与发票账单",
    "Subscription Expiration Date": "订阅套餐到期时间",
    "Subtotal": "小计",
    "Subtotal:": "小计:",
    "Suffix": "单据后缀",
    "Super Admin": "超级管理员",
    "SuperAdmin Sidebar Menu": "超级管理员侧边栏菜单",
    "Supermarket Touch POS": "超市触屏POS收银",
    "Supplier": "供应商",
    "Supplier Name *": "供应商名称 *",
    "Supplier bills & expenses": "供应商采购单与杂项开支",
    "Supplier bills & food purchases": "供应商账单与食材采购",
    "Supplier bills & purchase dues": "供应商账单与应付货款",
    "Suppliers & Vendors": "供应商与合作商户",
    "Support": "技术支持",
    "Support Email": "客服支持邮箱",
    "Support Phone": "客服支持电话",
    "Supported Platform Languages": "平台已支持语言列表",
    "Suspended": "已暂停服务",
    "Switch Account": "切换登录账号",
    "Switch Table": "餐桌换台",
    "Symbol Placement": "货币符号显示位置",
    "System Default": "系统默认值",
    "System Health & Global Maintenance Mode": "系统健康监控与全局维护模式",
    "TAX ESTIMATE": "预估税额",
    "TLS": "TLS",
    "TLS (Port 587 - Recommended)": "TLS (端口 587 - 推荐)",
    "TXN / Auth #": "交易号 / 授权号 #",
    "Table Name / Number *": "餐桌名称 / 桌号 *",
    "Table Order Review": "桌台订单详情核对",
    "Tables & Floor Plan": "桌台管理与楼层平面图",
    "Takeaway": "外带 (打包)",
    "Target Seat": "目标就餐座位",
    "Tax (GST/VAT)": "税费 (增值税/GST/VAT)",
    "Tax / GST:": "税费:",
    "Tax Amount ($)": "税额 ($)",
    "Tax Exempt": "免税",
    "Tax ID": "纳税人识别号",
    "Tax ID / Business Reg": "纳税人识别号 / 工商注册号",
    "Tax ID / VAT / Document": "纳税人识别号 / 增值税号 / 证件号",
    "Tax Rate (%)": "税率 (%)",
    "Tax rates & category hierarchy": "税率设置与商品品类层级",
    "Tax/GSTIN:": "税号/识别码:",
    "Taxable": "应税项目",
    "Taxable Base": "计税基数 (不含税金额)",
    "Taxes & Professional": "税金与专业服务费",
    "Taxes & Professional Services": "税金与外包专业服务",
    "Tenant Brand Primary": "商户品牌主色调",
    "Tenant app fallback primary": "商户应用默认备用主色",
    "Term / Phrase": "词条术语 / 语句",
    "Terminals & Devices": "收银终端与外设",
    "Terms and Conditions:": "服务条款与协议:",
    "Test SMTP": "测试SMTP连接",
    "Text Direction": "文字排版方向",
    "Thank you for your business! All sales are final unless otherwise specified in your service contract.": "感谢您的惠顾！除服务合同另有明确约定外，商品一经售出概不退换。",
    "The bar floats as an overlay above the UI, enabling free drag-and-drop placement anywhere across the viewport without altering page grid layout.": "工具栏以浮层形式展示在界面上方，支持在可视区域内自由拖拽定位，不影响页面原有的网格排版。",
    "The bar snaps rigidly into the screen structure (Left Sidebar, Right Sidebar, Top Header Bar, Bottom Dock Bar) and adjusts page padding accordingly so content never scrolls under or overlaps it.": "工具栏牢固吸附在屏幕边缘（左侧栏、右侧栏、顶部栏或底部栏），并自动调整内容内边距，确保内容不被遮挡。",
    "The remaining balance is payable upon delivery/project completion.": "项目交付或工程竣工验收时结清尾款。",
    "Thermal receipts & order history": "热敏小票打印与订单流水",
    "This email address will appear in the \"From:\" header of all outgoing system emails.": "该电子邮箱将作为所有系统外发邮件的 \"发件人(From:)\" 地址展示。",
    "This user has Administrator role and automatically enjoys full bypass access to all modules.": "该用户拥有超级管理员角色，享有全模块不受限的完全访问权限。",
    "Ticket Status:": "出单状态:",
    "Ticket is now active in the Kitchen Display System (KDS) queue.": "菜品单据已进入厨房大屏 (KDS) 制作队列。",
    "Time:": "时间:",
    "Toggle Fullscreen Mode": "切换全屏显示模式",
    "Toggle Sticky Navigation": "开启/关闭吸顶导航",
    "Top Header Bar": "顶部导航工具栏",
    "Total": "总计",
    "Total Active KOTs": "当前制作中厨房小票总数",
    "Total Amount": "总金额",
    "Total Amount Due": "应收/应付总额",
    "Total Amount Paid:": "已付总金额:",
    "Total Bill": "账单合计",
    "Total Due Today": "今日到期应付总额",
    "Total Order Amount:": "订单总额:",
    "Total Outstanding": "未结清挂账总额",
    "Total Outstanding Balance": "累计欠款余额",
    "Total Payable": "应付款总计",
    "Total Sales": "总销售额",
    "Total Tables:": "餐桌总数:",
    "Total:": "总计:",
    "Touch Department": "触屏分类大类",
    "Touch POS": "触屏POS收银",
    "Track customer balances, credit sales, partial payments, due dates, and overdue accounts.": "实时追踪客户挂账余额、赊销订单、分期收款、还款到期日以及逾期坏账。",
    "Trade / Brand Name": "商标 / 商号名称",
    "Transaction & Sales": "交易流水与销售",
    "Transfer Order": "转单",
    "Transfer Table": "餐桌换台",
    "Transfer Table Order": "转移桌台订单",
    "Type product name, SKU or barcode scan...": "输入商品名、SKU或扫码录入...",
    "URL Slug *": "URL别名 (Slug) *",
    "USD": "美元 (USD)",
    "Unassign Customer": "取消关联客户",
    "Unit": "计量单位",
    "Unit Name": "单位名称",
    "Unit Name *": "单位名称 *",
    "Unit Price": "单价",
    "Units of Measure": "计量单位管理",
    "Unlimited": "不限数量 / 无限",
    "Unlimited Inventory & Sales History": "海量库存管理与永久销售流水",
    "Upcoming (30 Days)": "未来30天内到期",
    "Upgrade or renew your plan with instant tax invoice generation": "在线升级或续费套餐，即刻获取电子开票凭据",
    "Upload Product Photo": "上传商品图片",
    "Uploading...": "正在上传...",
    "Use \"Adjust Stock\" button on the table.": "请使用表格中的 \"库存调整\" 按钮进行操作。",
    "User": "用户",
    "User / Terminal": "操作员 / 收银机终端",
    "Username": "用户名",
    "Utilities (Electricity, Water, Internet)": "水电与网络通讯费",
    "Utilities (Power/Water)": "公用事业费 (水电费)",
    "Valid Until:": "有效期至:",
    "Validity Expiry Date": "有效期截止时间",
    "Vendor / Supplier": "供应商 / 合作商",
    "Vendor Name (If not in suppliers)": "供应商名称 (如未在名录中)",
    "Vendor contacts & purchasing": "供应商联系人与采购管理",
    "Vendor directory & purchasing": "供应商档案与进货管理",
    "Verify Key & Upgrade": "校验密钥并开通升级",
    "View": "查看",
    "View & Download PDF Tax Invoice": "查看并下载PDF税务发票",
    "View All": "查看全部",
    "View All Sales": "查看全部销售明细",
    "View All Stores": "查看全部店铺",
    "View Invoices": "查看发票列表",
    "View Only": "仅查看权限",
    "View Z-Report": "查看日结Z报表",
    "View attached bill file": "查看所附账单文件",
    "Viewing as": "当前模拟查看身份:",
    "Violet Purple": "紫罗兰",
    "Volume, Outlets, Uptime": "交易量、门店数与系统高可用",
    "Walk-in": "散客",
    "Walk-in Customer": "散客客户",
    "Walk-in Member": "到店会员",
    "Walk-in Regular Customer": "到店老客户",
    "Warm Amber": "暖琥珀",
    "Weekly Automated Snapshot": "每周自动快照备份",
    "WhatsApp": "WhatsApp",
    "WhatsApp & Messaging Settings": "WhatsApp与即时消息设置",
    "WhatsApp Web / Mobile": "WhatsApp网页端 / 手机端",
    "With pending dues": "含未结清款项",
    "X-Report (live)": "X报表 (当班中途点检)",
    "Yearly": "按年",
    "You": "您 (当前用户)",
    "Your Custom Store Translation": "当前店铺专属自定义译文",
    "Your Name (Optional)": "您的姓名 (可选)",
    "Your Name *": "您的姓名 *",
    "Your Order Cart": "已点餐品明细",
    "Your Phone / WhatsApp Number": "您的手机号 / WhatsApp号",
    "Your Store Custom Translation *": "店铺自定义翻译文本 *",
    "Your cart is currently empty.": "购物车暂无商品。",
    "Your sale is currently empty. Tap items to add.": "当前收银台暂无商品。点击商品进行录入。",
    "Z-Report": "Z报表 (日结报表)",
    "active invoices": "张生效中发票",
    "admin@yourcompany.com": "admin@yourcompany.com",
    "apikey, username@domain.com…": "apikey, username@domain.com…",
    "billing@yourstore.com": "billing@yourstore.com",
    "by": "由",
    "days": "天",
    "discount": "折扣",
    "e.g. 1 for US/CA, 91 for IN, 44 for UK, 62 for ID": "例如：中国填86，美国填1，英国填44",
    "e.g. 15 mins, 06:00 PM": "例如：15分钟后、18:00",
    "e.g. Change fund top-up, petty cash withdrawal": "例如：钱箱零钱补充、备用金支取",
    "e.g. City Power Corp, Apex Landlord": "例如：国家电网、物业管理处",
    "e.g. Credit Card, UPI, PIX, Stripe": "例如：微信支付、支付宝、信用卡、现金",
    "e.g. Dutch": "例如：荷兰语",
    "e.g. For returns, keep this receipt within 7 days.": "例如：如需退换货，请在7日内凭此小票办理。",
    "e.g. Fresh Summer Produce, Special Deals…": "例如：夏季时令生鲜、限时特惠…",
    "e.g. Michael Scott": "例如：张伟",
    "e.g. Monthly Warehouse Rent or Stock Restock Batch #4": "例如：7月份仓库租金或第4批进货补仓款",
    "e.g. Nederlands": "例如：简体中文",
    "e.g. No onion": "例如：免葱、微辣",
    "e.g. Pay via terminal or contactless": "例如：POS机刷卡或扫码无接触支付",
    "e.g. Política de Devoluciones": "例如：退换货政策",
    "e.g. Restock, damaged, correction": "例如：进货入库、报损、盘点差异调整",
    "e.g. Return Policy": "例如：退换货条款",
    "e.g. Return Policy, Print Tax Invoice": "例如：退换货政策、开具发票须知",
    "e.g. Return Policy, Special Promo": "例如：退换货政策、会员特惠",
    "e.g. Rooftop Patio, Bar, Hall": "例如：露天阳台、吧台区、主大厅",
    "e.g. Sarah Jenkins": "例如：李娜",
    "e.g. Scope deliverables, milestone payment terms, project phases...": "例如：交付范围清单、阶段付款节点、项目实施周期...",
    "e.g. TAX-8891, VAT12345": "例如：91110108MA00000000 (统一社会信用代码)",
    "e.g. TXN-998822 or Check #4401": "例如：TXN-998822 或 支票 #4401",
    "e.g. Table 04, VIP-1, Bar-02": "例如：04号桌、包厢VIP-1、吧台02",
    "e.g. WIRE-884401 or Check #1002": "例如：WIRE-884401 或 支票 #1002",
    "e.g. card, upi, pix, stripe": "例如：微信、支付宝、刷卡、现金",
    "e.g. nl, ja, it": "例如：zh, en, ja",
    "e.g. smtp.mailgun.org, smtp.gmail.com": "例如：smtp.exmail.qq.com, smtp.163.com",
    "e.g. yourstore.com or https://yourstore.com": "例如：yourstore.com 或 https://yourstore.com",
    "each": "件 / 个",
    "https://example.com/favicon.ico": "https://example.com/favicon.ico",
    "https://example.com/logo.png": "https://example.com/logo.png",
    "https://example.com/product-image.jpg": "https://example.com/product-image.jpg",
    "if CNAME isn't supported at your registrar for this name) to": "若您的域名注册商不支持该名称的CNAME记录) 指向",
    "impersonated": "模拟登录",
    "items": "件商品",
    "line items": "条明细行",
    "m ago": "分钟前",
    "month": "月",
    "my-store": "my-store",
    "no-reply@saas.zoomnearby.com, billing@yourdomain.com": "no-reply@saas.zoomnearby.com, billing@yourdomain.com",
    "of": "/",
    "or": "或",
    "pcs": "件",
    "pcs, kg, box…": "件、公斤、箱…",
    "pcs, kg, bx…": "件、公斤、箱…",
    "pos.yourdomain.com or mycompany.com": "pos.yourdomain.com 或 mycompany.com",
    "postmaster@yourdomain.com": "postmaster@yourdomain.com",
    "pts": "分",
    "quotation(s) selected": "份报价单已选中",
    "sale(s) total, all methods": "笔销售总计，全渠道汇总",
    "sarah@store.com": "sarah@store.com",
    "save this form, then ask your platform admin to finish HTTPS setup for the domain — until that's done it may show a certificate warning.": "保存此表单后，请联系平台管理员为该独立域名配置HTTPS证书 — 在配置完成前访问可能会出现安全证书提示。",
    "seats": "座",
    "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…": "smtp.mailgun.org, smtp.sendgrid.net, smtp.gmail.com…",
    "subtotal": "小计",
    "tax": "税费",
    "to Sale invoice?": "为正式销售订单？",
    "total": "总计",
    "will be logged to Accounts Receivable.": "将被记入应收账款。",
    "with Razorpay": "通过Razorpay支付",
    "year": "年",
    "your-email@example.com": "your-email@example.com"
}

def update_zh():
    with open('lang/zh.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    with open('scratch/to_translate/zh_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
        
    missing_count = 0
    for k in missing:
        if k in CHINESE_TRANSLATIONS:
            existing[k] = CHINESE_TRANSLATIONS[k]
        else:
            print(f"Missing translation for key: {k}")
            missing_count += 1
            
    if missing_count > 0:
        print(f"FAILED: {missing_count} keys missing in CHINESE_TRANSLATIONS")
        return False
        
    with open('lang/zh.json', 'w', encoding='utf-8') as f:
        json.dump(existing, f, indent=4, ensure_ascii=False)
        f.write('\n')
        
    print(f"Successfully updated lang/zh.json! Total keys: {len(existing)}")
    return True

if __name__ == '__main__':
    update_zh()
